from __future__ import annotations

import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

SCRIPT = Path(__file__).parents[1] / "scripts" / "lint_prose.py"
EVAL_SCRIPT = Path(__file__).parents[1] / "scripts" / "run_evals.py"
sys.path.insert(0, str(SCRIPT.parent))

import lint_prose  # noqa: E402


class LintLibraryTests(unittest.TestCase):
    def codes(self, text: str, mode: str = "technical") -> list[str]:
        result = lint_prose.lint_text(text, mode=mode)
        return [finding.code for finding in result.findings]

    def test_clean_strict_procedure_has_no_findings(self) -> None:
        text = "Open the console.\n\nSelect the failed worker.\n\nSelect Restart."
        result = lint_prose.lint_text(text, mode="strict")
        self.assertEqual([], result.findings)

    def test_strict_detects_structural_rules(self) -> None:
        text = (
            "The report was generated by the service; it is being reviewed, "
            "and it can't be sent until every regional administrator approves "
            "the final version for publication."
        )
        codes = self.codes(text, "strict")
        self.assertIn("CLR001", codes)
        self.assertIn("CLR003", codes)
        self.assertIn("CLR004", codes)
        self.assertIn("CLR005", codes)
        self.assertIn("CLR006", codes)

    def test_language_modes_change_severity(self) -> None:
        text = "The report was generated by the service, and it can't be sent."
        strict = lint_prose.lint_text(text, mode="strict")
        technical = lint_prose.lint_text(text, mode="technical")
        self.assertEqual({"CLR004", "CLR005"}, {item.code for item in strict.findings})
        self.assertEqual(["CLR005", "CLR005"], [item.code for item in technical.findings])
        self.assertEqual("error", strict.findings[0].severity)
        self.assertEqual("warning", technical.findings[0].severity)

    def test_technical_keeps_anti_slop_checks(self) -> None:
        result = lint_prose.lint_text(
            "This robust tool will move the needle.", mode="technical"
        )
        levels = {item.code: item.severity for item in result.findings}
        self.assertEqual("error", levels["WRD002"])
        self.assertEqual("warning", levels["WRD004"])

    def test_markdown_exclusions_keep_prose_locations(self) -> None:
        text = """---
description: "A robust skill"
---

Use `robust; seamless` in this command:

```bash
echo "it is important to note"
```

Read https://example.com/robust;seamless before you start.
"""
        result = lint_prose.lint_text(text, mode="strict")
        self.assertEqual([], result.findings)

    def test_markdown_table_rows_do_not_merge_into_one_sentence(self) -> None:
        text = """| System | Quality | Fidelity |
|---|---:|---:|
| Alpha | 4.8 | 5.0 |
| Bravo | 4.7 | 4.9 |
| Charlie | 4.6 | 4.8 |
"""
        result = lint_prose.lint_text(text, mode="strict")
        self.assertNotIn("CLR001", [item.code for item in result.findings])

    def test_false_passive_adjective_is_ignored(self) -> None:
        self.assertNotIn("CLR005", self.codes("The advanced control is red.", "strict"))

    def test_nominalization_phrasal_and_inflated_words(self) -> None:
        codes = self.codes(
            "We conduct a review before we spin up a server and utilize it.",
            "strict",
        )
        self.assertIn("CLR007", codes)
        self.assertIn("CLR008", codes)
        self.assertIn("WRD001", codes)

    def test_repeated_word_has_source_location(self) -> None:
        result = lint_prose.lint_text("First line.\n\nUse the the file.", mode="strict")
        finding = next(item for item in result.findings if item.code == "TXT001")
        self.assertEqual(3, finding.line)
        self.assertEqual(5, finding.column)

    def test_sentence_limit_override(self) -> None:
        result = lint_prose.lint_text(
            "Use one short sentence here.", mode="strict", sentence_limit=3
        )
        self.assertIn("CLR001", [item.code for item in result.findings])

    def test_unsupported_attribution_and_importance_puffery(self) -> None:
        codes = self.codes(
            "Studies show this marks a pivotal moment.",
            "technical",
        )
        self.assertEqual(["WRD006", "WRD007"], codes)

    def test_structural_slop_patterns(self) -> None:
        text = (
            "This is not just a release but a revolution. "
            "The change creates momentum, highlighting our vision. "
            "The journey has just begun."
        )
        codes = self.codes(text, "technical")
        self.assertIn("WRD008", codes)
        self.assertIn("WRD009", codes)
        self.assertIn("WRD010", codes)

    def test_evidenced_participial_clause_is_not_flagged(self) -> None:
        text = "The benchmark fell by 12%, demonstrating that the fix worked."
        self.assertNotIn("WRD010", self.codes(text, "technical"))

    def test_em_dash_threshold(self) -> None:
        self.assertEqual(["TXT002"], self.codes("One—two—three.", "strict"))

    def test_all_modes_enforce_named_patterns(self) -> None:
        text = (
            "This is not a model problem. It is an eval problem. "
            "This is the part everyone misses. Not speed. Not scale. Evidence. "
            "Same problem, different angle. "
            "Customer-side fixes will help, but any spike can restart the loop."
        )
        for mode in lint_prose.MODES:
            with self.subTest(mode=mode):
                codes = {
                    item.code
                    for item in lint_prose.lint_text(text, mode=mode).findings
                }
                self.assertTrue(
                    {"STR001", "STR002", "STR004", "STR007", "STR014"} <= codes
                )

    def test_natural_relaxes_clarity_rules_but_keeps_anti_slop_review(self) -> None:
        text = (
            "We're spinning up the server; the work will delve into a "
            "transformative realm. This is not a model problem. It is an eval problem."
        )
        levels = {
            item.code: item.severity
            for item in lint_prose.lint_text(text, mode="natural").findings
        }
        self.assertNotIn("CLR003", levels)
        self.assertNotIn("CLR004", levels)
        self.assertNotIn("CLR006", levels)
        self.assertEqual("warning", levels["WRD011"])
        self.assertEqual("error", levels["STR001"])

    def test_modes_review_formatting_structure(self) -> None:
        text = """# Why this matters 🚀

This is **extremely important**.

## What comes next

We will test it.
"""
        codes = {
            item.code
            for item in lint_prose.lint_text(text, mode="technical").findings
        }
        self.assertTrue({"STR008", "STR009", "STR010", "STR011"} <= codes)

    def test_bold_labels_and_identifiers_are_not_decorative_emphasis(self) -> None:
        text = (
            "**Background**\n\n"
            "**Error code:** schedule_event_false\n\n"
            "The hook is **action_scheduler_run_queue**."
        )
        self.assertNotIn("STR010", self.codes(text))
        self.assertIn("STR010", self.codes("The result is **extremely important**."))

    def test_narrator_scaffolding_is_a_warning_not_a_ban(self) -> None:
        text = (
            "The log sequence shows the loop. "
            "We have documented customer damage."
        )
        result = lint_prose.lint_text(text, mode="technical")
        findings = [item for item in result.findings if item.code == "STR015"]
        self.assertEqual(1, len(findings))
        finding = findings[0]
        self.assertEqual("warning", finding.severity)
        self.assertIn("necessary inference", finding.suggestion)
        abstract = next(item for item in result.findings if item.code == "STR016")
        self.assertEqual("error", abstract.severity)

    def test_narrator_scaffolding_ignores_literal_technical_text(self) -> None:
        text = (
            "Run `echo 'The evidence shows the fault'`.\n\n"
            "```text\nThe log sequence shows the loop.\n```"
        )
        self.assertNotIn("STR015", self.codes(text))
        self.assertNotIn("STR003", self.codes(text))

    def test_colon_reveal_ignores_labels_and_list_explanations(self) -> None:
        text = "Site address: valid.example\n\n- Retry policy: use three attempts."
        self.assertNotIn("STR003", self.codes(text))
        self.assertIn("STR003", self.codes("The useful detail: a worker grades it."))


class LintCliTests(unittest.TestCase):
    def run_cli(
        self, *args: str, input_text: str | None = None
    ) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            [sys.executable, str(SCRIPT), *args],
            input=input_text,
            text=True,
            capture_output=True,
            check=False,
        )

    def test_json_stdin_and_failure_status(self) -> None:
        process = self.run_cli(
            "--mode",
            "strict",
            "--format",
            "json",
            input_text="This robust tool can leverage data.",
        )
        self.assertEqual(1, process.returncode)
        payload = json.loads(process.stdout)
        self.assertEqual("none", payload["certification"])
        self.assertGreater(payload["summary"]["errors"], 0)
        self.assertEqual("<stdin>", payload["files"][0]["path"])

    def test_fail_on_warning_and_never(self) -> None:
        warning_text = "The report was generated by the service."
        warning = self.run_cli(
            "--mode", "technical", "--fail-on", "warning", input_text=warning_text
        )
        never = self.run_cli(
            "--mode", "technical", "--fail-on", "never", input_text=warning_text
        )
        self.assertEqual(1, warning.returncode)
        self.assertEqual(0, never.returncode)

    def test_missing_file_returns_usage_error(self) -> None:
        process = self.run_cli("/path/that/does/not/exist.md")
        self.assertEqual(2, process.returncode)
        self.assertIn("input does not exist", process.stderr)

    def test_glob_reads_multiple_files(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            (root / "a.md").write_text("Open the file.", encoding="utf-8")
            (root / "b.md").write_text("Close the file.", encoding="utf-8")
            process = self.run_cli(
                "--mode", "strict", "--format", "json", str(root / "*.md")
            )
        self.assertEqual(0, process.returncode)
        self.assertEqual(2, json.loads(process.stdout)["summary"]["files"])

    def test_list_rules(self) -> None:
        process = self.run_cli("--mode", "technical", "--list-rules")
        self.assertEqual(0, process.returncode)
        self.assertIn("CLR005\twarning\tpossible passive voice", process.stdout)

    def test_structural_rules_are_in_default_json_output(self) -> None:
        process = self.run_cli(
            "--format",
            "json",
            "--fail-on",
            "never",
            input_text="Same problem, different angle.",
        )
        self.assertEqual(0, process.returncode)
        payload = json.loads(process.stdout)
        self.assertNotIn("profile", payload)
        self.assertIn(
            "STR007",
            {finding["code"] for finding in payload["files"][0]["findings"]},
        )

    def test_structural_rules_are_active_in_each_mode(self) -> None:
        for mode in lint_prose.MODES:
            with self.subTest(mode=mode):
                process = self.run_cli(
                    "--mode",
                    mode,
                    "--format",
                    "json",
                    input_text="This is not a model problem. It is an eval problem.",
                )
                self.assertEqual(1, process.returncode)
                payload = json.loads(process.stdout)
                self.assertIn(
                    "STR001",
                    {
                        finding["code"]
                        for finding in payload["files"][0]["findings"]
                    },
                )

    def test_eval_suite_passes(self) -> None:
        process = subprocess.run(
            [sys.executable, str(EVAL_SCRIPT), "--format", "json"],
            text=True,
            capture_output=True,
            check=False,
        )
        self.assertEqual(0, process.returncode, process.stdout + process.stderr)
        report = json.loads(process.stdout)
        self.assertTrue(report["passed"])
        self.assertEqual(report["total_rules"], report["covered_rules"])


if __name__ == "__main__":
    unittest.main()
