const BG = "#f4f6f8";
const CARD = "#ffffff";
const BORDER = "#d9e0e7";
const TEXT = "#1f2937";
const MUTED = "#64748b";
const DARK = "#0f172a";
const MINDKEEPER_URL = "https://github.com/asistent-alex/openclaw-mindkeeper";

function escapeHtml(text) {
  return String(text ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;");
}

function paletteForMode(briefMode) {
  if (briefMode === "lossless-only") {
    return {
      heroBg: "#9a3412",
      heroAccent: "#fdba74",
      infoBg: "#ffedd5",
      infoText: "#b45309",
      successBg: "#fff7ed",
      successText: "#c2410c",
      warnBg: "#ffedd5",
      warnText: "#9a3412",
      footerBg: "#fff7ed",
      footerAccent: "#fdba74",
      modeLabel: "Lossless-Only",
      provenanceLine: "Generated by Mindkeeper from lossless recall context only.",
    };
  }

  return {
    heroBg: "#7c2d12",
    heroAccent: "#fb923c",
    infoBg: "#fff7ed",
    infoText: "#9a3412",
    successBg: "#ffedd5",
    successText: "#9a3412",
    warnBg: "#fff1f2",
    warnText: "#9f1239",
    footerBg: "#eef2f7",
    footerAccent: "#fb923c",
    modeLabel: "Hybrid",
    provenanceLine: "Generated by Mindkeeper from daily memory and lossless recall context.",
  };
}

function list(items, empty = "None") {
  if (!items || items.length === 0) {
    return `<ul><li>${escapeHtml(empty)}</li></ul>`;
  }

  return `<ul style="margin:0;padding-left:18px;">${items.map((item) => `<li style="margin:0 0 8px 0;">${escapeHtml(item)}</li>`).join("")}</ul>`;
}

function summaryCard(label, value, bg, fg) {
  return (
    `<td width="33.33%" valign="top" style="padding:0 8px 0 0;">` +
      `<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="border-collapse:collapse;background:${bg};border:1px solid ${BORDER};">` +
        `<tr><td style="padding:14px 16px;">` +
          `<div style="font-size:12px;line-height:18px;color:${fg};text-transform:uppercase;letter-spacing:0.04em;">${escapeHtml(label)}</div>` +
          `<div style="font-size:28px;line-height:32px;font-weight:bold;color:${fg};margin-top:4px;">${escapeHtml(value)}</div>` +
        `</td></tr>` +
      `</table>` +
    `</td>`
  );
}

function sectionCard(title, items, fg, bg) {
  return (
    `<tr><td style="padding:0 0 18px 0;">` +
      `<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="border-collapse:collapse;background:${bg};border:1px solid ${BORDER};">` +
        `<tr><td style="padding:16px 18px;">` +
          `<div style="font-size:18px;line-height:24px;font-weight:bold;color:${DARK};margin-bottom:10px;">${escapeHtml(title)}</div>` +
          `<div style="font-size:14px;line-height:22px;color:${fg};">${list(items)}</div>` +
        `</td></tr>` +
      `</table>` +
    `</td></tr>`
  );
}

export function renderHtmlBrief(brief, { briefMode = "hybrid" } = {}) {
  const palette = paletteForMode(briefMode);
  const whatCount = brief.summary.whatMattered?.length ?? 0;
  const decisionsCount = brief.summary.decisions?.length ?? 0;
  const openLoopsCount = brief.summary.openLoops?.length ?? 0;
  const recommendationsCount = brief.summary.recommendations?.length ?? 0;
  const intro = openLoopsCount > 0
    ? "Today produced a few solid signals and a small number of open loops worth tracking."
    : "Today produced a clean set of signals with no major open loops left hanging.";

  return [
    `<html><body style="margin:0;padding:0;background:${BG};font-family:Arial,Helvetica,sans-serif;color:${TEXT};">`,
    `<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="background:${BG};">`,
    `<tr><td align="center" style="padding:24px;">`,
    `<table role="presentation" width="760" cellspacing="0" cellpadding="0" border="0" style="width:760px;max-width:760px;background:${CARD};border:1px solid ${BORDER};">`,
    `<tr><td style="background:${palette.heroBg};padding:24px 28px;color:#ffffff;border-bottom:4px solid ${palette.heroAccent};">`,
    `<div style="font-size:12px;line-height:18px;letter-spacing:0.14em;text-transform:uppercase;opacity:0.88;">Built for teams using <a href="https://firmade.ai" style="color:#ffffff;text-decoration:none;font-weight:700;">Firma de AI</a> and supported by <a href="https://firmade.it" style="color:#ffffff;text-decoration:none;font-weight:700;">Firma de IT</a>.</div>`,
    `<div style="font-size:30px;line-height:36px;font-weight:bold;margin-top:10px;">Mindkeeper Daily Brief</div>`,
    `<div style="font-size:16px;line-height:24px;font-weight:600;opacity:0.96;margin-top:10px;">${escapeHtml(brief.title)} — ${escapeHtml(brief.humanDate)}</div>`,
    `<div style="font-size:13px;line-height:20px;font-weight:700;letter-spacing:0.04em;text-transform:uppercase;opacity:0.9;margin-top:10px;">${escapeHtml(palette.modeLabel)} report</div>`,
    `<div style="font-size:14px;line-height:22px;opacity:0.90;margin-top:10px;">${escapeHtml(intro)}</div>`,
    `<div style="font-size:12px;line-height:18px;opacity:0.78;margin-top:10px;">${escapeHtml(palette.provenanceLine)}</div>`,
    `</td></tr>`,
    `<tr><td style="padding:24px 28px;">`,
    `<table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="border-collapse:collapse;margin-bottom:18px;">`,
    `<tr>`,
    summaryCard("Recommendations", recommendationsCount, palette.successBg, palette.successText),
    summaryCard("What mattered", whatCount, CARD, DARK),
    summaryCard("Open loops", openLoopsCount, openLoopsCount > 0 ? palette.warnBg : palette.infoBg, openLoopsCount > 0 ? palette.warnText : palette.infoText),
    `</tr></table>`,
    sectionCard("Recommendations", brief.summary.recommendations, palette.successText, palette.successBg),
    sectionCard("What mattered", brief.summary.whatMattered, TEXT, CARD),
    sectionCard("Decisions", brief.summary.decisions, palette.infoText, palette.infoBg),
    sectionCard("Open loops", brief.summary.openLoops, openLoopsCount > 0 ? palette.warnText : palette.infoText, openLoopsCount > 0 ? palette.warnBg : palette.infoBg),
    `<tr><td style="padding:0;">`,
    `<div style="font-size:12px;line-height:18px;color:${MUTED};">Mindkeeper prefers signal over noise and is designed to turn a day of memory into clarity.</div>`,
    `</td></tr>`,
    `</td></tr>`,
    `<tr><td style="background:${palette.footerBg};padding:16px 28px;font-size:12px;line-height:18px;color:${MUTED};border-top:3px solid ${palette.footerAccent};">`,
    `<div style="margin:0;">Generated by <a href="${MINDKEEPER_URL}" style="color:${palette.footerAccent};text-decoration:none;font-weight:600;">openclaw-mindkeeper</a> · <a href="https://firmade.ai" style="color:${palette.footerAccent};text-decoration:none;font-weight:600;">Firma de AI</a> · <a href="https://firmade.it" style="color:${palette.footerAccent};text-decoration:none;font-weight:600;">Firma de IT</a></div>`,
    `</td></tr>`,
    `</table></td></tr></table></body></html>`,
  ].join("");
}
