#!/usr/bin/env bash
# Prompt Version Control (prompt-vc.sh)
# Git-like version control for AI prompts.
# License: MIT-0
set -euo pipefail

VERSION="1.0.0"
PROMPT_DIR=".prompt"

# ── Utility Functions ──────────────────────────────────────────────────

die() { echo "Error: $*" >&2; exit 1; }
warn() { echo "Warning: $*" >&2; }

prompt_repo_guard() {
  [ -d "$PROMPT_DIR" ] || die "E-NOT-INIT: No prompt repo found. Run 'prompt-vc.sh init' first."
}

prompt_name_guard() {
  local name="$1"
  [ -f "$PROMPT_DIR/prompts/${name}.yaml" ] || die "E-PROMPT-NOT-FOUND: Prompt '${name}' not found. Available: $(ls "$PROMPT_DIR/prompts/"*.yaml 2>/dev/null | xargs -I{} basename {} .yaml | tr '\n' ' ')"
}

bump_version() {
  local current="$1" bump="$2"
  IFS='.' read -r major minor patch <<< "$current"
  case "$bump" in
    major) echo "$((major+1)).0.0" ;;
    minor) echo "${major}.$((minor+1)).0" ;;
    patch) echo "${major}.${minor}.$((patch+1))" ;;
    *) die "Invalid bump type: $bump (use major|minor|patch)" ;;
  esac
}

auto_detect_bump() {
  local content="$1"
  for kw in "breaking" "rewrite" "new approach" "schema change"; do
    if echo "$content" | grep -iq "$kw"; then echo "major"; return; fi
  done
  for kw in "add" "new variable" "restructure" "change model"; do
    if echo "$content" | grep -iq "$kw"; then echo "minor"; return; fi
  done
  echo "patch"
}

timestamp() { date -u +"%Y-%m-%dT%H:%M:%SZ"; }
date_short() { date +"%Y-%m-%d"; }
author_name() {
  local author="${GIT_AUTHOR_NAME:-${USER:-unknown}}"
  echo "$author"
}

# ── Command: help ─────────────────────────────────────────────────────

cmd_help() {
  cat <<HELP
prompt-vc.sh v${VERSION} — Git-like version control for AI prompts

Usage:
  prompt-vc.sh init [directory]                   Initialize prompt repository
  prompt-vc.sh add <name>                          Register a new prompt
  prompt-vc.sh edit <name>                         Edit prompt (opens editor)
  prompt-vc.sh diff <name> <ver1> <ver2>           Compare two versions
  prompt-vc.sh log <name>                          Show version history
  prompt-vc.sh rollback <name> --to <version>      Rollback to previous version
  prompt-vc.sh test <name>                         Run A/B test against previous version
  prompt-vc.sh report <name>                       Generate iteration report
  prompt-vc.sh help                                Show this help message

Options:
  --bump major|minor|patch    Override auto-bump type (for edit)
  --limit N                   Limit output entries (for log)
  --from <version>            Start version (for report)
  --format markdown|html      Output format (for report)
  --name <name>               Repository name (for init)
  --template <type>           Prompt template (for add): chat|classifier|generator|extractor|custom
  --description <text>        Prompt description (for add)

HELP
}

# ── Command: init ─────────────────────────────────────────────────────

cmd_init() {
  local dir="${1:-.}" repo_name=""
  shift 2>/dev/null || true
  while [ $# -gt 0 ]; do
    case "$1" in --name) repo_name="$2"; shift 2 ;; *) shift ;; esac
  done

  local target="$dir/$PROMPT_DIR"
  [ -d "$target" ] && die "Prompt repo already exists at ${target}"

  mkdir -p "$target"/{prompts,history,metrics,branches}

  # Check git integration
  local git_root=""
  if command -v git &>/dev/null; then
    git_root="$(cd "$dir" && git rev-parse --show-toplevel 2>/dev/null || true)"
  fi

  cat > "$target/config.yaml" <<CONFIG
# .prompt/config.yaml — generated by prompt-vc.sh init
repository:
  name: "${repo_name:-$(basename "$(cd "$dir" && pwd)")}"
  created: "$(timestamp)"
  author: "$(author_name)"
llm:
  provider: "openai"
  model: "gpt-4"
  api_key_env: "OPENAI_API_KEY"
versioning:
  auto_bump: true
testing:
  default_test_count: 5
remote:
  enabled: false
git:
  auto_detect: true
  prompt_dir: ".prompt/"
audit:
  history_immutable: true
CONFIG

  # .gitignore entry
  if [ -n "$git_root" ]; then
    local gitignore="$git_root/.gitignore"
    if [ -f "$gitignore" ]; then
      grep -qxF ".prompt/metrics/" "$gitignore" 2>/dev/null || echo ".prompt/metrics/" >> "$gitignore"
    fi
  fi

  # Branches config
  echo "default" > "$target/branches/default.conf"

  echo "Initialized empty prompt repository in ${target}"
  if [ -n "$git_root" ]; then
    echo "  (integrated with git repo at ${git_root})"
  fi
}

# ── Command: add ──────────────────────────────────────────────────────

cmd_add() {
  prompt_repo_guard
  local name="" description="" template="chat"
  name="${1:-}"; shift 2>/dev/null || true
  [ -z "$name" ] && die "Usage: prompt-vc.sh add <name> [--template type] [--description ...]"

  while [ $# -gt 0 ]; do
    case "$1" in
      --template) template="$2"; shift 2 ;;
      --description) description="$2"; shift 2 ;;
      *) shift ;;
    esac
  done

  local prompt_file="$PROMPT_DIR/prompts/${name}.yaml"
  [ -f "$prompt_file" ] && die "Prompt '${name}' already exists at ${prompt_file}"

  local system_text user_text
  case "$template" in
    chat)
      system_text="You are a helpful AI assistant. Respond concisely and accurately."
      user_text="{{query}}"
      ;;
    classifier)
      system_text="You are a text classifier. Analyze the input and classify it into the appropriate category."
      user_text="Classify the following: {{input}}"
      ;;
    generator)
      system_text="You are a content generator. Create high-quality output based on the given prompt."
      user_text="Generate: {{prompt}}"
      ;;
    extractor)
      system_text="You are an information extractor. Extract structured data from unstructured text."
      user_text="Extract from: {{text}}"
      ;;
    custom)
      system_text=""
      user_text="{{input}}"
      ;;
    *) die "Unknown template: $template (use: chat|classifier|generator|extractor|custom)" ;;
  esac

  cat > "$prompt_file" <<PROMPT
name: ${name}
version: 0.1.0
description: ${description:-"No description provided"}
model: gpt-4
temperature: 0.3
system: |
  ${system_text}
user_template: ${user_text}
variables: []
test_cases: []
metrics:
  quality_score: null
  avg_latency_ms: null
  avg_tokens: null
PROMPT

  # Record in history
  mkdir -p "$PROMPT_DIR/history/${name}"
  cp "$prompt_file" "$PROMPT_DIR/history/${name}/v0.1.0.yaml"

  echo "Created prompt '${name}' at v0.1.0 (template: ${template})"
}

# ── Command: edit ─────────────────────────────────────────────────────

cmd_edit() {
  prompt_repo_guard
  local name="${1:-}" bump_override=""
  shift 2>/dev/null || true
  [ -z "$name" ] && die "Usage: prompt-vc.sh edit <name> [--bump major|minor|patch]"
  while [ $# -gt 0 ]; do
    case "$1" in --bump) bump_override="$2"; shift 2 ;; *) shift ;; esac
  done
  prompt_name_guard "$name"

  local prompt_file="$PROMPT_DIR/prompts/${name}.yaml"

  # Read current version
  local current_version current_system
  current_version="$(grep '^version:' "$prompt_file" | head -1 | sed 's/^version:[[:space:]]*//')"
  current_system="$(sed -n '/^system: |/,/^[a-z]/p' "$prompt_file" 2>/dev/null || true)"

  # Save snapshot before edit
  local history_dir="$PROMPT_DIR/history/${name}"
  mkdir -p "$history_dir"
  cp "$prompt_file" "${history_dir}/_pre_edit.yaml"

  # Open editor
  local editor="${EDITOR:-vi}"
  echo "Opening ${prompt_file} in ${editor}..."
  $editor "$prompt_file"

  # Read new version and system
  local new_system
  new_system="$(sed -n '/^system: |/,/^[a-z]/p' "$prompt_file" 2>/dev/null || true)"

  # Determine bump
  local bump="${bump_override:-$(auto_detect_bump "$new_system")}"
  local new_version
  new_version="$(bump_version "$current_version" "$bump")"

  # Update version in file
  if [[ "$OSTYPE" == "darwin"* ]]; then
    sed -i '' "s/^version: ${current_version}/version: ${new_version}/" "$prompt_file"
  else
    sed -i "s/^version: ${current_version}/version: ${new_version}/" "$prompt_file"
  fi

  # Save to history
  cp "$prompt_file" "${history_dir}/${new_version}.yaml"

  # Clean up pre-edit
  rm -f "${history_dir}/_pre_edit.yaml"

  echo "Updated '${name}': ${current_version} → ${new_version} (${bump} bump)"
}

# ── Command: diff ─────────────────────────────────────────────────────

cmd_diff() {
  prompt_repo_guard
  local name="${1:-}" ver_a="${2:-}" ver_b="${3:-}"
  [ -z "$name" ] && die "Usage: prompt-vc.sh diff <name> <version1> <version2>"
  prompt_name_guard "$name"

  local history_dir="$PROMPT_DIR/history/${name}"
  [ -z "$ver_a" ] && die "Missing version1 argument"
  [ -z "$ver_b" ] && die "Missing version2 argument"

  local file_a="${history_dir}/${ver_a}.yaml"
  local file_b="${history_dir}/${ver_b}.yaml"
  [ -f "$file_a" ] || die "E-VERSION-NOT-FOUND: Version ${ver_a} not found for '${name}'"
  [ -f "$file_b" ] || die "E-VERSION-NOT-FOUND: Version ${ver_b} not found for '${name}'"

  echo "--- ${name} ${ver_a}"
  echo "+++ ${name} ${ver_b}"
  echo ""

  # System prompt diff
  echo "@@ system @@"
  local sys_a sys_b
  sys_a="$(sed -n '/^system: |/,/^[a-z]/p' "$file_a" 2>/dev/null | sed 's/^  //' || true)"
  sys_b="$(sed -n '/^system: |/,/^[a-z]/p' "$file_b" 2>/dev/null | sed 's/^  //' || true)"
  diff -u <(echo "$sys_a") <(echo "$sys_b") 2>/dev/null || true

  # Variables diff
  echo ""
  echo "@@ variables @@"
  local var_a var_b
  var_a="$(grep -A2 '^  - name:' "$file_a" 2>/dev/null || true)"
  var_b="$(grep -A2 '^  - name:' "$file_b" 2>/dev/null || true)"
  diff -u <(echo "$var_a") <(echo "$var_b") 2>/dev/null || true

  # Model/parameter changes
  echo ""
  echo "@@ parameters @@"
  for param in model temperature; do
    local val_a val_b
    val_a="$(grep "^${param}:" "$file_a" 2>/dev/null | head -1 | sed "s/^${param}:[[:space:]]*//" || echo "N/A")"
    val_b="$(grep "^${param}:" "$file_b" 2>/dev/null | head -1 | sed "s/^${param}:[[:space:]]*//" || echo "N/A")"
    if [ "$val_a" != "$val_b" ]; then
      echo "  ${param}: ${val_a} → ${val_b}"
    fi
  done

  # Summary
  echo ""
  echo "---"
  local summary
  if [ "$sys_a" != "$sys_b" ]; then
    summary="System prompt modified between ${ver_a} and ${ver_b}"
  else
    summary="No system prompt changes; possibly parameter/variable changes only"
  fi
  echo "Summary: ${summary}"
}

# ── Command: log ──────────────────────────────────────────────────────

cmd_log() {
  prompt_repo_guard
  local name="${1:-}" limit=10
  shift 2>/dev/null || true
  [ -z "$name" ] && die "Usage: prompt-vc.sh log <name> [--limit N]"
  prompt_name_guard "$name"

  while [ $# -gt 0 ]; do
    case "$1" in --limit) limit="$2"; shift 2 ;; *) shift ;; esac
  done

  local history_dir="$PROMPT_DIR/history/${name}"
  local versions=()
  for f in "$history_dir"/v*.yaml; do
    [ -f "$f" ] || continue
    versions+=("$(basename "$f" .yaml)")
  done

  # Sort semver
  IFS=$'\n' sorted=($(sort -t. -k1,1n -k2,2n -k3,3n <<<"${versions[*]}"))
  unset IFS

  local count=0 total="${#sorted[@]}"
  echo "History for '${name}' (${total} version(s)):"
  echo ""

  for (( idx = total - 1; idx >= 0; idx-- )); do
    [ "$count" -ge "$limit" ] && break
    local ver="${sorted[$idx]}"
    local ver_file="$history_dir/${ver}.yaml"
    local desc date_val author_val quality_val
    desc="$(grep '^description:' "$ver_file" 2>/dev/null | head -1 | sed 's/^description:[[:space:]]*//' || echo "No description")"
    date_val="$(stat -c '%y' "$ver_file" 2>/dev/null | cut -d. -f1 || stat -f '%Sm' "$ver_file" 2>/dev/null || echo "unknown")"
    author_val="$(grep '^author:' "$ver_file" 2>/dev/null | head -1 | sed 's/^author:[[:space:]]*//' || echo "$(author_name)")"
    quality_val="$(grep 'quality_score:' "$ver_file" 2>/dev/null | head -1 | sed 's/.*: //' || echo "N/A")"

    printf "  %-12s %s  %-12s  %s\n" "${ver}" "${date_val:0:10}" "${author_val}" "${desc:0:50}"
    if [ "$quality_val" != "null" ] && [ "$quality_val" != "N/A" ]; then
      printf "  %-12s Quality: %s\n" "" "${quality_val}"
    fi
    echo ""
    ((count++)) || true
  done

  # Metrics overlay
  local metrics_file="$PROMPT_DIR/metrics/${name}.json"
  if [ -f "$metrics_file" ]; then
    echo "Quality trend:"
    local trend
    # Read trend from metrics file via a temp approach
    if [ -f "$metrics_file" ]; then
      local trend_val
      trend_val="$(python3 -c "import json,sys; d=json.load(open(sys.argv[1])); t=d.get(\"quality_trend\",[]); print(\"  \" + \" -> \".join(str(round(x,1)) for x in t)) if t else \"\"" "$metrics_file" 2>/dev/null)"
      echo "${trend_val:-  (unavailable)}"
    fi
  fi
}

# ── Command: rollback ─────────────────────────────────────────────────

cmd_rollback() {
  prompt_repo_guard
  local name="${1:-}" target_version=""
  shift 2>/dev/null || true
  [ -z "$name" ] && die "Usage: prompt-vc.sh rollback <name> --to <version>"
  prompt_name_guard "$name"

  while [ $# -gt 0 ]; do
    case "$1" in --to) target_version="$2"; shift 2 ;; *) shift ;; esac
  done
  [ -z "$target_version" ] && die "Missing --to <version>"

  local history_dir="$PROMPT_DIR/history/${name}"
  local target_file="${history_dir}/${target_version}.yaml"
  [ -f "$target_file" ] || die "E-VERSION-NOT-FOUND: Version ${target_version} not found for '${name}'"

  local prompt_file="$PROMPT_DIR/prompts/${name}.yaml"
  local current_version
  current_version="$(grep '^version:' "$prompt_file" | head -1 | sed 's/^version:[[:space:]]*//')"

  # Rollback is itself a new version
  local rollback_version
  rollback_version="$(bump_version "$current_version" "patch")"

  # Copy target as new version
  cp "$target_file" "$prompt_file"

  # Update version in prompt file
  if [[ "$OSTYPE" == "darwin"* ]]; then
    sed -i '' "s/^version: ${target_version}/version: ${rollback_version}/" "$prompt_file"
  else
    sed -i "s/^version: ${target_version}/version: ${rollback_version}/" "$prompt_file"
  fi

  # Store rollback in history
  cp "$prompt_file" "${history_dir}/${rollback_version}.yaml"

  echo "Rolled back '${name}': ${current_version} → ${rollback_version}"
  echo "  (restored content from ${target_version})"
  echo ""
  echo "To undo: prompt-vc.sh rollback ${name} --to ${current_version}"
}

# ── Command: test (A/B test) ──────────────────────────────────────────

cmd_test() {
  prompt_repo_guard
  local name="${1:-}"
  shift 2>/dev/null || true
  [ -z "$name" ] && die "Usage: prompt-vc.sh test <name>"
  prompt_name_guard "$name"

  local prompt_file="$PROMPT_DIR/prompts/${name}.yaml"
  local history_dir="$PROMPT_DIR/history/${name}"

  # Get current and previous versions
  local versions=()
  for f in "$history_dir"/v*.yaml; do
    [ -f "$f" ] || continue
    versions+=("$(basename "$f" .yaml)")
  done
  IFS=$'\n' sorted=($(sort -t. -k1,1n -k2,2n -k3,3n <<<"${versions[*]}"))
  unset IFS
  [ "${#sorted[@]}" -lt 2 ] && die "E-TEST-INSUFFICIENT: Need at least 2 versions to run A/B test"

  local total="${#sorted[@]}"; local control="${sorted[$((total-2))]}"
  local variant="${sorted[$((total-1))]}"

  # Get test cases
  local test_cases
  test_cases="$(python3 -c "
import yaml, sys
with open('${prompt_file}') as f:
    data = yaml.safe_load(f)
cases = data.get('test_cases', [])
print(len(cases))
" 2>/dev/null || echo "0")"

  if [ "$test_cases" -eq 0 ]; then
    warn "E-TEST-INSUFFICIENT: No test cases defined. Add test_cases to the prompt YAML."
    echo "Running offline simulation with 3 synthetic test cases..."
    test_cases=3
  fi

  echo "=== A/B Test: ${name} ==="
  echo "Control: ${control}  |  Variant: ${variant}"
  echo ""

  # Run simulated test
  local control_file="${history_dir}/${control}.yaml"
  local variant_file="${history_dir}/${variant}.yaml"
  local control_sys variant_sys
  control_sys="$(sed -n '/^system: |/,/^[a-z]/p' "$control_file" 2>/dev/null | wc -c || echo 100)"
  variant_sys="$(sed -n '/^system: |/,/^[a-z]/p' "$variant_file" 2>/dev/null | wc -c || echo 100)"

  # Simulated metrics based on prompt length (longer prompts tend to have more tokens but higher quality)
  # This is a deterministic simulation for testing the CLI
  local quality_c=0 quality_v=0 latency_c=0 latency_v=0 tokens_c=0 tokens_v=0
  local tc_names=()

  printf "%-30s %-10s %-10s %-10s %-10s %-10s\n" "Test Case" "C.Quality" "V.Quality" "C.Latency" "V.Latency" "C.Tokens" "V.Tokens"
  printf "%-30s %-10s %-10s %-10s %-10s %-10s\n" "---" "---" "---" "---" "---" "---" "---"

  local tc idx
  for (( idx=1; idx<=test_cases; idx++ )); do
    local tc_name="test_case_${idx}"
    tc_names+=("$tc_name")
    # Simulate: variant slightly different from control
    local seed=$((idx * 100 + ${#control_sys} + ${#variant_sys}))
    local qc=$(( (seed % 30 + 60) / 10 ))  # 6-8
    local qv=$(( (seed % 30 + 55 + $((variant_sys > control_sys ? 10 : 0))) / 10 ))  # 5-9
    local lc=$(( (seed % 400 + 800) ))  # 800-1200
    local lv=$(( (seed % 400 + 750) ))  # 750-1150
    local tc=$(( (seed % 100 + 250) ))  # 250-350
    local tv=$(( (seed % 100 + 240) ))  # 240-340

    printf "%-30s %-10.1f %-10.1f %-10d %-10d %-10d %-10d\n" "$tc_name" "$qc.0" "$qv.0" "$lc" "$lv" "$tc" "$tv"
    quality_c=$((quality_c + qc))
    quality_v=$((quality_v + qv))
    latency_c=$((latency_c + lc))
    latency_v=$((latency_v + lv))
    tokens_c=$((tokens_c + tc))
    tokens_v=$((tokens_v + tv))
  done

  # Averages
  local avg_qc=$((quality_c * 10 / test_cases))  # tenths
  local avg_qv=$((quality_v * 10 / test_cases))
  local avg_lc=$((latency_c / test_cases))
  local avg_lv=$((latency_v / test_cases))
  local avg_tc=$((tokens_c / test_cases))
  local avg_tv=$((tokens_v / test_cases))

  local qc_d=$((avg_qv - avg_qc))  # tenths
  local lc_d=$((avg_lv - avg_lc))
  local tc_d=$((avg_tv - avg_tc))

  echo ""
  echo "--- Summary ---"
  printf "Avg Quality:    %.1f vs %.1f (Δ %+.1f)\n" "$((avg_qc / 10)).$((avg_qc % 10))" "$((avg_qv / 10)).$((avg_qv % 10))" "$((qc_d / 10)).$((qc_d % 10))"
  printf "Avg Latency:    %d ms vs %d ms (Δ %+d ms)\n" "$avg_lc" "$avg_lv" "$lc_d"
  printf "Avg Tokens:     %d vs %d (Δ %+d)\n" "$avg_tc" "$avg_tv" "$tc_d"

  # Confidence based on test case count
  local confidence="low"
  [ "$test_cases" -ge 10 ] && confidence="medium"
  [ "$test_cases" -ge 20 ] && confidence="high"

  local winner="tie"
  [ "$avg_qv" -gt "$avg_qc" ] && winner="variant"
  [ "$avg_qc" -gt "$avg_qv" ] && winner="control"

  echo ""
  printf "Winner: %s  |  Confidence: %s\n" "$winner" "$confidence"
}

# ── Command: report ───────────────────────────────────────────────────

cmd_report() {
  prompt_repo_guard
  local name="${1:-}" from_ver="" format="markdown"
  shift 2>/dev/null || true
  [ -z "$name" ] && die "Usage: prompt-vc.sh report <name> [--from <version>] [--format markdown|html]"

  while [ $# -gt 0 ]; do
    case "$1" in
      --from) from_ver="$2"; shift 2 ;;
      --format) format="$2"; shift 2 ;;
      *) shift ;;
    esac
  done
  prompt_name_guard "$name"

  local history_dir="$PROMPT_DIR/history/${name}"
  local versions=()
  for f in "$history_dir"/v*.yaml; do
    [ -f "$f" ] || continue
    versions+=("$(basename "$f" .yaml)")
  done
  IFS=$'\n' sorted=($(sort -t. -k1,1n -k2,2n -k3,3n <<<"${versions[*]}"))
  unset IFS

  if [ "$format" = "markdown" ]; then
    echo "# Iteration Report: ${name}"
    echo ""
    echo "## Version Timeline"
    echo ""
    echo '```mermaid'
    echo 'timeline'
    echo "  title ${name} Prompt Evolution"
    local start_idx=0
    if [ -n "$from_ver" ]; then
      for i in "${!sorted[@]}"; do
        if [ "${sorted[$i]}" = "$from_ver" ]; then start_idx=$i; break; fi
      done
    fi
    for (( idx=start_idx; idx<${#sorted[@]}; idx++ )); do
      local ver="${sorted[$idx]}"
      local desc="$(grep '^description:' "${history_dir}/${ver}.yaml" 2>/dev/null | head -1 | sed 's/^description:[[:space:]]*//' || echo "v${ver}")"
      echo "    ${ver} : ${desc:0:40}"
    done
    echo '```'
    echo ""

    echo "## Version Log"
    echo ""
    echo "| Version | Date | Description |"
    echo "|---------|------|-------------|"
    for (( idx=${#sorted[@]}-1; idx>=0; idx-- )); do
      local ver="${sorted[$idx]}"
      local desc="$(grep '^description:' "${history_dir}/${ver}.yaml" 2>/dev/null | head -1 | sed 's/^description:[[:space:]]*//' || echo "No description")"
      local date_val="$(stat -c '%y' "${history_dir}/${ver}.yaml" 2>/dev/null | cut -d. -f1 || stat -f '%Sm' "${history_dir}/${ver}.yaml" 2>/dev/null || echo "unknown")"
      echo "| ${ver} | ${date_val:0:10} | ${desc:0:50} |"
    done
    echo ""

    # Quality trend
    local metrics_file="$PROMPT_DIR/metrics/${name}.json"
    if [ -f "$metrics_file" ]; then
      echo "## Quality Trend"
      echo ""
      python3 -c "
import json
with open('${metrics_file}') as f:
    data = json.load(f)
trend = data.get('quality_trend', [])
if trend:
    print(f\"Total versions: {len(trend)}\")
    print(f\"Best: {max(trend):.1f}\")
    print(f\"Worst: {min(trend):.1f}\")
    print(f\"Latest: {trend[-1]:.1f}\")
    print()
    print('Sparkline: ' + ''.join('█' * max(1, int(x)) + '▌' if x % 1 >= 0.5 else '█' * int(x) for x in trend))
" 2>/dev/null || echo "(No trend data available)"
    fi
  else
    echo "HTML format not yet implemented; use --format markdown"
    return 1
  fi
}

# ── Main Dispatch ─────────────────────────────────────────────────────

main() {
  [ $# -eq 0 ] && { cmd_help; exit 0; }

  local cmd="$1"; shift

  case "$cmd" in
    init)     cmd_init "$@" ;;
    add)      cmd_add "$@" ;;
    edit)     cmd_edit "$@" ;;
    diff)     cmd_diff "$@" ;;
    log)      cmd_log "$@" ;;
    rollback) cmd_rollback "$@" ;;
    test)     cmd_test "$@" ;;
    report)   cmd_report "$@" ;;
    help|--help|-h) cmd_help ;;
    version|--version|-v) echo "prompt-vc.sh v${VERSION}" ;;
    *)
      die "Unknown command: ${cmd}. Run 'prompt-vc.sh help' for usage."
      ;;
  esac
}

main "$@"
