#!/usr/bin/env python3
"""grade_subj.py — AI-grading of subjective questions from 超星 homework.

Uses config.json for API settings. Reads subj_questions.json (generated by extract_subj.py).

Usage:
    python grade_subj.py --config config.json

Output: {work_dir}/subj_graded.json
"""

import json, requests, time, os, re, sys

def load_config():
    cfg_path = os.path.join(os.path.dirname(__file__), '..', 'config.json')
    # Also check --config arg
    for i, a in enumerate(sys.argv):
        if a == '--config' and i + 1 < len(sys.argv):
            cfg_path = sys.argv[i+1]
    
    if os.path.exists(cfg_path):
        with open(cfg_path, 'r') as f:
            return json.load(f)
    raise FileNotFoundError(f'config.json not found at {cfg_path}')

CONFIG = load_config()
API = CONFIG['api']
WORK_DIR = CONFIG['paths']['work_dir']
GRADING = CONFIG['grading']

API_KEY = API['key']
API_URL = API['base_url']
MODEL = API['model']
RATE_LIMIT = GRADING.get('rate_limit_seconds', 0.15)
SAVE_EVERY = GRADING.get('save_every', 20)

QUESTIONS_FILE = os.path.join(WORK_DIR, 'subj_questions.json')
GRADED_FILE = os.path.join(WORK_DIR, 'subj_graded.json')

def grade_one(question_text, student_answer, full_score):
    prompt = f"""批改学生答案，返回分数数字。

题目：{question_text}
学生答案：{student_answer}
满分：{full_score}分

评分标准：
- 完全正确=满分
- 部分正确=按比例给分
- 完全错误=0分
- 倾向宽容给分

最终评分（仅输出数字）："""

    try:
        resp = requests.post(API_URL, json={
            'model': MODEL,
            'messages': [{'role': 'user', 'content': prompt}],
            'temperature': API.get('temperature', 0),
            'max_tokens': API.get('max_tokens', 500)
        }, headers={
            'Authorization': f'Bearer {API_KEY}',
            'Content-Type': 'application/json'
        }, timeout=60)
        
        if resp.status_code != 200:
            print(f'  HTTP {resp.status_code}: {resp.text[:200]}')
            return None
        
        result = resp.json()
        msg = result['choices'][0]['message']
        text = msg.get('content', '') or msg.get('reasoning', '')
        
        if not text:
            print(f'  Empty response: {json.dumps(msg)[:100]}')
            return None
        
        numbers = re.findall(r'(\d+\.?\d*)', text)
        if not numbers:
            print(f'  No numbers in: {text[:80]}')
            return None
        
        for n in reversed(numbers):
            score = float(n)
            if 0 <= score <= full_score:
                return round(score, 1)
        
        score = float(numbers[-1])
        return round(max(0, min(score, full_score)), 1)
            
    except Exception as e:
        print(f'  Exception: {e}')
        return None

def main():
    if 'YOUR_API_KEY' in API_KEY:
        print('ERROR: Please set api.key in config.json')
        return
    
    if not os.path.exists(QUESTIONS_FILE):
        print(f'ERROR: {QUESTIONS_FILE} not found. Run extract_subj.py first.')
        return
    
    with open(QUESTIONS_FILE, 'r', encoding='utf-8') as f:
        questions = json.load(f)
    
    graded = {}
    if os.path.exists(GRADED_FILE):
        with open(GRADED_FILE, 'r', encoding='utf-8') as f:
            graded = json.load(f)
    
    print(f'Existing: {len(graded)}, To do: {len(questions)}')
    
    total = len(questions)
    
    for i, q in enumerate(questions):
        key = f"{q['student']}|{q['work']}|{q['qid']}"
        
        if key in graded:
            continue
        
        if i % SAVE_EVERY == 0 and i > 0:
            done = sum(1 for v in graded.values() if v is not None)
            total_fail = sum(1 for v in graded.values() if v is None)
            print(f'[{done}/{total}] saving... (fails: {total_fail})')
            with open(GRADED_FILE, 'w', encoding='utf-8') as f:
                json.dump(graded, f, ensure_ascii=False)
        
        short = re.sub(r'\s+', ' ', q['title'][:60]).strip()
        print(f'  #{i+1} {q["student"]} {short} /{q["full_score"]} -> ', end='', flush=True)
        
        score = grade_one(q['question'], q['answer'], q['full_score'])
        
        if score is not None:
            print(score)
            graded[key] = score
        else:
            print('FAIL')
            graded[key] = None
        
        time.sleep(RATE_LIMIT)
    
    # Final save
    with open(GRADED_FILE, 'w', encoding='utf-8') as f:
        json.dump(graded, f, ensure_ascii=False)
    
    done = sum(1 for v in graded.values() if v is not None)
    fail = sum(1 for v in graded.values() if v is None)
    print(f'\nDone: {done} OK, {fail} FAIL, {total} total')

if __name__ == '__main__':
    main()