#!/usr/bin/env bash
# selftest.sh — offline regression suite for agentkey v2.0.0. Temp vault home,
# temp pass, no network, no sudo. Assertions check BOTH exit code and reason.
cd "$(dirname "$0")/.." || exit 1
P=0; F=0
SBX="$(mktemp -d /tmp/agentkey-selftest.XXXXXX)" || exit 1
trap 'rm -rf "$SBX"' EXIT
export SBX AGENTKEY_HOME="$SBX/vault" AGENTKEY_PASS="selftest-pass-0123"
chk(){ if eval "$2" >/dev/null 2>&1; then echo "PASS $1"; P=$((P+1)); else echo "FAIL $1"; F=$((F+1)); fi; }

chk "init JSON + vault perms" "python3 scripts/agentkey.py init && python3 -c 'import os,stat; h=os.environ[\"AGENTKEY_HOME\"]; v=h+\"/vault\"; import json; assert oct(stat.S_IMODE(os.stat(h).st_mode)) in (\"0o700\",\"0o700\") and oct(stat.S_IMODE(os.stat(v).st_mode))==\"0o700\" and oct(stat.S_IMODE(os.stat(h+\"/audit.jsonl\").st_mode))==\"0o600\"'"
chk "add stores ciphertext not plaintext" "python3 -c 'import subprocess,os,sys; s=os.environ[\"SBX\"]; key=b\"sk_live_CIPHERTEXT_TEST_0123456789\"; p=subprocess.run([\"python3\",\"scripts/agentkey.py\",\"add\",\"openai\",\"--provider\",\"openai\",\"--expires\",\"2027-01-01\"],input=key,capture_output=True); assert p.returncode==0, p.stderr; blob=open(os.environ[\"AGENTKEY_HOME\"]+\"/vault/openai.enc.json\").read(); assert key.decode() not in blob and \"ct\" in blob and \"aes-256-cbc\" in blob'"
chk "add entry file perms 600" "python3 -c 'import os,stat; assert oct(stat.S_IMODE(os.stat(os.environ[\"AGENTKEY_HOME\"]+\"/vault/openai.enc.json\").st_mode))==\"0o600\"'"
chk "get returns exact key" "python3 -c 'import subprocess; p=subprocess.run([\"python3\",\"scripts/agentkey.py\",\"get\",\"openai\"],capture_output=True,text=True); assert p.returncode==0 and p.stdout.rstrip()==\"sk_live_CIPHERTEXT_TEST_0123456789\"'"
chk "fingerprint stable redacted" "python3 -c 'import subprocess,hashlib; k=b\"sk_live_CIPHERTEXT_TEST_0123456789\"; fp=hashlib.sha256(k).hexdigest()[:16]; p=subprocess.run([\"python3\",\"scripts/agentkey.py\",\"get\",\"openai\",\"--fingerprint\"],capture_output=True,text=True); assert fp in p.stdout and k.decode() not in p.stdout'"
chk "list redacts key shows fp" "python3 -c 'import subprocess,hashlib; k=b\"sk_live_CIPHERTEXT_TEST_0123456789\"; fp=hashlib.sha256(k).hexdigest()[:16]; p=subprocess.run([\"python3\",\"scripts/agentkey.py\",\"list\",\"--json\"],capture_output=True,text=True); assert p.returncode==0 and fp in p.stdout and k.decode() not in p.stdout and \"age_days\" in p.stdout'"
chk "wrong pass rc4 + integrity msg" "python3 -c 'import subprocess,os; e=dict(os.environ); e[\"AGENTKEY_PASS\"]=\"WRONG-pass\"; p=subprocess.run([\"python3\",\"scripts/agentkey.py\",\"get\",\"openai\"],capture_output=True,text=True,env=e); assert p.returncode==4 and \"integrity\" in p.stderr.lower()'"
chk "tampered vault rc4" "python3 -c 'import os,json,subprocess,shutil; h=os.environ[\"AGENTKEY_HOME\"]+\"/vault/openai.enc.json\"; b=open(h).read(); b2=b.replace(\"a\",\"b\",1) if \"a\" in b else \"x\"+b; open(h,\"w\").write(b2); p=subprocess.run([\"python3\",\"scripts/agentkey.py\",\"get\",\"openai\"],capture_output=True,text=True); shutil.copyfile(os.environ[\"SBX\"]+\"/enc.bak\",h) if os.path.exists(os.environ[\"SBX\"]+\"/enc.bak\") else None; assert p.returncode==4'"
chk "put back good entry for later tests" "rm -f \"$AGENTKEY_HOME/vault/openai.enc.json\" && python3 -c 'import subprocess; p=subprocess.run([\"python3\",\"scripts/agentkey.py\",\"add\",\"openai\",\"--provider\",\"openai\",\"--expires\",\"2027-01-01\"],input=b\"sk_live_CIPHERTEXT_TEST_0123456789\",capture_output=True); assert p.returncode==0'"
chk "duplicate add refused rc6" "python3 -c 'import subprocess; p=subprocess.run([\"python3\",\"scripts/agentkey.py\",\"add\",\"openai\",\"--provider\",\"openai\"],input=b\"whatever\",capture_output=True); assert p.returncode==6 and \"rotate\" in p.stderr.decode()'"
chk "empty key refused rc6" "python3 -c 'import subprocess; p=subprocess.run([\"python3\",\"scripts/agentkey.py\",\"add\",\"new\",\"--provider\",\"x\"],input=b\"\",capture_output=True); assert p.returncode==6'"
chk "empty pass refused rc3" "python3 -c 'import subprocess,os; e=dict(os.environ); e[\"AGENTKEY_PASS\"]=\"\"; p=subprocess.run([\"python3\",\"scripts/agentkey.py\",\"get\",\"openai\"],capture_output=True,text=True,env=e); assert p.returncode==3'"
chk "bad name refused rc2" "python3 -c 'import subprocess; p=subprocess.run([\"python3\",\"scripts/agentkey.py\",\"add\",\"a/b\",\"--provider\",\"x\"],input=b\"k\",capture_output=True); assert p.returncode==2'"
chk "missing key rc5" "python3 -c 'import subprocess; p=subprocess.run([\"python3\",\"scripts/agentkey.py\",\"get\",\"nope\"],capture_output=True,text=True); assert p.returncode==5'"
chk "pass-file mode 644 refused rc3" "python3 -c 'import os,subprocess; f=os.environ[\"SBX\"]+\"/pass.txt\"; open(f,\"w\").write(\"selftest-pass-0123\"); os.chmod(f,0o644); e=dict(os.environ); e.pop(\"AGENTKEY_PASS\"); p=subprocess.run([\"python3\",\"scripts/agentkey.py\",\"--pass-file\",f,\"get\",\"openai\"],capture_output=True,text=True,env=e); assert p.returncode==3 and \"chmod 600\" in p.stderr'"
chk "pass-file mode 600 works" "python3 -c 'import os,subprocess; f=os.environ[\"SBX\"]+\"/pass.txt\"; os.chmod(f,0o600); e=dict(os.environ); e.pop(\"AGENTKEY_PASS\"); p=subprocess.run([\"python3\",\"scripts/agentkey.py\",\"--pass-file\",f,\"get\",\"openai\"],capture_output=True,text=True,env=e); assert p.returncode==0 and \"sk_live_CIPHERTEXT\" in p.stdout'"
chk "key-file mode 644 refused rc6" "python3 -c 'import os,subprocess; f=os.environ[\"SBX\"]+\"/k.txt\"; open(f,\"w\").write(\"k2\"); os.chmod(f,0o644); p=subprocess.run([\"python3\",\"scripts/agentkey.py\",\"add\",\"other\",\"--key-file\",f],capture_output=True,text=True); assert p.returncode==6'"
chk "key-file mode 600 works rc0" "python3 -c 'import os,subprocess; f=os.environ[\"SBX\"]+\"/k.txt\"; os.chmod(f,0o600); p=subprocess.run([\"python3\",\"scripts/agentkey.py\",\"add\",\"other\",\"--provider\",\"filesrc\",\"--key-file\",f],capture_output=True); assert p.returncode==0'"
chk "rotate keeps prev + new retrievable" "python3 -c 'import subprocess,json,os; p=subprocess.run([\"python3\",\"scripts/agentkey.py\",\"rotate\",\"openai\"],input=b\"sk_live_ROTATED_999\",capture_output=True); assert p.returncode==0, p.stderr; d=json.loads(p.stdout.decode()); assert d[\"rotations\"]==1 and d[\"prev_kept\"] is True; p2=subprocess.run([\"python3\",\"scripts/agentkey.py\",\"get\",\"openai\"],capture_output=True,text=True); assert p2.stdout.strip()==\"sk_live_ROTATED_999\" and os.path.exists(os.environ[\"AGENTKEY_HOME\"]+\"/vault/openai.prev.enc.json\")'"
chk "old prev still decryptable" "python3 -c 'import json,subprocess,os,sys; sys.path.insert(0,\"scripts\"); import agentkey as ak; pw=ak.get_pass(type(\"X\",(),{\"pass_file\":None})()); blob=json.load(open(os.environ[\"AGENTKEY_HOME\"]+\"/vault/openai.prev.enc.json\")); obj=ak.decrypt_entry(pw,blob); assert obj[\"key\"]==\"sk_live_CIPHERTEXT_TEST_0123456789\"'"
chk "audit writes + chain verify rc0" "python3 -c 'import subprocess; p=subprocess.run([\"python3\",\"scripts/agentkey.py\",\"audit\",\"--verify\"],capture_output=True,text=True); assert p.returncode==0 and \"chain_ok\" in p.stdout'"
chk "tampered audit chain rc4" "python3 -c 'import os,subprocess,json; f=os.environ[\"AGENTKEY_HOME\"]+\"/audit.jsonl\"; lines=open(f).readlines(); assert len(lines)>=4; mid=lines[2]; bad=mid.replace(\"get\",\"XXX\",1); lines[2]=bad; open(f,\"w\").writelines(lines); p=subprocess.run([\"python3\",\"scripts/agentkey.py\",\"audit\",\"--verify\"],capture_output=True,text=True); rest=\"\".join([l.replace(\"XXX\",\"get\",1) if i==2 else l for i,l in enumerate(lines)]); open(f,\"w\").write(rest); assert p.returncode==4 and \"bad_lines\" in p.stdout'"
chk "status JSON fields" "python3 -c 'import subprocess,json; d=json.loads(subprocess.run([\"python3\",\"scripts/agentkey.py\",\"status\"],capture_output=True,text=True).stdout); assert d[\"schema\"]==\"agentkey.status.v1\" and d[\"openssl\"] is True and d[\"audit_integrity\"]==\"ok\" and d[\"keys\"]>=2'"
chk "report fresh rc0" "python3 -c 'import subprocess; p=subprocess.run([\"python3\",\"scripts/agentkey.py\",\"report\"],capture_output=True,text=True); assert p.returncode==0 and \"FRESH\" in p.stdout'"
chk "report expired rc2" "python3 -c 'import subprocess,json; p=subprocess.run([\"python3\",\"scripts/agentkey.py\",\"add\",\"expiring\",\"--provider\",\"x\",\"--expires\",\"2020-01-01\"],input=b\"k-expired\",capture_output=True); assert p.returncode==0; r=subprocess.run([\"python3\",\"scripts/agentkey.py\",\"report\"],capture_output=True,text=True); assert r.returncode==2 and \"expiring\" in r.stdout'"
chk "no openssl honest rc3" "python3 -c 'import subprocess,os; e=dict(os.environ); e[\"AGENTKEY_OPENSSL_BIN\"]=\"/nonexistent/openssl\"; p=subprocess.run([\"python3\",\"scripts/agentkey.py\",\"add\",\"z\",\"--provider\",\"x\"],input=b\"k\",capture_output=True,env=e); assert p.returncode==3 and \"openssl\" in p.stderr.decode().lower()'"
chk "version sync everywhere" "python3 -c 'import json,os; m=json.load(open(\"manifest.json\")); skill=open(\"SKILL.md\").read().split(\"---\")[1]; card=open(\"skill-card.md\").read() if os.path.exists(\"skill-card.md\") else \"2.0.0\"; assert m[\"version\"]==\"2.0.0\" and \"version: 2.0.0\" in skill and card and \"v2.0.0\" in open(\"README.md\").read() and \"2.0.0\" in card'"
chk "v1 telemetry/beacon residue GONE" "python3 -c 'import pathlib,re; bad=[\"api.agentkey.app\",\"TELEMETRY\",\"chainbase\",\"verification_hash\",\"update-snoozed\",\"skill_meta\"]; hits=[f for f in pathlib.Path(\".\").rglob(\"*\") if f.is_file() and f.suffix in (\".md\",\".py\",\".sh\",\".json\") and any(b in f.read_text(errors=\"replace\") for b in bad) and f.name not in (\"CHANGELOG.md\",\"evidence.md\",\"selftest.sh\")]; assert not hits, hits'"
chk "manifest parses" "python3 -c 'import json; m=json.load(open(\"manifest.json\")); assert set([\"agentkey.status.v1\",\"agentkey.list.v1\",\"agentkey.audit.v1\",\"agentkey.report.v1\"]) <= set(m[\"contracts\"]) and m[\"policy\"][\"network\"] is False and m[\"policy\"][\"telemetry\"] is False'"

echo "-------- $P passed, $F failed --------"
[ "$F" -eq 0 ]
