"""
scripts/pre_dream_sql_feed.py — Pre-dream SQL corpus feeder

Runs BEFORE the OpenClaw dream cycle (e.g., 3:00 AM when dream runs at 3:30 AM).

What it does:
1. Queries SQL for memories WHERE importance >= threshold AND recent
2. Writes a clean memory/YYYY-MM-DD.md file containing only curated content
3. Records what was fed to dreams.DreamCorpus for audit trail

The OpenClaw dreamer picks up this clean file and dreams on curated content
instead of raw session noise.

Usage:
    python scripts/pre_dream_sql_feed.py
    python scripts/pre_dream_sql_feed.py --config /path/to/config.yml
    python scripts/pre_dream_sql_feed.py --dry-run   # Preview without writing
"""

import sys
import os
import argparse
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import yaml
from src.sql_connector import SQLDreamerConnector


def load_config(config_path: str) -> dict:
    with open(config_path) as f:
        return yaml.safe_load(f)


def build_memory_content(memories: list[dict]) -> str:
    """
    Format memories as a clean memory/YYYY-MM-DD.md file.
    Groups by category, orders by importance descending.
    """
    lines = []
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    lines.append(f"# Session Memory — {today}")
    lines.append(f"# Generated by openclaw-sql-dreamer (pre_dream_sql_feed.py)")
    lines.append(f"# Source: SQL memory.Memories (importance >= threshold)")
    lines.append("")

    # Group by category
    by_category: dict[str, list] = {}
    for m in memories:
        cat = m.get("category", "uncategorized")
        by_category.setdefault(cat, []).append(m)

    for category, items in sorted(by_category.items()):
        lines.append(f"## {category.replace('_', ' ').title()}")
        lines.append("")
        for m in sorted(items, key=lambda x: x.get("importance", 0), reverse=True):
            key = m.get("key_name", "")
            content = m.get("content", "").strip()
            importance = m.get("importance", 0)
            lines.append(f"### [{importance}] {key}")
            lines.append(content)
            lines.append("")

    return "\n".join(lines)


def run(config_path: str, dry_run: bool = False) -> None:
    cfg = load_config(config_path)

    workspace_dir = cfg["dreaming"]["workspace_dir"]
    importance_threshold = cfg["corpus"]["importance_threshold"]
    lookback_days = cfg["corpus"]["lookback_days"]

    today_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    output_path = Path(workspace_dir) / "memory" / f"{today_str}.md"

    print(f"pre_dream_sql_feed: {today_str}")
    print(f"  Threshold: importance >= {importance_threshold}")
    print(f"  Lookback: {lookback_days} days")
    print(f"  Output: {output_path}")

    with SQLDreamerConnector.from_config(config_path) as conn:
        memories = conn.get_corpus_memories(
            importance_threshold=importance_threshold,
            lookback_days=lookback_days,
        )

        print(f"  Memories found: {len(memories)}")

        if not memories:
            print("  ⚠️  No memories above threshold — skipping write")
            return

        content = build_memory_content(memories)

        if dry_run:
            print("\n--- DRY RUN: would write ---")
            print(content[:2000])
            if len(content) > 2000:
                print(f"... [{len(content) - 2000} more chars]")
            return

        # Write the clean memory file
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)

        print(f"  ✅ Wrote {len(content)} chars to {output_path}")

        # Record corpus batch to SQL
        conn.write_dream_corpus_batch(today_str, memories)
        print(f"  ✅ Recorded {len(memories)} corpus entries to dreams.DreamCorpus")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Pre-dream SQL corpus feeder")
    parser.add_argument("--config", default="config/config.yml", help="Path to config.yml")
    parser.add_argument("--dry-run", action="store_true", help="Preview without writing")
    args = parser.parse_args()

    run(args.config, dry_run=args.dry_run)
