#!/usr/bin/env bash
# Initialize docs/cccc workspace from templates.
# Called internally by cccc-setup.sh and other scripts.
# Does not overwrite existing files. Reads language from config.json.
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=/dev/null
source "$SCRIPT_DIR/cccc-common.sh"

ROOT="$(cccc_repo_root)"
cd "$ROOT"
cccc_init_dirs

NOW="$(cccc_now)"
SKILL_DIR="$(cccc_skill_dir)"
TEMPLATE_DIR="$SKILL_DIR/templates/cccc"

# Generate docs/cccc markdown files from templates. Never overwrite.
for file in project-brief project-map current-state architecture test-strategy roadmap milestone-backlog decision-log risk-register open-questions context-bundle README; do
  target="docs/cccc/${file}.md"
  template="$TEMPLATE_DIR/${file}.template.md"
  if [[ ! -f "$target" ]]; then
    if [[ -f "$template" ]]; then
      cp "$template" "$target"
    else
      cat > "$target" <<EOF2
# $file

Generated by cc-codex-collaborate.

Status: draft
EOF2
    fi
  fi
done

# Generate config.json if missing (fallback; normally created by cccc-setup.sh)
if [[ ! -f docs/cccc/config.json ]]; then
  if [[ -f "$TEMPLATE_DIR/config.template.json" ]]; then
    cp "$TEMPLATE_DIR/config.template.json" docs/cccc/config.json
  else
    echo '{}' > docs/cccc/config.json
  fi
fi

# Read language from config.json
LANGUAGE="$(python3 - <<'PY'
import json
try:
    data = json.loads(open('docs/cccc/config.json').read())
    lang = data.get('language', {}).get('user_language', 'auto')
    print(lang)
except Exception:
    print('auto')
PY
)"

# Generate state.json if missing; preserve all existing fields
if [[ ! -f docs/cccc/state.json ]]; then
  if [[ -f "$TEMPLATE_DIR/state.template.json" ]]; then
    cp "$TEMPLATE_DIR/state.template.json" docs/cccc/state.json
  else
    echo '{}' > docs/cccc/state.json
  fi
fi

# Update state.json: only runtime fields
CCCC_LANGUAGE="$LANGUAGE" CCCC_NOW="$NOW" python3 - <<'PY'
import json, pathlib, os
p = pathlib.Path('docs/cccc/state.json')
try:
    data = json.loads(p.read_text())
except Exception:
    data = {}

# Only set runtime status fields, never overwrite language from config
data.setdefault('skill_name', 'cc-codex-collaborate')
data.setdefault('skill_version', '0.1.4')
data.setdefault('workspace', 'docs/cccc')
data.setdefault('task', '')
data.setdefault('enabled', False)
data.setdefault('status', 'NOT_INITIALIZED')
data.setdefault('project_context_status', 'not_ready')
data.setdefault('roadmap_status', 'not_reviewed')
data.setdefault('codex_plan_review_status', 'not_run')
data.setdefault('codex_final_review_status', 'not_run')
data.setdefault('last_codex_plan_review_file', None)
data.setdefault('last_codex_milestone_review_file', None)
data.setdefault('last_codex_final_review_file', None)
data.setdefault('codex_unavailable_reason', None)
data.setdefault('current_milestone_id', None)
data.setdefault('current_milestone_codex_review_status', 'not_run')
data.setdefault('current_milestone_codex_review_file', None)
data.setdefault('completed_milestones', [])
data.setdefault('blocked_milestones', [])
data.setdefault('known_risks', [])
data.setdefault('pause_reason', None)
data.setdefault('stop_hook_continuations', 0)
data.setdefault('review_round_current', 0)
data.setdefault('fix_attempts_current', 0)
data.setdefault('last_context_update', None)
data.setdefault('mode', 'supervised-auto')
data.setdefault('created_at', os.environ.get('CCCC_NOW', ''))

data['updated_at'] = os.environ.get('CCCC_NOW', '')

# Language: prefer existing, then config, then default
existing_language = data.get('user_language')
if not existing_language or existing_language == 'unknown':
    from_config = os.environ.get('CCCC_LANGUAGE', 'auto')
    if from_config and from_config != 'auto':
        data['user_language'] = from_config
        data['language_source'] = 'from_config'

p.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n')
PY

cat > docs/cccc/runtime/last-init.txt <<EOF2
Initialized at: $NOW
User language: $LANGUAGE
EOF2

echo "Initialized cc-codex-collaborate workspace at docs/cccc"
