#!/usr/bin/env python3
"""
xhs-keepalive.py — xiaohongshu cookie / state 管理

子命令:
  inject    把 /tmp/xiaohongshu/cookies.txt (你贴的 k=v; k=v; 格式) 转成 Netscape
  load      把 cookies.txt 灌入 agent-browser (set ... --url --domain)
  check     验证 cookie 是否还有效 (用 search_result 页面能否正常打开判断)
  paths     打印当前路径配置
  state     ab state save / load / check (管理 agent-browser session)
  help      用法

注意:
  - 不依赖任何第三方库 (除 agent-browser 自身)
  - cookies 必须 chmod 600 (含 web_session + id_token 等敏感字段)
  - xhs cookie 6-12 小时会失效 (web_session 短效),需要定期重导
"""

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path

# 路径统一管理
from paths import (
    COOKIE_RAW, COOKIE_FILE, STATE_FILE, DATA_DIR,
    LEGACY_DIR, LEGACY_COOKIE, report as report_paths,
)


def err(msg):
    print(f"❌ {msg}", file=sys.stderr)


def ok(msg):
    print(f"✅ {msg}")


def cmd_inject(args):
    """把分号格式 cookies (k=v; k=v;) 转成 Netscape 格式"""
    src = Path(args.src) if args.src else (COOKIE_RAW if COOKIE_RAW.exists() else LEGACY_COOKIE)
    if not src.exists():
        err(f"源 cookie 文件不存在: {src}")
        print(f"  请把分号格式的 cookie 写到 {COOKIE_RAW}")
        print(f"  格式: a1=xxx; web_session=xxx; id_token=xxx; ...")
        return 1

    with open(src) as f:
        content = f.read().strip()

    # 解析分号分隔
    cookies = {}
    for part in content.split(';'):
        part = part.strip()
        if not part or '=' not in part:
            continue
        name, value = part.split('=', 1)
        cookies[name.strip()] = value.strip()

    if not cookies:
        err("没解析到任何 cookie")
        return 1

    # 必填字段检查
    required = ('a1', 'web_session', 'id_token')
    missing = [r for r in required if r not in cookies]
    if missing:
        err(f"缺关键字段: {missing}")
        print(f"  当前有: {list(cookies.keys())}")
        return 1

    # 转 Netscape
    domain = ".xiaohongshu.com"
    secure_cookies = {'acw_tc', 'id_token', 'web_session', 'websectiga', 'sec_poison_id'}
    http_only_cookies = {'acw_tc', 'id_token', 'web_session', 'a1', 'webId', 'websectiga'}

    lines = [
        "# Netscape HTTP Cookie File",
        "# https://curl.haxx.se/rfc/cookie_spec.html",
        "# Generated by xhs-keepalive.py inject",
        "",
    ]

    for name, value in cookies.items():
        secure = "TRUE" if name in secure_cookies else "FALSE"
        http_only = "TRUE" if name in http_only_cookies else "FALSE"
        lines.append(f"{domain}\t{http_only}\t/\t{secure}\t0\t{name}\t{value}")

    COOKIE_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(COOKIE_FILE, 'w') as f:
        f.write('\n'.join(lines) + '\n')

    os.chmod(COOKIE_FILE, 0o600)
    ok(f"已写入 {COOKIE_FILE} ({len(cookies)} 个 cookies)")
    ok("已 chmod 600")
    return 0


def _cookie_to_agent_browser_flags(name):
    """根据 cookie 名决定是否带 secure / httpOnly flag"""
    secure_cookies = {'acw_tc', 'id_token', 'web_session', 'websectiga', 'sec_poison_id'}
    http_only_cookies = {'acw_tc', 'id_token', 'web_session', 'a1', 'webId', 'websectiga'}

    flags = ['--domain', '.xiaohongshu.com', '--path', '/', '--sameSite', 'Lax']
    if name in secure_cookies:
        flags.append('--secure')
    if name in http_only_cookies:
        flags.append('--httpOnly')
    return flags


def cmd_load(args):
    """把 Netscape cookies 灌入 agent-browser (用于后续 open)"""
    if not COOKIE_FILE.exists():
        err(f"cookie 文件不存在: {COOKIE_FILE}")
        print(f"  先跑: xhs-keepalive.py inject")
        return 1

    # 清掉旧的
    subprocess.run(['agent-browser', 'cookies', 'clear'],
                   capture_output=True, text=True)

    # 读 Netscape
    count = 0
    with open(COOKIE_FILE) as f:
        for line in f:
            line = line.rstrip('\n')
            if not line or line.startswith('#'):
                continue
            parts = line.split('\t')
            if len(parts) < 7:
                continue
            domain, include_subdomain, path, secure, expires, name, value = parts[:7]
            flags = _cookie_to_agent_browser_flags(name)
            r = subprocess.run(
                ['agent-browser', 'cookies', 'set', name, value] + flags,
                capture_output=True, text=True
            )
            if r.returncode == 0:
                count += 1
            else:
                print(f"  ⚠️  {name} 失败: {r.stderr.strip()}")

    ok(f"已加载 {count} 个 cookies 到 agent-browser")
    return 0


def cmd_check(args):
    """验证 cookie 是否还有效 (用 search_result 能否正常打开)"""
    if not COOKIE_FILE.exists():
        err(f"cookie 文件不存在: {COOKIE_FILE}")
        return 1

    # 先 load
    print("Loading cookies...")
    cmd_load(args)

    # 打开一个低风险页面测试
    print("Probing https://www.xiaohongshu.com ...")
    r = subprocess.run(
        ['agent-browser', 'open', 'https://www.xiaohongshu.com/explore'],
        capture_output=True, text=True, timeout=30
    )
    out = (r.stdout + r.stderr).strip()
    print(out)

    if '300012' in out or 'IP存在风险' in out:
        err("IP 被风控 (300012) — 这是网络层问题,不是 cookie 问题")
        print("  解决: 换网络环境 (代理 / 4G 切 WiFi / 等 1-2 小时)")
        return 2

    if '安全限制' in out or 'error_code' in out:
        err("页面被重定向到错误页,cookie 可能失效或账号被风控")
        return 1

    # 检查 title
    r = subprocess.run(
        ['agent-browser', 'eval', 'document.title'],
        capture_output=True, text=True, timeout=10
    )
    title = r.stdout.strip().strip('"')
    if '小红书' in title and '安全限制' not in title and 'error' not in title.lower():
        ok(f"cookie 有效 ✓ (title: {title})")
        return 0
    else:
        err(f"页面 title 异常: {title!r}")
        return 1


def cmd_paths(args):
    report_paths()
    return 0


def cmd_state(args):
    """ab state save / load / check"""
    if args.action == 'save':
        # 先 open 一下建立 session
        subprocess.run(
            ['agent-browser', 'open', 'https://www.xiaohongshu.com/explore'],
            capture_output=True, text=True, timeout=30
        )
        r = subprocess.run(
            ['agent-browser', 'state', 'save', str(STATE_FILE)],
            capture_output=True, text=True
        )
        print(r.stdout, r.stderr)
        if r.returncode == 0:
            ok(f"state saved to {STATE_FILE}")
        return r.returncode
    elif args.action == 'load':
        # 需要先 close --all 才能用 --state 启动
        subprocess.run(['agent-browser', 'close', '--all'],
                       capture_output=True, text=True)
        r = subprocess.run(
            ['agent-browser', 'open', 'https://www.xiaohongshu.com/explore',
             '--state', str(STATE_FILE)],
            capture_output=True, text=True, timeout=30
        )
        print(r.stdout, r.stderr)
        return r.returncode
    elif args.action == 'check':
        r = subprocess.run(
            ['agent-browser', 'eval', 'document.title'],
            capture_output=True, text=True, timeout=10
        )
        print(f"title: {r.stdout.strip()}")
        return 0


def main():
    parser = argparse.ArgumentParser(
        description="xiaohongshu-search cookie / state 管理",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
子命令:
  inject              把分号格式 cookie 转 Netscape
  load                把 Netscape 灌入 agent-browser
  check               验证 cookie 是否还有效 (跑搜索页测试)
  paths               打印当前路径配置
  state {save|load|check}  管理 agent-browser session
        """
    )
    sub = parser.add_subparsers(dest='cmd', required=True)

    # inject
    p = sub.add_parser('inject', help='分号格式 cookie → Netscape')
    p.add_argument('--src', help=f'源文件 (默认 {COOKIE_RAW} 或 /tmp/xiaohongshu/cookies.txt)')

    # load
    sub.add_parser('load', help='把 cookie 灌入 agent-browser')

    # check
    sub.add_parser('check', help='验证 cookie 是否还有效')

    # paths
    sub.add_parser('paths', help='打印路径配置')

    # state
    p = sub.add_parser('state', help='管理 agent-browser state')
    p.add_argument('action', choices=['save', 'load', 'check'])

    args = parser.parse_args()
    fn = globals().get(f'cmd_{args.cmd}')
    if not fn:
        err(f"未知子命令: {args.cmd}")
        return 1
    return fn(args) or 0


if __name__ == '__main__':
    sys.exit(main())
