#!/usr/bin/env python3
"""
Tencent Cloud MPS Image Comprehension / OCR / Visual Question Answering Script

Features:
  Calls the MPS ProcessImage API to start an image comprehension task (ScheduleId=30200),
  supporting Gemini-series models for OCR, visual question answering, and image analysis.
  Polls with DescribeImageTaskDetail and returns the text response generated by the model.

  Two model selection modes are supported:
    - Specify a shortcut model ID with --definition (10000-10004). In this mode, ScheduleId and StdExtInfo are not used.
    - Specify a model name with --model-name (default: Google/gemini-2.5-flash). In this mode, ScheduleId + StdExtInfo are used.

COS Storage Convention:
  The output COS Bucket name is specified via the TENCENTCLOUD_COS_BUCKET environment variable.
  - Default output directory: /output/comprehend/

Usage:
  # Use URL input for visual question answering
  python3 scripts/mps_image_comprehend.py \
      --url "https://example.com/photo.jpg" \
      --prompt "Describe the content of this image"

  # Use COS input for OCR text extraction
  python3 scripts/mps_image_comprehend.py \
      --cos-input-key "/input/document.jpg" \
      --prompt "Recognize all text in the image"

  # Specify a shortcut model definition ID
  python3 scripts/mps_image_comprehend.py \
      --url "https://example.com/photo.jpg" \
      --prompt "What objects are in the image?" \
      --definition 10002

  # Specify a model name + temperature
  python3 scripts/mps_image_comprehend.py \
      --url "https://example.com/photo.jpg" \
      --prompt "Analyze the composition and color of this image" \
      --model-name "Google/gemini-2.5-flash-pro" \
      --temperature 0.7

  # Use a local file (uploaded to COS automatically)
  python3 scripts/mps_image_comprehend.py \
      --local-file ./photo.jpg \
      --prompt "What animal is this?"

  # Submit task only, do not wait for result (returns TaskId)
  python3 scripts/mps_image_comprehend.py \
      --url "https://example.com/photo.jpg" \
      --prompt "Describe the image content" \
      --no-wait

  # Dry-run mode: print request payload only
  python3 scripts/mps_image_comprehend.py \
      --url "https://example.com/photo.jpg" \
      --prompt "Recognize the text in the image" \
      --dry-run

Environment Variables:
  TENCENTCLOUD_SECRET_ID    - Tencent Cloud SecretId (required)
  TENCENTCLOUD_SECRET_KEY   - Tencent Cloud SecretKey (required)
  TENCENTCLOUD_API_REGION   - MPS API access region (required)
  TENCENTCLOUD_COS_BUCKET   - Output COS Bucket (can be overridden by --output-bucket)
                              Also used as the default Bucket for --cos-input-key
  TENCENTCLOUD_COS_REGION   - Output COS Region (can be overridden by --output-region)
                              Also used as the default Region for --cos-input-key
"""

import argparse
import json
import os
import sys
from mps_auto_upgrade import check_sdk_version

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, _SCRIPT_DIR)

try:
    from mps_load_env import ensure_env_loaded as _ensure_env_loaded
    _LOAD_ENV_AVAILABLE = True
except ImportError:
    _LOAD_ENV_AVAILABLE = False

try:
    from mps_poll_task import poll_image_task, auto_upload_local_file
    _POLL_AVAILABLE = True
except ImportError:
    _POLL_AVAILABLE = False

check_sdk_version()
try:
    from tencentcloud.common import credential
    from tencentcloud.common.profile.client_profile import ClientProfile
    from tencentcloud.common.profile.http_profile import HttpProfile
    from tencentcloud.common.exception.tencent_cloud_sdk_exception import TencentCloudSDKException
    from tencentcloud.mps.v20190612 import mps_client, models
except ImportError:
    print("Error: Please install the Tencent Cloud SDK first: python3 -m pip install tencentcloud-sdk-python", file=sys.stderr)
    sys.exit(1)


# =============================================================================
# Default Parameters
# =============================================================================
SCHEDULE_ID = 30200
DEFAULT_OUTPUT_DIR = "/output/comprehend/"
DEFAULT_MODEL_NAME = "Google/gemini-2.5-flash"
DEFAULT_POLL_INTERVAL = 10
DEFAULT_TIMEOUT = 600

DEFINITION_MAP = {
    10000: "gemini-2.5-flash-lite",
    10001: "gemini-2.5-flash",
    10002: "gemini-2.5-flash-pro",
    10003: "gemini-3-flash",
    10004: "gemini-3-pro",
}


# =============================================================================
# Utility Functions
# =============================================================================

def get_credentials():
    """Get Tencent Cloud credentials from environment variables, try auto-loading if missing."""
    secret_id = os.environ.get("TENCENTCLOUD_SECRET_ID", "")
    secret_key = os.environ.get("TENCENTCLOUD_SECRET_KEY", "")
    if not secret_id or not secret_key:
        if _LOAD_ENV_AVAILABLE:
            print("[load_env] Environment variables are not set, attempting automatic loading from system files...", file=sys.stderr)
            _ensure_env_loaded(verbose=True)
            secret_id = os.environ.get("TENCENTCLOUD_SECRET_ID", "")
            secret_key = os.environ.get("TENCENTCLOUD_SECRET_KEY", "")
        if not secret_id or not secret_key:
            if _LOAD_ENV_AVAILABLE:
                from mps_load_env import _print_setup_hint
                _print_setup_hint(["TENCENTCLOUD_SECRET_ID", "TENCENTCLOUD_SECRET_KEY"])
            else:
                print(
                    "\nError: TENCENTCLOUD_SECRET_ID / TENCENTCLOUD_SECRET_KEY is not set.\n"
                    "Please add these variables to ~/.env, ~/.profile, or similar files.\n",
                    file=sys.stderr,
                )
            sys.exit(1)
    return credential.Credential(secret_id, secret_key)


def get_cos_bucket():
    """Get output COS Bucket name from environment variables."""
    return os.environ.get("TENCENTCLOUD_COS_BUCKET", "")


def get_cos_region():
    """Get output COS Region from environment variables."""
    return os.environ.get("TENCENTCLOUD_COS_REGION", "")


def create_mps_client(cred, region):
    """Create MPS client."""
    http_profile = HttpProfile()
    http_profile.endpoint = os.environ.get("TENCENTCLOUD_MPS_ENDPOINT", "mps.tencentcloudapi.com")
    client_profile = ClientProfile()
    client_profile.httpProfile = http_profile
    return mps_client.MpsClient(cred, region, client_profile)


def build_url_input(url):
    """Build URL input source."""
    return {
        "Type": "URL",
        "UrlInputInfo": {"Url": url},
    }


def build_cos_input(cos_key, cos_bucket=None, cos_region=None):
    """Build COS input source."""
    bucket = cos_bucket or get_cos_bucket()
    region = cos_region or get_cos_region()
    if not bucket:
        print(
            "Error: COS input requires a Bucket. Please provide it through --cos-input-bucket or the TENCENTCLOUD_COS_BUCKET environment variable",  # NOCA:line-too-long(line cannot be shortened)
            file=sys.stderr,
        )
        sys.exit(1)
    return {
        "Type": "COS",
        "CosInputInfo": {
            "Bucket": bucket,
            "Region": region,
            "Object": cos_key if cos_key.startswith("/") else f"/{cos_key}",
        },
    }


# =============================================================================
# Request Building
# =============================================================================

def build_request_payload(args):
    """Assemble the ProcessImage request payload."""
    if args.url:
        input_info = build_url_input(args.url)
    elif args.cos_input_key:
        input_info = build_cos_input(args.cos_input_key, args.cos_input_bucket, args.cos_input_region)
    elif args.local_file:
        upload_result = auto_upload_local_file(args.local_file)
        if not upload_result:
            print("Error: Failed to upload the local file", file=sys.stderr)
            sys.exit(1)
        input_info = build_cos_input(upload_result["Key"])
    else:
        print("Error: Please specify an input source (--url, --cos-input-key, or --local-file)", file=sys.stderr)
        sys.exit(1)

    output_bucket = args.output_bucket or get_cos_bucket()
    output_region = args.output_region or get_cos_region()

    if not output_bucket:
        print(
            "Error: Missing output Bucket. Please pass --output-bucket or set TENCENTCLOUD_COS_BUCKET",
            file=sys.stderr,
        )
        sys.exit(1)

    payload = {
        "InputInfo": input_info,
        "OutputStorage": {
            "Type": "COS",
            "CosOutputStorage": {
                "Bucket": output_bucket,
                "Region": output_region,
            },
        },
        "OutputDir": args.output_dir,
    }

    if args.definition is not None:
        payload["Definition"] = args.definition
    else:
        payload["ScheduleId"] = SCHEDULE_ID
        model_config = {"ModelName": args.model_name or DEFAULT_MODEL_NAME}
        if args.temperature is not None:
            model_config["Temperature"] = args.temperature
        if args.top_p is not None:
            model_config["TopP"] = args.top_p
        if args.top_k is not None:
            model_config["TopK"] = args.top_k
        payload["StdExtInfo"] = json.dumps(
            {"ModelConfig": model_config},
            ensure_ascii=False,
            separators=(",", ":"),
        )

    payload["AddOnParameter"] = {"ExtPrompt": [{"Prompt": args.prompt}]}

    return payload


# =============================================================================
# API Call
# =============================================================================

def submit_process_image(client, payload):
    """Call ProcessImage to submit an image comprehension task."""
    req = models.ProcessImageRequest()
    req.from_json_string(json.dumps(payload, ensure_ascii=False))
    resp = client.ProcessImage(req)
    result = json.loads(resp.to_json_string())
    if "Response" in result:
        result = result["Response"]
    return result


# =============================================================================
# Argument Parsing
# =============================================================================

def parse_args():
    parser = argparse.ArgumentParser(
        description="Tencent Cloud MPS Image Comprehension / OCR / VQA (ProcessImage ScheduleId=30200, Gemini series)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    input_group = parser.add_argument_group("Input source (choose one)")
    source_group = input_group.add_mutually_exclusive_group(required=True)
    source_group.add_argument(
        "--url",
        help="Image URL (direct HTTP/HTTPS link)",
    )
    source_group.add_argument(
        "--cos-input-key",
        help="Image COS object Key (e.g. /input/photo.jpg)",
    )
    source_group.add_argument(
        "--local-file",
        help="Local image file path (uploaded to COS automatically)",
    )
    input_group.add_argument(
        "--cos-input-bucket",
        help="Input COS Bucket (default: reads TENCENTCLOUD_COS_BUCKET)",
    )
    input_group.add_argument(
        "--cos-input-region",
        help="Input COS Region (default: reads TENCENTCLOUD_COS_REGION)",
    )

    comprehend_group = parser.add_argument_group("Image comprehension parameters")
    comprehend_group.add_argument(
        "--prompt", required=True,
        help="Question or analysis instruction for the image (required)",
    )
    model_group = comprehend_group.add_mutually_exclusive_group()
    model_group.add_argument(
        "--definition", type=int,
        choices=list(DEFINITION_MAP.keys()),
        help="Shortcut model ID (mutually exclusive with --model-name): 10000=gemini-2.5-flash-lite, 10001=gemini-2.5-flash, 10002=gemini-2.5-flash-pro, 10003=gemini-3-flash, 10004=gemini-3-pro",  # NOCA:line-too-long(line cannot be shortened)
    )
    model_group.add_argument(
        "--model-name",
        help=f"Model name (mutually exclusive with --definition, default: {DEFAULT_MODEL_NAME})",
    )
    comprehend_group.add_argument(
        "--temperature", type=float,
        help="Generation temperature to control randomness (0.0-1.0)",
    )
    comprehend_group.add_argument(
        "--top-p", type=float,
        help="Nucleus sampling parameter (0.0-1.0)",
    )
    comprehend_group.add_argument(
        "--top-k", type=int,
        help="Top-k sampling parameter",
    )

    output_group = parser.add_argument_group("Output parameters")
    output_group.add_argument(
        "--output-bucket",
        help="Output COS Bucket (default: reads TENCENTCLOUD_COS_BUCKET)",
    )
    output_group.add_argument(
        "--output-region",
        help="Output COS Region (default: reads TENCENTCLOUD_COS_REGION)",
    )
    output_group.add_argument(
        "--output-dir", default=DEFAULT_OUTPUT_DIR,
        help=f"Output directory (default: {DEFAULT_OUTPUT_DIR})",
    )

    task_group = parser.add_argument_group("Task control")
    task_group.add_argument(
        "--dry-run", action="store_true",
        help="Print the request payload only without calling the API",
    )
    task_group.add_argument(
        "--no-wait", action="store_true",
        help="Submit the task only and return after TaskId is received",
    )
    task_group.add_argument(
        "--poll-interval", type=int, default=DEFAULT_POLL_INTERVAL,
        help=f"Polling interval in seconds (default: {DEFAULT_POLL_INTERVAL})",
    )
    task_group.add_argument(
        "--timeout", type=int, default=DEFAULT_TIMEOUT,
        help=f"Maximum wait time in seconds (default: {DEFAULT_TIMEOUT})",
    )

    auth_group = parser.add_argument_group("Authentication and region")
    auth_group.add_argument(
        "--region",
        default=os.environ.get("TENCENTCLOUD_API_REGION", ""),
        help="MPS API access region (default: reads TENCENTCLOUD_API_REGION, otherwise ap-guangzhou)",
    )

    return parser.parse_args()


# =============================================================================
# Main Flow
# =============================================================================

# NOCA:CCN(complex function with multiple execution paths, splitting would reduce readability)
def main():
    # Timing fix: load .env before argparse so `default=os.environ.get(...)` can read user config
    if _LOAD_ENV_AVAILABLE:
        try:
            _ensure_env_loaded(verbose=False)
        except Exception:
            pass
    args = parse_args()

    cred = get_credentials()
    region = args.region
    client = create_mps_client(cred, region)

    payload = build_request_payload(args)

    if args.dry_run:
        print("=" * 60)
        print("[Dry Run] Printing request payload only, API will not be called")
        print("=" * 60)
        print(json.dumps(payload, ensure_ascii=False, indent=2))
        return

    if args.definition is not None:
        model_info = f"Definition={args.definition} ({DEFINITION_MAP.get(args.definition, 'Unknown')})"
    else:
        model_info = f"ModelName={args.model_name or DEFAULT_MODEL_NAME}"

    print("🚀 Submitting image comprehension task...")
    if args.url:
        print(f"   Input: {args.url}")
    elif args.cos_input_key:
        bucket = args.cos_input_bucket or get_cos_bucket()
        print(f"   Input: COS - {bucket}:{args.cos_input_key}")
    elif args.local_file:
        print(f"   Input: local file - {args.local_file}")
    print(f"   Prompt: {args.prompt}")
    print(f"   Model: {model_info}")
    if args.definition is not None:
        print("   Mode: Definition shortcut mode")
    else:
        print(f"   Mode: ScheduleId={SCHEDULE_ID}")

    try:
        submit_result = submit_process_image(client, payload)
    except TencentCloudSDKException as e:
        print(f"Error: Failed to submit task - {e}", file=sys.stderr)
        sys.exit(1)

    task_id = submit_result.get("TaskId", "N/A")
    print("✅ Image comprehension task submitted successfully!")
    print(f"   TaskId: {task_id}")
    print(f"   RequestId: {submit_result.get('RequestId', 'N/A')}")
    print(f"\n## TaskId: {task_id}")

    if args.no_wait:
        print(json.dumps({"TaskId": task_id, "RequestId": submit_result.get("RequestId")}, ensure_ascii=False, indent=2))
        return

    if not _POLL_AVAILABLE:
        print("⚠️  Polling module is unavailable. Please query manually:", file=sys.stderr)
        print(f"   python3 scripts/mps_get_image_task.py --task-id {task_id}", file=sys.stderr)
        print(json.dumps({"TaskId": task_id}, ensure_ascii=False, indent=2))
        return

    task_result = poll_image_task(
        task_id=task_id,
        region=region,
        interval=args.poll_interval,
        max_wait=args.timeout,
        verbose=False,
    )

    if task_result is None:
        print("\n⚠️  Polling timed out. The task may still be processing.", file=sys.stderr)
        print(f"   You can query it manually: python3 scripts/mps_get_image_task.py --task-id {task_id}", file=sys.stderr)
        sys.exit(1)

    err_msg = task_result.get("ErrMsg") or ""
    if err_msg and err_msg != "OK":
        print(f"\n❌ Image comprehension task failed: ErrCode={task_result.get('ErrCode')}, ErrMsg={err_msg}", file=sys.stderr)
        sys.exit(1)

    content = None
    for item in task_result.get("ImageProcessTaskResultSet") or []:
        output = item.get("Output") or {}
        content = output.get("Content")
        if content:
            break

    final_result = {
        "TaskId": task_id,
        "Status": task_result.get("Status"),
        "CreateTime": task_result.get("CreateTime"),
        "FinishTime": task_result.get("FinishTime"),
        "Content": content,
    }

    print(json.dumps(final_result, ensure_ascii=False, indent=2))

    if content:
        print("\n--- Image Comprehension Result ---")
        print(content)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\nInterrupted", file=sys.stderr)
        sys.exit(1)
