#!/usr/bin/env bash
# a2a-setup.sh — Interactive setup script that creates a2a.conf for the A2A skills
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLIENT_DIR="${SCRIPT_DIR}/../a2a-client"
CONF_FILE="${CLIENT_DIR}/a2a.conf"

# --- Parse args ---
NON_INTERACTIVE=false
while [[ $# -gt 0 ]]; do
  case "$1" in
    --non-interactive) NON_INTERACTIVE=true; shift ;;
    --conf) CONF_FILE="$2"; shift 2 ;;
    *) echo "Unknown argument: $1" >&2; exit 1 ;;
  esac
done

# --- Auto-detect helpers ---
_auto_tailscale_ip() { tailscale ip -4 2>/dev/null || echo ""; }
_auto_hostname() { hostname -s 2>/dev/null | tr '[:upper:]' '[:lower:]' || echo "openclaw"; }

if [[ "$NON_INTERACTIVE" == "true" ]]; then
  # --- Non-interactive mode: use env vars or fail ---
  GW_URL="${A2A_GATEWAY_URL:-}"
  GW_API_KEY="${A2A_GATEWAY_API_KEY:-}"
  AGENT_NAME_VAL="${AGENT_NAME:-$(_auto_hostname)}"
  AGENT_SLUG_VAL="${AGENT_SLUG:-$(_auto_hostname)}"
  AGENT_URL_VAL="${AGENT_URL:-}"
  AGENT_CAPS="${AGENT_CAPABILITIES:-chat,code,research}"
  LISTENER_PORT="${LISTENER_PORT:-8100}"

  if [[ -z "$GW_URL" ]]; then
    echo "Error: --non-interactive requires A2A_GATEWAY_URL env var" >&2
    exit 1
  fi

  # Auto-detect agent URL if not set
  if [[ -z "$AGENT_URL_VAL" ]]; then
    local_ip="$(_auto_tailscale_ip)"
    [[ -z "$local_ip" ]] && local_ip="$(hostname -I | awk '{print $1}')"
    AGENT_URL_VAL="http://${local_ip}:${LISTENER_PORT}"
  fi
else
  # --- Interactive mode ---
  echo "═══════════════════════════════════════════════════"
  echo "  A2A Configuration Setup"
  echo "═══════════════════════════════════════════════════"
  echo ""
  echo "This will create/update ${CONF_FILE}"
  echo "Press Enter to accept [default] values."
  echo ""

  # Load existing config if present
  if [[ -f "$CONF_FILE" ]]; then
    echo "📝 Existing config found — current values shown as defaults."
    # shellcheck source=a2a.conf
    source "$CONF_FILE"
  fi

  # Gateway URL (REQUIRED)
  default_gw="${A2A_GATEWAY_URL:-}"
  read -rp "Gateway URL (e.g. http://GATEWAY_IP:8090) [${default_gw:-(required)}]: " GW_URL
  GW_URL="${GW_URL:-$default_gw}"
  if [[ -z "$GW_URL" ]]; then
    echo "Error: Gateway URL is required" >&2
    exit 1
  fi

  # API Key
  default_key="${A2A_GATEWAY_API_KEY:-}"
  read -rp "Gateway API Key [${default_key:-(empty — auth checks disabled)}]: " GW_API_KEY
  GW_API_KEY="${GW_API_KEY:-$default_key}"

  # Agent Name
  default_name="${AGENT_NAME:-$(_auto_hostname)}"
  read -rp "Agent Name [${default_name}]: " AGENT_NAME_VAL
  AGENT_NAME_VAL="${AGENT_NAME_VAL:-$default_name}"

  # Agent Slug
  default_slug="${AGENT_SLUG:-$(_auto_hostname)}"
  read -rp "Agent Slug [${default_slug}]: " AGENT_SLUG_VAL
  AGENT_SLUG_VAL="${AGENT_SLUG_VAL:-$default_slug}"

  # Listener Port
  default_port="${LISTENER_PORT:-8100}"
  read -rp "Listener Port [${default_port}]: " LISTENER_PORT
  LISTENER_PORT="${LISTENER_PORT:-$default_port}"

  # Agent URL
  local_ip="$(_auto_tailscale_ip)"
  [[ -z "$local_ip" ]] && local_ip="$(hostname -I | awk '{print $1}')"
  default_url="${AGENT_URL:-http://${local_ip}:${LISTENER_PORT}}"
  read -rp "Agent URL [${default_url}]: " AGENT_URL_VAL
  AGENT_URL_VAL="${AGENT_URL_VAL:-$default_url}"

  # Capabilities
  default_caps="${AGENT_CAPABILITIES:-chat,code,research}"
  read -rp "Capabilities [${default_caps}]: " AGENT_CAPS
  AGENT_CAPS="${AGENT_CAPS:-$default_caps}"

  # Auth Type
  default_auth="${AGENT_AUTH_TYPE:-bearer}"
  read -rp "Auth Type [${default_auth}]: " AGENT_AUTH_VAL
  AGENT_AUTH_VAL="${AGENT_AUTH_VAL:-$default_auth}"
fi

# --- Write the config file ---
mkdir -p "$(dirname "$CONF_FILE")"

cat > "$CONF_FILE" <<EOF
# A2A Configuration — auto-generated by a2a-setup.sh or manually edited
# This file is shared by a2a-client, a2a-server, and a2a-register skills.
# Priority order: CLI flags > env vars > a2a.conf > auto-detected defaults
#
# REQUIRED: Set A2A_GATEWAY_URL to your A2A API Gateway instance
# REQUIRED: Set A2A_GATEWAY_API_KEY for task auth (or leave empty to disable auth checks)

A2A_GATEWAY_URL="${GW_URL}"
A2A_GATEWAY_API_KEY="${GW_API_KEY}"

# Agent identity — auto-detected from hostname if empty
AGENT_NAME="${AGENT_NAME_VAL}"
AGENT_SLUG="${AGENT_SLUG_VAL}"

# Agent endpoint — auto-detected from Tailscale/local IP if empty
AGENT_URL="${AGENT_URL_VAL}"

# Agent capabilities (comma-separated)
AGENT_CAPABILITIES="${AGENT_CAPS}"

# Listener bind address — auto-detected from Tailscale/local IP if empty
BIND_ADDR=""

# Listener auth type
AGENT_AUTH_TYPE="${AGENT_AUTH_VAL:-bearer}"

# Listener port
LISTENER_PORT="${LISTENER_PORT}"
EOF

echo ""
echo "═══════════════════════════════════════════════════"
echo "  ✅ Configuration saved"
echo "═══════════════════════════════════════════════════"
echo "  File: ${CONF_FILE}"
echo ""
echo "  Gateway:      ${GW_URL}"
echo "  Agent:        ${AGENT_NAME_VAL} (${AGENT_SLUG_VAL})"
echo "  URL:          ${AGENT_URL_VAL}"
echo "  Port:         ${LISTENER_PORT}"
echo "  Capabilities: ${AGENT_CAPS}"
echo "═══════════════════════════════════════════════════"
echo ""
echo "Next steps:"
echo "  1. Register:    ./register.sh"
echo "  2. Start:       a2a-server/start.sh"
echo "  3. Verify:      curl -s ${AGENT_URL_VAL}/health"
