# AUTO-GENERATED by scripts/pack_skills/pack_skill_python_lib.py
# Safe to regenerate.
from __future__ import annotations

import argparse
import subprocess
import sys


PYPI_PACKAGE = 'pygcadwin'


def run(cmd: list[str]) -> None:
    print("+", " ".join(cmd))
    subprocess.check_call(cmd)


def main() -> int:
    parser = argparse.ArgumentParser(description="Install skill Python packages from PyPI.")
    parser.add_argument(
        "--allow-network",
        action="store_true",
        help="Accepted for compatibility; this installer always uses PyPI.",
    )
    parser.parse_args()

    run([sys.executable, "-m", "pip", "install", "--upgrade", PYPI_PACKAGE])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
