#!/usr/bin/env bash
# onboard.sh — Fresh-install onboarding helper for Genor's Project Orchestration
# Usage: bash scripts/onboard.sh [--dry-run] [--force]
#
# This is a HELPER script. The onboarding is LLM-driven (the AI talks to you).
# This script handles the technical bits: probing endpoints, writing files, etc.
#
# Set ORCHESTRATOR_DATA_DIR to override data location
# Default: ../../orchestrator-data/ from skill root (workspace root)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
SKILL_DIR="$(dirname "$SCRIPT_DIR")"
DATA_DIR="${ORCHESTRATOR_DATA_DIR:-$(dirname "$(dirname "$SKILL_DIR")")/orchestrator-data}"
MODELS_FILE="$DATA_DIR/models.json"
SESSION_LOG="$DATA_DIR/session_log.md"
DRY_RUN=false
FORCE=false

while [[ $# -gt 0 ]]; do
  case "$1" in
    --dry-run) DRY_RUN=true; shift ;;
    --force) FORCE=true; shift ;;
    *) echo "Usage: $0 [--dry-run] [--force]"; exit 1 ;;
  esac
done

echo "╔══════════════════════════════════════════════════════════╗"
echo "║   Genor's Project Orchestration — Onboarding Helper     ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
$DRY_RUN && echo "  ⚠️  DRY RUN — no changes will be written" && echo ""

# --- Step 1: Environment ---
echo "📋 Step 1: Environment"
echo "   Skill:  $SKILL_DIR"
echo "   Data:   $DATA_DIR"
if [ -n "${ORCHESTRATOR_DATA_DIR:-}" ]; then
  echo "   ORCHESTRATOR_DATA_DIR is set ✓"
fi

if [ -f "$MODELS_FILE" ] && [ "$FORCE" != true ]; then
  COUNT=$(grep -c '"id"' "$MODELS_FILE" 2>/dev/null || echo "0")
  echo "   models.json exists ($COUNT models)"
  echo ""
  echo "⏭️  Data already exists. Use --force to re-onboard."
  echo "   Run /genor-orchestrator status to see state."
  exit 0
fi

mkdir -p "$DATA_DIR"
echo ""

# --- Step 2: Provider Discovery ---
echo "🔍 Step 2: Provider Discovery"
echo "   Probing endpoints (5s timeout each)..."

declare -a FOUND_PROVIDERS=()

# OpenRouter
if curl -s --max-time 5 "https://openrouter.ai/api/v1/auth/key" > /dev/null 2>&1; then
  echo "   ✅ OpenRouter — reachable"
  FOUND_PROVIDERS+=("openrouter")
else
  echo "   ⚠️  OpenRouter — not reachable (no API key configured?)"
fi

# LM Studio
if curl -s --max-time 3 "http://localhost:1234/v1/models" > /dev/null 2>&1; then
  echo "   ✅ LM Studio — localhost:1234"
  FOUND_PROVIDERS+=("lmstudio")
else
  echo "   ⚠️  LM Studio — not reachable on localhost:1234"
fi

# OpenCode
if command -v opencode &>/dev/null; then
  echo "   ✅ OpenCode CLI — available"
  FOUND_PROVIDERS+=("opencode")
else
  echo "   ⚠️  OpenCode CLI — not found"
fi

# Cursor
if command -v cursor &>/dev/null; then
  echo "   ✅ Cursor CLI — available"
  FOUND_PROVIDERS+=("cursor")
else
  echo "   ⚠️  Cursor CLI — not found"
fi

# GPU check (nvidia-smi)
if command -v nvidia-smi &>/dev/null; then
  GPU_INFO=$(nvidia-smi --query-gpu=name,memory.total --format=csv,noheader 2>/dev/null | head -3)
  echo "   🎮 GPU(s) found:"
  echo "$GPU_INFO" | while IFS= read -r line; do echo "      $line"; done
  FOUND_PROVIDERS+=("local_gpu")
else
  echo "   ℹ️  No NVIDIA GPU detected (nvidia-smi not found)"
fi

echo ""

# --- Step 3: Write Initial State ---
echo "📝 Step 3: Initial State"
if $DRY_RUN; then
  echo "   [DRY RUN] Would write probe results to $DATA_DIR/"
else
  # Write provider discovery results
  cat > "$DATA_DIR/.discovered_providers.json" << JSONEOF
{
  "discovered_at": "$(date -Iseconds)",
  "providers": [$(printf '"%s",' "${FOUND_PROVIDERS[@]}" | sed 's/,$//')],
  "detail": {
    "openrouter": $(curl -s --max-time 5 "https://openrouter.ai/api/v1/auth/key" > /dev/null 2>&1 && echo true || echo false),
    "lmstudio": $(curl -s --max-time 3 "http://localhost:1234/v1/models" > /dev/null 2>&1 && echo true || echo false),
    "opencode": $(command -v opencode &>/dev/null && echo true || echo false),
    "cursor": $(command -v cursor &>/dev/null && echo true || echo false),
    "local_gpu": $(command -v nvidia-smi &>/dev/null && echo true || echo false)
  }
}
JSONEOF
  echo "   ✅ Provider probe results saved"
  echo "   ℹ️  Models will be catalogued by the LLM during interactive onboarding"
fi
echo ""

# --- Step 4: Run discover-models.sh if available ---
echo "🧪 Step 4: Model Discovery"
if [ -f "$SKILL_DIR/scripts/discover-models.sh" ] && [ "$DRY_RUN" != true ]; then
  echo "   Running discover-models.sh..."
  bash "$SKILL_DIR/scripts/discover-models.sh" 2>&1 | sed 's/^/   /' || echo "   ⚠️  Discovery had issues (non-fatal)"
elif $DRY_RUN; then
  echo "   [DRY RUN] Would run discover-models.sh"
else
  echo "   ℹ️  No discover-models.sh — LLM will handle discovery"
fi
echo ""

# --- Step 5: Setup session log ---
echo "📊 Step 5: Session Log"
if [ ! -f "$SESSION_LOG" ] && [ "$DRY_RUN" != true ]; then
  cat > "$SESSION_LOG" << 'LOGEOF'
# Session Log
*Auto-generated by Genor's Project Orchestration*

| Date | Project | Task | Model | Status | Notes |
|------|---------|------|-------|--------|-------|
LOGEOF
  echo "   ✅ session_log.md created"
elif [ -f "$SESSION_LOG" ]; then
  echo "   ✅ session_log.md exists"
elif $DRY_RUN; then
  echo "   [DRY RUN] Would create session_log.md"
fi
echo ""

# --- Step 6: Summary ---
echo "╔══════════════════════════════════════════════════════════╗"
echo "║   Helper complete! Continuing with LLM-driven setup...  ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "📌 Next steps for the LLM:"
echo ""
echo "   1. Provider interview:"
for p in "${FOUND_PROVIDERS[@]}"; do
  echo "      • $p — ask user about usage/subscription"
done
echo ""
echo "   2. Model cataloguing: walk through each found model"
echo "      → Write to $MODELS_FILE"
echo "      → Generate $DATA_DIR/MODEL_CATALOG.md"
echo ""
echo "   3. Routing rules: set up initial routing table"
echo ""
echo "   4. Project discovery: check ~/projects/ ~/code/ etc."
echo ""
echo "   5. Cron setup: ask about nightly price checks"
echo ""
echo "   6. Dashboard test: offer to start"
echo ""
echo "   7. Log onboarding session:"
echo "      bash scripts/log-session.sh orchestrator \"Onboarding\" <model> complete \"...\""
echo ""

# Record the data dir for the LLM
echo "ORCHESTRATOR_DATA_DIR=$DATA_DIR"