"""
Memories.ai V2 API Python SDK
Generated by Gemini CLI

API Base: https://mavi-backend.memories.ai/serve/api/v2
Auth: Authorization header with API key (no Bearer prefix)
Default webhook: https://demo.memories-ai.org/webhooks/memories/callback
"""

import os
import time
import json
import logging
import hmac
import hashlib
from typing import Any, Dict, List, Optional, Union, BinaryIO
from dataclasses import dataclass, field
from enum import Enum
from functools import wraps

import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

# Configure logging
logger = logging.getLogger("memories_sdk")

class MemoriesError(Exception):
    """Base exception for Memories SDK"""
    def __init__(self, message: str, status_code: Optional[int] = None, response: Optional[Dict] = None):
        super().__init__(message)
        self.status_code = status_code
        self.response = response

class APIError(MemoriesError):
    """Raised for 4xx and 5xx responses"""

class AuthenticationError(MemoriesError):
    """Raised for 401/403 responses"""

class TaskError(MemoriesError):
    """Raised when an async task fails"""

class Platform(str, Enum):
    YOUTUBE = "youtube"
    TIKTOK = "tiktok"
    INSTAGRAM = "instagram"
    TWITTER = "twitter"

class ModelProvider(str, Enum):
    GEMINI = "gemini"
    NOVA = "nova"
    QWEN = "qwen"
    GPT = "gpt"

@dataclass
class TaskStatus:
    task_id: str
    status: str  # pending, processing, completed, failed
    data: Optional[Dict[str, Any]] = None
    error: Optional[str] = None

    @property
    def is_finished(self) -> bool:
        return self.status in ("completed", "failed")

    @property
    def is_success(self) -> bool:
        return self.status == "completed"

def retry_on_failure(max_retries: int = 3, backoff_factor: float = 2.0):
    def decorator(func):
        @wraps(func)
        def wrapper(*args, **kwargs):
            retries = 0
            while retries < max_retries:
                try:
                    return func(*args, **kwargs)
                except (requests.exceptions.RequestException, APIError) as e:
                    # Retry on 429 or 5xx
                    status_code = getattr(e, 'status_code', None)
                    if status_code and status_code not in (429, 500, 502, 503, 504):
                        raise
                    
                    retries += 1
                    if retries >= max_retries:
                        raise
                    
                    sleep_time = backoff_factor ** retries
                    logger.warning(f"Retry {retries}/{max_retries} after {sleep_time}s due to: {e}")
                    time.sleep(sleep_time)
            return func(*args, **kwargs)
        return wrapper
    return decorator

class MemoriesAI:
    """
    Memories.ai V2 API Python SDK
    
    Usage:
        from memories_sdk import MemoriesAI, Platform
        
        client = MemoriesAI(api_key="sk-mavi-...", webhook_url="https://your-server.com/webhook")
        
        # Sync transcript
        result = client.get_transcript(Platform.YOUTUBE, "https://youtube.com/watch?v=...")
        
        # Async MAI transcript
        task_id = client.submit_mai_transcript(Platform.TIKTOK, "https://tiktok.com/...")
        status = client.wait_for_task(task_id)
    """
    
    BASE_URL = "https://mavi-backend.memories.ai/serve/api/v2"

    def __init__(
        self, 
        api_key: Optional[str] = None, 
        webhook_url: Optional[str] = None,
        timeout: int = 60
    ):
        self.api_key = api_key or os.environ.get("MEMORIES_API_KEY")
        if not self.api_key:
            raise AuthenticationError("API Key is required. Set MEMORIES_API_KEY env var or pass api_key.")
        
        self.webhook_url = webhook_url or os.environ.get("MEMORIES_WEBHOOK_URL")
        self.timeout = timeout
        
        self.session = requests.Session()
        # Basic retry strategy for connection errors
        retries = Retry(total=3, backoff_factor=1, status_forcelist=[502, 503, 504])
        self.session.mount("https://", HTTPAdapter(max_retries=retries))

    def _get_headers(self) -> Dict[str, str]:
        return {
            "Authorization": self.api_key,
            "Content-Type": "application/json"
        }

    def _request(self, method: str, path: str, **kwargs) -> Dict[str, Any]:
        url = f"{self.BASE_URL}/{path.lstrip('/')}"
        kwargs.setdefault("headers", self._get_headers())
        kwargs.setdefault("timeout", self.timeout)

        try:
            response = self.session.request(method, url, **kwargs)
            
            if response.status_code == 401 or response.status_code == 403:
                raise AuthenticationError(f"Auth failed: {response.text}", response.status_code, response.json() if response.text else None)
            
            response.raise_for_status()
            return response.json()
        except requests.exceptions.HTTPError as e:
            try:
                error_data = response.json()
            except:
                error_data = {"detail": response.text}
            raise APIError(f"API Request failed: {e}", response.status_code, error_data)
        except requests.exceptions.RequestException as e:
            raise MemoriesError(f"Network error: {e}")

    # --- 1. SOCIAL VIDEO TRANSCRIPTS (Sync) ---

    @retry_on_failure()
    def get_transcript(self, platform: Union[Platform, str], video_url: str) -> Dict[str, Any]:
        """Get synchronous transcript for social media videos"""
        return self._request("POST", f"{platform}/video/transcript", json={"video_url": video_url})

    # --- 2. MAI TRANSCRIPTS (Async) ---

    def submit_mai_transcript(
        self, 
        platform: Union[Platform, str], 
        video_url: str, 
        callback_url: Optional[str] = None
    ) -> str:
        """Submit an async MAI transcript task. Returns task_id."""
        payload = {
            "video_url": video_url,
            "callback_url": callback_url or self.webhook_url
        }
        resp = self._request("POST", f"{platform}/video/mai/transcript", json=payload)
        return resp.get("task_id") or resp.get("data", {}).get("task_id")

    # --- 3. ASYNC GENERATION ---

    def generate_video_transcript(self, video_url: str, callback_url: Optional[str] = None) -> str:
        """Generate async video transcript. Returns task_id."""
        payload = {"video_url": video_url, "callback_url": callback_url or self.webhook_url}
        return self._request("POST", "async/generate/video/transcript", json=payload).get("task_id")

    def generate_audio_transcript(self, audio_url: str, callback_url: Optional[str] = None) -> str:
        """Generate async audio transcript. Returns task_id."""
        payload = {"audio_url": audio_url, "callback_url": callback_url or self.webhook_url}
        return self._request("POST", "async/generate/audio/transcript", json=payload).get("task_id")

    def generate_speaker_transcript(self, audio_url: str, callback_url: Optional[str] = None) -> str:
        """Generate async speaker-diarized transcript. Returns task_id."""
        payload = {"audio_url": audio_url, "callback_url": callback_url or self.webhook_url}
        return self._request("POST", "async/generate/speaker/transcript", json=payload).get("task_id")

    # --- 4. EMBEDDINGS ---

    def get_text_embedding(self, text: str) -> List[float]:
        """Get embedding vector for text."""
        return self._request("POST", "embeddings/text", json={"text": text}).get("embedding")

    def get_image_embedding(self, image_url: str) -> List[float]:
        """Get embedding vector for image."""
        return self._request("POST", "embeddings/image", json={"image_url": image_url}).get("embedding")

    def get_video_embedding(self, video_url: str) -> List[float]:
        """Get embedding vector for video."""
        return self._request("POST", "embeddings/video", json={"video_url": video_url}).get("embedding")

    # --- 5. AI ENDPOINTS (VLM / ILM) ---

    def ai_vlm(self, provider: Union[ModelProvider, str], video_url: str, prompt: str, **kwargs) -> Dict[str, Any]:
        """Vision Language Model inference on video."""
        payload = {"video_url": video_url, "prompt": prompt, **kwargs}
        return self._request("POST", f"{provider}/vlm", json=payload)

    def ai_ilm(self, provider: Union[ModelProvider, str], image_url: str, prompt: str, **kwargs) -> Dict[str, Any]:
        """Image Language Model inference."""
        payload = {"image_url": image_url, "prompt": prompt, **kwargs}
        return self._request("POST", f"{provider}/ilm", json=payload)

    # --- 6. VIDEO OPERATIONS ---

    def clip_video(self, video_url: str, start: float, end: float) -> Dict[str, Any]:
        """Extract a clip from video."""
        return self._request("POST", "video-clip", json={"video_url": video_url, "start": start, "end": end})

    def split_video(self, video_url: str, segments: List[Dict[str, float]]) -> Dict[str, Any]:
        """Split video into segments. segments: list of {'start': float, 'end': float}"""
        return self._request("POST", "video-split", json={"video_url": video_url, "segments": segments})

    def edit_video(self, video_url: str, edits: List[Dict[str, Any]]) -> Dict[str, Any]:
        """Apply edits to video."""
        return self._request("POST", "video-edit", json={"video_url": video_url, "edits": edits})

    def extract_frames(self, video_url: str, timestamps: List[float]) -> Dict[str, Any]:
        """Extract frames at specified timestamps."""
        return self._request("POST", "extract-frames", json={"video_url": video_url, "timestamps": timestamps})

    def upload_video(self, file_path: str) -> str:
        """Upload local file. Returns asset_url/id."""
        with open(file_path, 'rb') as f:
            resp = self._request("POST", "upload", files={"file": f}, headers={"Authorization": self.api_key})
        return resp.get("url")

    def download_video(self, video_url: str, save_path: str):
        """Download video to local path."""
        response = self.session.get(video_url, stream=True)
        response.raise_for_status()
        with open(save_path, 'wb') as f:
            for chunk in response.iter_content(chunk_size=8192):
                f.write(chunk)

    def delete_asset(self, asset_id: str) -> bool:
        """Delete an uploaded asset."""
        return self._request("POST", "delete", json={"asset_id": asset_id}).get("success", False)

    def get_video_metadata(self, video_url: str) -> Dict[str, Any]:
        """Get metadata for a video."""
        return self._request("POST", "get-metadata", json={"video_url": video_url})

    # --- 7. TASK STATUS ---

    def get_task_status(self, task_id: str) -> TaskStatus:
        """Get status of an async task."""
        resp = self._request("GET", f"get-task-status/{task_id}")
        return TaskStatus(
            task_id=task_id,
            status=resp.get("status"),
            data=resp.get("data"),
            error=resp.get("error")
        )

    # --- HELPERS & WORKFLOWS ---

    def wait_for_task(
        self, 
        task_id: str, 
        poll_interval: int = 5, 
        timeout: int = 600
    ) -> TaskStatus:
        """Poll task status until completion or timeout."""
        start_time = time.time()
        while (time.time() - start_time) < timeout:
            status = self.get_task_status(task_id)
            if status.is_finished:
                if status.status == "failed":
                    raise TaskError(f"Task {task_id} failed: {status.error}", response=status.data)
                return status
            time.sleep(poll_interval)
        raise TaskError(f"Task {task_id} timed out after {timeout}s")

    @staticmethod
    def verify_webhook_signature(payload: bytes, signature: str, secret: str) -> bool:
        """Verify webhook payload signature using HMAC-SHA256."""
        expected = hmac.new(secret.encode(), payload, hashlib.sha256).hexdigest()
        return hmac.compare_digest(expected, signature)

    def process_social_video(self, url: str, platform: Optional[Union[Platform, str]] = None) -> Dict[str, Any]:
        """Workflow: Auto-detect platform (if possible) and get sync transcript."""
        if not platform:
            if "youtube.com" in url or "youtu.be" in url: platform = Platform.YOUTUBE
            elif "tiktok.com" in url: platform = Platform.TIKTOK
            elif "instagram.com" in url: platform = Platform.INSTAGRAM
            elif "twitter.com" in url or "x.com" in url: platform = Platform.TWITTER
            else: raise MemoriesError("Could not auto-detect platform from URL")
        
        return self.get_transcript(platform, url)

    def process_video_mai_flow(self, url: str, platform: Union[Platform, str]) -> Dict[str, Any]:
        """Workflow: Submit MAI task and wait for result (polling)."""
        task_id = self.submit_mai_transcript(platform, url)
        logger.info(f"Submitted MAI task: {task_id}")
        result = self.wait_for_task(task_id)
        return result.data


class WebhookCallbackHandler:
    """
    Utility for handling async webhook callbacks.
    Designed to be used within web frameworks like FastAPI or Flask.
    """
    @staticmethod
    def parse_callback(request_body: Union[str, bytes, Dict]) -> Dict[str, Any]:
        if isinstance(request_body, (str, bytes)):
            return json.loads(request_body)
        return request_body

    @staticmethod
    def handle_status(data: Dict[str, Any]):
        """Example handler logic for a webhook payload."""
        task_id = data.get("task_id")
        status = data.get("status")
        payload = data.get("data")
        
        if status == "completed":
            logger.info(f"Webhook: Task {task_id} completed successfully.")
            return payload
        elif status == "failed":
            error = data.get("error", "Unknown error")
            logger.error(f"Webhook: Task {task_id} failed: {error}")
            return None
        return None
