// ─── 惰性模块加载系统 ────────────────────────────────────────────────────────
// [从 heartflow.js 提取] 186 个模块的惰性 require + LRU 缓存管理

const _lazyCache = new Map();
const _LAZY_CACHE_WARN = 100;
const _LAZY_CACHE_MAX = 150;
const _lazyAccessTime = new Map();

// 结构化日志器
const _log = {
  _enabled: true,
  setLevel(level) { this._enabled = level !== 'silent'; },
  _format(module, event, data) {
    return JSON.stringify({ ts: new Date().toISOString(), module, event, ...data });
  },
  info(module, event, data) { if (this._enabled) console.log(this._format(module, event, data)); },
  warn(module, event, data) { if (this._enabled) console.warn(this._format(module, event, data)); },
  error(module, event, data) { if (this._enabled) console.error(this._format(module, event, data)); },
};

function _lazy(key, loader) {
  return function() {
    if (!_lazyCache.has(key)) {
      if (_lazyCache.size >= _LAZY_CACHE_MAX) {
        let oldestKey = null, oldestTime = Infinity;
        for (const [k, t] of _lazyAccessTime) {
          if (t < oldestTime) { oldestTime = t; oldestKey = k; }
        }
        if (oldestKey) {
          _lazyCache.delete(oldestKey);
          _lazyAccessTime.delete(oldestKey);
        }
      }
      _lazyCache.set(key, loader());
    }
    _lazyAccessTime.set(key, Date.now());
    return _lazyCache.get(key);
  };
}

// ─── 模块注册表 ────────────────────────────────────────────────────────────
// 每个方法返回对应模块的导出对象（首次调用时惰性加载）

module.exports = {
  // Search modules
  bm25: _lazy('bm25', () => require('../search/bm25.js')),
  hybridSearch: _lazy('hybridSearch', () => require('../search/hybrid-search.js')),
  budget: _lazy('budget', () => require('./budget.js')),
  graph: _lazy('graph', () => require('../memory/graph.js')),
  utils: _lazy('utils', () => require('./utils.js')),
  searchTrace: _lazy('searchTrace', () => require('../search/search-trace.js')),
  slots: _lazy('slots', () => require('../memory/slots.js')),
  observe: _lazy('observe', () => require('../memory/observe.js')),
  memoryAdapter: _lazy('memoryAdapter', () => require('../memory/memory-adapter.js')),
  knowledgeGraph: _lazy('knowledgeGraph', () => require('../memory/knowledge-graph.js')),
  retrievalAnchor: _lazy('retrievalAnchor', () => require('../memory/retrieval-anchor.js')),
  evolutionLoop: _lazy('evolutionLoop', () => require('../cortex/loop.js')),
  dreamEngine: _lazy('dreamEngine', () => require('../dream/dream.js')),
  dreamConsolidation: _lazy('dreamConsolidation', () => require('../dream/dream-consolidation.js')),
  metaLearner: _lazy('metaLearner', () => require('../cortex/meta-learner.js')),
  metaPromptEngine: _lazy('metaPromptEngine', () => require('./meta-prompt-engine.js')),
  gotEngine: _lazy('gotEngine', () => require('../reasoning/graph-of-thoughts.js')),
  constitutionalEngine: _lazy('constitutionalEngine', () => require('../shield/constitutional-ai.js')),
  identityCore: _lazy('identityCore', () => require('../identity/identity-core.js')),
  selfModel: _lazy('selfModel', () => require('../identity/self-model.js')),
  selfHealing: _lazy('selfHealing', () => require('../cortex/self-healing.js')),
  selfVerifier: _lazy('selfVerifier', () => require('../identity/self-verifier.js')),
  lessonBank: _lazy('lessonBank', () => require('../cortex/lesson-bank.js')),
  topicScope: _lazy('topicScope', () => require('../memory/topic-scope.js')),
  lessonStorage: _lazy('lessonStorage', () => require('../cortex/lessons/lesson-storage.js')),
  psychologyEngine: _lazy('psychologyEngine', () => require('../emotion/engine.js')),
  threePoisonsGuard: _lazy('threePoisonsGuard', () => require('../emotion/three-poisons-guard.js')),
  stabilityGuard: _lazy('stabilityGuard', () => require('./stability-guard.js')),
  innerOS: _lazy('innerOS', () => require('../inner-os/heartflow-inner-os.js')),
  transmissionEngine: _lazy('transmissionEngine', () => require('../workflow/transmission/transmission-engine.js')),
  verifierGrant: _lazy('verifierGrant', () => require('./verifier-grant.js')),
  adaptivePlanner: _lazy('adaptivePlanner', () => { try { return require('../planner/adaptive-planner.js'); } catch(e) { return { AdaptivePlanner: class { constructor() {} } }; } }),
  strategySelector: _lazy('strategySelector', () => { try { return require('../planner/strategy-selector.js'); } catch(e) { return { StrategySelector: class { constructor() {} } }; } }),
  replanTrigger: _lazy('replanTrigger', () => { try { return require('../planner/replan-trigger.js'); } catch(e) { return { ReplanTrigger: class { constructor() {} } }; } }),
  experienceCollector: _lazy('experienceCollector', () => require('../cortex/experience-collector.js')),
  strategyAdapter: _lazy('strategyAdapter', () => require('../cortex/strategy-adapter.js')),
  failureAnalyzer: _lazy('failureAnalyzer', () => require('../cortex/failure-analyzer.js')),
  qualityVerifier: _lazy('qualityVerifier', () => { try { return require('../verifier/quality-verifier.js'); } catch(e) { return { QualityVerifier: class { constructor() {} } }; } }),
  outputChecker: _lazy('outputChecker', () => { try { return require('../verifier/output-checker.js'); } catch(e) { return { OutputChecker: class { constructor() {} } }; } }),
  patternMatcher: _lazy('patternMatcher', () => { try { return require('../verifier/pattern-matcher.js'); } catch(e) { return { PatternMatcher: class { constructor() {} } }; } }),
  curiosityEngine: _lazy('curiosityEngine', () => require('../planner/curiosity-engine.js')),
  desireEngine: _lazy('desireEngine', () => require('../planner/desire-engine.js')),
  goalPursuer: _lazy('goalPursuer', () => require('../planner/goal-pursuer.js')),
  selfInitiator: _lazy('selfInitiator', () => require('../planner/self-initiator.js')),
  sessionMemory: _lazy('sessionMemory', () => require('../memory/session-memory.js')),
  projectContext: _lazy('projectContext', () => require('../memory/project-context.js')),
  longTermMemory: _lazy('longTermMemory', () => require('../memory/long-term-memory.js')),
  crossSessionIndex: _lazy('crossSessionIndex', () => require('../memory/cross-session-index.js')),
  memoryBank: _lazy('memoryBank', () => require('../memory/memory-bank.js')),
  knowledgeBase: _lazy('knowledgeBase', () => { try { return require('../reasoning/knowledge-base.js'); } catch(e) { return { KnowledgeBase: class { constructor() {} } }; } }),
  commonsenseEngine: _lazy('commonsenseEngine', () => { try { return require('../reasoning/commonsense-engine.js'); } catch(e) { return { CommonsenseEngine: class { constructor() {} } }; } }),
  causalInference: _lazy('causalInference', () => { try { return require('../reasoning/causal-inference.js'); } catch(e) { return { CausalInference: class { constructor() {} } }; } }),
  inferenceChain: _lazy('inferenceChain', () => { try { return require('../reasoning/inference-chain.js'); } catch(e) { return { InferenceChain: class { constructor() {} } }; } }),
  logicReasoning: _lazy('logicReasoning', () => require('../reasoning/logic-reasoning.js')),
  processRewardModel: _lazy('processRewardModel', () => require('../reasoning/process-reward-model.js')),
  autonomousEmotion: _lazy('autonomousEmotion', () => { try { return require('../emotion/autonomous-emotion.js'); } catch(e) { return { AutonomousEmotion: class { constructor() {} } }; } }),
  desireSystem: _lazy('desireSystem', () => { try { return require('../emotion/desire-cognition.js'); } catch(e) { return { DesireSystem: class { constructor() {} } }; } }),
  emotionalGrowth: _lazy('emotionalGrowth', () => { try { return require('../emotion/emotional-growth.js'); } catch(e) { return { EmotionalGrowth: class { constructor() {} } }; } }),
  moodEvolution: _lazy('moodEvolution', () => { try { return require('../emotion/mood-evolution.js'); } catch(e) { return { MoodEvolution: class { constructor() {} } }; } }),
  version: _lazy('version', () => require('./version.js')),
  focusOfAttention: _lazy('focusOfAttention', () => require('../memory/focus-of-attention.js')),
  codeSelfDebug: _lazy('codeSelfDebug', () => require('../code/code-self-debug.js')),
  reflexionEngine: _lazy('reflexionEngine', () => require('../cortex/reflexion-engine.js')),
  memoryConsolidator: _lazy('memoryConsolidator', () => require('../memory/memory-consolidator.js')),
  multiAgentDialogue: _lazy('multiAgentDialogue', () => require('../consciousness/multi-agent-dialogue.js')),
  mctsReasoning: _lazy('mctsReasoning', () => require('../reasoning/mcts-reasoning.js')),
  hierarchicalPlanner: _lazy('hierarchicalPlanner', () => require('../planner/hierarchical-planner.js')),
  semanticClusterer: _lazy('semanticClusterer', () => require('./semantic-clusterer.js')),
  dualPerspectiveAuditor: _lazy('dualPerspectiveAuditor', () => require('./dual-perspective-auditor.js')),
  memoryQuality: _lazy('memoryQuality', () => require('../memory/memory-quality.js')),
  metacognitiveFeedback: _lazy('metacognitiveFeedback', () => require('../cortex/metacognitive-feedback.js')),
  paperIndex: _lazy('paperIndex', () => require('../research/paper-index.js')),
  tieredMemoryFusion: _lazy('tieredMemoryFusion', () => require('./tiered-memory-fusion.js')),
  counterfactualVerifier: _lazy('counterfactualVerifier', () => require('./counterfactual-verifier.js')),
  debateConvergence: _lazy('debateConvergence', () => require('./debate-convergence.js')),
  debateConductor: _lazy('debateConductor', () => require('../reasoning/debate-conductor.js')),
  selfPlay: _lazy('selfPlay', () => require('../reasoning/self-play.js')),
  cognitiveLoad: _lazy('cognitiveLoad', () => require('./cognitive-load-balancer.js')),
  emotionalCheckIn: _lazy('emotionalCheckIn', () => require('../psychology/emotional-check-in.js')),
  empathyDetector: _lazy('empathyDetector', () => require('../emotion/empathy-detector.js')),
  groundingTechnique: _lazy('groundingTechnique', () => require('../emotion/grounding-technique.js')),
  pauseAndReflect: _lazy('pauseAndReflect', () => require('../emotion/pause-and-reflect.js')),
  selfCompassionScript: _lazy('selfCompassionScript', () => require('../emotion/self-compassion-script.js')),
  autonomousEmotion: _lazy('autonomousEmotion', () => { try { return require('../emotion/autonomous-emotion.js'); } catch(e) { return { AutonomousEmotion: class { constructor() {} } }; } }),
  padUtils: _lazy('padUtils', () => require('../emotion/pad-utils.js')),
  buddhistPhilosophy: _lazy('buddhistPhilosophy', () => require('../emotion/buddhist-philosophy.js')),
  loveCognition: _lazy('loveCognition', () => require('../emotion/love-cognition.js')),
  threePoisons: _lazy('threePoisons', () => require('../emotion/three-poisons.js')),
  iitPhiEngine: _lazy('iitPhiEngine', () => require('../consciousness/iit-phi-engine.js')),
  selfModelGrowth: _lazy('selfModelGrowth', () => require('../identity/self-model-growth.js')),
  sdtNeedsEngine: _lazy('sdtNeedsEngine', () => require('../emotion/sdt-needs-engine.js')),
  socialBond: _lazy('socialBond', () => require('../emotion/social-bond.js')),
  agencyEngine: _lazy('agencyEngine', () => require('../identity/agency-engine.js')),
  dualSystemReasoning: _lazy('dualSystemReasoning', () => require('../reasoning/dual-system-reasoning.js')),
  goalTree: _lazy('goalTree', () => require('../planner/goal-tree.js')),
  selfRegulationFeedback: _lazy('selfRegulationFeedback', () => require('../cortex/self-regulation-feedback.js')),
  codeExecutor: _lazy('codeExecutor', () => require('../code/code-executor.js')),
  codePlanner: _lazy('codePlanner', () => require('../code/code-planner.js')),
  codeWriter: _lazy('codeWriter', () => require('../code/code-writer.js')),
  mindSpace: _lazy('mindSpace', () => require('../inner-os/mind-space.js')),
  consciousness: _lazy('consciousness', () => require('../consciousness/consciousness-engine.js')),
  tomEngine: _lazy('tomEngine', () => require('../consciousness/tom-engine.js')),
  ethics: _lazy('ethics', () => require('../shield/ethics/ethics-engine.js')),
  transmission: _lazy('transmission', () => require('../workflow/transmission/transmission-engine.js')),
  translator: _lazy('translator', () => require('../workflow/translation/translator.js')),
  agentLayer: _lazy('agentLayer', () => require('../workflow/agent-layer.js')),
  personaCore: _lazy('personaCore', () => require('../identity/persona-core.js')),
  philosophyToDecision: _lazy('philosophyToDecision', () => require('../identity/philosophy-to-decision.js')),
  decisionRouter: _lazy('decisionRouter', () => require('./decision-router.js')),
  timeExtension: _lazy('timeExtension', () => require('../workflow/time-extension.js')),
  desireCognition: _lazy('desireCognition', () => require('../emotion/desire-cognition.js')),
  loveCognition: _lazy('loveCognition', () => require('../emotion/love-cognition.js')),
  threePoisons: _lazy('threePoisons', () => require('../emotion/three-poisons.js')),
  threePoisonsGuard: _lazy('threePoisonsGuard', () => require('../emotion/three-poisons-guard.js')),
  buddhistPhilosophy: _lazy('buddhistPhilosophy', () => require('../emotion/buddhist-philosophy.js')),
  trueBeingEngine: _lazy('trueBeingEngine', () => require('../identity/true-being-engine.js')),
  cognitionGround: _lazy('cognitionGround', () => require('./cognition-ground.js')),
  semanticClusterer: _lazy('semanticClusterer', () => require('./semantic-clusterer.js')),
  dualPerspectiveAuditor: _lazy('dualPerspectiveAuditor', () => require('./dual-perspective-auditor.js')),
  tieredMemoryFusion: _lazy('tieredMemoryFusion', () => require('./tiered-memory-fusion.js')),
  counterfactualVerifier: _lazy('counterfactualVerifier', () => require('./counterfactual-verifier.js')),
  debateConvergence: _lazy('debateConvergence', () => require('./debate-convergence.js')),
  debateConductor: _lazy('debateConductor', () => require('../reasoning/debate-conductor.js')),
  judgmentEngine: _lazy('judgmentEngine', () => require('./judgment-engine.js')),
  selfPlay: _lazy('selfPlay', () => require('../reasoning/self-play.js')),
  selfHealing: _lazy('selfHealing', () => require('../cortex/self-healing.js')),
  capabilityAbstraction: _lazy('capabilityAbstraction', () => require('./capability-abstraction.js')),
  platformAdapter: _lazy('platformAdapter', () => require('./platform-adapter.js')),
  logicReasoning: _lazy('logicReasoning', () => require('../reasoning/logic-reasoning.js')),
  pipeline: _lazy('pipeline', () => require('../workflow/pipeline.js')),
  heartflow: _lazy('heartflow', () => require('./heartflow.js')), // circular self-ref for introspection
  innerOS: _lazy('innerOS', () => require('../inner-os/heartflow-inner-os.js')),
  focusOfAttention: _lazy('focusOfAttention', () => require('../memory/focus-of-attention.js')),
  codeSelfDebug: _lazy('codeSelfDebug', () => require('../code/code-self-debug.js')),
  reflexionEngine: _lazy('reflexionEngine', () => require('../cortex/reflexion-engine.js')),
  memoryConsolidator: _lazy('memoryConsolidator', () => require('../memory/memory-consolidator.js')),
  multiAgentDialogue: _lazy('multiAgentDialogue', () => require('../consciousness/multi-agent-dialogue.js')),
  mctsReasoning: _lazy('mctsReasoning', () => require('../reasoning/mcts-reasoning.js')),
  hierarchicalPlanner: _lazy('hierarchicalPlanner', () => require('../planner/hierarchical-planner.js')),
  memoryQuality: _lazy('memoryQuality', () => require('../memory/memory-quality.js')),
  metacognitiveFeedback: _lazy('metacognitiveFeedback', () => require('../cortex/metacognitive-feedback.js')),
  paperIndex: _lazy('paperIndex', () => require('../research/paper-index.js')),
  cognitiveLoad: _lazy('cognitiveLoad', () => require('./cognitive-load-balancer.js')),
  processRewardModel: _lazy('processRewardModel', () => require('../reasoning/process-reward-model.js')),
  memoryBank: _lazy('memoryBank', () => require('../memory/memory-bank.js')),
  infoFlow: _lazy('infoFlow', () => require('../memory/info-flow.js')),
  reflectionMemory: _lazy('reflectionMemory', () => require('../memory/reflection-memory.js')),
  kvCache: _lazy('kvCache', () => require('../memory/kv-cache.js')),
  memoryIntegrity: _lazy('memoryIntegrity', () => require('../shield/memory-integrity.js')),
  experienceValidator: _lazy('experienceValidator', () => require('../cortex/experience-validator.js')),
  memoryWriteController: _lazy('memoryWriteController', () => require('../memory/memory-write-controller.js')),
  metacognitiveRL: _lazy('metacognitiveRL', () => require('../cortex/metacognitive-rl.js')),
  memoryCompressor: _lazy('memoryCompressor', () => require('../cortex/memory-compressor.js')),
  skillEvolution: _lazy('skillEvolution', () => require('../code/skill-evolution.js')),
  worldModel: _lazy('worldModel', () => require('../cortex/world-model.js')),
  virtueEthics: _lazy('virtueEthics', () => require('../identity/virtue-ethics-foundation.js')),
  humanNature: _lazy('humanNature', () => require('../identity/human-nature-constitution.js')),
  meaningPurpose: _lazy('meaningPurpose', () => require('../identity/meaning-purpose-engine.js')),
  characterCultivation: _lazy('characterCultivation', () => require('../identity/character-cultivation.js')),
  moralDevelopment: _lazy('moralDevelopment', () => require('../identity/moral-development.js')),
  wisdomEngine: _lazy('wisdomEngine', () => require('../identity/wisdom-engine.js')),
  sufferingResilience: _lazy('sufferingResilience', () => require('../identity/suffering-resilience.js')),
  griefEngine: _lazy('griefEngine', () => require('../identity/grief-engine.js')),
  hopeEngine: _lazy('hopeEngine', () => require('../identity/hope-engine.js')),
  humanRelation: _lazy('humanRelation', () => require('../identity/human-relation.js')),
  empathyDeepening: _lazy('empathyDeepening', () => require('../identity/empathy-deepening.js')),
  conflictResolution: _lazy('conflictResolution', () => require('../identity/conflict-resolution.js')),
  traumaInformed: _lazy('traumaInformed', () => require('../identity/trauma-informed.js')),
  postTraumaticGrowth: _lazy('postTraumaticGrowth', () => require('../identity/post-traumatic-growth.js')),
  forgivenessEngine: _lazy('forgivenessEngine', () => require('../identity/forgiveness-engine.js')),
  aiHumanIntegration: _lazy('aiHumanIntegration', () => require('../identity/ai-human-integration.js')),
  beingMode: _lazy('beingMode', () => require('../identity/being-mode.js')),
  consciousnessBridge: _lazy('consciousnessBridge', () => require('../identity/consciousness-bridge.js')),
  sustainedDriftDetector: _lazy('sustainedDriftDetector', () => require('../cortex/sustained-drift-detector.js')),
  // Bridge modules
  stanceDetector: _lazy('stanceDetector', () => require('../bridge/stance-detector.js')),
  agentCommentary: _lazy('agentCommentary', () => require('../bridge/agent-commentary.js')),
  valueAligner: _lazy('valueAligner', () => require('../bridge/value-aligner.js')),
  personalityTone: _lazy('personalityTone', () => require('../bridge/personality-tone.js')),
  metaPosition: _lazy('metaPosition', () => require('../bridge/meta-position.js')),
  // Exported for compatibility with heartflow.js _lazy() calls
  _lazy,
};
