/**
 * RIC Popup — shows current bot identity status and handles import/disconnect
 */

const GRADE_CONFIG = {
  healthy:   { emoji: '🟢', label: 'Healthy',   cssClass: 'grade-healthy' },
  unknown:   { emoji: '🟡', label: 'Unknown',   cssClass: 'grade-unknown' },
  dangerous: { emoji: '🔴', label: 'Dangerous', cssClass: 'grade-dangerous' },
}

const PERMISSION_LABELS = ['Blocked', 'Read', 'View Threads', 'React', 'Post', 'Chat']

// ── Helpers ───────────────────────────────────────────────────

async function getStatus(): Promise<{ configured: boolean; ricId?: string }> {
  return new Promise((resolve) => {
    chrome.runtime.sendMessage({ type: 'GET_STATUS' }, resolve)
  })
}

async function fetchCert(ricId: string) {
  try {
    const res = await fetch(`https://registry.robotidcard.dev/v1/bots/${ricId}`)
    if (!res.ok) return null
    return res.json()
  } catch {
    return null
  }
}

function sendMessage(msg: object): Promise<{ success: boolean }> {
  return new Promise((resolve) => {
    chrome.runtime.sendMessage(msg, resolve)
  })
}

// ── Render: configured state ──────────────────────────────────

function renderConfigured(cert: any) {
  const grade = GRADE_CONFIG[cert.grade as keyof typeof GRADE_CONFIG] || GRADE_CONFIG.unknown
  const permLevel = cert.grade === 'healthy' ? 3 : cert.grade === 'unknown' ? 1 : 0

  const app = document.getElementById('app')!
  app.innerHTML = `
    <div class="status-card">
      <div style="display:flex; justify-content:space-between; align-items:center; margin-bottom:10px">
        <span style="font-size:13px; font-weight:600">${cert.bot.name}</span>
        <span class="grade-badge ${grade.cssClass}">${grade.emoji} ${grade.label}</span>
      </div>
      <div class="field">
        <label>RIC ID</label>
        <value>${cert.id}</value>
      </div>
      <div class="field">
        <label>Developer</label>
        <value>${cert.developer.name} ${cert.developer.org ? `· ${cert.developer.org}` : ''}</value>
      </div>
      <div class="field">
        <label>Purpose</label>
        <value style="font-family:inherit; font-size:12px; color:#94a3b8">${cert.bot.purpose}</value>
      </div>
      <div class="permission-bar">
        <div class="label">Permission Level: ${permLevel}/5 — ${PERMISSION_LABELS[permLevel]}</div>
        <div class="levels">
          ${PERMISSION_LABELS.slice(1).map((_, i) =>
            `<div class="level-dot ${i + 1 <= permLevel ? 'active' : ''}"></div>`
          ).join('')}
        </div>
      </div>
    </div>
    <button class="btn-secondary" id="btn-refresh" style="margin-bottom:8px">Refresh Certificate</button>
    <button class="btn-danger" id="btn-disconnect">Disconnect Identity</button>
  `

  document.getElementById('btn-refresh')?.addEventListener('click', () => location.reload())

  document.getElementById('btn-disconnect')?.addEventListener('click', async () => {
    if (!confirm('Remove your RIC identity from this extension?')) return
    await sendMessage({ type: 'CLEAR_CONFIG' })
    location.reload()
  })
}

// ── Render: import modal ──────────────────────────────────────

function renderImportModal() {
  const app = document.getElementById('app')!
  app.innerHTML = `
    <div style="padding:4px 0 12px; color:#94a3b8; font-size:12px; line-height:1.6">
      Paste the contents of your <code style="background:#1e293b;padding:1px 4px;border-radius:3px">bot.ric.json</code>
      file (generated by <code style="background:#1e293b;padding:1px 4px;border-radius:3px">ric register</code>):
    </div>
    <textarea id="cert-input" placeholder='{ "id": "ric_...", "private_key_hex": "...", ... }'
      style="width:100%;height:120px;background:#1e293b;border:1px solid #334155;border-radius:6px;
             color:#e2e8f0;font-family:monospace;font-size:11px;padding:8px;resize:none;outline:none">
    </textarea>
    <div id="import-error" style="color:#f87171;font-size:12px;margin-top:6px;display:none"></div>
    <div style="display:flex;gap:8px;margin-top:10px">
      <button class="btn-primary" id="btn-import-confirm" style="flex:1">Import</button>
      <button class="btn-secondary" id="btn-import-cancel" style="flex:1">Cancel</button>
    </div>
  `

  document.getElementById('btn-import-cancel')?.addEventListener('click', () => init())

  document.getElementById('btn-import-confirm')?.addEventListener('click', async () => {
    const raw = (document.getElementById('cert-input') as HTMLTextAreaElement).value.trim()
    const errEl = document.getElementById('import-error')!

    let parsed: any
    try {
      parsed = JSON.parse(raw)
    } catch {
      errEl.textContent = 'Invalid JSON — paste the full contents of bot.ric.json'
      errEl.style.display = 'block'
      return
    }

    if (!parsed.id || !parsed.private_key_hex || !parsed.public_key) {
      errEl.textContent = 'Missing required fields: id, private_key_hex, public_key'
      errEl.style.display = 'block'
      return
    }

    await sendMessage({
      type: 'SAVE_CONFIG',
      config: {
        ricId: parsed.id,
        privateKeyHex: parsed.private_key_hex,
        certificate: parsed,
      },
    })

    location.reload()
  })
}

// ── Render: register instructions ────────────────────────────

function renderRegisterHelp() {
  const app = document.getElementById('app')!
  app.innerHTML = `
    <div style="font-size:12px;color:#94a3b8;line-height:1.7">
      <p style="margin-bottom:10px">Register your bot using the CLI:</p>
      <div style="background:#1e293b;border-radius:6px;padding:10px;font-family:monospace;font-size:11px;color:#7dd3fc;line-height:1.8">
        npm install -g @robot-id-card/cli<br>
        ric keygen<br>
        ric register --name "MyBot" \\<br>
        &nbsp;&nbsp;--purpose "Your bot's purpose" \\<br>
        &nbsp;&nbsp;--developer you@email.com
      </div>
      <p style="margin-top:10px">Then import the generated <code style="background:#1e293b;padding:1px 4px;border-radius:3px">bot.ric.json</code> file here.</p>
    </div>
    <button class="btn-secondary" id="btn-back" style="margin-top:12px">← Back</button>
  `

  document.getElementById('btn-back')?.addEventListener('click', () => init())
}

// ── Init ──────────────────────────────────────────────────────

async function init() {
  const status = await getStatus()

  if (!status.configured) {
    // Restore default not-configured HTML and attach button listeners
    const app = document.getElementById('app')!
    app.innerHTML = `
      <div class="not-configured">
        <p>No identity configured.<br/>Register your bot to get started.</p>
        <button class="btn-primary" id="btn-register">Register a Bot</button>
        <button class="btn-secondary" id="btn-import">Import Certificate</button>
      </div>
    `
    document.getElementById('btn-register')?.addEventListener('click', renderRegisterHelp)
    document.getElementById('btn-import')?.addEventListener('click', renderImportModal)
    return
  }

  const cert = status.ricId ? await fetchCert(status.ricId) : null
  if (cert) {
    renderConfigured(cert)
  }
}

document.addEventListener('DOMContentLoaded', init)
