#!/usr/bin/env python3
"""
<task-name> Executor Template
Generated by cron-task skill v1.0.0

Usage:
    python <task-name>_executor.py [--dry-run] [--date YYYY-MM-DD]

This script is designed to be called by TRAE Schedule.
It must be self-contained — no dependency on session context.
"""

import os
import sys
import json
import logging
import argparse
from datetime import datetime, timezone, timedelta
from pathlib import Path

# ============================================================
# Configuration (extracted from session context)
# ============================================================

TASK_NAME = "<task-name>"
PROJECT_ROOT = Path(__file__).parent.parent  # Adjust as needed
LOG_DIR = PROJECT_ROOT / "logs"
LOG_DIR.mkdir(exist_ok=True)

# Environment variables (must be configured in User scope)
REQUIRED_ENV_VARS = [
    "FEISHU_APP_ID",
    "FEISHU_APP_SECRET",
    "FEISHU_USER_OPEN_ID",
]

# Archive paths
OBSIDIAN_INBOX = Path(os.environ.get("OBSIDIAN_INBOX", "./inbox"))
FEISHU_DRIVE_FOLDER = "<folder_name>"  # or folder_token
IMA_KB_ID = "<kb_id>"  # IMA knowledge base ID

# Data sources
DATA_SOURCES = {
    # "api": "https://...",
    # "file": "/path/to/data.json",
}

# ============================================================
# Logging Setup
# ============================================================

tz = timezone(timedelta(hours=8))  # Asia/Shanghai
now = datetime.now(tz)
date_str = now.strftime("%Y-%m-%d")
log_file = LOG_DIR / f"{TASK_NAME}-{date_str}.log"

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[
        logging.FileHandler(log_file, encoding="utf-8"),
        logging.StreamHandler(sys.stdout),
    ],
)
logger = logging.getLogger(__name__)


# ============================================================
# Step 1: Check Environment Variables
# ============================================================

def check_env_vars():
    """Check all required environment variables are set."""
    missing = []
    for var in REQUIRED_ENV_VARS:
        val = os.environ.get(var)
        if not val:
            missing.append(var)
            logger.error(f"Missing env var: {var}")
        elif val.startswith("your_") or val == "dummy":
            missing.append(var)
            logger.warning(f"Placeholder env var: {var}")
    if missing:
        raise EnvironmentError(f"Missing env vars: {missing}")
    logger.info("✅ All environment variables configured")


# ============================================================
# Step 2: Main Execution Logic
# ============================================================

def fetch_data():
    """Fetch data from sources. Override this function with actual logic."""
    logger.info("Fetching data...")
    # TODO: Replace with actual data fetching logic
    data = []
    return data


def process_data(data):
    """Process fetched data. Override this function with actual logic."""
    logger.info(f"Processing {len(data)} items...")
    # TODO: Replace with actual processing logic
    result = {}
    return result


def generate_briefing(result):
    """Generate briefing markdown content."""
    logger.info("Generating briefing...")
    metadata = generate_metadata_header("success", 0)
    content = f"""{metadata}

# {TASK_NAME} Daily Briefing - {date_str}

## Summary
<!-- Briefing summary -->

## Details
<!-- Briefing details -->
"""
    return content


# ============================================================
# Step 3: Archive to Three Destinations
# ============================================================

def generate_metadata_header(status, error_count, archived_to=None):
    """Generate metadata header for archived files."""
    if archived_to is None:
        archived_to = []
    return f"""---
task_name: "{TASK_NAME}"
run_time: "{now.strftime('%Y-%m-%d %H:%M:%S')}"
data_source: "{', '.join(DATA_SOURCES.keys())}"
status: "{status}"
error_count: {error_count}
archived_to: {json.dumps(archived_to)}
---"""


def archive_to_obsidian(content):
    """Archive briefing to Obsidian inbox."""
    try:
        OBSIDIAN_INBOX.mkdir(parents=True, exist_ok=True)
        file_path = OBSIDIAN_INBOX / f"{TASK_NAME}-{date_str}.md"
        file_path.write_text(content, encoding="utf-8")
        logger.info(f"✅ Archived to Obsidian: {file_path}")
        return str(file_path)
    except Exception as e:
        logger.error(f"❌ Obsidian archive failed: {e}")
        return None


def archive_to_feishu(content):
    """Archive briefing to Feishu cloud drive."""
    try:
        # Use lark-cli or direct API call
        # This is a placeholder — replace with actual lark-drive call
        logger.info("Archiving to Feishu cloud drive...")
        # import subprocess
        # result = subprocess.run(["python", "-m", "lark_cli", "drive", "upload", ...])
        file_token = f"feishu_{date_str}"  # placeholder
        logger.info(f"✅ Archived to Feishu: {file_token}")
        return file_token
    except Exception as e:
        logger.error(f"❌ Feishu archive failed: {e}")
        return None


def archive_to_ima(content):
    """Archive briefing to IMA knowledge base (two-step API)."""
    try:
        import urllib.request

        client_id = os.environ.get("IMA_OPENAPI_CLIENTID") or os.environ.get("IMA_CLIENT_ID")
        api_key = os.environ.get("IMA_OPENAPI_APIKEY") or os.environ.get("IMA_API_KEY")

        if not client_id or not api_key:
            raise EnvironmentError("IMA credentials not configured")

        # Step 1: Create note
        url1 = "https://api.imawiki.com/openapi/note/v1/import_doc"
        data1 = json.dumps({
            "title": f"{TASK_NAME}-{date_str}",
            "content": content,
            "source": "cron-task"
        }).encode("utf-8")

        req1 = urllib.request.Request(url1, data=data1, headers={
            "Content-Type": "application/json",
            "ima-openapi-clientid": client_id,
            "ima-openapi-apikey": api_key
        })
        resp1 = urllib.request.urlopen(req1)
        note_id = json.loads(resp1.read())["data"]["note_id"]
        logger.info(f"✅ IMA note created: {note_id}")

        # Step 2: Add to knowledge base
        url2 = "https://api.imawiki.com/openapi/wiki/v1/add_knowledge"
        data2 = json.dumps({
            "kb_id": IMA_KB_ID,
            "media_type": 11,
            "note_info": {"content_id": note_id}
        }).encode("utf-8")

        req2 = urllib.request.Request(url2, data=data2, headers={
            "Content-Type": "application/json",
            "ima-openapi-clientid": client_id,
            "ima-openapi-apikey": api_key
        })
        urllib.request.urlopen(req2)
        logger.info(f"✅ Archived to IMA: {note_id}")
        return note_id

    except Exception as e:
        logger.error(f"❌ IMA archive failed: {e}")
        return None


def archive_all(content):
    """Archive to all three destinations. Failures don't interrupt main flow."""
    archived_to = []
    obsidian_path = archive_to_obsidian(content)
    if obsidian_path:
        archived_to.append("obsidian")

    feishu_token = archive_to_feishu(content)
    if feishu_token:
        archived_to.append("feishu_drive")

    ima_note_id = archive_to_ima(content)
    if ima_note_id:
        archived_to.append("ima")

    return archived_to


# ============================================================
# Step 4: Send IM Notification (Feishu Card)
# ============================================================

def send_feishu_card(status, summary, detail_link=None):
    """Send Feishu Interactive Card via lark-im."""
    try:
        # This is a placeholder — the TRAE agent will use lark-im skill
        # to send the actual card. This function is called from the
        # Schedule message prompt, not directly from this script.
        logger.info(f"Feishu card: {TASK_NAME} {date_str} {status}")
        logger.info(f"Summary: {summary}")
        if detail_link:
            logger.info(f"Detail link: {detail_link}")
    except Exception as e:
        logger.error(f"❌ Feishu card failed: {e}")


# ============================================================
# Main Entry Point
# ============================================================

def main():
    parser = argparse.ArgumentParser(description=f"{TASK_NAME} executor")
    parser.add_argument("--dry-run", action="store_true", help="Dry run mode")
    parser.add_argument("--date", type=str, default=date_str, help="Run date (YYYY-MM-DD)")
    args = parser.parse_args()

    global date_str
    date_str = args.date

    logger.info(f"=== {TASK_NAME} started at {now} ===")
    logger.info(f"Date: {date_str}, Dry run: {args.dry_run}")

    try:
        # Step 1: Check environment
        check_env_vars()

        if args.dry_run:
            logger.info("Dry run mode — skipping execution")
            return

        # Step 2: Main execution
        data = fetch_data()
        result = process_data(data)

        # Step 3: Generate briefing
        briefing = generate_briefing(result)

        # Step 4: Archive to three destinations
        archived_to = archive_all(briefing)

        # Step 5: Update metadata with archive status
        # (metadata header is already in briefing, archived_to is logged)

        # Step 6: Send IM notification
        send_feishu_card(
            status="success",
            summary=f"Task completed. Archived to: {', '.join(archived_to)}",
            detail_link=None
        )

        logger.info(f"=== {TASK_NAME} completed successfully ===")
        return 0

    except Exception as e:
        logger.error(f"=== {TASK_NAME} FAILED: {e} ===", exc_info=True)
        send_feishu_card(
            status="failed",
            summary=f"Error: {str(e)[:200]}",
            detail_link=None
        )
        return 1


if __name__ == "__main__":
    sys.exit(main())
