// mapper.ts — 中文名映射（species / moves / types）
// 数据来源：PvPoke + 本地手工对照

export const SPECIES_CN: Record<string, string> = {
  lickilicky: '大舌舔',
  lickitung: '大舌头',
  azumarill: '玛力露丽',
  altaria: '七夕青鸟',
  sableye: '勾魂眼',
  quagsire: '沼王',
  jellicent: '胖嘟嘟',
  toxicroak: '毒骷蛙',
  garchomp: '烈咬陆鲨',
  togekiss: '波克基斯',
  melmetal: '美录梅塔',
  bastiodon: '护城龙',
  tangrowth: '巨蔓藤',
  machamp: '怪力',
  snorlax: '卡比兽',
  swampert: '巨沼怪',
  umbreon: '月亮伊布',
  sylveon: '仙子伊布',
  dialga: '帝牙卢卡',
  giratina: '骑拉帝纳',
  mewtwo: '超梦',
  lugia: '洛奇亚',
  kyogre: '盖欧卡',
  groudon: '固拉多',
  palkia: '帕路奇亚',
  metagross: '巨金怪',
  dragonite: '快龙',
  tyranitar: '班基拉斯',
  steelix: '大钢蛇',
  cresselia: '克雷色利亚',
  feraligatr: '大力鳄',
  corviknight: '钢铠鸦',
  lapras: '拉普拉斯',
  tinkaton: '巨锻匠',
  wigglytuff: '胖可丁',
  empoleon: '帝王拿波',
  forretress: '佛烈托斯',
  annihilape: '弃世猴',
  xerneas: '哲尔尼亚斯',
  rayquaza: '烈空坐',
  hooh: '凤王',
  lucario: '路卡利欧',
  goodra: '黏美龙',
  hydreigon: '三首恶龙',
  clefable: '皮可西',
  blissey: '幸福蛋',
  chansey: '吉利蛋',
  roserade: '罗丝雷朵',
  magnezone: '自爆磁怪',
  electivire: '电击魔兽',
  blaziken: '火焰鸡',
  sceptile: '蜥蜴王',
  corsola_galarian: '伽勒尔太阳珊瑚',
  stunfisk: '泥巴鱼',
  stunfisk_galarian: '伽勒尔泥巴鱼',
  guzzlord: '恶食大王',
  malamar: '乌贼王',
  cetitan: '浩大鲸',
  spheal: '海豹球',
  croconaw: '蓝鳄',
  exeggutor: '椰蛋树',
  scolipede: '龙头蜈蚣',
  bouffalant: '爆炸头水牛',
  ninetales: '九尾',
  sandslash: '穿山王',
  sandslash_alolan: '穿山王（阿罗拉）',
  araquanid: '滴蛛霸',
  dusknoir: '黑夜魔灵',
  crabominable: '暴雪王',
  politoed: '牛蛙君',
  miltank: '大奶罐',
  walrein: '帝牙海狮',
  kingdra: '刺龙王',
  gastrodon: '海兔兽',
  sealeo: '海魔狮',
  mienshao: '师父鼬',
  dewott: '双刃丸',
  florges: '花洁夫人',
  rapidash_galarian: '伽勒尔烈焰马',
  rapidash: '烈焰马',
  charjabug: '虫电宝',
  snorunt: '雪童子',
  gyarados: '暴鲤龙',
  dragonair: '哈克龙',
  mamoswine: '象牙猪',
  piloswine: '长毛猪',
  dunsparce: '土龙弟弟',
  cradily: '摇篮百合',
  venusaur: '妙蛙花',
  abomasnow: '暴雪王',
  blastoise: '水箭龟',
  talonflame: '烈箭鹰',
};

/** 招式中文名 */
export const MOVE_CN: Record<string, string> = {
  // 快速招式
  COUNTER: '双倍奉还',
  MUD_SHOT: '泥巴射击',
  BUBBLE: '泡沫',
  DRAGON_BREATH: '龙息',
  SHADOW_CLAW: '暗影爪',
  VINE_WHIP: '藤鞭',
  LICK: '舔舌头',
  ZEN_HEADBUTT: '意念头锤',
  ROLLOUT: '滚动',
  WATER_GUN: '水枪',
  ROCK_SMASH: '碎岩',
  WATERFALL: '攀瀑',
  POWDER_SNOW: '细雪',
  HEX: '祸不单行',
  POISON_JAB: '毒击',
  DRAGON_TAIL: '龙尾',
  HIDDEN_POWER: '觉醒力量',
  AIR_SLASH: '空气利刃',
  ICE_SHARD: '冰砾',
  FAIRY_WIND: '妖精之风',
  LOW_KICK: '踢倒',
  BITE: '咬住',
  ICE_FANG: '冰牙',
  STEEL_WING: '钢翼',
  METAL_CLAW: '金属爪',
  SAND_ATTACK: '泼沙',
  FROST_BREATH: '冰息',
  PSYWAVE: '精神波',
  TACKLE: '撞击',
  GEOMANCY: '大地掌控',
  FURY_CUTTER: '连斩',
  BUG_BITE: '虫咬',
  INFESTATION: '纠缠不休',
  CHARM: '妖精之风',
  CONCUSSION: '意念',
  ROCK_THROW: '投掷岩石',
  THUNDER_SHOCK: '电击',
  SMACK_DOWN: '击落',
  KARATE_CHOP: '空手劈',
  BULLET_PUNCH: '子弹拳',
  PSYCHO_CUT: '精神切割',
  FEINT_ATTACK: '出奇一击',
  QUICK_ATTACK: '电光一闪',
  SPARK: '电光',
  SNARL: '大声咆哮',
  CONFUSION: '念力',
  EXTRASENSORY: '神通力',
  SUCKER_PUNCH: '突袭',
  LOW_SWEEP: '下盘踢',
  THUNDER_FANG: '雷电牙',
  FIRE_FANG: '火焰牙',
  RAZOR_LEAF: '飞叶快刀',
  INCINERATE: '火焰旋涡',
  MUD_SLAP: '掷泥',
  VOLT_SWITCH: '伏特替换',
  LOCK_ON: '锁定',

  // 蓄力招式
  BODY_SLAM: '泰山压顶',
  ICE_BEAM: '冰冻光束',
  PLAY_ROUGH: '嬉闹',
  HYDRO_PUMP: '水炮',
  SKY_ATTACK: '神鸟猛攻',
  MOONBLAST: '月亮之力',
  FOUL_PLAY: '欺诈',
  SHADOW_BALL: '暗影球',
  EARTHQUAKE: '地震',
  AQUA_TAIL: '水流尾',
  SURF: '冲浪',
  SLUDGE_BOMB: '污泥炸弹',
  HYDRO_CANNON: '加农水炮',
  EARTH_POWER: '大地之力',
  DRACO_METEOR: '流星群',
  OUTRAGE: '逆鳞',
  PRECIPICE_BLADES: '断崖之剑',
  STONE_EDGE: '尖石攻击',
  FLAMETHROWER: '喷射火焰',
  THUNDERBOLT: '十万伏特',
  PSYSTRIKE: '精神击破',
  SUPER_POWER: '蛮力',
  ROCK_SLIDE: '岩石封锁',
  TWISTER: '龙卷风',
  BREAKING_SWIPE: '广域破坏',
  RAGE_FIST: '愤怒之拳',
  NIGHT_SLASH: '暗袭要害',
  ICE_PUNCH: '冰冻拳',
  CLOSE_COMBAT: '近身战',
  BUBBLE_BEAM: '泡沫光线',
  DARK_PULSE: '恶之波动',
  SLUDGE_WAVE: '污泥波',
  FOCUS_BLAST: '真气弹',
  THUNDER_PUNCH: '雷电拳',
  FIRE_PUNCH: '火焰拳',
  DRAIN_PUNCH: '吸收拳',
  WILD_CHARGE: '疯狂伏特',
  ENERGY_BALL: '能量球',
  GRASS_KNOT: '打草结',
  FLAME_CHARGE: '蓄能焰袭',
  FLAME_BURST: '烈焰溅射',
  SEED_BOMB: '种子炸弹',
  LEAF_BLADE: '叶刃',
  LEAF_STORM: '飞叶风暴',
  BULLDOZE: '重踏',
  SCALD: '热水',
  WEATHER_BALL: '气象球',
  BRAVE_BIRD: '勇鸟猛攻',
  DRILL_RUN: '直冲钻',
  MEGAHORN: '超级角击',
  HURRICANE: '暴风',
  AURA_SPHERE: '波导弹',
  CRUNCH: '咬碎',
  PSYCHIC_FANGS: '精神之牙',
  PSYCHIC: '精神强念',
  MUD_BOMB: '泥巴炸弹',
  ROCK_TOMB: '岩石封锁',
  POWER_GEM: '力量宝石',
  FLASH_CANNON: '加农光炮',
  MIRROR_SHOT: '镜光射击',
  IRON_HEAD: '铁头',
  ZAP_CANNON: '电磁炮',
  DISCHARGE: '放电',
  GYRO_BALL: '陀螺球',
  DOOM_DESIRE: '破灭之愿',
  LUNGE: '突袭',
  POISON_FANG: '毒击',
  FELL_STINGER: '致命针刺',
  SIGNAL_BEAM: '信号光束',
  X_SCISSOR: '十字剪',
  BUG_BUZZ: '虫鸣',
  BLAST_BURN: '爆炸烈焰',
  FRENZY_PLANT: '疯狂植物',
  RETURN: '报恩',
  LAST_RESORT: '珍藏',
  AEROBLAST: '气旋攻击',
  DYNAMIC_PUNCH: '爆裂拳',
  CROSS_CHOP: '十字劈',
  BRICK_BREAK: '劈瓦',
  POWER_WHIP: '强力鞭打',
  PETAL_BLIZZARD: '花瓣舞',
  SOLAR_BEAM: '日光束',
  HYPER_BEAM: '破坏光线',
  BLIZZARD: '暴风雪',
  THUNDER: '打雷',
  FIRE_BLAST: '大字爆炎',
  OVERHEAT: '过热',
  ACID_SPRAY: '酸液炸弹',
  GUNK_SHOT: '垃圾射击',
  MAGNET_BOMB: '磁铁炸弹',
  STUN_SPORE: '麻痹粉',
};

/** 属性中文名 */
export const TYPE_CN: Record<string, string> = {
  Normal: '一般',
  Fire: '火',
  Water: '水',
  Electric: '电',
  Grass: '草',
  Ice: '冰',
  Fighting: '格斗',
  Poison: '毒',
  Ground: '地面',
  Flying: '飞行',
  Psychic: '超能力',
  Bug: '虫',
  Rock: '岩石',
  Ghost: '幽灵',
  Dragon: '龙',
  Dark: '恶',
  Steel: '钢',
  Fairy: '妖精',
};

export function getSpeciesCn(speciesId: string): string {
  if (SPECIES_CN[speciesId]) return SPECIES_CN[speciesId];
  // 尝试去掉影子后缀
  const base = speciesId.replace(/_shadow$/, '');
  if (base !== speciesId && SPECIES_CN[base]) {
    return SPECIES_CN[base] + '（暗影）';
  }
  // 驼峰转空格
  return speciesId.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}

export function getMoveCn(moveId: string): string {
  return MOVE_CN[moveId] || moveId.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}

export function getTypeCn(typeKey: string): string {
  return TYPE_CN[typeKey] || typeKey;
}
