// Generated by fetch_league.py (epl). Do not edit by hand.
window.HUB_DATA = {
 "league": {
  "key": "epl",
  "id": "4328",
  "name": "Premier League",
  "fullName": "English Premier League",
  "country": "England",
  "brandColor": "#00ff87"
 },
 "generatedAt": "2026-07-15 22:21 UTC",
 "teams": [
  {
   "id": "133604",
   "name": "Arsenal",
   "short": "ARS",
   "badge": "https://r2.thesportsdb.com/images/media/team/badge/uyhbfe1612467038.png",
   "colors": [
    "#EF0107",
    "#fbffff",
    "#013373"
   ],
   "stadium": "Emirates Stadium",
   "formed": "1892"
  },
  {
   "id": "133601",
   "name": "Aston Villa",
   "short": "AVL",
   "badge": "https://r2.thesportsdb.com/images/media/team/badge/jykrpv1717309891.png",
   "colors": [
    "#490125",
    "#93bde4",
    "#fee407"
   ],
   "stadium": "Villa Park",
   "formed": "1874"
  },
  {
   "id": "134301",
   "name": "Bournemouth",
   "short": "BOU",
   "badge": "https://r2.thesportsdb.com/images/media/team/badge/y08nak1534071116.png",
   "colors": [
    "#B50E12",
    "#000000",
    ""
   ],
   "stadium": "Vitality Stadium",
   "formed": "1890"
  },
  {
   "id": "134355",
   "name": "Brentford",
   "short": "BRE",
   "badge": "https://r2.thesportsdb.com/images/media/team/badge/grv1aw1546453779.png",
   "colors": [
    "#e30613",
    "#FFFFFF",
    "#fbb800"
   ],
   "stadium": "Brentford Community Stadium",
   "formed": "1889"
  },
  {
   "id": "133619",
   "name": "Brighton and Hove Albion",
   "short": "BRI",
   "badge": "https://r2.thesportsdb.com/images/media/team/badge/ywypts1448810904.png",
   "colors": [
    "#0057B8",
    "#FFFFFF",
    ""
   ],
   "stadium": "American Express Stadium",
   "formed": "1901"
  },
  {
   "id": "133610",
   "name": "Chelsea",
   "short": "CHE",
   "badge": "https://www.thesportsdb.com/images/media/team/badge/pbf4ul1782638263.png",
   "colors": [
    "#034694",
    "#FFFFFF",
    "#DBA111"
   ],
   "stadium": "Stamford Bridge",
   "formed": "1905"
  },
  {
   "id": "133625",
   "name": "Coventry City",
   "short": "CVC",
   "badge": "https://r2.thesportsdb.com/images/media/team/badge/uxyqys1424033798.png",
   "colors": [
    "#77bbff",
    "#ffffff",
    "#007711"
   ],
   "stadium": "The Coventry Building Society Arena",
   "formed": "1883"
  },
  {
   "id": "133632",
   "name": "Crystal Palace",
   "short": "CRY",
   "badge": "https://r2.thesportsdb.com/images/media/team/badge/ia6i3m1656014992.png",
   "colors": [
    "#1B458F",
    "#C4122E",
    ""
   ],
   "stadium": "Selhurst Park",
   "formed": "1905"
  },
  {
   "id": "133615",
   "name": "Everton",
   "short": "EVE",
   "badge": "https://r2.thesportsdb.com/images/media/team/badge/eqayrf1523184794.png",
   "colors": [
    "#003399",
    "#FFFFFF",
    ""
   ],
   "stadium": "Hill Dickinson Stadium",
   "formed": "1878"
  },
  {
   "id": "133600",
   "name": "Fulham",
   "short": "FUL",
   "badge": "https://r2.thesportsdb.com/images/media/team/badge/xwwvyt1448811086.png",
   "colors": [
    "#FFFFFF",
    "#000000",
    "#CC0000"
   ],
   "stadium": "Craven Cottage",
   "formed": "1879"
  },
  {
   "id": "133617",
   "name": "Hull City",
   "short": "HUL",
   "badge": "https://r2.thesportsdb.com/images/media/team/badge/fbqqda1601726113.png",
   "colors": [
    "#f5971d",
    "#000000",
    "#ffffff"
   ],
   "stadium": "The MKM Stadium",
   "formed": "1904"
  },
  {
   "id": "133622",
   "name": "Ipswich Town",
   "short": "IPS",
   "badge": "https://r2.thesportsdb.com/images/media/team/badge/mdj1ey1634670785.png",
   "colors": [
    "#3a64a3",
    "#de2c37",
    "#FFFFFF"
   ],
   "stadium": "Portman Road",
   "formed": "1878"
  },
  {
   "id": "133635",
   "name": "Leeds United",
   "short": "LEE",
   "badge": "https://r2.thesportsdb.com/images/media/team/badge/jcgrml1756649030.png",
   "colors": [
    "#ffffff",
    "#1D428A",
    "#FFCD00"
   ],
   "stadium": "Elland Road",
   "formed": "1919"
  },
  {
   "id": "133602",
   "name": "Liverpool",
   "short": "LIV",
   "badge": "https://r2.thesportsdb.com/images/media/team/badge/kfaher1737969724.png",
   "colors": [
    "#C8102E",
    "#FFFFFF",
    ""
   ],
   "stadium": "Anfield",
   "formed": "1892"
  },
  {
   "id": "133613",
   "name": "Manchester City",
   "short": "MCI",
   "badge": "https://r2.thesportsdb.com/images/media/team/badge/vwpvry1467462651.png",
   "colors": [
    "#6CABDD",
    "#FFFFFF",
    "#1C2C5B"
   ],
   "stadium": "Etihad Stadium",
   "formed": "1880"
  },
  {
   "id": "133612",
   "name": "Manchester United",
   "short": "MUN",
   "badge": "https://r2.thesportsdb.com/images/media/team/badge/xzqdr11517660252.png",
   "colors": [
    "#DA291C",
    "#Ffffff",
    "#000000"
   ],
   "stadium": "Old Trafford",
   "formed": "1878"
  },
  {
   "id": "134777",
   "name": "Newcastle United",
   "short": "NEW",
   "badge": "https://r2.thesportsdb.com/images/media/team/badge/lhwuiz1621593302.png",
   "colors": [
    "#FFFFFF",
    "#241F20",
    ""
   ],
   "stadium": "St James Park",
   "formed": "1892"
  },
  {
   "id": "133603",
   "name": "Sunderland",
   "short": "SUN",
   "badge": "https://r2.thesportsdb.com/images/media/team/badge/tprtus1448813498.png",
   "colors": [
    "#ff0000",
    "#ffffff",
    "#000000"
   ],
   "stadium": "Stadium of Light",
   "formed": "1879"
  },
  {
   "id": "133616",
   "name": "Tottenham Hotspur",
   "short": "TOT",
   "badge": "https://r2.thesportsdb.com/images/media/team/badge/dfyfhl1604094109.png",
   "colors": [
    "#FFFFFF",
    "#132257",
    ""
   ],
   "stadium": "Tottenham Hotspur Stadium",
   "formed": "1882"
  }
 ],
 "leagueFixtures": [
  {
   "id": "2521554",
   "event": "Crystal Palace vs Swindon Town",
   "timestamp": "2026-07-18T11:30:00",
   "home": "Crystal Palace",
   "away": "Swindon Town",
   "homeScore": null,
   "awayScore": null,
   "venue": "Selhurst Park",
   "homeGoals": null,
   "awayGoals": null,
   "season": "2026"
  },
  {
   "id": "2504385",
   "event": "Newcastle United vs Darlington",
   "timestamp": "2026-07-18T12:00:00",
   "home": "Newcastle United",
   "away": "Darlington",
   "homeScore": null,
   "awayScore": null,
   "venue": "St James Park",
   "homeGoals": null,
   "awayGoals": null,
   "season": "2026"
  },
  {
   "id": "2477304",
   "event": "Northampton Town vs Coventry City",
   "timestamp": "2026-07-18T13:00:00",
   "home": "Northampton Town",
   "away": "Coventry City",
   "homeScore": null,
   "awayScore": null,
   "venue": "Sixfields Stadium",
   "homeGoals": null,
   "awayGoals": null,
   "season": "2026"
  },
  {
   "id": "2502488",
   "event": "Dundee vs Everton",
   "timestamp": "2026-07-18T13:00:00",
   "home": "Dundee",
   "away": "Everton",
   "homeScore": null,
   "awayScore": null,
   "venue": "Dens Park",
   "homeGoals": null,
   "awayGoals": null,
   "season": "2026"
  },
  {
   "id": "2497663",
   "event": "York City vs Sunderland",
   "timestamp": "2026-07-18T14:00:00",
   "home": "York City",
   "away": "Sunderland",
   "homeScore": null,
   "awayScore": null,
   "venue": "LNER Community Stadium",
   "homeGoals": null,
   "awayGoals": null,
   "season": "2026"
  },
  {
   "id": "2467926",
   "event": "Manchester United vs Wrexham",
   "timestamp": "2026-07-18T15:00:00",
   "home": "Manchester United",
   "away": "Wrexham",
   "homeScore": null,
   "awayScore": null,
   "venue": "Helsinki Olympic Stadium",
   "homeGoals": null,
   "awayGoals": null,
   "season": "2026"
  },
  {
   "id": "2482867",
   "event": "Walsall vs Aston Villa",
   "timestamp": "2026-07-21T18:30:00",
   "home": "Walsall",
   "away": "Aston Villa",
   "homeScore": null,
   "awayScore": null,
   "venue": "Pallet-Track Bescot Stadium",
   "homeGoals": null,
   "awayGoals": null,
   "season": "2026"
  },
  {
   "id": "2499471",
   "event": "Tottenham Hotspur vs Milton Keynes Dons",
   "timestamp": "2026-07-22T12:00:00",
   "home": "Tottenham Hotspur",
   "away": "Dons",
   "homeScore": null,
   "awayScore": null,
   "venue": "Tottenham Hotspur Stadium",
   "homeGoals": null,
   "awayGoals": null,
   "season": "2026"
  },
  {
   "id": "2521611",
   "event": "Bournemouth vs St Pauli",
   "timestamp": "2026-07-24T14:00:00",
   "home": "Bournemouth",
   "away": "St Pauli",
   "homeScore": null,
   "awayScore": null,
   "venue": "Vitality Stadium",
   "homeGoals": null,
   "awayGoals": null,
   "season": "2026"
  },
  {
   "id": "2521622",
   "event": "Annecy vs Brighton and Hove Albion",
   "timestamp": "2026-07-25T12:00:00",
   "home": "Annecy",
   "away": "Brighton and Hove Albion",
   "homeScore": null,
   "awayScore": null,
   "venue": "Parc des Sports",
   "homeGoals": null,
   "awayGoals": null,
   "season": "2026"
  }
 ],
 "leagueResults": [
  {
   "id": "2470622",
   "event": "Crystal Palace vs Rayo Vallecano",
   "timestamp": "2026-05-27T19:00:00",
   "home": "Crystal Palace",
   "away": "Rayo Vallecano",
   "homeScore": "1",
   "awayScore": "0",
   "venue": "Red Bull Arena Leipzig",
   "homeGoals": null,
   "awayGoals": null,
   "season": "2025-2026"
  },
  {
   "id": "2267452",
   "event": "West Ham United vs Leeds United",
   "timestamp": "2026-05-24T15:00:00",
   "home": "West Ham United",
   "away": "Leeds United",
   "homeScore": "3",
   "awayScore": "0",
   "venue": "London Stadium",
   "homeGoals": null,
   "awayGoals": null,
   "season": "2025-2026"
  },
  {
   "id": "2267443",
   "event": "Brighton and Hove Albion vs Manchester United",
   "timestamp": "2026-05-24T15:00:00",
   "home": "Brighton and Hove Albion",
   "away": "Manchester United",
   "homeScore": "0",
   "awayScore": "3",
   "venue": "American Express Stadium",
   "homeGoals": null,
   "awayGoals": null,
   "season": "2025-2026"
  },
  {
   "id": "2267446",
   "event": "Fulham vs Newcastle United",
   "timestamp": "2026-05-24T15:00:00",
   "home": "Fulham",
   "away": "Newcastle United",
   "homeScore": "2",
   "awayScore": "0",
   "venue": "Craven Cottage",
   "homeGoals": null,
   "awayGoals": null,
   "season": "2025-2026"
  },
  {
   "id": "2267447",
   "event": "Liverpool vs Brentford",
   "timestamp": "2026-05-24T15:00:00",
   "home": "Liverpool",
   "away": "Brentford",
   "homeScore": "1",
   "awayScore": "1",
   "venue": "Anfield",
   "homeGoals": null,
   "awayGoals": null,
   "season": "2025-2026"
  },
  {
   "id": "2267448",
   "event": "Manchester City vs Aston Villa",
   "timestamp": "2026-05-24T15:00:00",
   "home": "Manchester City",
   "away": "Aston Villa",
   "homeScore": "1",
   "awayScore": "2",
   "venue": "Etihad Stadium",
   "homeGoals": null,
   "awayGoals": null,
   "season": "2025-2026"
  },
  {
   "id": "2267450",
   "event": "Sunderland vs Chelsea",
   "timestamp": "2026-05-24T15:00:00",
   "home": "Sunderland",
   "away": "Chelsea",
   "homeScore": "2",
   "awayScore": "1",
   "venue": "Stadium of Light",
   "homeGoals": null,
   "awayGoals": null,
   "season": "2025-2026"
  },
  {
   "id": "2267451",
   "event": "Tottenham Hotspur vs Everton",
   "timestamp": "2026-05-24T15:00:00",
   "home": "Tottenham Hotspur",
   "away": "Everton",
   "homeScore": "1",
   "awayScore": "0",
   "venue": "Tottenham Hotspur Stadium",
   "homeGoals": null,
   "awayGoals": null,
   "season": "2025-2026"
  },
  {
   "id": "2475703",
   "event": "Hull City vs Middlesbrough",
   "timestamp": "2026-05-23T14:30:00",
   "home": "Hull City",
   "away": "Middlesbrough",
   "homeScore": "1",
   "awayScore": "0",
   "venue": "Wembley Stadium",
   "homeGoals": null,
   "awayGoals": null,
   "season": "2025-2026"
  },
  {
   "id": "2267437",
   "event": "Chelsea vs Tottenham Hotspur",
   "timestamp": "2026-05-19T19:15:00",
   "home": "Chelsea",
   "away": "Tottenham Hotspur",
   "homeScore": "2",
   "awayScore": "1",
   "venue": "Stamford Bridge",
   "homeGoals": null,
   "awayGoals": null,
   "season": "2025-2026"
  }
 ],
 "teamFixtures": {
  "133604": {
   "next": [
    {
     "id": "2521780",
     "event": "Girona vs Arsenal",
     "timestamp": "2026-08-01T18:00:00",
     "home": "Girona",
     "away": "Arsenal",
     "homeScore": null,
     "awayScore": null,
     "venue": "Estadi Municipal de Montilivi",
     "homeGoals": null,
     "awayGoals": null,
     "season": "2026"
    }
   ],
   "past": [
    {
     "id": "2267433",
     "event": "Arsenal vs Burnley",
     "timestamp": "2026-05-18T19:00:00",
     "home": "Arsenal",
     "away": "Burnley",
     "homeScore": "1",
     "awayScore": "0",
     "venue": "Emirates Stadium",
     "homeGoals": null,
     "awayGoals": null,
     "season": "2025-2026"
    }
   ]
  },
  "133601": {
   "next": [
    {
     "id": "2482867",
     "event": "Walsall vs Aston Villa",
     "timestamp": "2026-07-21T18:30:00",
     "home": "Walsall",
     "away": "Aston Villa",
     "homeScore": null,
     "awayScore": null,
     "venue": "Pallet-Track Bescot Stadium",
     "homeGoals": null,
     "awayGoals": null,
     "season": "2026"
    }
   ],
   "past": [
    {
     "id": "2267434",
     "event": "Aston Villa vs Liverpool",
     "timestamp": "2026-05-15T19:00:00",
     "home": "Aston Villa",
     "away": "Liverpool",
     "homeScore": "4",
     "awayScore": "2",
     "venue": "Villa Park",
     "homeGoals": null,
     "awayGoals": null,
     "season": "2025-2026"
    }
   ]
  },
  "134301": {
   "next": [
    {
     "id": "2521611",
     "event": "Bournemouth vs St Pauli",
     "timestamp": "2026-07-24T14:00:00",
     "home": "Bournemouth",
     "away": "St Pauli",
     "homeScore": null,
     "awayScore": null,
     "venue": "Vitality Stadium",
     "homeGoals": null,
     "awayGoals": null,
     "season": "2026"
    }
   ],
   "past": [
    {
     "id": "2267435",
     "event": "Bournemouth vs Manchester City",
     "timestamp": "2026-05-19T18:30:00",
     "home": "Bournemouth",
     "away": "Manchester City",
     "homeScore": "1",
     "awayScore": "1",
     "venue": "Vitality Stadium",
     "homeGoals": null,
     "awayGoals": null,
     "season": "2025-2026"
    }
   ]
  },
  "134355": {
   "next": [
    {
     "id": "2480183",
     "event": "Rennes vs Brentford",
     "timestamp": "2026-08-08T16:00:00",
     "home": "Rennes",
     "away": "Brentford",
     "homeScore": null,
     "awayScore": null,
     "venue": "Roazhon Park",
     "homeGoals": null,
     "awayGoals": null,
     "season": "2026"
    }
   ],
   "past": [
    {
     "id": "2267436",
     "event": "Brentford vs Crystal Palace",
     "timestamp": "2026-05-17T14:00:00",
     "home": "Brentford",
     "away": "Crystal Palace",
     "homeScore": "2",
     "awayScore": "2",
     "venue": "Brentford Community Stadium",
     "homeGoals": null,
     "awayGoals": null,
     "season": "2025-2026"
    }
   ]
  },
  "133619": {
   "next": [
    {
     "id": "2521622",
     "event": "Annecy vs Brighton and Hove Albion",
     "timestamp": "2026-07-25T12:00:00",
     "home": "Annecy",
     "away": "Brighton and Hove Albion",
     "homeScore": null,
     "awayScore": null,
     "venue": "Parc des Sports",
     "homeGoals": null,
     "awayGoals": null,
     "season": "2026"
    }
   ],
   "past": [
    {
     "id": "2267443",
     "event": "Brighton and Hove Albion vs Manchester United",
     "timestamp": "2026-05-24T15:00:00",
     "home": "Brighton and Hove Albion",
     "away": "Manchester United",
     "homeScore": "0",
     "awayScore": "3",
     "venue": "American Express Stadium",
     "homeGoals": null,
     "awayGoals": null,
     "season": "2025-2026"
    }
   ]
  },
  "133610": {
   "next": [
    {
     "id": "2414270",
     "event": "Chelsea vs Western Sydney Wanderers",
     "timestamp": "2026-07-28T09:45:00",
     "home": "Chelsea",
     "away": "Western Sydney Wanderers",
     "homeScore": null,
     "awayScore": null,
     "venue": "Stamford Bridge",
     "homeGoals": null,
     "awayGoals": null,
     "season": "2026"
    }
   ],
   "past": [
    {
     "id": "2267437",
     "event": "Chelsea vs Tottenham Hotspur",
     "timestamp": "2026-05-19T19:15:00",
     "home": "Chelsea",
     "away": "Tottenham Hotspur",
     "homeScore": "2",
     "awayScore": "1",
     "venue": "Stamford Bridge",
     "homeGoals": null,
     "awayGoals": null,
     "season": "2025-2026"
    }
   ]
  },
  "133625": {
   "next": [
    {
     "id": "2477304",
     "event": "Northampton Town vs Coventry City",
     "timestamp": "2026-07-18T13:00:00",
     "home": "Northampton Town",
     "away": "Coventry City",
     "homeScore": null,
     "awayScore": null,
     "venue": "Sixfields Stadium",
     "homeGoals": null,
     "awayGoals": null,
     "season": "2026"
    }
   ],
   "past": [
    {
     "id": "2275722",
     "event": "Coventry City vs Wrexham",
     "timestamp": "2026-04-26T11:00:00",
     "home": "Coventry City",
     "away": "Wrexham",
     "homeScore": "3",
     "awayScore": "1",
     "venue": "The Coventry Building Society Arena",
     "homeGoals": null,
     "awayGoals": null,
     "season": "2025-2026"
    }
   ]
  },
  "133632": {
   "next": [
    {
     "id": "2521554",
     "event": "Crystal Palace vs Swindon Town",
     "timestamp": "2026-07-18T11:30:00",
     "home": "Crystal Palace",
     "away": "Swindon Town",
     "homeScore": null,
     "awayScore": null,
     "venue": "Selhurst Park",
     "homeGoals": null,
     "awayGoals": null,
     "season": "2026"
    }
   ],
   "past": [
    {
     "id": "2470622",
     "event": "Crystal Palace vs Rayo Vallecano",
     "timestamp": "2026-05-27T19:00:00",
     "home": "Crystal Palace",
     "away": "Rayo Vallecano",
     "homeScore": "1",
     "awayScore": "0",
     "venue": "Red Bull Arena Leipzig",
     "homeGoals": null,
     "awayGoals": null,
     "season": "2025-2026"
    }
   ]
  },
  "133615": {
   "next": [
    {
     "id": "2502488",
     "event": "Dundee vs Everton",
     "timestamp": "2026-07-18T13:00:00",
     "home": "Dundee",
     "away": "Everton",
     "homeScore": null,
     "awayScore": null,
     "venue": "Dens Park",
     "homeGoals": null,
     "awayGoals": null,
     "season": "2026"
    }
   ],
   "past": [
    {
     "id": "2267438",
     "event": "Everton vs Sunderland",
     "timestamp": "2026-05-17T14:00:00",
     "home": "Everton",
     "away": "Sunderland",
     "homeScore": "1",
     "awayScore": "3",
     "venue": "Hill Dickinson Stadium",
     "homeGoals": null,
     "awayGoals": null,
     "season": "2025-2026"
    }
   ]
  },
  "133600": {
   "next": [
    {
     "id": "2494009",
     "event": "Fulham vs Chelsea",
     "timestamp": "2026-08-24T19:00:00",
     "home": "Fulham",
     "away": "Chelsea",
     "homeScore": null,
     "awayScore": null,
     "venue": "Craven Cottage",
     "homeGoals": null,
     "awayGoals": null,
     "season": "2026-2027"
    }
   ],
   "past": [
    {
     "id": "2267446",
     "event": "Fulham vs Newcastle United",
     "timestamp": "2026-05-24T15:00:00",
     "home": "Fulham",
     "away": "Newcastle United",
     "homeScore": "2",
     "awayScore": "0",
     "venue": "Craven Cottage",
     "homeGoals": null,
     "awayGoals": null,
     "season": "2025-2026"
    }
   ]
  },
  "133617": {
   "next": [
    {
     "id": "2527403",
     "event": "Konyaspor vs Hull City",
     "timestamp": "2026-07-25T15:30:00",
     "home": "Konyaspor",
     "away": "Hull City",
     "homeScore": null,
     "awayScore": null,
     "venue": "Konya B\u00fcy\u00fck\u015fehir Belediye Stadyumu",
     "homeGoals": null,
     "awayGoals": null,
     "season": "2026"
    }
   ],
   "past": [
    {
     "id": "2475703",
     "event": "Hull City vs Middlesbrough",
     "timestamp": "2026-05-23T14:30:00",
     "home": "Hull City",
     "away": "Middlesbrough",
     "homeScore": "1",
     "awayScore": "0",
     "venue": "Wembley Stadium",
     "homeGoals": null,
     "awayGoals": null,
     "season": "2025-2026"
    }
   ]
  },
  "133622": {
   "next": [
    {
     "id": "2521678",
     "event": "Ipswich Town vs Osasuna",
     "timestamp": "2026-07-29T18:45:00",
     "home": "Ipswich Town",
     "away": "Osasuna",
     "homeScore": null,
     "awayScore": null,
     "venue": "Portman Road",
     "homeGoals": null,
     "awayGoals": null,
     "season": "2026"
    }
   ],
   "past": [
    {
     "id": "2275734",
     "event": "Ipswich Town vs Queens Park Rangers",
     "timestamp": "2026-05-02T11:30:00",
     "home": "Ipswich Town",
     "away": "Queens Park Rangers",
     "homeScore": "3",
     "awayScore": "0",
     "venue": "Portman Road",
     "homeGoals": null,
     "awayGoals": null,
     "season": "2025-2026"
    }
   ]
  },
  "133635": {
   "next": [
    {
     "id": "2529345",
     "event": "Wrexham vs Leeds United",
     "timestamp": "2026-07-25T20:00:00",
     "home": "Wrexham",
     "away": "Leeds United",
     "homeScore": null,
     "awayScore": null,
     "venue": "Raymond James Stadium",
     "homeGoals": null,
     "awayGoals": null,
     "season": "2026"
    }
   ],
   "past": [
    {
     "id": "2267439",
     "event": "Leeds United vs Brighton and Hove Albion",
     "timestamp": "2026-05-17T14:00:00",
     "home": "Leeds United",
     "away": "Brighton and Hove Albion",
     "homeScore": "1",
     "awayScore": "0",
     "venue": "Elland Road",
     "homeGoals": null,
     "awayGoals": null,
     "season": "2025-2026"
    }
   ]
  },
  "133602": {
   "next": [
    {
     "id": "2529346",
     "event": "Liverpool vs Sunderland",
     "timestamp": "2026-07-25T22:00:00",
     "home": "Liverpool",
     "away": "Sunderland",
     "homeScore": null,
     "awayScore": null,
     "venue": "GEODIS Park",
     "homeGoals": null,
     "awayGoals": null,
     "season": "2026"
    }
   ],
   "past": [
    {
     "id": "2267447",
     "event": "Liverpool vs Brentford",
     "timestamp": "2026-05-24T15:00:00",
     "home": "Liverpool",
     "away": "Brentford",
     "homeScore": "1",
     "awayScore": "1",
     "venue": "Anfield",
     "homeGoals": null,
     "awayGoals": null,
     "season": "2025-2026"
    }
   ]
  },
  "133613": {
   "next": [
    {
     "id": "2477357",
     "event": "Manchester City vs Inter Milan",
     "timestamp": "2026-08-01T11:30:00",
     "home": "Manchester City",
     "away": "Inter Milan",
     "homeScore": null,
     "awayScore": null,
     "venue": "Etihad Stadium",
     "homeGoals": null,
     "awayGoals": null,
     "season": "2026"
    }
   ],
   "past": [
    {
     "id": "2267448",
     "event": "Manchester City vs Aston Villa",
     "timestamp": "2026-05-24T15:00:00",
     "home": "Manchester City",
     "away": "Aston Villa",
     "homeScore": "1",
     "awayScore": "2",
     "venue": "Etihad Stadium",
     "homeGoals": null,
     "awayGoals": null,
     "season": "2025-2026"
    }
   ]
  },
  "133612": {
   "next": [
    {
     "id": "2467926",
     "event": "Manchester United vs Wrexham",
     "timestamp": "2026-07-18T15:00:00",
     "home": "Manchester United",
     "away": "Wrexham",
     "homeScore": null,
     "awayScore": null,
     "venue": "Helsinki Olympic Stadium",
     "homeGoals": null,
     "awayGoals": null,
     "season": "2026"
    }
   ],
   "past": [
    {
     "id": "2267440",
     "event": "Manchester United vs Nottingham Forest",
     "timestamp": "2026-05-17T11:30:00",
     "home": "Manchester United",
     "away": "Nottingham Forest",
     "homeScore": "3",
     "awayScore": "2",
     "venue": "Old Trafford",
     "homeGoals": null,
     "awayGoals": null,
     "season": "2025-2026"
    }
   ]
  },
  "134777": {
   "next": [
    {
     "id": "2504385",
     "event": "Newcastle United vs Darlington",
     "timestamp": "2026-07-18T12:00:00",
     "home": "Newcastle United",
     "away": "Darlington",
     "homeScore": null,
     "awayScore": null,
     "venue": "St James Park",
     "homeGoals": null,
     "awayGoals": null,
     "season": "2026"
    }
   ],
   "past": [
    {
     "id": "2267441",
     "event": "Newcastle United vs West Ham United",
     "timestamp": "2026-05-17T16:30:00",
     "home": "Newcastle United",
     "away": "West Ham United",
     "homeScore": "3",
     "awayScore": "1",
     "venue": "St James Park",
     "homeGoals": null,
     "awayGoals": null,
     "season": "2025-2026"
    }
   ]
  },
  "133603": {
   "next": [
    {
     "id": "2497663",
     "event": "York City vs Sunderland",
     "timestamp": "2026-07-18T14:00:00",
     "home": "York City",
     "away": "Sunderland",
     "homeScore": null,
     "awayScore": null,
     "venue": "LNER Community Stadium",
     "homeGoals": null,
     "awayGoals": null,
     "season": "2026"
    }
   ],
   "past": [
    {
     "id": "2267450",
     "event": "Sunderland vs Chelsea",
     "timestamp": "2026-05-24T15:00:00",
     "home": "Sunderland",
     "away": "Chelsea",
     "homeScore": "2",
     "awayScore": "1",
     "venue": "Stadium of Light",
     "homeGoals": null,
     "awayGoals": null,
     "season": "2025-2026"
    }
   ]
  },
  "133616": {
   "next": [
    {
     "id": "2499471",
     "event": "Tottenham Hotspur vs Milton Keynes Dons",
     "timestamp": "2026-07-22T12:00:00",
     "home": "Tottenham Hotspur",
     "away": "Dons",
     "homeScore": null,
     "awayScore": null,
     "venue": "Tottenham Hotspur Stadium",
     "homeGoals": null,
     "awayGoals": null,
     "season": "2026"
    }
   ],
   "past": [
    {
     "id": "2267451",
     "event": "Tottenham Hotspur vs Everton",
     "timestamp": "2026-05-24T15:00:00",
     "home": "Tottenham Hotspur",
     "away": "Everton",
     "homeScore": "1",
     "awayScore": "0",
     "venue": "Tottenham Hotspur Stadium",
     "homeGoals": null,
     "awayGoals": null,
     "season": "2025-2026"
    }
   ]
  }
 },
 "squads": {
  "133604": [
   {
    "name": "David Raya",
    "position": "Goalkeeper",
    "nationality": "Spain",
    "number": "1",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/877ews1779732793.jpg"
   }
  ],
  "133601": [
   {
    "name": "Bradley-Paul Burrowes",
    "position": "Midfielder",
    "nationality": "England",
    "number": "83",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/uxp2yx1770199284.jpg"
   },
   {
    "name": "Emiliano Martinez",
    "position": "Goalkeeper",
    "nationality": "Argentina",
    "number": "23",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/7drp311770201331.jpg"
   }
  ],
  "134301": [
   {
    "name": "Amine Adli",
    "position": "Midfielder",
    "nationality": "France",
    "number": "17",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/cutxxz1771752339.jpg"
   },
   {
    "name": "Bafod\u00e9 Diakit\u00e9",
    "position": "Defender",
    "nationality": "France",
    "number": "18",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/14tgw71771751183.jpg"
   },
   {
    "name": "\u0110or\u0111e Petrovi\u0107",
    "position": "Goalkeeper",
    "nationality": "Serbia",
    "number": "1",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/rz7f471771751668.jpg"
   }
  ],
  "134355": [
   {
    "name": "Antoni Milambo",
    "position": "Midfielder",
    "nationality": "The Netherlands",
    "number": "17",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/omxef01700835001.jpg"
   },
   {
    "name": "Caoimh\u00edn Kelleher",
    "position": "Goalkeeper",
    "nationality": "Ireland",
    "number": "1",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/jwy8ud1771939335.jpg"
   },
   {
    "name": "Edmond-Paris Maghoma",
    "position": "Midfielder",
    "nationality": "England",
    "number": "25",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/jzjqxl1690900932.jpg"
   },
   {
    "name": "Ellery Balcombe",
    "position": "Goalkeeper",
    "nationality": "England",
    "number": "31",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/1z89nu1631715668.jpg"
   },
   {
    "name": "H\u00e1kon Rafn Valdimarsson",
    "position": "Goalkeeper",
    "nationality": "Iceland",
    "number": "12",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/lgxldx1708098593.jpg"
   }
  ],
  "133619": [
   {
    "name": "Bart Verbruggen",
    "position": "Goalkeeper",
    "nationality": "The Netherlands",
    "number": "1",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/2ldxic1772017667.jpg"
   },
   {
    "name": "Diego Coppola",
    "position": "Defender",
    "nationality": "Italy",
    "number": "42",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/ptm9451772016730.jpg"
   }
  ],
  "133610": [
   {
    "name": "Filip J\u00f6rgensen",
    "position": "Goalkeeper",
    "nationality": "Denmark",
    "number": "12",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/1jn0bn1771427812.jpg"
   },
   {
    "name": "Gabriel Slonina",
    "position": "Goalkeeper",
    "nationality": "United States",
    "number": "44",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/ipb9mg1641469245.jpg"
   },
   {
    "name": "Genesis Antwi",
    "position": "Defender",
    "nationality": "Sweden",
    "number": "",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/dbyzxw1766827918.jpg"
   },
   {
    "name": "James Hillson",
    "position": "Goalkeeper",
    "nationality": "England",
    "number": "30",
    "thumb": ""
   }
  ],
  "133625": [
   {
    "name": "Ben Wilson",
    "position": "Goalkeeper",
    "nationality": "England",
    "number": "13",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/ztceir1511792102.jpg"
   },
   {
    "name": "Carl Rushworth",
    "position": "Goalkeeper",
    "nationality": "England",
    "number": "19",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/9jypl41690900547.jpg"
   },
   {
    "name": "Jack Rudoni",
    "position": "Midfielder",
    "nationality": "England",
    "number": "5",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/mjlxqz1632337567.jpg"
   }
  ],
  "133632": [
   {
    "name": "Caleb Kporha",
    "position": "Defender",
    "nationality": "England",
    "number": "38",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/t1sgyq1752343356.jpg"
   }
  ],
  "133615": [
   {
    "name": "Adam Aznou",
    "position": "Defender",
    "nationality": "Morocco",
    "number": "39",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/ri34fc1756976649.jpg"
   },
   {
    "name": "Harrison Armstrong",
    "position": "Midfielder",
    "nationality": "England",
    "number": "45",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/31pakx1756816044.jpg"
   },
   {
    "name": "Iliman Ndiaye",
    "position": "Midfielder",
    "nationality": "Senegal",
    "number": "10",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/mewy8h1628334209.jpg"
   }
  ],
  "133600": [
   {
    "name": "Benjamin Lecomte",
    "position": "Goalkeeper",
    "nationality": "France",
    "number": "23",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/sun2ma1772026097.jpg"
   },
   {
    "name": "Bernd Leno",
    "position": "Goalkeeper",
    "nationality": "Germany",
    "number": "1",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/dkrqvd1772026031.jpg"
   }
  ],
  "133617": [
   {
    "name": "Dillon Phillips",
    "position": "Goalkeeper",
    "nationality": "England",
    "number": "12",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/9zda8w1536058652.jpg"
   },
   {
    "name": "Eliot Matazo",
    "position": "Midfielder",
    "nationality": "Belgium",
    "number": "8",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/jkchcm1609235910.jpg"
   },
   {
    "name": "Harvey Cartwright",
    "position": "Goalkeeper",
    "nationality": "England",
    "number": "34",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/wcx9ht1688499161.jpg"
   },
   {
    "name": "Ivor Pandur",
    "position": "Goalkeeper",
    "nationality": "Croatia",
    "number": "1",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/3ks0h91611325329.jpg"
   }
  ],
  "133622": [
   {
    "name": "Alex Palmer",
    "position": "Goalkeeper",
    "nationality": "England",
    "number": "1",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/a2j3i71631474179.jpg"
   },
   {
    "name": "Christian Walton",
    "position": "Goalkeeper",
    "nationality": "England",
    "number": "28",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/02typx1534960217.jpg"
   }
  ],
  "133635": [
   {
    "name": "Alex Cairns",
    "position": "Goalkeeper",
    "nationality": "England",
    "number": "21",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/ovcpbb1772199599.jpg"
   },
   {
    "name": "Anton Stach",
    "position": "Midfielder",
    "nationality": "Germany",
    "number": "18",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/j2rih31772200454.jpg"
   }
  ],
  "133602": [
   {
    "name": "Alisson Becker",
    "position": "Goalkeeper",
    "nationality": "Brazil",
    "number": "1",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/yi6dt21746034945.jpg"
   },
   {
    "name": "\u00c1rmin P\u00e9csi",
    "position": "Goalkeeper",
    "nationality": "Hungary",
    "number": "41",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/s2siv81752000603.jpg"
   }
  ],
  "133613": [
   {
    "name": "Gianluigi Donnarumma",
    "position": "Goalkeeper",
    "nationality": "Italy",
    "number": "25",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/7kahd81704447713.jpg"
   }
  ],
  "133612": [
   {
    "name": "Altay Bay\u0131nd\u0131r",
    "position": "Goalkeeper",
    "nationality": "Turkey",
    "number": "1",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/8meai71770993191.jpg"
   },
   {
    "name": "Ayden Heaven",
    "position": "Defender",
    "nationality": "England",
    "number": "26",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/xrtzyr1742156158.jpg"
   },
   {
    "name": "Bendito Mantato",
    "position": "Midfielder",
    "nationality": "England",
    "number": "",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/ow27r71770992348.jpg"
   }
  ],
  "134777": [
   {
    "name": "Aaron Ramsdale",
    "position": "Goalkeeper",
    "nationality": "England",
    "number": "32",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/z0dple1678273036.jpg"
   },
   {
    "name": "Alex Murphy",
    "position": "Defender",
    "nationality": "Ireland",
    "number": "37",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/kj95131725473548.jpg"
   }
  ],
  "133603": [
   {
    "name": "Ahmed Abdullahi",
    "position": "Forward",
    "nationality": "France",
    "number": "29",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/ieehth1739976231.jpg"
   },
   {
    "name": "Enzo Le F\u00e9e",
    "position": "Midfielder",
    "nationality": "France",
    "number": "28",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/yexuf41772029451.jpg"
   }
  ],
  "133616": [
   {
    "name": "Anton\u00edn Kinsk\u00fd",
    "position": "Goalkeeper",
    "nationality": "Czechia",
    "number": "31",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/n3la6s1736172359.jpg"
   },
   {
    "name": "Brandon Austin",
    "position": "Goalkeeper",
    "nationality": "England",
    "number": "40",
    "thumb": "https://r2.thesportsdb.com/images/media/player/thumb/3an9yx1770823763.jpg"
   }
  ]
 },
 "writeups": {
  "133604": "Arsenal beat Burnley 1-0 at Emirates Stadium. It stayed close, but the lads saw it out to the final whistle. Attention now turns to the next fixture.",
  "133601": "Aston Villa beat Liverpool 4-2 at Villa Park. The goals flowed and the fans got their money's worth. Attention now turns to the next fixture.",
  "134301": "Bournemouth drew 1-1 with Manchester City at Vitality Stadium. A point apiece felt about right on the day. Attention now turns to the next fixture.",
  "134355": "Brentford drew 2-2 with Crystal Palace at Brentford Community Stadium. The goals flowed and the fans got their money's worth. Attention now turns to the next fixture.",
  "133619": "Brighton and Hove Albion lost 0-3 to Manchester United at American Express Stadium. It was tight all the way, and one moment settled it. Attention now turns to the next fixture.",
  "133610": "Chelsea beat Tottenham Hotspur 2-1 at Stamford Bridge. It stayed close, but the lads saw it out to the final whistle. Attention now turns to the next fixture.",
  "133625": "Coventry City beat Wrexham 3-1 at The Coventry Building Society Arena. The goals flowed and the fans got their money's worth. Attention now turns to the next fixture.",
  "133632": "Crystal Palace beat Rayo Vallecano 1-0 at Red Bull Arena Leipzig. It stayed close, but the lads saw it out to the final whistle. Attention now turns to the next fixture.",
  "133615": "Everton lost 1-3 to Sunderland at Hill Dickinson Stadium. The goals flowed and the fans got their money's worth. Attention now turns to the next fixture.",
  "133600": "Fulham beat Newcastle United 2-0 at Craven Cottage. It stayed close, but the lads saw it out to the final whistle. Attention now turns to the next fixture.",
  "133617": "Hull City beat Middlesbrough 1-0 at Wembley Stadium. It stayed close, but the lads saw it out to the final whistle. Attention now turns to the next fixture.",
  "133622": "Ipswich Town beat Queens Park Rangers 3-0 at Portman Road. It stayed close, but the lads saw it out to the final whistle. Attention now turns to the next fixture.",
  "133635": "Leeds United beat Brighton and Hove Albion 1-0 at Elland Road. It stayed close, but the lads saw it out to the final whistle. Attention now turns to the next fixture.",
  "133602": "Liverpool drew 1-1 with Brentford at Anfield. A point apiece felt about right on the day. Attention now turns to the next fixture.",
  "133613": "Manchester City lost 1-2 to Aston Villa at Etihad Stadium. It was tight all the way, and one moment settled it. Attention now turns to the next fixture.",
  "133612": "Manchester United beat Nottingham Forest 3-2 at Old Trafford. The goals flowed and the fans got their money's worth. Attention now turns to the next fixture.",
  "134777": "Newcastle United beat West Ham United 3-1 at St James Park. The goals flowed and the fans got their money's worth. Attention now turns to the next fixture.",
  "133603": "Sunderland beat Chelsea 2-1 at Stadium of Light. It stayed close, but the lads saw it out to the final whistle. Attention now turns to the next fixture.",
  "133616": "Tottenham Hotspur beat Everton 1-0 at Tottenham Hotspur Stadium. It stayed close, but the lads saw it out to the final whistle. Attention now turns to the next fixture."
 },
 "stats": {
  "games": 20,
  "avgGoals": 2.8,
  "homeWinPct": 70,
  "bttsPct": 55,
  "topScoringTeam": {
   "name": "Aston Villa",
   "goals": 6
  }
 }
};
