#!/usr/bin/env bash
set -euo pipefail

# ── Defaults ──────────────────────────────────────────────
GOG_LIBRARY_PATH="${GOG_LIBRARY_PATH:-config/gog_library.json}"
STALE_DAYS="${STALE_DAYS:-30}"
REMINDERS_LIST="${REMINDERS_LIST:-Gaming}"
EMAIL_ACCOUNT="${EMAIL_ACCOUNT:-personal}"
EMAIL_TO="${EMAIL_TO:-}"          # empty = use account address
DRY_RUN=false

[[ "${1:-}" == "--dry-run" ]] && DRY_RUN=true

# ── Resolve workspace root ───────────────────────────────
WORKSPACE="${WORKSPACE:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
LIBRARY_FILE="$WORKSPACE/$GOG_LIBRARY_PATH"

if [[ ! -f "$LIBRARY_FILE" ]]; then
  echo "❌ GOG library not found: $LIBRARY_FILE" >&2
  exit 1
fi

# ── Compute cutoff date ──────────────────────────────────
CUTOFF_EPOCH=$(( $(date +%s) - STALE_DAYS * 86400 ))

# ── Parse stale games with jq ────────────────────────────
STALE_JSON=$(jq --arg cutoff "$CUTOFF_EPOCH" '
  .games
  | map(select(.installed == true))
  | map(select(
      (.last_played // null) == null
      or ((.last_played | sub("\\.[0-9]+Z?$"; "Z") | strptime("%Y-%m-%dT%H:%M:%S%z") | mktime) < ($cutoff | tonumber))
    ))
' "$LIBRARY_FILE" 2>/dev/null) || STALE_JSON="[]"

COUNT=$(echo "$STALE_JSON" | jq 'length')

if [[ "$COUNT" -eq 0 ]]; then
  echo "✅ No stale games found (threshold: $STALE_DAYS days)."
  exit 0
fi

# ── Build report ─────────────────────────────────────────
echo ""
echo "🧹 Stale GOG Games (not played in ${STALE_DAYS}+ days)"
echo "─────────────────────────────────────────────"

PLAIN_BODY=""
HTML_ROWS=""

while IFS=$'\t' read -r name last_played install_path; do
  LP_DISPLAY="${last_played:-never}"
  printf "  %-30s last played %s\n" "$name" "$LP_DISPLAY"
  PLAIN_BODY+="• $name — last played: $LP_DISPLAY (path: $install_path)"$'\n'
  HTML_ROWS+="<tr><td style='padding:6px 12px'>$(echo "$name" | sed 's/&/\&amp;/g;s/</\&lt;/g')</td><td style='padding:6px 12px'>$LP_DISPLAY</td><td style='padding:6px 12px;font-size:0.85em;color:#888'>$(echo "$install_path" | sed 's/&/\&amp;/g;s/</\&lt;/g')</td></tr>"
done < <(echo "$STALE_JSON" | jq -r '.[] | [.name, (.last_played // "never" | split("T")[0]), .install_path] | @tsv')

echo "─────────────────────────────────────────────"
echo "$COUNT stale games found."

# ── Email ────────────────────────────────────────────────
if [[ "$DRY_RUN" == true ]]; then
  echo "📧 [dry-run] Would send email to $EMAIL_ACCOUNT account."
else
  TODAY=$(date +%Y-%m-%d)
  SUBJECT="🧹 GOG Stale Games Report — $TODAY"
  HTML_BODY="<html><body><h2>Stale GOG Games ($TODAY)</h2><p>These installed games haven't been played in ${STALE_DAYS}+ days. Consider uninstalling to free up space.</p><table style='border-collapse:collapse;border:1px solid #ddd'><tr style='background:#f5f5f5'><th style='padding:6px 12px;text-align:left'>Game</th><th style='padding:6px 12px;text-align:left'>Last Played</th><th style='padding:6px 12px;text-align:left'>Install Path</th></tr>${HTML_ROWS}</table><p style='margin-top:16px;color:#888;font-size:0.85em'>Generated by gog-stale-games skill</p></body></html>"

  # Write MML template and send via himalaya
  TMPFILE=$(mktemp /tmp/gog-stale-email-XXXXXX.mml)
  TO_HEADER="${EMAIL_TO:+To: $EMAIL_TO}"
  cat > "$TMPFILE" <<HEREDOC
From: $(himalaya account list 2>/dev/null | grep -A1 "$EMAIL_ACCOUNT" | tail -1 | awk '{print $NF}' || echo "")
${TO_HEADER}
Subject: ${SUBJECT}
Content-Type: text/html

${HTML_BODY}
HEREDOC

  if himalaya template send --account "$EMAIL_ACCOUNT" < "$TMPFILE" 2>&1; then
    echo "📧 Email sent."
  else
    echo "⚠️  Email failed. Check himalaya config." >&2
  fi
  rm -f "$TMPFILE"
fi

# ── Apple Reminders ──────────────────────────────────────
if [[ "$DRY_RUN" == true ]]; then
  echo "🔔 [dry-run] Would add $COUNT reminders to '$REMINDERS_LIST' list."
else
  # Ensure the list exists
  if ! remindctl list "$REMINDERS_LIST" &>/dev/null; then
    remindctl list "$REMINDERS_LIST" --create 2>/dev/null || true
  fi

  ADDED=0
  while IFS=$'\t' read -r name last_played; do
    LP_DISPLAY="${last_played:-never}"
    if remindctl add --title "Consider uninstalling: $name" --list "$REMINDERS_LIST" --note "Last played: $LP_DISPLAY" 2>/dev/null; then
      ADDED=$((ADDED + 1))
    else
      echo "⚠️  Failed to add reminder for: $name" >&2
    fi
  done < <(echo "$STALE_JSON" | jq -r '.[] | [.name, (.last_played // "never" | split("T")[0])] | @tsv')

  echo "🔔 $ADDED reminders added to '$REMINDERS_LIST'."
fi

echo "✅ Done."
