import { defineCapabilityCatalog, defineProviderManifest } from "./catalog";
import type { AgentCapabilityDescriptor } from "./contracts";

export const VIBEVIDEO_AGENT_CAPABILITY_CATALOG = defineCapabilityCatalog([
  {
    key: "auth.google_oauth.start",
    title: "Start Google OAuth login",
    category: "auth",
    status: "implemented",
    scopes: ["anonymous"],
    route: {
      method: "GET",
      path: "/api/auth/login",
      responseContract: "legacy",
      localeHeader: true,
      notes: "Returns Google OAuth URL and derives locale-aware redirect URI.",
    },
    tags: ["auth", "google", "oauth"],
  },
  {
    key: "auth.google_oauth.callback",
    title: "Complete Google OAuth login",
    category: "auth",
    status: "implemented",
    scopes: ["anonymous"],
    route: {
      method: "POST",
      path: "/api/auth/callback",
      responseContract: "legacy",
      localeHeader: true,
      notes: "Returns a local VibeVideo access token.",
    },
    tags: ["auth", "google", "oauth"],
  },
  {
    key: "auth.wechat.login_config",
    title: "Get WeChat login config",
    category: "auth",
    status: "implemented",
    scopes: ["anonymous"],
    route: {
      method: "GET",
      path: "/api/auth/wechat/login-config",
      responseContract: "standard",
      localeHeader: true,
    },
    tags: ["auth", "wechat"],
  },
  {
    key: "auth.wechat.callback",
    title: "Complete WeChat login",
    category: "auth",
    status: "implemented",
    scopes: ["anonymous"],
    route: {
      method: "POST",
      path: "/api/auth/wechat/callback",
      responseContract: "standard",
      localeHeader: true,
    },
    tags: ["auth", "wechat"],
  },
  {
    key: "auth.captcha.generate",
    title: "Generate CAPTCHA",
    category: "auth",
    status: "implemented",
    scopes: ["anonymous"],
    route: {
      method: "GET",
      path: "/api/auth/captcha/generate",
      responseContract: "typed",
      localeHeader: true,
    },
    tags: ["auth", "captcha"],
  },
  {
    key: "auth.captcha.verify",
    title: "Verify CAPTCHA",
    category: "auth",
    status: "implemented",
    scopes: ["anonymous"],
    route: {
      method: "POST",
      path: "/api/auth/captcha/verify",
      responseContract: "typed",
      localeHeader: true,
      notes: "Also doubles as email-link login sender in the current backend.",
    },
    tags: ["auth", "captcha", "email"],
  },
  {
    key: "auth.email_code.send",
    title: "Send email verification code",
    category: "auth",
    status: "implemented",
    scopes: ["anonymous", "owner"],
    route: {
      method: "POST",
      path: "/api/auth/email-code/send",
      responseContract: "standard",
      localeHeader: true,
      notes: "Supports owner login and sub-user bootstrap.",
    },
    tags: ["auth", "email", "verification-code"],
    dependsOn: ["auth.captcha.generate", "auth.captcha.verify"],
  },
  {
    key: "auth.email_code.verify",
    title: "Verify email code and issue session",
    category: "auth",
    status: "implemented",
    scopes: ["anonymous", "owner"],
    route: {
      method: "POST",
      path: "/api/auth/email-code/verify",
      responseContract: "standard",
      localeHeader: true,
    },
    tags: ["auth", "email", "verification-code"],
  },
  {
    key: "auth.email_link.verify",
    title: "Verify email login link",
    category: "auth",
    status: "implemented",
    scopes: ["anonymous"],
    route: {
      method: "GET",
      path: "/api/auth/email-verify",
      responseContract: "redirect",
      localeHeader: true,
    },
    tags: ["auth", "email", "magic-link"],
  },
  {
    key: "auth.cookie_setup",
    title: "Set cookies from issued local token",
    category: "auth",
    status: "implemented",
    scopes: ["anonymous", "authenticated"],
    route: {
      method: "POST",
      path: "/api/auth/email-token-setup",
      responseContract: "legacy",
      localeHeader: false,
      notes: "Useful when a provider or email flow returns a local token to the browser.",
    },
    tags: ["auth", "cookie", "session"],
  },
  {
    key: "identity.current_user",
    title: "Read current user profile",
    category: "identity",
    status: "implemented",
    scopes: ["authenticated", "owner", "sub_user"],
    route: {
      method: "GET",
      path: "/api/users/me",
      responseContract: "typed",
      localeHeader: true,
    },
    tags: ["identity", "profile"],
  },
  {
    key: "access.overview.read",
    title: "Read access-control overview",
    category: "access",
    status: "implemented",
    scopes: ["owner", "sub_user"],
    route: {
      method: "GET",
      path: "/api/access/overview",
      responseContract: "standard",
      localeHeader: true,
    },
    tags: ["access", "permissions"],
  },
  {
    key: "access.sub_users.read",
    title: "List sub users",
    category: "access",
    status: "implemented",
    scopes: ["owner"],
    route: {
      method: "GET",
      path: "/api/access/sub-users",
      responseContract: "standard",
      localeHeader: true,
    },
    tags: ["access", "sub-user"],
  },
  {
    key: "access.sub_users.create",
    title: "Create sub user",
    category: "access",
    status: "implemented",
    scopes: ["owner"],
    route: {
      method: "POST",
      path: "/api/access/sub-users",
      responseContract: "standard",
      localeHeader: true,
    },
    tags: ["access", "sub-user", "write"],
  },
  {
    key: "access.sub_users.update",
    title: "Update sub user",
    category: "access",
    status: "implemented",
    scopes: ["owner"],
    route: {
      method: "PUT",
      path: "/api/access/sub-users/{sub_user_id}",
      responseContract: "standard",
      localeHeader: true,
    },
    tags: ["access", "sub-user", "write"],
  },
  {
    key: "access.sub_users.delete",
    title: "Delete sub user",
    category: "access",
    status: "implemented",
    scopes: ["owner"],
    route: {
      method: "DELETE",
      path: "/api/access/sub-users/{sub_user_id}",
      responseContract: "standard",
      localeHeader: true,
    },
    tags: ["access", "sub-user", "write"],
  },
  {
    key: "access.tokens.read",
    title: "List active session tokens",
    category: "access",
    status: "implemented",
    scopes: ["owner", "sub_user"],
    route: {
      method: "GET",
      path: "/api/access/tokens",
      responseContract: "standard",
      localeHeader: true,
    },
    tags: ["access", "tokens"],
  },
  {
    key: "access.tokens.update",
    title: "Update session token policy",
    category: "access",
    status: "implemented",
    scopes: ["owner", "sub_user"],
    route: {
      method: "PUT",
      path: "/api/access/tokens/{token_id}",
      responseContract: "standard",
      localeHeader: true,
    },
    tags: ["access", "tokens", "write"],
  },
  {
    key: "scripts.create_async",
    title: "Create a Studio episode draft from script text",
    category: "scripts",
    status: "implemented",
    scopes: ["owner", "sub_user"],
    route: {
      method: "POST",
      path: "/api/scripts/create_async",
      responseContract: "standard",
      localeHeader: true,
      notes: "Creates a single Studio episode draft and returns video_id/query_id.",
    },
    tags: ["scripts", "studio", "episode", "write"],
  },
  {
    key: "scripts.task_status.read",
    title: "Read Studio script task status",
    category: "scripts",
    status: "implemented",
    scopes: ["owner", "sub_user"],
    route: {
      method: "GET",
      path: "/api/scripts/task_status",
      responseContract: "standard",
      localeHeader: true,
      notes: "Poll with step=create_script until the Studio draft is ready.",
    },
    tags: ["scripts", "studio", "polling"],
  },
  {
    key: "tools.generate_async",
    title: "Create async tool generation task",
    category: "tools",
    status: "implemented",
    scopes: ["owner", "sub_user"],
    route: {
      method: "POST",
      path: "/api/tools/generate_async",
      responseContract: "standard",
      localeHeader: true,
      notes: "Current entry point for image and video generation tasks.",
    },
    tags: ["tools", "image", "video"],
  },
  {
    key: "tools.task_status.read",
    title: "Read tool task status",
    category: "tools",
    status: "implemented",
    scopes: ["owner", "sub_user"],
    route: {
      method: "GET",
      path: "/api/tools/task_status",
      responseContract: "standard",
      localeHeader: true,
    },
    tags: ["tools", "polling"],
  },
  {
    key: "tools.result.read",
    title: "Fetch tool task result",
    category: "tools",
    status: "implemented",
    scopes: ["owner", "sub_user"],
    route: {
      method: "GET",
      path: "/api/tools/fetch_result",
      responseContract: "standard",
      localeHeader: true,
    },
    tags: ["tools", "result"],
  },
  {
    key: "service.flags.sora2_not_stable.read",
    title: "Read service flag",
    category: "service",
    status: "implemented",
    scopes: ["anonymous", "authenticated"],
    route: {
      method: "GET",
      path: "/api/service/get-sora2-not-stable",
      responseContract: "standard",
      localeHeader: false,
    },
    tags: ["service", "flags"],
  },
  {
    key: "service.flags.sora2_not_stable.write",
    title: "Write service flag",
    category: "service",
    status: "implemented",
    scopes: ["owner", "sub_user"],
    route: {
      method: "POST",
      path: "/api/service/set-sora2-not-stable",
      responseContract: "standard",
      localeHeader: false,
    },
    tags: ["service", "flags", "write"],
  },
  {
    key: "agent_bridge.session.issue",
    title: "Issue provider bridge session",
    category: "agent_bridge",
    status: "planned",
    scopes: ["owner", "sub_user"],
    route: {
      method: "POST",
      path: "/api/agent-bridge/providers/{provider_id}/session",
      responseContract: "planned",
      localeHeader: true,
      notes: "Recommended future endpoint for short-lived provider handoff tokens.",
    },
    tags: ["agent-bridge", "session"],
  },
  {
    key: "projects.read",
    title: "Read projects",
    category: "projects",
    status: "implemented",
    scopes: ["owner", "sub_user"],
    route: {
      method: "GET",
      path: "/api/projects",
      responseContract: "standard",
      localeHeader: true,
      notes: "Returns Studio projects for the current account.",
    },
    tags: ["projects"],
    notes: "Used by OpenClaw to list Studio projects and build direct project-page links.",
  },
  {
    key: "projects.write",
    title: "Mutate projects",
    category: "projects",
    status: "planned",
    scopes: ["owner", "sub_user"],
    tags: ["projects", "write"],
    notes: "Keep disabled for initial OpenClaw binding.",
  },
  {
    key: "assets.upload.presign",
    title: "Presign asset uploads",
    category: "assets",
    status: "planned",
    scopes: ["owner", "sub_user"],
    tags: ["assets", "upload"],
    notes: "Future capability for provider-mediated uploads.",
  },
  {
    key: "notifications.email.send",
    title: "Trigger system email",
    category: "notifications",
    status: "planned",
    scopes: ["internal"],
    tags: ["notifications", "email"],
    notes: "Keep internal-only unless a provider has a clear business need.",
  },
] as const satisfies ReadonlyArray<AgentCapabilityDescriptor>);

export const OPENCLAW_PROVIDER_MANIFEST = defineProviderManifest(
  {
    providerId: "openclaw",
    displayName: "OpenClaw",
    providerUrl: "https://openclaw.example.com",
    transport: "redirect",
    auth: {
      primaryStrategy: "session_handoff",
      fallbackStrategies: ["email_code"],
      login: {
        method: "POST",
        path: "/api/agent-bridge/providers/openclaw/session",
        responseContract: "planned",
        localeHeader: true,
        notes: "Recommended bridge-session entry for OpenClaw.",
      },
      verify: {
        method: "POST",
        path: "/api/auth/email-code/verify",
        responseContract: "standard",
        localeHeader: true,
      },
      callback: {
        method: "GET",
        path: "/api/agent-bridge/providers/openclaw/callback",
        responseContract: "planned",
        localeHeader: true,
      },
      currentUser: {
        method: "GET",
        path: "/api/users/me",
        responseContract: "typed",
        localeHeader: true,
      },
      cookieSetup: {
        method: "POST",
        path: "/api/auth/email-token-setup",
        responseContract: "legacy",
        localeHeader: false,
      },
      sessionBrokerPath: "/api/agent-bridge/providers/openclaw/session",
      bridgeTokenTtlSeconds: 300,
      neverSharePrimaryCookie: true,
    },
    capabilities: [
      "auth.captcha.generate",
      "identity.current_user",
      "auth.email_code.send",
      "auth.email_code.verify",
      "access.tokens.update",
      "projects.read",
      "scripts.create_async",
      "scripts.task_status.read",
    ],
    requiredScopes: ["authenticated", "owner"],
    extensionPoints: ["auth", "identity", "access", "scripts", "projects", "agent_bridge"],
    ui: {
      launcher: "redirect",
      entryPath: "/agents/openclaw",
      callbackPath: "/api/agent-bridge/providers/openclaw/callback",
    },
    security: {
      bridgeMode: "backend_only",
      auditEventNamespace: "agent.openclaw",
      requiresAuditTrail: true,
      allowedOrigins: ["https://openclaw.example.com"],
    },
    notes:
      "Implemented OpenClaw scope: email-code login with CAPTCHA, Studio project listing, single-episode Studio draft creation from script text, and local logout with best-effort remote token expiry.",
  },
  VIBEVIDEO_AGENT_CAPABILITY_CATALOG,
);
