"""Hardcoded xStocks Solana token catalog."""

from typing import Any, Dict, List


# Scraped from https://api.xstocks.fi/api/v1/token
# 104 tokens with Solana deployments
SOLANA_TOKENS: List[Dict[str, Any]] = [
    {"name": "Abbott xStock", "symbol": "ABTx", "address": "svm:XsHtf5RpxsQ7jeJ9ivNewouZKJHbPxhPoEy6yYvULr7"},
    {"name": "AbbVie xStock", "symbol": "ABBVx", "address": "svm:XswbinNKyPmzTa5CskMbCPvMW6G5CMnZXZEeQSSQoie"},
    {"name": "abrdn Physical Palladium Shares xStock", "symbol": "PALLx", "address": "svm:XsTTtPA5V19YwHKDv4xeVXNM6kdsQNJvg3MyWkRUckt"},
    {"name": "abrdn Physical Platinum Shares xStock", "symbol": "PPLTx", "address": "svm:Xst6eFD4YT6sz9RLMysN9SyvaZWtraSdVJQGu5ZkAme"},
    {"name": "Accenture xStock", "symbol": "ACNx", "address": "svm:Xs5UJzmCRQ8DWZjskExdSQDnbE6iLkRu2jjrRAB1JSU"},
    {"name": "Adobe xStock", "symbol": "ADBEx", "address": "svm:XsDZMGEU8zadWFCkTtPBoPWYcUX3JHVmghnwf2Mve2q"},
    {"name": "Alphabet xStock", "symbol": "GOOGLx", "address": "svm:XsCPL9dNWBMvFtTmwcCA5v3xWPSMEBCszbQdiLLq6aN"},
    {"name": "Amazon.com xStock", "symbol": "AMZNx", "address": "svm:Xs3eBt7uRfJX8QUs4suhyU8p2M6DoUDrJyWBa8LLZsg"},
    {"name": "Amber xStock", "symbol": "AMBRx", "address": "svm:XsaQTCgebC2KPbf27KUhdv5JFvHhQ4GDAPURwrEhAzb"},
    {"name": "AMD xStock", "symbol": "AMDx", "address": "svm:XsXcJ6GZ9kVnjqGsjBnktRcuwMBmvKWh8S93RefZ1rF"},
    {"name": "Apple xStock", "symbol": "AAPLx", "address": "svm:XsbEhLAtcf6HdfpFZ5xEMdqW8nfAvcsP5bdudRLJzJp"},
    {"name": "AppLovin xStock", "symbol": "APPx", "address": "svm:XsPdAVBi8Zc1xvv53k4JcMrQaEDTgkGqKYeh7AYgPHV"},
    {"name": "AST SpaceMobile xStock", "symbol": "ASTSx", "address": "svm:XsR4LAtaBgTKTRUhiijY1ba13nx4bepeEcag2Pr4dZ1"},
    {"name": "AstraZeneca xStock", "symbol": "AZNx", "address": "svm:Xs3ZFkPYT2BN7qBMqf1j1bfTeTm1rFzEFSsQ1z3wAKU"},
    {"name": "Backed GameStop Corp", "symbol": "bGME", "address": "svm:bG5CYb7Z48BfpZwhN6LqnyHYz8orvFwrufCjmc3RJHb"},
    {"name": "Backed Tesla Inc", "symbol": "bTSLA", "address": "svm:9JMgSynsVkKrDvKCf21npkAW5oacp7XcVYHigNBvmwT7"},
    {"name": "Bank of America xStock", "symbol": "BACx", "address": "svm:XswsQk4duEQmCbGzfqUUWYmi7pV7xpJ9eEmLHXCaEQP"},
    {"name": "Berkshire Hathaway xStock", "symbol": "BRK.Bx", "address": "svm:Xs6B6zawENwAbWVi7w92rjazLuAr5Az59qgWKcNb45x"},
    {"name": "Bit Digital xStock", "symbol": "BTBTx", "address": "svm:XsPLBFy59Q3hY59KLAJur8QyvziMF4xUxGTxXqXE7cT"},
    {"name": "Bitgo xStock", "symbol": "BTGOx", "address": "svm:XsvHMmbDcd14DHHW16PkxPGW7ks77ehxUv1E9Zmxgj4"},
    {"name": "Bitmine xStock", "symbol": "BMNRx", "address": "svm:XsrBCwaH8c46xiqXBChzobgufRKxQxAWUWbndgBNzFn"},
    {"name": "Brera xStock", "symbol": "SLMTx", "address": "svm:XsPHkGBbztHCCe1RMhiAs7CxVqoghmyd6zDUfrbfVWG"},
    {"name": "Broadcom xStock", "symbol": "AVGOx", "address": "svm:XsgSaSvNSqLTtFuyWPBhK9196Xb9Bbdyjj4fH3cPJGo"},
    {"name": "Chevron xStock", "symbol": "CVXx", "address": "svm:XsNNMt7WTNA2sV3jrb1NNfNgapxRF5i4i6GcnTRRHts"},
    {"name": "Circle xStock", "symbol": "CRCLx", "address": "svm:XsueG8BtpquVJX9LVLLEGuViXUungE6WmK5YZ3p3bd1"},
    {"name": "Cisco xStock", "symbol": "CSCOx", "address": "svm:Xsr3pdLQyXvDJBFgpR5nexCEZwXvigb8wbPYp4YoNFf"},
    {"name": "CleanSpark xStock", "symbol": "CLSKx", "address": "svm:Xsn3H7ACEpSF2ULxeiD6kW4jRZXpurh8ZPttyfoS56W"},
    {"name": "Coca-Cola xStock", "symbol": "KOx", "address": "svm:XsaBXg8dU5cPM6ehmVctMkVqoiRG2ZjMo1cyBJ3AykQ"},
    {"name": "Coinbase xStock", "symbol": "COINx", "address": "svm:Xs7ZdzSHLU9ftNJsii5fCeJhoRWSC32SQGzGQtePxNu"},
    {"name": "Comcast xStock", "symbol": "CMCSAx", "address": "svm:XsvKCaNsxg2GN8jjUmq71qukMJr7Q1c5R2Mk9P8kcS8"},
    {"name": "Core MSCI Emerging Markets xStock", "symbol": "IEMGx", "address": "svm:XsFnZawJdLdXfBSEt5Vw29K5vdBiHotdPLjUPafpfHs"},
    {"name": "Core Scientific xStock", "symbol": "CORZx", "address": "svm:XsBGEXxbBcuu8Nrokj14G8v4ezT3JYWWLneTzXK8t6Z"},
    {"name": "CrowdStrike xStock", "symbol": "CRWDx", "address": "svm:Xs7xXqkcK7K8urEqGg52SECi79dRp2cEKKuYjUePYDw"},
    {"name": "Danaher xStock", "symbol": "DHRx", "address": "svm:Xseo8tgCZfkHxWS9xbFYeKFyMSbWEvZGFV1Gh53GtCV"},
    {"name": "DFDV xStock", "symbol": "DFDVx", "address": "svm:Xs2yquAgsHByNzx68WJC55WHjHBvG9JsMB7CWjTLyPy"},
    {"name": "Eli Lilly xStock", "symbol": "LLYx", "address": "svm:Xsnuv4omNoHozR6EEW5mXkw8Nrny5rB3jVfLqi6gKMH"},
    {"name": "Exxon Mobil xStock", "symbol": "XOMx", "address": "svm:XsaHND8sHyfMfsWPj6kSdd5VwvCayZvjYgKmmcNL5qh"},
    {"name": "Galaxy Digital xStock", "symbol": "GLXYx", "address": "svm:Xs3c2aZenyRQwXjki5MDxJEJ2km27ef2rWQMFWx7QKJ"},
    {"name": "Gamestop xStock", "symbol": "GMEx", "address": "svm:Xsf9mBktVB9BSU5kf4nHxPq5hCBJ2j2ui3ecFGxPRGc"},
    {"name": "Global X Copper Miners xStock", "symbol": "COPXx", "address": "svm:XsybfiKkD4UmjkAGT2uR8X2sq9AWFtvGJM2KTffoALZ"},
    {"name": "Gold xStock", "symbol": "GLDx", "address": "svm:Xsv9hRk1z5ystj9MhnA7Lq4vjSsLwzL2nxrwmwtD3re"},
    {"name": "Goldman Sachs xStock", "symbol": "GSx", "address": "svm:XsgaUyp4jd1fNBCxgtTKkW64xnnhQcvgaxzsbAq5ZD1"},
    {"name": "Home Depot xStock", "symbol": "HDx", "address": "svm:XszjVtyhowGjSC5odCqBpW1CtXXwXjYokymrk7fGKD3"},
    {"name": "Honeywell xStock", "symbol": "HONx", "address": "svm:XsRbLZthfABAPAfumWNEJhPyiKDW6TvDVeAeW7oKqA2"},
    {"name": "Hut 8 xStock", "symbol": "HUTx", "address": "svm:XsG5QyZTQnVSpsXRpD92K5ZGoxXjsmfTyx7fW7r18DV"},
    {"name": "Intel xStock", "symbol": "INTCx", "address": "svm:XshPgPdXFRWB8tP1j82rebb2Q9rPgGX37RuqzohmArM"},
    {"name": "International Business Machines xStock", "symbol": "IBMx", "address": "svm:XspwhyYPdWVM8XBHZnpS9hgyag9MKjLRyE3tVfmCbSr"},
    {"name": "iShares Silver Trust xStock", "symbol": "SLVx", "address": "svm:XsxAd6okt8y1RRK6gNg7iJaqiWNiq5Md5EDf3ZrF2dm"},
    {"name": "Johnson & Johnson xStock", "symbol": "JNJx", "address": "svm:XsGVi5eo1Dh2zUpic4qACcjuWGjNv8GCt3dm5XcX6Dn"},
    {"name": "JPMorgan Chase xStock", "symbol": "JPMx", "address": "svm:XsMAqkcKsUewDrzVkait4e5u4y8REgtyS7jWgCpLV2C"},
    {"name": "KRAQ xStock", "symbol": "KRAQx", "address": "svm:XsAiRejKuvLAdq9KtedrMSrabz7SWdzKoVK6Qgac1Ki"},
    {"name": "Linde xStock", "symbol": "LINx", "address": "svm:XsSr8anD1hkvNMu8XQiVcmiaTP7XGvYu7Q58LdmtE8Z"},
    {"name": "MARA xStock", "symbol": "MARAx", "address": "svm:XsguBZPkM9BDmxspmWe29EmrYZBv21ENcC27Pqh7grB"},
    {"name": "Marvell xStock", "symbol": "MRVLx", "address": "svm:XsuxRGDzbLjnJ72v74b7p9VY6N66uYgTCyfwwRjVCJA"},
    {"name": "Mastercard xStock", "symbol": "MAx", "address": "svm:XsApJFV9MAktqnAc6jqzsHVujxkGm9xcSUffaBoYLKC"},
    {"name": "McDonald's xStock", "symbol": "MCDx", "address": "svm:XsqE9cRRpzxcGKDXj1BJ7Xmg4GRhZoyY1KpmGSxAWT2"},
    {"name": "Medtronic xStock", "symbol": "MDTx", "address": "svm:XsDgw22qRLTv5Uwuzn6T63cW69exG41T6gwQhEK22u2"},
    {"name": "Merck xStock", "symbol": "MRKx", "address": "svm:XsnQnU7AdbRZYe2akqqpibDdXjkieGFfSkbkjX1Sd1X"},
    {"name": "Meta xStock", "symbol": "METAx", "address": "svm:Xsa62P5mvPszXL1krVUnU5ar38bBSVcWAB6fmPCo5Zu"},
    {"name": "Micron Technology xStock", "symbol": "MUx", "address": "svm:XsQLZycSZ7QnBBdBXQaTbQdiUcbRqjNJgyBGAMzhHav"},
    {"name": "Microsoft xStock", "symbol": "MSFTx", "address": "svm:XspzcW1PRtgf6Wj92HCiZdjzKCyFekVD8P5Ueh3dRMX"},
    {"name": "MicroStrategy xStock", "symbol": "MSTRx", "address": "svm:XsP7xzNPvEHS1m6qfanPUGjNmdnmsLKEoNAnHjdxxyZ"},
    {"name": "Nasdaq xStock", "symbol": "QQQx", "address": "svm:Xs8S1uUs1zvS2p7iwtsG3b6fkhpvmwz4GYU3gWAmWHZ"},
    {"name": "Netflix xStock", "symbol": "NFLXx", "address": "svm:XsEH7wWfJJu2ZT3UCFeVfALnVA6CP5ur7Ee11KmzVpL"},
    {"name": "Novo Nordisk xStock", "symbol": "NVOx", "address": "svm:XsfAzPzYrYjd4Dpa9BU3cusBsvWfVB9gBcyGC87S57n"},
    {"name": "NVIDIA xStock", "symbol": "NVDAx", "address": "svm:Xsc9qvGR1efVDFGLrVsmkzv3qi45LTBjeUKSPmx9qEh"},
    {"name": "Oklo xStock", "symbol": "OKLOx", "address": "svm:XsJb1p4Ks6VFggq68JyMz7S3kdRfkqh4wA6EMyxi4DD"},
    {"name": "OPEN xStock", "symbol": "OPENx", "address": "svm:XsGtpmjhmC8kyjVSWL4VicGu36ceq9u55PTgF8bhGv6"},
    {"name": "Oracle xStock", "symbol": "ORCLx", "address": "svm:XsjFwUPiLofddX5cWFHW35GCbXcSu1BCUGfxoQAQjeL"},
    {"name": "Palantir xStock", "symbol": "PLTRx", "address": "svm:XsoBhf2ufR8fTyNSjqfU71DYGaE6Z3SUGAidpzriAA4"},
    {"name": "Palo Alto Networks xStock", "symbol": "PANWx", "address": "svm:XsQ6NfzzLH8nspjrB9X8R2K64Zz7Tnxqu12juDiMPMW"},
    {"name": "PayPal xStock", "symbol": "PYPLx", "address": "svm:XshWQWYVp5ff8CrAEsGmLVKD47nBWi3Ygn5v8wXK27G"},
    {"name": "PepsiCo xStock", "symbol": "PEPx", "address": "svm:Xsv99frTRUeornyvCfvhnDesQDWuvns1M852Pez91vF"},
    {"name": "Pfizer xStock", "symbol": "PFEx", "address": "svm:XsAtbqkAP1HJxy7hFDeq7ok6yM43DQ9mQ1Rh861X8rw"},
    {"name": "Philip Morris xStock", "symbol": "PMx", "address": "svm:Xsba6tUnSjDae2VcopDB6FGGDaxRrewFCDa5hKn5vT3"},
    {"name": "Planet Labs xStock", "symbol": "PLx", "address": "svm:XsMJtFbb8BwzQtck3oRXyAfs7SAPRuTXnSEDNd7BAVz"},
    {"name": "Procter & Gamble xStock", "symbol": "PGx", "address": "svm:XsYdjDjNUygZ7yGKfQaB6TxLh2gC6RRjzLtLAGJrhzV"},
    {"name": "Riot Platforms xStock", "symbol": "RIOTx", "address": "svm:Xs31mE5EiqjSHEaiX9QDKCN6NvSGCqpJ6f1FNq2wri5"},
    {"name": "Robinhood xStock", "symbol": "HOODx", "address": "svm:XsvNBAYkrDRNhA7wPHQfX3ZUXZyZLdnCQDfHZ56bzpg"},
    {"name": "Roblox xStock", "symbol": "RBLXx", "address": "svm:Xss5RAku5EH6UViFdvW7ss9xQjwQLsrs2opPMhb3k43"},
    {"name": "Russell 2000 xStock", "symbol": "IWMx", "address": "svm:XsbELVbLGBkn7xfMfyYuUipKGt1iRUc2B7pYRvFTFu3"},
    {"name": "S&P Small Cap xStock", "symbol": "IJRx", "address": "svm:XsyZcb97BzETAqi9BoP2C9D196MiMNBisGMVNje2Thz"},
    {"name": "Salesforce xStock", "symbol": "CRMx", "address": "svm:XsczbcQ3zfcgAEt9qHQES8pxKAVG5rujPSHQEXi4kaN"},
    {"name": "Schwab International Equity xStock", "symbol": "SCHFx", "address": "svm:XsWAnFM77x6YvpdaZoos79R12o4Yj4r7EVkaTWddzhU"},
    {"name": "SharpLink Gaming xStock", "symbol": "SBETx", "address": "svm:XsEoih2x6nZuUjFwzGoba6MFmtzCkzW2c4YAm6baQbq"},
    {"name": "SP500 xStock", "symbol": "SPYx", "address": "svm:XsoCS1TfEyfFhfvj8EtZ528L3CaKBDBRqRapnBbDF2W"},
    {"name": "Strategy PP Fixed xStock", "symbol": "STRKx", "address": "svm:XsaQGz41BEQkS9xAB44uvUtuXcdLJAXEU1dogEzWMZ8"},
    {"name": "Strategy PP Variable xStock", "symbol": "STRCx", "address": "svm:Xs78JED6PFZxWc2wCEPspZW9kL3Se5J7L5TChKgsidH"},
    {"name": "T-Mobile xStock", "symbol": "TMUSx", "address": "svm:XswCi2U1G6Ppbw1QhG45yKb8UKuR1FKLJrquv2FZSD4"},
    {"name": "TBLL xStock", "symbol": "TBLLx", "address": "svm:XsqBC5tcVQLYt8wqGCHRnAUUecbRYXoJCReD6w7QEKp"},
    {"name": "TeraWulf xStock", "symbol": "WULFx", "address": "svm:XsuwUbQSzCJN2wZabD1Gxf1MER2Ypa7hMzVMYB2WawJ"},
    {"name": "Tesla xStock", "symbol": "TSLAx", "address": "svm:XsDoVfqeBukxuZHWhdvWHBhgEHjGNst4MLodqsJHzoB"},
    {"name": "Thermo Fisher xStock", "symbol": "TMOx", "address": "svm:Xs8drBWy3Sd5QY3aifG9kt9KFs2K3PGZmx7jWrsrk57"},
    {"name": "TON xStock", "symbol": "TONXx", "address": "svm:XscE4GUcsYhcyZu5ATiGUMmhxYa1D5fwbpJw4K6K4dp"},
    {"name": "TQQQ xStock", "symbol": "TQQQx", "address": "svm:XsjQP3iMAaQ3kQScQKthQpx9ALRbjKAjQtHg6TFomoc"},
    {"name": "TSMC xStock", "symbol": "TSMx", "address": "svm:XsafvsGtzFqqHgTnA3aPC83EAMkacU5mcGtcSayhpVV"},
    {"name": "Uber xStock", "symbol": "UBERx", "address": "svm:XsAsZLF4MmsvS1sDxRMrUz7REjHfwbC9UAMXSRBqgEB"},
    {"name": "UnitedHealth xStock", "symbol": "UNHx", "address": "svm:XszvaiXGPwvk2nwb3o9C1CX4K6zH8sez11E6uyup6fe"},
    {"name": "Vanguard Total World xStock", "symbol": "VTx", "address": "svm:XsEdDDTcVGJU6nvdRdVnj53eKTrsCkvtrVfXGmUK68V"},
    {"name": "Vanguard xStock", "symbol": "VTIx", "address": "svm:XsssYEQjzxBCFgvYFFNuhJFBeHNdLWYeUSP8F45cDr9"},
    {"name": "Virgin Galactic xStock", "symbol": "SPCEx", "address": "svm:Xsgrm4D6VBTfDx5bs7GNdjtmWDgZ8V79r3YpsYwf5py"},
    {"name": "Visa xStock", "symbol": "Vx", "address": "svm:XsqgsbXwWogGJsNcVZ3TyVouy2MbTkfCFhCGGGcQZ2p"},
    {"name": "Walmart xStock", "symbol": "WMTx", "address": "svm:Xs151QeqTCiuKtinzfRATnUESM2xTU6V9Wy8Vy538ci"},
    {"name": "Warner Bros. Discovery xStock", "symbol": "WBDx", "address": "svm:XsZUSqxAXKJkEimvD4CoVvEb4WUC92TFgj5zRtBxFeL"},
]


def get_catalog() -> List[Dict[str, Any]]:
    """Return the full hardcoded Solana xStocks catalog."""
    return list(SOLANA_TOKENS)

