#!/usr/bin/env bash
# a2a-send-task.sh — Send a task to an agent via the A2A API Gateway
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONF_FILE="${SCRIPT_DIR}/a2a.conf"

# --- Source config file if it exists ---
if [[ -f "$CONF_FILE" ]]; then
  # shellcheck source=a2a.conf
  source "$CONF_FILE"
fi

# --- Defaults (empty = must be configured) ---
: "${A2A_GATEWAY_URL:=}"
: "${A2A_GATEWAY_API_KEY:=}"

# --- Apply config ---
GATEWAY_URL="${A2A_GATEWAY_URL}"
API_KEY="${A2A_GATEWAY_API_KEY}"
AGENT=""
MESSAGE=""
MODEL="auto"
TARGET_AGENT=""
SESSION_ID=""

# --- Parse args (CLI flags override everything) ---
while [[ $# -gt 0 ]]; do
  case "$1" in
    --agent) AGENT="$2"; shift 2 ;;
    --message) MESSAGE="$2"; shift 2 ;;
    --model) MODEL="$2"; shift 2 ;;
    --target-agent) TARGET_AGENT="$2"; shift 2 ;;
    --session-id) SESSION_ID="$2"; shift 2 ;;
    --gateway-url) GATEWAY_URL="$2"; shift 2 ;;
    --api-key) API_KEY="$2"; shift 2 ;;
    *) echo "Unknown argument: $1" >&2; exit 1 ;;
  esac
done

# --- Validate gateway URL ---
if [[ -z "$GATEWAY_URL" ]]; then
  echo "❌ ERROR: A2A_GATEWAY_URL not set. Configure it in a2a.conf or export it." >&2
  echo "  Set it in a2a.conf, via env var, or use --gateway-url flag" >&2
  exit 1
fi

# --- Validate required args ---
if [[ -z "$AGENT" ]]; then
  echo "Error: --agent is required" >&2
  echo "Usage: a2a-send-task.sh --agent <slug> --message <text> [--model auto] [--target-agent <slug>] [--session-id <id>]" >&2
  exit 1
fi

if [[ -z "$MESSAGE" ]]; then
  echo "Error: --message is required" >&2
  echo "Usage: a2a-send-task.sh --agent <slug> --message <text> [--model auto] [--target-agent <slug>] [--session-id <id>]" >&2
  exit 1
fi

# Generate a session ID if not provided
if [[ -z "$SESSION_ID" ]]; then
  SESSION_ID="a2a-${AGENT}-$(date +%s)"
fi

# --- Get admin JWT for API authentication ---
AUTH_TOKEN=$(curl -sS "${GATEWAY_URL}/v0/admin/bootstrap" 2>/dev/null | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    print(data.get('accessToken', ''))
except: print('')
" 2>/dev/null)

if [[ -z "$AUTH_TOKEN" ]]; then
  echo "Error: Failed to obtain admin JWT from gateway" >&2
  exit 1
fi

# --- Build the payload via python3 for proper JSON escaping ---
PAYLOAD=$(python3 -c "
import json, sys
metadata = {'model': sys.argv[1], 'agent': sys.argv[2]}
if sys.argv[3]:
    metadata['target_agent'] = sys.argv[3]
payload = {
    'sessionId': sys.argv[4],
    'message': {'role': 'user', 'content': sys.argv[5]},
    'metadata': metadata
}
print(json.dumps(payload))
" "$MODEL" "$AGENT" "$TARGET_AGENT" "$SESSION_ID" "$MESSAGE")

# --- Send the task ---
RESPONSE=$(curl -sS -w "\n%{http_code}" \
  -X POST \
  -H "Authorization: Bearer ${AUTH_TOKEN}" \
  -H "Content-Type: application/json" \
  -d "$PAYLOAD" \
  "${GATEWAY_URL}/v1/a2a/tasks/send")

HTTP_CODE=$(echo "$RESPONSE" | tail -1)
BODY=$(echo "$RESPONSE" | sed '$d')

if [[ "$HTTP_CODE" != "200" && "$HTTP_CODE" != "201" && "$HTTP_CODE" != "202" ]]; then
  echo "Error: HTTP $HTTP_CODE" >&2
  echo "$BODY" >&2
  exit 1
fi

# --- Format output ---
echo "$BODY" | python3 -c "
import sys, json
try:
    data = json.load(sys.stdin)
    task = data.get('task', data)
    task_id = task.get('id', 'unknown')
    status = task.get('status', 'submitted')
    session = task.get('sessionId', 'N/A')
    model_used = ''
    artifacts = task.get('artifacts', [])
    if artifacts:
        a = artifacts[0]
        desc = a.get('description', '')
        model_used = desc.replace('Generated by ', '') if desc else ''
        content = a.get('content', {})
        if isinstance(content, dict):
            model_used = content.get('model', model_used)
    
    print('✅ Task submitted')
    print(f'  Task ID:  {task_id}')
    print(f'  Status:   {status}')
    print(f'  Session:  {session}')
    print(f'  Agent:    ${AGENT}')
    if '${TARGET_AGENT}':
        print(f'  Target:   ${TARGET_AGENT}')
    if model_used:
        print(f'  Model:    {model_used}')
        # Show the result if completed
        if status == 'completed' and artifacts:
            a = artifacts[0]
            c = a.get('content', {})
            if isinstance(c, dict):
                payload = c.get('payload', {})
                choices = payload.get('choices', [])
                if choices:
                    msg = choices[0].get('message', {})
                    result_text = msg.get('content', '')
                    if result_text:
                        print(f'  Result:   {result_text.strip()[:200]}')
    print()
    print(f'Check status: a2a-get-task.sh --task-id {task_id}')
except Exception as e:
    print(sys.stdin.read())
    print(f'Parse error: {e}')
" 2>/dev/null
