import Database from 'better-sqlite3';
import type { ListFilter } from '../types/cairn.types.js';
import type { Db, HydratedHit, InsertSourceInput, SearchFilter, SearchHitRaw, UpsertEdgeInput, UpsertEntityInput, UpsertFileInput, UpsertFileResult } from '../types/db.types.js';
import type { ChunkId, EdgeRow, Embedding, EntityId, EntityRow, FileId, FileRow, SourceId, SourceRow } from '../types/primitives.types.js';
export declare class DbProvider implements Db {
    private db;
    private sInsertSource;
    private sGetSourceById;
    private sGetSourceByUri;
    private sListSources;
    private sListSourcesByKind;
    private sDeleteSource;
    private sTouchSource;
    private sInsertFile;
    private sGetFile;
    private sUpdateFileChanged;
    private sUpdateFileMtime;
    private sListFiles;
    private sDeleteFilesNotIn;
    private sClearFileHashes;
    private sInsertChunk;
    private sDeleteChunksByFile;
    private sInsertVec;
    private sSearchFts;
    private sSearchFtsBySource;
    private sSearchFtsByKind;
    private sSearchVec;
    private sSearchVecBySource;
    private sSearchVecByKind;
    private sChunksByIds;
    private sFilesByIds;
    private sSourcesByIds;
    private sUpsertEntity;
    private sGetEntity;
    private sGetEntitiesBySource;
    private sSoftDeleteEntity;
    private sDeleteEntity;
    private sUpdateEntityLineRange;
    private sInsertEdge;
    private sGetEdges;
    private sGetEdgesInbound;
    private sGetEdgesForMany;
    private sGetEdgesInboundForMany;
    private sDeleteParseEdgesForPaths;
    private sDeleteDocEdgesForPath;
    private sListEntitiesBySourceWithRowid;
    private sGetDocExtractedHash;
    private sSetDocExtractedHash;
    private sAddSourceLink;
    private sRemoveSourceLink;
    private sListSourceLinks;
    private sGetSourcesLinkedFrom;
    private sGetSourcesLinkingTo;
    private sGetActiveEntitiesForSource;
    private sInsertEntityVec;
    private sUpdateEntityVec;
    private sDeleteEntityVec;
    private sSearchEntityVec;
    private sDeleteTagsForEntity;
    private sInsertTag;
    private sGetTagsForEntity;
    private sGetTagsForMany;
    private sGetEntitiesByTag;
    private sListTags;
    constructor(dbPath: string);
    insertSource(input: InsertSourceInput): SourceRow;
    getSource(ref: SourceId | string): SourceRow | null;
    listSources(filter?: ListFilter): SourceRow[];
    deleteSource(id: SourceId): void;
    touchSource(id: SourceId, ts: number): void;
    upsertFile(input: UpsertFileInput): UpsertFileResult;
    getFile(source_id: SourceId, path: string): FileRow | null;
    listFiles(source_id: SourceId): FileRow[];
    deleteFilesNotIn(source_id: SourceId, paths: string[]): FileId[];
    clearFileHashes(source_id: SourceId): void;
    replaceChunks(file_id: FileId, chunks: {
        content: string;
        start_line: number;
        end_line: number;
    }[], embeddings: Embedding[]): ChunkId[];
    deleteChunksForFile(file_id: FileId): number;
    upsertEntity(input: UpsertEntityInput): {
        rowid: number;
        inserted: boolean;
    };
    upsertEdges(edges: UpsertEdgeInput[]): void;
    getEntity(id: EntityId): EntityRow | null;
    getEntitiesBySource(source: string): EntityRow[];
    getEdges(entityId: EntityId): EdgeRow[];
    getEdgesInbound(entityId: EntityId): EdgeRow[];
    getEdgesForMany(ids: EntityId[]): Map<EntityId, EdgeRow[]>;
    getEdgesInboundForMany(ids: EntityId[]): Map<EntityId, EdgeRow[]>;
    private fetchEdgesByGroup;
    softDeleteMissingEntities(source: string, keepIds: Set<EntityId>): number;
    deleteParseEdgesForSources(paths: string[]): number;
    deleteDocEdgesForSource(path: string): number;
    getDocExtractedHash(file_id: FileId): string | null;
    setDocExtractedHash(file_id: FileId, hash: string): void;
    addSourceLink(from: SourceId, to: SourceId): void;
    removeSourceLink(from: SourceId, to: SourceId): void;
    listSourceLinks(): Array<{
        from: SourceId;
        to: SourceId;
    }>;
    getSourcesLinkedFrom(from: SourceId): SourceId[];
    getSourcesLinkingTo(to: SourceId): SourceId[];
    getActiveEntitiesForSource(source_id: SourceId): EntityRow[];
    searchEntitiesByEmbedding(queryVec: Embedding, k: number): EntityRow[];
    softDeleteEntity(id: EntityId): void;
    deleteEntity(id: EntityId): void;
    searchFts(query: string, k: number, filter?: SearchFilter): SearchHitRaw[];
    searchVec(queryVec: Embedding, k: number, filter?: SearchFilter): SearchHitRaw[];
    hydrate(chunkIds: ChunkId[]): Map<ChunkId, HydratedHit>;
    replaceEntityTags(entity_id: EntityId, tags: string[]): void;
    getTagsForEntity(entity_id: EntityId): string[];
    getEntitiesByTag(tag: string, k?: number): EntityRow[];
    getTagsForMany(ids: EntityId[]): Map<EntityId, string[]>;
    listTags(): Array<{
        tag: string;
        count: number;
    }>;
    close(): void;
    get rawDb(): Database.Database;
    private runSearchFts;
    private runSearchVec;
}
