#!/usr/bin/env node
import fs from 'fs';
import os from 'os';
import path from 'path';

function parseArgs(argv){const args={}; for(let i=2;i<argv.length;i++){const a=argv[i]; if(!a.startsWith('--')) continue; const k=a.slice(2); const v=argv[i+1]&&!argv[i+1].startsWith('--')?argv[++i]:'true'; args[k]=v;} return args;}
function expandHome(p){if(!p)return p; return p.startsWith('~/')?path.join(os.homedir(),p.slice(2)):p;}
function safeErrorText(value){return String(value??'').replace(/sk-[A-Za-z0-9_\-]{8,}/g,'sk-***').replace(/Bearer\s+[A-Za-z0-9_\.\-]+/gi,'Bearer ***').replace(/("?(?:apiKey|api_key|appSecret|app_secret|token|secret)"?\s*[:=]\s*")[^"]+/gi,'$1[redacted]');}
function parseErrorBody(text){try{const data=JSON.parse(text); const err=data?.error&&typeof data.error==='object'?data.error:data; return {upstream_error_type:err?.type,upstream_error_message:err?.message,upstream_error_code:err?.code,raw_error_body:safeErrorText(text).slice(0,1000)};}catch{return {raw_error_body:safeErrorText(text).slice(0,1000)};}}
function diagnose({status,text,stage}){const lower=String(text||'').toLowerCase(); let category='unknown', human_reason='Unknown failure; inspect the redacted error.', retryable=false; if(status===502||lower.includes('upstream_error')||lower.includes('upstream request failed')){category='upstream_failure'; human_reason='Image provider upstream failed or is temporarily unavailable.'; retryable=true;} else if(status===400||lower.includes('invalid_request')){category='invalid_request'; human_reason='Invalid request; check prompt/model/size/API parameters.';} else if(status===401||status===403||lower.includes('unauthorized')||lower.includes('forbidden')){category='auth_or_permission'; human_reason='Authentication or permission failure.';} else if(status===429||lower.includes('rate limit')||lower.includes('too many')){category='rate_limited'; human_reason='Rate limited; retry later.'; retryable=true;} else if(lower.includes('timeout')||stage==='timeout'){category='timeout'; human_reason='Request timed out.'; retryable=true;} return {category,human_reason,retryable};}
function fail(obj){console.log(JSON.stringify({ok:false,...obj},null,2)); process.exit(1);}
function resolveProviderConfig(cfg, providerId){const provider=cfg.models?.providers?.[providerId]; if(!provider) throw new Error(`provider not found: ${providerId}`); const apiKey=provider.apiKey||(provider.apiKeyEnv?process.env[provider.apiKeyEnv]:''); if(!apiKey) throw new Error(`apiKey not configured for provider: ${providerId}`); const baseUrl=String(provider.baseUrl||'').replace(/\/$/,''); if(!baseUrl) throw new Error(`baseUrl not configured for provider: ${providerId}`); return {apiKey,baseUrl};}
async function fetchWithTimeout(url,options,timeoutMs){const ctrl=new AbortController(); const timer=setTimeout(()=>ctrl.abort(),timeoutMs); try{return await fetch(url,{...options,signal:ctrl.signal});} finally{clearTimeout(timer);}}
async function main(){const args=parseArgs(process.argv); const prompt=args.prompt; if(!prompt) throw new Error('missing --prompt'); const providerId=args.provider||process.env.OPENCLAW_IMAGE_PROVIDER||'happy'; const model=args.model||process.env.OPENCLAW_IMAGE_MODEL||'gpt-image-2'; const size=args.size||'1024x1024'; const timeoutMs=Number(args['timeout-ms']||args.timeoutMs||600000); const output=expandHome(args.output||`~/.openclaw/generated-images/image-${Date.now()}.png`); const cfgPath=expandHome(process.env.OPENCLAW_CONFIG_PATH||'~/.openclaw/openclaw.json'); const cfg=JSON.parse(fs.readFileSync(cfgPath,'utf8')); const {apiKey,baseUrl}=resolveProviderConfig(cfg,providerId); fs.mkdirSync(path.dirname(output),{recursive:true}); let res,text; try{res=await fetchWithTimeout(baseUrl+'/images/generations',{method:'POST',headers:{Authorization:`Bearer ${apiKey}`,'Content-Type':'application/json'},body:JSON.stringify({model,prompt,size,n:1,response_format:'b64_json'})},timeoutMs); text=await res.text();}catch(err){const e=safeErrorText(err?.stack||err?.message||err); fail({stage:String(e).toLowerCase().includes('timeout')?'timeout':'request',error:e,diagnosis:diagnose({text:e,stage:'request'})});} if(!res.ok){const parsed=parseErrorBody(text); fail({stage:'request',http_status:res.status,...parsed,error:`image api failed HTTP ${res.status}: ${safeErrorText(text).slice(0,1000)}`,diagnosis:diagnose({status:res.status,text,stage:'request'})});} let data; try{data=JSON.parse(text);}catch{fail({stage:'parse_response',error:`image api returned non-json: ${safeErrorText(text).slice(0,1000)}`,diagnosis:diagnose({text,stage:'parse_response'})});} const item=data.data?.[0]; if(!item?.b64_json&&!item?.url) fail({stage:'parse_response',error:`no image payload in response: ${safeErrorText(JSON.stringify(data)).slice(0,1000)}`,diagnosis:{category:'empty_image_payload',human_reason:'API returned no image payload.',retryable:true}}); if(item.b64_json){fs.writeFileSync(output,Buffer.from(item.b64_json,'base64'));}else{const img=await fetchWithTimeout(item.url,{},timeoutMs); if(!img.ok) fail({stage:'download_image',http_status:img.status,error:`image download failed HTTP ${img.status}`,diagnosis:diagnose({status:img.status,text:'',stage:'download_image'})}); fs.writeFileSync(output,Buffer.from(await img.arrayBuffer()));} const stat=fs.statSync(output); if(stat.size<=0) throw new Error('output file is empty'); console.log(JSON.stringify({ok:true,stage:'done',provider:providerId,model,size,output,bytes:stat.size},null,2));}
main().catch(err=>fail({stage:'runtime',error:safeErrorText(err?.stack||err?.message||err),diagnosis:diagnose({text:err?.message||err,stage:'runtime'})}));
