#!/usr/bin/env bash
set -euo pipefail

# ── Config ───────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(dirname "$SCRIPT_DIR")"
WORKSPACE_ROOT="$(cd "$SKILL_DIR/../.." && pwd)"

STALE_DAYS="${STALE_DAYS:-30}"
SKIP_EMAIL="${SKIP_EMAIL:-0}"
SKIP_REMINDERS="${SKIP_REMINDERS:-0}"
EMAIL_TO="${EMAIL_TO:-}"
REMINDERS_LIST="${REMINDERS_LIST:-Gaming}"

LIBRARY_FILE="$WORKSPACE_ROOT/config/gog_library.json"
HIMALAYA_CONFIG="$WORKSPACE_ROOT/config/himalaya.toml"

# ── Validate ─────────────────────────────────────────────────────────────────
if ! command -v jq &>/dev/null; then
  echo "ERROR: jq is required. Install with: brew install jq" >&2; exit 1
fi

if [[ ! -f "$LIBRARY_FILE" ]]; then
  echo "ERROR: Library file not found: $LIBRARY_FILE" >&2; exit 1
fi

# ── Find stale games ────────────────────────────────────────────────────────
CUTOFF_EPOCH=$(date -d "-${STALE_DAYS} days" +%s 2>/dev/null || date -v-${STALE_DAYS}d +%s)

stale_games=$(jq -r --arg cutoff "$CUTOFF_EPOCH" '
  .games
  | map(select(.installed == true))
  | map(select(
      (.last_played == null) or
      ((.last_played | split("T")[0] | strptime("%Y-%m-%d") | mktime) < ($cutoff | tonumber))
    ))
  | .[]
  | "\(.id)\t\(.name)\t\(.last_played // "never")\t\(.install_path // "N/A")"
' "$LIBRARY_FILE" 2>/dev/null || true)

if [[ -z "$stale_games" ]]; then
  echo "✅ No stale games found (threshold: ${STALE_DAYS} days). All clear!"
  exit 0
fi

# Parse into arrays
mapfile -t lines <<< "$stale_games"
game_count=${#lines[@]}

echo "🎮 Found ${game_count} stale game(s) (not played in ${STALE_DAYS}+ days):"
echo ""

declare -a names=()
for line in "${lines[@]}"; do
  IFS=$'\t' read -r id name last_played install_path <<< "$line"
  names+=("$name")
  echo "  • $name (last played: $last_played, path: $install_path)"
done
echo ""

# ── Build email body ────────────────────────────────────────────────────────
email_subject="🧹 GOG Cleanup: ${game_count} game(s) to consider uninstalling"

email_body="<html><body style='font-family:system-ui,sans-serif;color:#333;max-width:600px;margin:0 auto;padding:20px;'>"
email_body+="<h2 style='color:#8b5cf6;'>🧹 GOG Game Cleanup Report</h2>"
email_body+="<p>You have <strong>${game_count} installed game(s)</strong> that haven't been played in ${STALE_DAYS}+ days:</p>"
email_body+="<table style='width:100%;border-collapse:collapse;margin:16px 0;'>"
email_body+="<tr style='background:#f3f4f6;text-align:left;'><th style='padding:8px;border:1px solid #e5e7eb;'>Game</th><th style='padding:8px;border:1px solid #e5e7eb;'>Last Played</th><th style='padding:8px;border:1px solid #e5e7eb;'>Install Path</th></tr>"

for line in "${lines[@]}"; do
  IFS=$'\t' read -r id name last_played install_path <<< "$line"
  email_body+="<tr><td style='padding:8px;border:1px solid #e5e7eb;'>${name}</td><td style='padding:8px;border:1px solid #e5e7eb;'>${last_played}</td><td style='padding:8px;border:1px solid #e5e7eb;font-size:0.85em;'>${install_path}</td></tr>"
done

email_body+="</table>"
email_body+="<p style='color:#6b7280;font-size:0.9em;'>Reminders have been added to your Gaming list in Apple Reminders. Generated by gog-cleanup skill.</p>"
email_body+="</body></html>"

# ── Send email ───────────────────────────────────────────────────────────────
if [[ "$SKIP_EMAIL" != "1" ]]; then
  if command -v himalaya &>/dev/null; then
    # Resolve recipient from config if not set
    if [[ -z "$EMAIL_TO" && -f "$HIMALAYA_CONFIG" ]]; then
      EMAIL_TO=$(jq -r '.accounts.personal.email // empty' "$HIMALAYA_CONFIG" 2>/dev/null || \
        grep -A1 '\[accounts.personal\]' "$HIMALAYA_CONFIG" 2>/dev/null | grep 'email' | head -1 | sed 's/.*=.*"\(.*\)".*/\1/' || true)
    fi

    if [[ -n "$EMAIL_TO" ]]; then
      # Create MML with HTML body
      tmp_mml=$(mktemp)
      cat > "$tmp_mml" << MML_EOF
From: $(grep -A5 '\[accounts.personal\]' "$HIMALAYA_CONFIG" 2>/dev/null | grep 'email' | head -1 | sed 's/.*=.*"\(.*\)".*/\1/' || echo "me")
To: ${EMAIL_TO}
Subject: ${email_subject}
Content-Type: text/html

${email_body}
MML_EOF

      if himalaya --account personal template send < "$tmp_mml" 2>/dev/null; then
        echo "📧 Email sent to ${EMAIL_TO}"
      else
        echo "⚠️  Failed to send email via himalaya. Check your config." >&2
      fi
      rm -f "$tmp_mml"
    else
      echo "⚠️  No recipient email configured. Set EMAIL_TO or check himalaya.toml." >&2
    fi
  else
    echo "⚠️  himalaya not found. Skipping email. Install: brew install himalaya" >&2
  fi
else
  echo "📧 Email skipped (SKIP_EMAIL=1)"
fi

# ── Add Apple Reminders ─────────────────────────────────────────────────────
if [[ "$SKIP_REMINDERS" != "1" ]]; then
  if command -v remindctl &>/dev/null; then
    # Ensure Gaming list exists
    if ! remindctl list "$REMINDERS_LIST" &>/dev/null; then
      remindctl list "$REMINDERS_LIST" --create 2>/dev/null && echo "📝 Created '$REMINDERS_LIST' reminders list"
    fi

    added=0
    skipped=0
    for name in "${names[@]}"; do
      reminder_title="🧹 Consider uninstalling: ${name}"
      # Check if reminder already exists (idempotency)
      if remindctl list "$REMINDERS_LIST" --plain 2>/dev/null | grep -qF "$reminder_title"; then
        ((skipped++)) || true
      else
        if remindctl add --title "$reminder_title" --list "$REMINDERS_LIST" 2>/dev/null; then
          ((added++)) || true
        else
          echo "⚠️  Failed to add reminder for: $name" >&2
        fi
      fi
    done
    echo "📝 Reminders: ${added} added, ${skipped} already existed (in '$REMINDERS_LIST' list)"
  else
    echo "⚠️  remindctl not found. Skipping reminders. Install: brew install steipete/tap/remindctl" >&2
  fi
else
  echo "📝 Reminders skipped (SKIP_REMINDERS=1)"
fi

echo ""
echo "✅ GOG cleanup sweep complete!"
