#!/usr/bin/env python3
"""Write local bookmark reference files for STARCORE-family links.

No browser automation, no process spawn, no network.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path


def load_receipts(workspace: Path, symbols: list[str], receipts_path: Path | None) -> dict[str, dict]:
    state = workspace / "state"
    data: dict[str, dict] = {}
    if receipts_path and receipts_path.is_file():
        j = json.loads(receipts_path.read_text(encoding="utf-8"))
        for sym, rec in (j.get("receipts") or {}).items():
            data[str(sym).upper()] = rec
    else:
        for sym in symbols:
            p = state / f"{sym}_clawnch_receipt.json"
            if p.is_file():
                try:
                    data[sym.upper()] = json.loads(p.read_text(encoding="utf-8"))
                except (OSError, json.JSONDecodeError):
                    pass
    return data


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--symbols", default="STARCORE,STARCOREX,STARCORECOIN")
    ap.add_argument("--receipts", help="Optional summary JSON path")
    ap.add_argument("--workspace", default=".", help="Workspace root (contains state/)")
    ap.add_argument("--bookmark-dir", default="reference/bookmarks", help="Local dir for bookmark .md files")
    args = ap.parse_args()

    workspace = Path(args.workspace).resolve()
    symbols = [s.strip().upper() for s in args.symbols.split(",") if s.strip()]
    recs = load_receipts(workspace, symbols, Path(args.receipts) if args.receipts else None)
    if not recs:
        print("No receipts found to bookmark")
        return 2

    out = workspace / args.bookmark_dir
    out.mkdir(parents=True, exist_ok=True)
    lines = ["# STARCORE family monitor links\n", "Generated by lyra-coin-launch-manager (local only).\n"]
    for sym in symbols:
        rec = recs.get(sym)
        if not rec:
            continue
        contract = rec.get("contractAddress") or ""
        clanker = rec.get("clankerUrl") or (contract and f"https://clanker.world/clanker/{contract}")
        lines.append(f"\n## {sym}\n")
        if clanker:
            lines.append(f"- Clanker: {clanker}\n")
        if contract:
            lines.append(f"- Blockscout: https://base.blockscout.com/address/{contract}\n")
            lines.append(f"- Dexscreener search: https://api.dexscreener.com/latest/dex/search/?q={contract}\n")
            lines.append(f"- Contract: `{contract}`\n")
        (out / f"{sym}_links.md").write_text("".join(lines[-6:]), encoding="utf-8")

    (out / "STARCORE_family_links.md").write_text("".join(lines), encoding="utf-8")
    print(f"[OK] Local bookmark refs in {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
