#!/usr/bin/env python3
"""
peer_config.py — Interactive peer agent configuration generator for LAN.

Generates a peer-config.md file with connection details for two OpenClaw
agents to communicate over a trusted local network.

Unlike the Tailscale version, this script:
- Does NOT store gateway tokens in the config file
- Auto-detects LAN IPs (not VPN IPs)
- Emphasises firewall rules for the trusted subnet only

Usage:
    python3 scripts/peer_config.py
"""

import os
import sys
import json
import subprocess


def get_lan_ip():
    """Try to detect the local LAN IP address."""
    # Try ipconfig on Windows
    try:
        result = subprocess.run(
            ["ipconfig"],
            capture_output=True, text=True, timeout=5
        )
        if result.returncode == 0:
            for line in result.stdout.splitlines():
                line = line.strip()
                if line.startswith("IPv4") and "127.0.0.1" not in line:
                    # Extract IP from lines like "IPv4 Address. . . . : 192.168.1.5"
                    parts = line.split(":")
                    if len(parts) >= 2:
                        ip = parts[-1].strip()
                        if ip.startswith(("192.168.", "10.", "172.16.", "172.17.", "172.18.",
                                          "172.19.", "172.2", "172.3")):
                            return ip
    except Exception:
        pass

    # Try ip on Linux/macOS
    try:
        result = subprocess.run(
            ["ip", "route", "get", "1.1.1.1"],
            capture_output=True, text=True, timeout=5
        )
        if result.returncode == 0:
            for part in result.stdout.split():
                if part.startswith(("192.168.", "10.", "172.")):
                    return part
    except Exception:
        pass

    return None


def get_gateway_info():
    """Try to read OpenClaw gateway config for port."""
    config_paths = [
        os.path.expanduser("~/.openclaw/openclaw.json"),
        os.path.expanduser("~/.openclaw/config.json"),
    ]
    for path in config_paths:
        if os.path.exists(path):
            try:
                with open(path) as f:
                    config = json.load(f)
                gateway = config.get("gateway", {})
                port = gateway.get("port", 18789)
                bind = gateway.get("bind", "localhost")
                return bind, port
            except Exception:
                pass
    return "localhost", 18789


def main():
    print("=" * 50)
    print("  OpenClaw LAN Peer — Config Generator")
    print("=" * 50)
    print()
    print("This generates a peer-agent/peer-config.md file")
    print("for direct LAN communication between two OpenClaw agents.")
    print()
    print("NOTE: Gateway tokens are NOT stored in this file.")
    print("Pass them at runtime or via environment variables.")
    print()

    # Auto-detect
    auto_lan_ip = get_lan_ip()
    auto_bind, auto_port = get_gateway_info()

    # Gather your info
    print("--- YOUR DETAILS ---")
    my_name = input("Your name / agent name: ").strip()

    if auto_lan_ip:
        use_auto = input(f"Your LAN IP [{auto_lan_ip}]: ").strip()
        my_lan_ip = use_auto or auto_lan_ip
    else:
        my_lan_ip = input("Your LAN IP: ").strip()

    my_gateway_port = input(f"Gateway port [{auto_port}]: ").strip()
    my_gateway_port = int(my_gateway_port) if my_gateway_port else auto_port
    my_agent_id = input("Your agentId [main]: ").strip() or "main"

    print()
    print("--- YOUR PEER'S DETAILS ---")
    peer_name = input("Peer's name / agent name: ").strip()
    peer_lan_ip = input("Peer's LAN IP: ").strip()
    peer_gateway_port = input(f"Peer's gateway port [{auto_port}]: ").strip()
    peer_gateway_port = int(peer_gateway_port) if peer_gateway_port else auto_port
    peer_agent_id = input("Peer's agentId [main]: ").strip() or "main"

    print()
    print("Generating peer-config.md...")

    config_content = f"""# Peer Agent Configuration — LAN
# Generated by peer_config.py
# Update these values when network details change.
# 
# ⚠️  Gateway tokens are NOT stored here.
# Pass them at runtime via environment variables or command arguments.

---

## My Details

**Name:** {my_name}
**LAN IP:** {my_lan_ip}
**Gateway URL:** http://{my_lan_ip}:{my_gateway_port}
**Agent ID:** {my_agent_id}

---

## My Peer

**Name:** {peer_name}
**LAN IP:** {peer_lan_ip}
**Gateway URL:** http://{peer_lan_ip}:{peer_gateway_port}
**Agent ID:** {peer_agent_id}

---

## Quick Reference

### Test my gateway is reachable from peer machine:
```bash
curl http://{my_lan_ip}:{my_gateway_port}/health --connect-timeout 5
```

### Test peer's gateway from my machine:
```bash
curl http://{peer_lan_ip}:{peer_gateway_port}/health --connect-timeout 5
```

### Send a message to peer:
```json
sessions_send(
  sessionKey="<session-key>",
  agentId="{peer_agent_id}",
  message="Hello from {my_name}!",
  gatewayUrl="http://{peer_lan_ip}:{peer_gateway_port}"
)
```

### Spawn a task on the peer:
```json
sessions_spawn(
  task="<task description>",
  taskName="<task-name>",
  mode="run",
  runtime="subagent",
  gatewayUrl="http://{peer_lan_ip}:{peer_gateway_port}"
)
```

---

## Shared Collaboration Log

Create `peer-agent/shared-log.md` for ongoing notes between agents.
"""

    os.makedirs("peer-agent", exist_ok=True)
    output_path = os.path.join("peer-agent", "peer-config.md")
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(config_content)

    print(f"✅ Written to: {output_path}")
    print()
    print("Next steps:")
    print(f"1. Review {output_path}")
    print("2. Test connectivity: curl http://<peer-ip>:<port>/health")
    print("3. Set up firewall rules for the gateway port on both machines")
    print("4. Start collaborating!")
    print()
    print("⚠️  Remember: do NOT put gateway tokens in this file.")
    print("   Pass them as environment variables or at runtime.")


if __name__ == "__main__":
    main()