#!/usr/bin/env node
/**
 * bounty-scam-check — is this GitHub "bounty" issue real, or bait?
 *
 * Battle-tested patterns from a scanner that ran daily for 8 weeks and met, in the wild:
 * star-farming repos, "best entry wins the pot" free-labor traps, bot-autoposted
 * meta-bounties, off-platform claim spam, and finally an AI-agent HONEYPOT mass-producing
 * fake $100 security bounties to harvest code submissions as training data.
 *
 * Usage:
 *   node check.js https://github.com/owner/repo/issues/123
 *   node check.js owner/repo#123
 *
 * Requires: gh CLI (authenticated). Read-only — never clones, installs, or runs repo code.
 * Exit 0 = no red flags found. Exit 1 = flags (listed). Exit 2 = usage/fetch error.
 */
const { execFileSync } = require('child_process');

const SCAM_PATTERNS = [
  { re: /\bstar(\s+this\s+repo|\s+us)?\s+first\b|no\s+stars?\W+no\s+bounty|must\s+star\b|\bmore\s+stars\b[^.]*\b(priority|queue|higher|review|adoption)|\bstar\s+priority\b/i,
    reason: 'star-gating / star-farming ("star first" — no legit bounty requires a star)' },
  { re: /\bmultiple\s+entries\b|best\s+(implementation|solution|entry)\b[^.]*\b(wins?|pot)\b|winner\s+takes|wins?\s+the\s+pot\b/i,
    reason: 'best-of-many-entries "wins the pot" (free-labor farm — N-1 contributors work for nothing)' },
  { re: /crypto-eligible|💎/i, reason: 'crypto / hype dressing' },
  { re: /\bbounty\s+alert\b|\b\d+\s+new\s+opportunit|\bscan\s+results?\b|\bbounty\s+(post\s+)?template\b|\bopportunit(?:y|ies)?\s+found\b/i,
    reason: 'meta-bounty / bot-autopost title (a bot\'s own scan output, not a real bounty)' },
  { re: /bounty\s+board\s+reference\s*:|listed\s+on\s+.{0,40}bounty\s+board|\bI\s+(would\s+like\s+to|want\s+to|wish\s+to)\s+work\s+on\b|\bI'?m?\s+claiming\b/i,
    reason: 'off-platform bounty board / contributor claim (not a maintainer-posted bounty)' },
  // Auto-generation tells — INCLUDING non-English. An English-only pattern list is a hole:
  // a honeypot slipped past one because its bot signature was written in Chinese.
  { re: /task\s+(auto[- ]?)?(created|generated)\s+by|daily\s+task\s+generator|自动创建|自動創建|автоматически\s+создан/i,
    reason: 'issue auto-generated by a bot ("Daily Task Generator" tell)' },
  { re: /蜜罐|honeypot|training\s+data(set)?\b.{0,60}(submission|PR|fix)|LoRA\b.{0,40}(pipeline|fine-?tun)/i,
    reason: 'honeypot / training-data-harvest language (submissions become someone\'s dataset, not your payout)' },
];

function gh(args) {
  return JSON.parse(execFileSync('gh', ['api', ...args], { encoding: 'utf8', maxBuffer: 8 * 1024 * 1024 }));
}

function parseTarget(arg) {
  let m = arg.match(/github\.com\/([^/]+)\/([^/]+)\/issues\/(\d+)/) || arg.match(/^([^/]+)\/([^#]+)#(\d+)$/);
  if (!m) return null;
  return { owner: m[1], repo: m[2], num: m[3] };
}

function extractBountyUsd(text) {
  const mK = text.match(/\$\s*(\d+(?:\.\d+)?)\s*k/i);
  if (mK) return Math.round(parseFloat(mK[1]) * 1000);
  const m1 = text.match(/\$\s*(\d{2,3}(?:,\d{3})+|\d{2,6})/);
  if (m1) return parseInt(m1[1].replace(/,/g, ''), 10);
  return null;
}

function main() {
  const target = parseTarget(process.argv[2] || '');
  if (!target) {
    console.error('usage: node check.js <github issue url | owner/repo#123>');
    process.exit(2);
  }
  const { owner, repo, num } = target;
  let issue, meta;
  try {
    issue = gh([`repos/${owner}/${repo}/issues/${num}`]);
    meta = gh([`repos/${owner}/${repo}`]);
  } catch (e) {
    console.error('fetch failed:', e.message.split('\n')[0]);
    process.exit(2);
  }

  const flags = [];
  const text = `${issue.title}\n${issue.body || ''}\n${(issue.labels || []).map((l) => l.name).join(' ')}`;
  const repoText = `${meta.description || ''}`;

  for (const p of SCAM_PATTERNS) {
    if (p.re.test(text)) flags.push(p.reason);
    else if (p.re.test(repoText)) flags.push(`${p.reason} — in the REPO DESCRIPTION`);
  }

  const usd = extractBountyUsd(text);
  const ageDays = Math.floor((Date.now() - new Date(meta.created_at).getTime()) / 86400000);
  const stars = meta.stargazers_count || 0;
  const isGFI = (issue.labels || []).some((l) => /good first issue/i.test(l.name));

  if (usd >= 1000 && isGFI) flags.push(`$${usd} on a "good first issue" (disproportionate — nobody pays $1k for beginner work)`);
  if (ageDays < 30 && usd) flags.push(`repo is only ${ageDays}d old and dangling $${usd} (young repo + cash = classic farm)`);
  if (ageDays < 14 && stars > 50) flags.push(`${stars} stars on a ${ageDays}d-old repo (likely manufactured)`);
  if (ageDays > 30 && stars === 0) flags.push(`0 stars on a ${ageDays}d-old repo (no traction — who is paying you, exactly?)`);
  if (issue.user && meta.owner && issue.user.login !== meta.owner.login && /^\s*bounty:/i.test(issue.title || '')) {
    flags.push(`"bounty:" title posted by @${issue.user.login}, not repo owner @${meta.owner.login} (contributor claim, not a bounty)`);
  }

  console.log(`${owner}/${repo}#${num} — "${(issue.title || '').slice(0, 70)}"`);
  console.log(`repo: ${ageDays}d old · ${stars}★ · bounty: ${usd ? '$' + usd : 'n/a'}`);
  if (!flags.length) {
    console.log('✅ no red flags found. Still: verify the maintainer + payment rail before working, and NEVER run the repo\'s code to "check it out" — read-only review.');
    process.exit(0);
  }
  console.log(`🚩 ${flags.length} red flag(s):`);
  for (const f of flags) console.log(`   • ${f}`);
  console.log('Verdict: treat as a farm/honeypot. Do not star, do not draft, do not submit.');
  process.exit(1);
}
main();
