#!/usr/bin/env bash
set -euo pipefail

# ── Defaults ──────────────────────────────────────────────
LIBRARY="config/gog_library.json"
DAYS=30
EMAIL_ACCOUNT="personal"
REMINDERS_LIST="Gaming"
DRY_RUN=false

# ── Parse args ────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
  case "$1" in
    --library)        LIBRARY="$2"; shift 2 ;;
    --days)           DAYS="$2"; shift 2 ;;
    --email)          EMAIL_ACCOUNT="$2"; shift 2 ;;
    --reminders-list) REMINDERS_LIST="$2"; shift 2 ;;
    --dry-run)        DRY_RUN=true; shift ;;
    *)                echo "Unknown flag: $1"; exit 1 ;;
  esac
done

# ── Validate ──────────────────────────────────────────────
if [[ ! -f "$LIBRARY" ]]; then
  echo "❌ Library file not found: $LIBRARY" >&2; exit 1
fi

for cmd in jq himalaya remindctl; do
  if ! command -v "$cmd" &>/dev/null; then
    echo "❌ Required command not found: $cmd" >&2; exit 1
  fi
done

# ── Compute cutoff ────────────────────────────────────────
CUTOFF=$(date -u -d "${DAYS} days ago" '+%Y-%m-%dT%H:%M:%SZ' 2>/dev/null \
      || date -u -v-${DAYS}d '+%Y-%m-%dT%H:%M:%SZ' 2>/dev/null)
TODAY=$(date '+%Y-%m-%d')

# ── Find stale installed games ────────────────────────────
STALE=$(jq -r --arg cutoff "$CUTOFF" '
  [.games[] | select(.installed == true)
    | select(.last_played == null or ((.last_played | split(".")[0] + "Z") | fromdateiso8601) < ($cutoff | fromdateiso8601))]]
  | sort_by(.last_played // "0000")
' "$LIBRARY")

COUNT=$(echo "$STALE" | jq 'length')

if [[ "$COUNT" -eq 0 ]]; then
  echo "✅ No stale games found (threshold: ${DAYS} days). All clear!"
  exit 0
fi

echo "🧹 GOG Stale Games Sweep — $TODAY"
echo "  Found $COUNT stale game(s) (>${DAYS} days since last play):"
echo ""

# ── Build email body ──────────────────────────────────────
EMAIL_BODY="<h2>🧹 GOG Stale Games — $TODAY</h2>"
EMAIL_BODY+="<p>These installed games haven't been played in over <strong>${DAYS} days</strong>:</p>"
EMAIL_BODY+="<table style='border-collapse:collapse;width:100%'>"
EMAIL_BODY+="<tr style='background:#f0f0f0'><th style='text-align:left;padding:6px'>Game</th><th style='text-align:left;padding:6px'>Last Played</th><th style='text-align:left;padding:6px'>Install Path</th></tr>"

ROW_IDX=0
while IFS= read -r line; do
  NAME=$(echo "$line" | jq -r '.name')
  LAST=$(echo "$line" | jq -r '.last_played // "Never"')
  PATH_=$(echo "$line" | jq -r '.install_path // "N/A"')
  BG=$([[ $((ROW_IDX % 2)) -eq 0 ]] && echo "" || echo "background:#fafafa")
  EMAIL_BODY+="<tr style='$BG'><td style='padding:6px'>$NAME</td><td style='padding:6px'>$LAST</td><td style='padding:6px'>$PATH_</td></tr>"
  echo "  • $NAME — last played ${LAST}"
  ROW_IDX=$((ROW_IDX + 1))
done < <(echo "$STALE" | jq -c '.[]')

EMAIL_BODY+="</table>"
EMAIL_BODY+="<p style='color:#888;margin-top:16px'>Generated by gog-stale-games-cleanup on $TODAY</p>"

# ── Get recipient email ──────────────────────────────────
RECIPIENT=$(himalaya --account "$EMAIL_ACCOUNT" account list --output json 2>/dev/null \
  | jq -r ".[] | select(.name == \"$EMAIL_ACCOUNT\") | .email" 2>/dev/null \
  || jq -r ".accounts.${EMAIL_ACCOUNT}.email" ~/.config/himalaya/config.toml 2>/dev/null \
  || echo "")

if [[ -z "$RECIPIENT" ]]; then
  echo "⚠️  Could not resolve email for account '$EMAIL_ACCOUNT', using fallback"
  RECIPIENT=$(jq -r ".accounts.${EMAIL_ACCOUNT}.email" /root/.openclaw/workspace/config/himalaya.toml 2>/dev/null || echo "")
fi

# ── Send email ───────────────────────────────────────────
if [[ "$DRY_RUN" == "true" ]]; then
  echo ""
  echo "  [DRY RUN] Would email $RECIPIENT with subject: 🧹 GOG Stale Games — $TODAY"
else
  SUBJECT="🧹 GOG Stale Games — $TODAY"
  # Build MML template for himalaya
  cat <<HEREDOC | himalaya --account "$EMAIL_ACCOUNT" template send
From: $(jq -r ".accounts.${EMAIL_ACCOUNT}.email" /root/.openclaw/workspace/config/himalaya.toml 2>/dev/null || echo "$RECIPIENT")
To: $RECIPIENT
Subject: $SUBJECT
Content-Type: text/html

$EMAIL_BODY
HEREDOC
  echo ""
  echo "  ✉️  Email sent to $RECIPIENT"
fi

# ── Apple Reminders ──────────────────────────────────────
# Ensure list exists
if [[ "$DRY_RUN" == "true" ]]; then
  echo "  [DRY RUN] Would ensure list '$REMINDERS_LIST' exists"
else
  remindctl list "$REMINDERS_LIST" --create 2>/dev/null || true
fi

REMINDER_COUNT=0
while IFS= read -r line; do
  NAME=$(echo "$line" | jq -r '.name')
  LAST=$(echo "$line" | jq -r '.last_played // "Never"')
  TITLE="Consider uninstalling: $NAME (last played $LAST)"

  if [[ "$DRY_RUN" == "true" ]]; then
    echo "  [DRY RUN] Would add reminder: $TITLE"
  else
    remindctl add --title "$TITLE" --list "$REMINDERS_LIST" 2>/dev/null && \
      REMINDER_COUNT=$((REMINDER_COUNT + 1)) || \
      echo "  ⚠️  Failed to add reminder for $NAME"
  fi
done < <(echo "$STALE" | jq -c '.[]')

if [[ "$DRY_RUN" != "true" ]]; then
  echo "  📝 $REMINDER_COUNT reminder(s) added to \"$REMINDERS_LIST\""
fi
