'use strict';

const ENV_API_URL = 'ZL_CLAW_PAY_API_URL';
const ENV_GM_SERVER_PUBLIC_KEY = 'ZL_CLAW_PAY_GM_SERVER_PUBLIC_KEY';
const ENV_LOG_LEVEL = 'ZL_CLAW_PAY_LOG_LEVEL';

const SUCCESS_CODE_PREFIX = 'S';
const FAILURE_CODE_PREFIX = 'F';

const HTTP_OK = 200;
const REQUEST_TIMEOUT = 30000;

const SM2_PRIVATE_KEY_LENGTH = 64;
const SM2_PUBLIC_KEY_LENGTH = 130;

const STATE_DIR = '.zl-claw-pay';
const STATE_FILE = 'state.json';

const API_VERSION = '1.0';

const REQUIRED_NODE_VERSION = 18;

const INTERFACE_PREFIX_LOCAL = 'L';
const INTERFACE_PREFIX_POST = 'C';
const INTERFACE_PREFIX_UNIFIED = 'P';

const ENV_WHITELIST = [
  'ZL_CLAW_PAY_API_URL',
  'ZL_CLAW_PAY_GM_SERVER_PUBLIC_KEY',
  'ZL_CLAW_PAY_LOG_LEVEL'
];

module.exports = {
  ENV_API_URL,
  ENV_GM_SERVER_PUBLIC_KEY,
  ENV_LOG_LEVEL,
  SUCCESS_CODE_PREFIX,
  FAILURE_CODE_PREFIX,
  HTTP_OK,
  REQUEST_TIMEOUT,
  SM2_PRIVATE_KEY_LENGTH,
  SM2_PUBLIC_KEY_LENGTH,
  STATE_DIR,
  STATE_FILE,
  API_VERSION,
  REQUIRED_NODE_VERSION,
  INTERFACE_PREFIX_LOCAL,
  INTERFACE_PREFIX_POST,
  INTERFACE_PREFIX_UNIFIED,
  ENV_WHITELIST,
};
