#!/usr/bin/env bash
# worktree-agents/scripts/push_and_pr.sh
# 推送分支并在 GitHub 上创建 PR
#
# 用法: push_and_pr.sh <repo_dir> <gh_token> <github_owner_repo> <agent_name> <worktree_path> <branch> <base_branch>
# 输出: PR URL

set -euo pipefail

REPO_DIR="$1"
GH_TOKEN="$2"
OWNER_REPO="$3"
AGENT_NAME="$4"
WORKTREE_PATH="$5"
BRANCH="$6"
BASE_BRANCH="$7"

# 设置 token auth
cd "$WORKTREE_PATH"
git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/${OWNER_REPO}.git"

# 推送
GIT_ASKPASS=true git push origin "$BRANCH" 2>&1 >&2

# 开 PR
PR_BODY="## $AGENT_NAME Output\n\nGenerated by OpenClaw multi-agent worktree orchestrator.\n\nWorktree: \`$WORKTREE_PATH\`\nBranch: \`$BRANCH\`"

RESPONSE=$(curl -s -X POST \
  -H "Authorization: Bearer $GH_TOKEN" \
  -H "Accept: application/vnd.github+json" \
  "https://api.github.com/repos/$OWNER_REPO/pulls" \
  -d "$(jq -n \
    --arg title "[$AGENT_NAME] automated task" \
    --arg head "$BRANCH" \
    --arg base "$BASE_BRANCH" \
    --arg body "$PR_BODY" \
    '{title: $title, head: $head, base: $base, body: $body}')")

echo "$RESPONSE" | jq -r '.html_url'
