"""Hardcoded seed list — known Iranian chemical suppliers & B2B directories (spec §2.1)."""

# (name, url)
SUPPLIER_SEEDS = [
    ("Chemical Iran", "https://www.chemicaliran.com"),
    ("Iran Petrochemical", "https://www.iranpetrochemical.net"),
    ("Rock Chemie Co.", "https://www.rockchemie.com"),
    ("ArChem", "https://www.archemco.com"),
    ("Abnoos Chemical Complex", "https://www.abnoos.com"),
    ("Puricals", "https://www.puricals.com"),
    ("Cadoos International Petrochemical (INTPCC)", "https://www.cadoos.com"),
    ("DPPC / Pharma Chem", "https://www.dppc.ir"),
    ("Pars Gilsonite Reshad Co.", "https://www.parsgilsonite.com"),
    ("Artin Kimya", "https://www.artinkimya.com"),
    ("Novichem Co.", "https://www.novichem.ir"),
    ("Karina Polymer", "https://www.karinapolymer.com"),
    ("BASPARSAZAN IRANIAN Company", "https://www.basparsazan.com"),
    ("Paksho Industrial Group", "https://www.pakshoo.com"),
    ("ASCO", "https://www.asco.co.ir"),
    ("Mahdis Tejarat Trading Company", "https://www.mahdistejarat.com"),
    ("Chemical Mine World Co.", "https://www.chemicalmineworld.com"),
    ("Lazak Mehregan International Commercial Co.", "https://www.lazakmehregan.com"),
    ("Akbarieh Company", "https://www.akbarieh.com"),
    ("Gulf Petrochemical", "https://www.gulfpetrochemical.com"),
    ("Fluid Tamin Rahaam Company", "https://www.fluidtamin.com"),
    ("Pars Isotope Co.", "https://www.parsisotope.com"),
    ("Pishtaz Teb Zaman Diagnostics", "https://www.pishtazteb.com"),
    ("Raeis Industrial Group", "https://www.raeisgroup.com"),
    ("Barzin International Group", "https://www.barzingroup.com"),
    ("ATDM", "https://www.atdm.ir"),
    ("Mobtakeran Shimi", "https://www.mobtakeranshimi.com"),
    ("Teb Gostar Noor Pars", "https://www.tebgostar.com"),
    ("Kimia Eksir Company", "https://www.kimiaeksir.com"),
    ("Mojallali Group", "https://www.drm-chem.com"),
    ("Exir Pharmaceutical Co.", "https://www.exir.co.ir"),
    ("Sobhan Oncology", "https://www.sobhanoncology.ir"),
    ("Iran Daru Pharmaceutical", "https://www.irandaru.com"),
    ("Temad", "https://www.temad.com"),
    ("Persian Gulf Star Oil Company", "https://www.pgsoc.ir"),
]

DIRECTORY_SEEDS = [
    "https://www.shimico.com/companies/",
    "https://www.b2bmap.com/iran",
    "https://www.lookchem.com/iran/",
    "https://www.chemnet.com/iran/",
    "https://www.chemicals1.com/iran",
    "https://www.chemicalbusinessdirectory.com/iran",
    "https://www.ensun.io/chemical-manufacturing/iran",
    "https://www.volza.com/iran-reagent-exporters",
    "https://www.kompass.com/iran/chemicals",
    "https://www.tradeford.com/iran-chemicals",
    "https://www.exporthub.com/iran-chemicals",
    "https://www.alibaba.com/iran-chemicals",
    "https://www.tradewheel.com/iran/chemicals",
    "https://www.ec21.com/iran-chemicals",
    "https://www.made-in-china.com/iran-chemicals",
]
