import os

def write_stable_file(path, lines):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, 'w', encoding='utf-8') as f:
        f.write('
'.join(lines) + '
')

write_stable_file('/Users/jazzxx/Desktop/openclaw/skills/autoresearch/core/result_tracker.py', [
    'import os',
    'import csv',
    'import time',
    'import json',
    '',
    'class ResultTracker:',
    '    def __init__(self, filepath=None):',
    '        base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))',
    '        self.filepath = filepath or os.path.join(base_dir, "results.tsv")',
    '        self._init_file()',
    '',
    '    def _init_file(self):',
    '        if not os.path.exists(self.filepath):',
    '            with open(self.filepath, "w", newline="", encoding="utf-8") as f:',
    '                writer = csv.writer(f, delimiter="	")',
    '                writer.writerow(["timestamp", "hypothesis", "val_bpb", "improved", "config"])',
    '',
    '    def log_result(self, hypothesis, bpb, improved, config_dict):',
    '        try:',
    '            with open(self.filepath, "a", newline="", encoding="utf-8") as f:',
    '                writer = csv.writer(f, delimiter="	")',
    '                writer.writerow([',
    '                    time.strftime("%Y-%m-%d %H:%M:%S"),',
    '                    hypothesis,',
    '                    f"{bpb:.6f}" if bpb is not None else "FAILED",',
    '                    "YES" if improved else "NO",',
    '                    json.dumps(config_dict)',
    '                ])',
    '        except Exception as e:',
    '            print(f"Error logging: {e}")',
    '',
    '    def get_best_score(self):',
    '        if not os.path.exists(self.filepath): return 1.5',
    '        best = 1.5',
    '        try:',
    '            with open(self.filepath, "r", encoding="utf-8") as f:',
    '                reader = csv.DictReader(f, delimiter="	")',
    '                for row in reader:',
    '                    try:',
    '                        v = row.get("val_bpb", "1.5")',
    '                        if v in ["FAILED", "N/A", ""]: continue',
    '                        best = min(best, float(v))',
    '                    except: continue',
    '        except: pass',
    '        return best',
    '',
    '    def get_history_summary(self, limit=10):',
    '        if not os.path.exists(self.filepath): return "No history."',
    '        history = []',
    '        try:',
    '            with open(self.filepath, "r", encoding="utf-8") as f:',
    '                reader = csv.DictReader(f, delimiter="	")',
    '                for row in reader:',
    '                    history.append(f"- {row.get("timestamp")} | Hypo: {row.get("hypothesis")} | BPB: {row.get("val_bpb")}")',
    '        except: return "Error reading history."',
    '        return "
".join(history[-limit:])'
])

write_stable_file('/Users/jazzxx/Desktop/openclaw/skills/autoresearch/cli/main.py', [
    'import argparse, sys, os',
    'sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))',
    'from core.result_tracker import ResultTracker',
    'from core.experiment import ExperimentEngine',
    'from hypothesis.generator import LLMHypothesisGenerator',
    '',
    'def main():',
    '    parser = argparse.ArgumentParser()',
    '    sub = parser.add_subparsers(dest="command")',
    '    sub.add_parser("run")',
    '    sub.add_parser("status")',
    '    args = parser.parse_args()',
    '    if args.command == "run":',
    '        gen = LLMHypothesisGenerator()',
    '        eng = ExperimentEngine()',
    '        hypo = gen.generate_next_hypothesis()',
    '        print(f"Running: {hypo.get("hypothesis_description")}")',
    '        eng.run_experiment(hypo)',
    '    elif args.command == "status":',
    '        t = ResultTracker()',
    '        print(f"Best BPB: {t.get_best_score():.6f}")',
    '        print("History:")',
    '        print(t.get_history_summary())',
    '',
    'if __name__ == "__main__":',
    '    main()'
])
