#!/usr/bin/env python3
"""构建 self-contained dashboard.html。

流程：
1. 读取契约 references/file-contract.json，校验 ALIASES 与契约一致。
2. 读取源码 assets/dashboard.html。
3. 在生成文件顶部记录版本和生成命令。
4. 输出到 assets/dashboard.html（原地覆盖，确定性构建）。

本脚本确保：
- canonical/alias 路径按同一份机器契约解析（CI 检查文档表格和机器契约一致）。
- 构建产物大小可控。
- CSP 中 connect-src 'none' 不被移除。
- 无外部 src/href 资源依赖。

运行：python scripts/build_dashboard.py
"""

import json
import os
import re
import sys
from datetime import datetime, timezone

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONTRACT_PATH = os.path.join(ROOT, "references", "file-contract.json")
DASHBOARD_PATH = os.path.join(ROOT, "assets", "dashboard.html")
BUILD_CMD = "python scripts/build_dashboard.py"


def load_contract():
    with open(CONTRACT_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def read_dashboard():
    with open(DASHBOARD_PATH, "r", encoding="utf-8") as f:
        return f.read()


def check_aliases_match(html, contract):
    """检查 HTML 中的 ALIASES 与契约完全一致（key 集合 + 每条 value）。"""
    aliases = contract.get("aliases", {})
    m = re.search(r"const ALIASES\s*=\s*\{([^}]*)\}", html, re.DOTALL)
    if not m:
        print("[build] 警告：未找到 ALIASES 对象")
        return False
    body = m.group(1)
    html_aliases = {}
    for km in re.finditer(r"'([^']+)':\s*\[([^\]]*)\]", body):
        html_aliases[km.group(1)] = re.findall(r"'([^']*)'", km.group(2))

    contract_keys = set(aliases.keys())
    html_keys = set(html_aliases.keys())
    missing = contract_keys - html_keys
    extra = html_keys - contract_keys
    if missing:
        print(f"[build] 警告：ALIASES 缺少契约中的 key：{sorted(missing)}")
    if extra:
        print(f"[build] 警告：ALIASES 有多余的 key：{sorted(extra)}")
    # 值比对（catch value drift，如 story/ 前缀不一致）
    value_drift = []
    for k in contract_keys & html_keys:
        if html_aliases[k] != list(aliases[k]):
            value_drift.append((k, html_aliases[k], list(aliases[k])))
    for k, hv, cv in value_drift:
        print(f"[build] 警告：ALIASES 值漂移 {k}：HTML={hv} 契约={cv}")
    return not missing and not extra and not value_drift


def check_no_external_deps(html):
    """检查无外部 src/href 资源依赖。"""
    # 查找 src= 或 href= 中指向外部资源（非 data: 非 # 非 javascript:）
    external = re.findall(r'(?:src|href)\s*=\s*["\']([^"\']+)["\']', html)
    bad = [u for u in external if u.startswith("http://") or u.startswith("https://")]
    if bad:
        print(f"[build] 错误：发现外部资源依赖：{bad}")
        return False
    return True


def check_csp(html):
    """检查 CSP 中 connect-src 'none' 不被移除。"""
    if "connect-src 'none'" not in " ".join(html.split()):
        print("[build] 错误：CSP 中 connect-src 'none' 被移除")
        return False
    return True


STAMP_RE = re.compile(r"/\* \[build\] generated by [^\n]*\*/\n?")


def add_build_stamp(html):
    """在 <script> 顶部写入构建时间戳和命令（幂等：先清除旧戳记，避免堆叠）。"""
    html = STAMP_RE.sub("", html)
    stamp = f"/* [build] generated by {BUILD_CMD} at {datetime.now(timezone.utc).isoformat()} */"
    # 在第一个 <script> 后插入
    html = html.replace("<script>\n", f"<script>\n{stamp}\n", 1)
    return html


def main():
    contract = load_contract()
    html = read_dashboard()

    ok = True
    ok = check_aliases_match(html, contract) and ok
    ok = check_no_external_deps(html) and ok
    ok = check_csp(html) and ok

    # 确定性构建：添加构建戳
    html = add_build_stamp(html)

    with open(DASHBOARD_PATH, "w", encoding="utf-8") as f:
        f.write(html)

    size_kb = len(html.encode("utf-8")) / 1024
    print(f"[build] 已生成 assets/dashboard.html ({size_kb:.1f} KB)")

    if not ok:
        print("[build] 构建完成，但有警告（见上方）。")
        sys.exit(0)  # 警告不阻断，仅报告
    print("[build] 构建成功，全部检查通过。")


if __name__ == "__main__":
    main()
