#!/usr/bin/env bash
# build-issue-body.sh — Generate a standard issue body for template updates.
#
# Usage:
#   build-issue-body.sh <file-path> <version> <languages-added> [wiki-url]
#
# Example:
#   build-issue-body.sh kb-templates/common-responses.md v1.1 "French, Korean" \
#     "https://open.feishu.cn/wiki/abc123"

set -euo pipefail

FILE="${1:?Usage: $0 <file-path> <version> <languages> [wiki-url]}"
VERSION="${2:?Missing version}"
LANGS="${3:?Missing languages}"
WIKI_URL="${4:-N/A}"
DATE=$(date +%Y-%m-%d)

# Extract categories from the file
CATEGORIES=$(grep '^## [0-9]' "$FILE" | sed 's/^## //' | paste -sd', ' -)

cat <<EOF
## 📝 Template Update: $VERSION

**Date:** $DATE
**File:** \`$FILE\`
**Languages added:** $LANGS

### Changes

- Added translations for **$LANGS** across all template categories
- Categories covered: $CATEGORIES
- Version bumped to **$VERSION**

### Feishu Wiki

$WIKI_URL

### Checklist

- [x] Local template updated
- [x] Changelog updated
- [x] Synced to Feishu Wiki
- [ ] Reviewed by native speaker (recommended)
- [ ] Committed and pushed

---
*Auto-generated by multilingual-kb-sync skill*
EOF
