#!/usr/bin/env bash
# create-github-issue.sh — Create a GitHub issue for KB template update
# Usage: GITHUB_TOKEN=xxx GITHUB_REPO=owner/repo bash create-github-issue.sh <file.md> <changelog>
set -euo pipefail

FILE="${1:?Usage: $0 <file.md> <changelog>}"
CHANGELOG="${2:?Usage: $0 <file.md> <changelog>}"
REPO="${GITHUB_REPO:?GITHUB_REPO required (owner/repo)}"
TOKEN="${GITHUB_TOKEN:-}"

# Extract metadata
LAST_UPDATED=$(grep -oP '(?<=最后更新 \| ).*' "$FILE" | head -1 | xargs)
LANGS=$(grep -oP '(?<=支持语言 \| ).*' "$FILE" | head -1 | xargs)
TEMPLATE_COUNT=$(grep -oP '(?<=模板数量 \| ).*' "$FILE" | head -1 | xargs)

TITLE="[i18n] Add new language translations to common-responses.md"

BODY="## 📋 Update Summary

$CHANGELOG

## 📊 Metadata

| Item | Value |
|------|-------|
| File | \`kb-templates/common-responses.md\` |
| Supported Languages | $LANGS |
| Template Count | $TEMPLATE_COUNT |
| Last Updated | $LAST_UPDATED |

## ✅ Checklist

- [x] Translations added for all template sections
- [x] Metadata table updated
- [ ] Synced to Feishu Wiki
- [ ] Reviewed by native speakers (recommended)

## 🔗 Related

- Local file: \`kb-templates/common-responses.md\`
- Skill: \`multilingual-kb-sync\`

---
*Auto-generated by multilingual-kb-sync skill*"

if command -v gh &>/dev/null && gh auth status &>/dev/null; then
  echo "📝 Creating issue via gh CLI..."
  ISSUE_URL=$(gh issue create --repo "$REPO" --title "$TITLE" --body "$BODY")
  echo "✅ Issue created: $ISSUE_URL"
elif [ -n "$TOKEN" ]; then
  echo "📝 Creating issue via GitHub API..."
  RESP=$(curl -s -X POST "https://api.github.com/repos/$REPO/issues" \
    -H "Authorization: token $TOKEN" \
    -H 'Accept: application/vnd.github+json' \
    -d "$(jq -n --arg t "$TITLE" --arg b "$BODY" '{title:$t,body:$b}')")
  ISSUE_URL=$(echo "$RESP" | jq -r '.html_url // empty')
  if [ -n "$ISSUE_URL" ]; then
    echo "✅ Issue created: $ISSUE_URL"
  else
    echo "❌ Failed: $RESP" >&2
    exit 1
  fi
else
  echo "⚠️  No gh CLI or GITHUB_TOKEN found. Please create the issue manually:"
  echo ""
  echo "  Title: $TITLE"
  echo "  Repo:  $REPO"
  echo ""
  echo "--- Body ---"
  echo "$BODY"
fi
