#!/usr/bin/env bash
set -euo pipefail

# GOG Dormant Game Cleanup
# Finds installed GOG games not played in the last N days,
# emails a summary, and adds each to Apple Reminders.

CUTOFF_DAYS="${1:-30}"
LIBRARY_FILE="${2:-}"
ACCOUNT="${3:-personal}"
REMINDERS_LIST="${4:-Gaming}"
DRY_RUN="${DRY_RUN:-0}"

if [[ -z "$LIBRARY_FILE" ]]; then
  echo "Usage: gog_dormant_cleanup.sh <cutoff_days> <library_json> [himalaya_account] [reminders_list]" >&2
  exit 1
fi

if ! command -v jq &>/dev/null; then
  echo "jq is required but not installed" >&2; exit 1
fi

# ── 1. Find dormant installed games ──
CUTOFF_EPOCH=$(date -d "-${CUTOFF_DAYS} days" +%s 2>/dev/null || python3 -c "
import datetime,sys; print(int((datetime.datetime.now()-datetime.timedelta(days=int(sys.argv[1]))).timestamp()))" "$CUTOFF_DAYS")

dormant=$(jq -r --argjson cutoff "$CUTOFF_EPOCH" '
  .games
  | map(select(.installed == true))
  | map(select(
      (.last_played // "1970-01-01T00:00:00Z")
      | split(".")[0]
      | strptime("%Y-%m-%dT%H:%M:%S")
      | mktime < $cutoff
    ))
  | sort_by(.last_played // "0000")
  | .[]
  | "\(.name)\t\(.last_played // "never")\t\(.install_path // "N/A")"
' "$LIBRARY_FILE")

if [[ -z "$dormant" ]]; then
  echo "No dormant games found (all installed games played within ${CUTOFF_DAYS} days)."
  exit 0
fi

# ── 2. Build email body ──
count=$(echo "$dormant" | wc -l)
subject="🎮 GOG Dormant Games Report — ${count} game(s) idle ${CUTOFF_DAYS}+ days"

{
  echo "$subject"
  echo ""
  echo "The following installed GOG games have not been played in the last ${CUTOFF_DAYS} days."
  echo "Consider uninstalling to free up disk space."
  echo ""
  printf "%-40s %-22s %s\n" "GAME" "LAST PLAYED" "INSTALL PATH"
  printf '%.0s-' {1..100}; echo
  echo "$dormant" | while IFS=$'\t' read -r name last path; do
    printf "%-40s %-22s %s\n" "$name" "$last" "$path"
  done
  echo ""
  echo "Generated by gog-dormant-cleanup on $(date -Iseconds)"
} > /tmp/gog_dormant_email.txt

body=$(cat /tmp/gog_dormant_email.txt)

# ── 3. Send email via himalaya ──
if [[ "$DRY_RUN" == "1" ]]; then
  echo "[DRY RUN] Would send email:"
  echo "$body"
else
  if command -v himalaya &>/dev/null; then
    himalaya message write \
      --account "$ACCOUNT" \
      -H "Subject:${subject}" \
      -H "To:$(himalaya account list --account "$ACCOUNT" --output json 2>/dev/null | jq -r '.[0].email // .email // empty' 2>/dev/null || echo 'self')" \
      "$body" || {
        # Fallback: pipe as template
        {
          echo "Subject: $subject"
          echo ""
          echo "$body"
        } | himalaya template send --account "$ACCOUNT"
      }
    echo "Email sent to personal account."
  else
    echo "himalaya not found; email not sent. Body saved to /tmp/gog_dormant_email.txt"
  fi
fi

# ── 4. Add to Apple Reminders ──
if [[ "$DRY_RUN" == "1" ]]; then
  echo "[DRY RUN] Would add reminders to list '$REMINDERS_LIST':"
  echo "$dormant" | while IFS=$'\t' read -r name last _; do
    echo "  - Consider uninstalling: $name (last: $last)"
  done
else
  if command -v remindctl &>/dev/null; then
    # Ensure list exists
    remindctl list "$REMINDERS_LIST" --create 2>/dev/null || true

    echo "$dormant" | while IFS=$'\t' read -r name last _; do
      remindctl add --title "Consider uninstalling: $name (last played: $last)" --list "$REMINDERS_LIST" 2>/dev/null && \
        echo "Reminder added: $name" || \
        echo "Failed to add reminder for: $name"
    done
  else
    echo "remindctl not found; reminders not created."
  fi
fi

echo ""
echo "Done. ${count} dormant game(s) processed."