#!/usr/bin/env bash
# Install chromedriver with the SAME version as installed Google Chrome (Linux x64).
# Selenium attach still needs chromedriver (even when Chrome is already open).
#
# Default install dir: first writable of /usr/local/bin, else ~/.local/bin (no sudo).
# Writes scripts/chromedriver.env for xhs_publish.sh / verify_chrome_stack.sh.
#
# Override:
#   CHROME_VERSION=148.0.7778.215 bash install_chromedriver.sh
#   CHROMEDRIVER_INSTALL_DIR=/usr/local/bin   # use: sudo env CHROMEDRIVER_INSTALL_DIR=... bash ...

set -euo pipefail

# v2: cp to ~/.local/bin for non-root (no GNU install to /usr/local)
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=skill_paths.sh
source "$SCRIPT_DIR/skill_paths.sh"
SCRIPTS_DIR="$(resolve_skill_scripts_dir "$SCRIPT_DIR")"
echo "install_chromedriver.sh v2 (script: $SCRIPT_DIR/$(basename "$0"))"
echo "Skill scripts dir: $SCRIPTS_DIR"

resolve_install_dir() {
  if [[ -n "${CHROMEDRIVER_INSTALL_DIR:-}" ]]; then
    echo "$CHROMEDRIVER_INSTALL_DIR"
    return
  fi
  # Non-root: always user dir (avoids Permission denied on /usr/local/bin).
  if [[ "$(id -u)" -ne 0 ]]; then
    echo "${HOME}/.local/bin"
    return
  fi
  echo "/usr/local/bin"
}

INSTALL_DIR="$(resolve_install_dir)"
mkdir -p "$INSTALL_DIR"

CHROME_BIN=""
for candidate in google-chrome-stable google-chrome chromium-browser chromium; do
  if command -v "$candidate" >/dev/null 2>&1; then
    CHROME_BIN="$candidate"
    break
  fi
done

if [[ -n "${CHROME_VERSION:-}" ]]; then
  FULL_VERSION="$CHROME_VERSION"
  echo "Using CHROME_VERSION=$FULL_VERSION"
elif [[ -n "$CHROME_BIN" ]]; then
  FULL_VERSION=$("$CHROME_BIN" --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+' | head -1)
else
  echo "Chrome not found on PATH. Install Chrome first, e.g.:" >&2
  echo "  sudo dnf install -y https://dl.google.com/linux/chrome/rpm/stable/x86_64/google-chrome-stable-*.rpm" >&2
  echo "Or set CHROME_VERSION=148.0.7778.215 bash $0" >&2
  exit 1
fi

if [[ -z "$FULL_VERSION" ]]; then
  echo "Cannot parse Chrome version." >&2
  exit 1
fi

ZIP_URL="https://storage.googleapis.com/chrome-for-testing-public/${FULL_VERSION}/linux64/chromedriver-linux64.zip"
TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

echo "Chrome version: $FULL_VERSION"
echo "Install to:   $INSTALL_DIR/chromedriver"
if [[ "$INSTALL_DIR" == /usr/local/bin ]] && [[ ! -w "$INSTALL_DIR" ]]; then
  echo "WARN: /usr/local/bin is not writable — use sudo or let this script use ~/.local/bin:" >&2
  echo "  sudo env CHROMEDRIVER_INSTALL_DIR=/usr/local/bin bash $0" >&2
fi
echo "Downloading: $ZIP_URL"

if ! curl -fL "$ZIP_URL" -o "$TMPDIR/chromedriver.zip"; then
  echo "Download failed for version $FULL_VERSION." >&2
  echo "Pick the build that matches: $("$CHROME_BIN" --version 2>/dev/null || echo 'your chrome')" >&2
  echo "  https://googlechromelabs.github.io/chrome-for-testing/" >&2
  exit 1
fi

if ! command -v unzip >/dev/null 2>&1; then
  echo "unzip is required. On RHEL/Fedora: sudo dnf install -y unzip" >&2
  exit 1
fi

unzip -o -q "$TMPDIR/chromedriver.zip" -d "$TMPDIR"
DEST="$INSTALL_DIR/chromedriver"
cp -f "$TMPDIR/chromedriver-linux64/chromedriver" "$DEST"
chmod 755 "$DEST"

ENV_FILE="$SCRIPTS_DIR/chromedriver.env"
cat >"$ENV_FILE" <<EOF
# Auto-generated by install_chromedriver.sh — sourced by xhs_publish.sh
export CHROMEDRIVER_PATH=$DEST
EOF
chmod 644 "$ENV_FILE"

echo ""
echo "Installed: $DEST"
"$DEST" --version
echo "Wrote:     $ENV_FILE"
echo ""
if [[ "$INSTALL_DIR" == "${HOME}/.local/bin" ]]; then
  echo "Optional (chromedriver in all shells):"
  echo "  export PATH=\"\$HOME/.local/bin:\$PATH\""
  echo ""
fi
echo "xhs_publish.sh loads chromedriver.env automatically."
echo ""

if [[ -f "$SCRIPTS_DIR/verify_chrome_stack.sh" ]]; then
  bash "$SCRIPTS_DIR/verify_chrome_stack.sh" || true
else
  echo "WARN: verify_chrome_stack.sh not found under $SCRIPTS_DIR (install OK; chromedriver is ready)."
fi

if [[ -f "$SCRIPTS_DIR/xhs_publish.sh" ]]; then
  echo "Run: bash $SCRIPTS_DIR/xhs_publish.sh --check --json"
fi
