/**
 * Core backup orchestration for backup skill
 */

import { exec } from 'child_process';
import { promisify } from 'util';
import fs from 'fs';
import path from 'path';

import * as git from './git.js';
import * as lfs from './lfs.js';

const execAsync = promisify(exec);

const DOT = process.env.OPENCLAW_DIR || process.env.HOME + '/.openclaw';
const LOCK_FILE = `${DOT}/.backup.lock`;

/**
 * Generate .gitignore content dynamically.
 *
 * PRINCIPLE: Only ignore clearly harmless runtime artifacts.
 * Everything else — user data, configs, credentials, knowledge bases,
 * agent memory, scripts — must be backed up. No exceptions for open-source.
 *
 * Ignore (harmless, rebuildable or transient):
 *   .git/              — git repo itself
 *   logs/              — runtime logs
 *   canvas/*            — canvas runtime state
 *   media/             — uploaded files (can re-upload)
 *   npm/               — npm packages (npm install rebuilds)
 *   node_modules/    — skill dependencies (ignored at any depth)
 *   __pycache__/     — python bytecode cache
 *   .cache/          — generic cache
 *   dreaming/        — short-term memory dream state (transient)
 *   cron/runs/         — cron execution history (transient, not definitions)
 *   *.tmp, *.bak, .DS_Store — OS noise
 *   .backup.lock       — runtime lock file
 *
 * Back up everything else (if in doubt, back it up).
 */
function generateGitignore() {
  const lines = ['# Generated by OpenClaw Backup Skill — do not edit manually', ''];

  // === Always-ignore: git repo itself ===
  lines.push('# Git repository');
  lines.push('.git/');
  lines.push('');

  // === Always-ignore: transient / rebuildable runtime artifacts ===
  // These are auto-detected because even harmless dirs may not exist on all installs.
  const topLevelDirs = (() => {
    try {
      return fs.readdirSync(DOT).filter(name => {
        try { return fs.statSync(path.join(DOT, name)).isDirectory(); }
        catch { return false; }
      });
    } catch { return []; }
  })();

  const transientDirs = {
    'logs':     'Runtime log files (rebuildable)',
    'canvas':   'Canvas runtime state (rebuildable)',
    'media':    'Uploaded media files (can re-upload)',
    'npm':      'NPM packages directory (npm install rebuilds)',
  };

  for (const [dir, desc] of Object.entries(transientDirs)) {
    if (topLevelDirs.includes(dir)) {
      lines.push(`# ${desc}`);
      lines.push(`${dir}/`);
      lines.push('');
    }
  }

  // === Always-ignore: cron run history (transient executions, not definitions) ===
  if (topLevelDirs.includes('cron')) {
    lines.push('# Cron execution history (transient — job definitions are in skills)');
    lines.push('cron/runs/');
    lines.push('');
  }

  // === Always-ignore: broad transient patterns (any depth) ===
  lines.push('# Node modules (rebuildable via npm install / pip install)');
  lines.push('**/node_modules/');
  lines.push('');

  lines.push('# Python bytecode cache');
  lines.push('**/__pycache__/');
  lines.push('');

  lines.push('# Generic cache directories');
  lines.push('**/.cache/');
  lines.push('');

  lines.push('# Short-term memory / dreaming state (transient, regenerated by OpenClaw)');
  lines.push('**/dreaming/');
  lines.push('**/.dreams/');
  lines.push('');

  // === Always-ignore: OS / editor noise ===
  lines.push('# OS and editor noise');
  lines.push('*.tmp');
  lines.push('*.bak');
  lines.push('*.last-good');
  lines.push('.DS_Store');
  lines.push('');

  // === Always-ignore: runtime lock file ===
  lines.push('# Backup lock (managed at runtime — never commit this)');
  lines.push('.backup.lock');
  lines.push('');

  // === NOTE: Everything else is BACKED UP ===
  lines.push('# === BACKED UP (do not ignore) ===');
  lines.push('# The following are intentionally NOT ignored because they contain');
  lines.push('# user data, credentials, configurations, or are not rebuildable:');
  lines.push('#');
  lines.push('#   agents/         — Agent configurations and auth profiles');
  lines.push('#   credentials/    — Channel credentials (keys, tokens)');
  lines.push('#   identity/       — Device identity keys');
  lines.push('#   kb/             — Knowledge base (user docs + vector DB)');
  lines.push('#   lts/            — Long-term scripts (cleanup, OOM protection)');
  lines.push('#   openclaw.json   — Core configuration with tokens');
  lines.push('#   skills/         — Installed skills and their configs');
  lines.push('#   workspace-* /   — Agent workspaces, memory, and learnings');
  lines.push('#   **/.learnings/  — Agent self-improvement logs');
  lines.push('#   **/.openclaw/   — Per-workspace OpenClaw state');
  lines.push('#   And all other directories not listed above');

  return lines.join('\n');
}

/**
 * Run the full backup flow.
 *
 * Lock strategy: atomic mkdir-based lock.
 * - Tries to mkdir(LOCK_FILE) — succeeds only if lock is free
 * - If mkdir fails (EEXIST), checks if lock holder is still alive
 * - Stale locks (dead holder) are forcibly removed and re-acquired
 * - Lock is always released via finally{} block using rmdir
 */
export async function runBackup({ dryRun = false } = {}) {
  // 0. Acquire lock (mkdir atomic, pid-tracked)
  if (!acquireLock()) {
    throw new Error('Backup already in progress (lock held). Try again later.');
  }

  try {
    const config = await loadConfig();
    const token = process.env.OPENCLAW_BACKUP_GIT_TOKEN;

    // 1. Ensure .gitignore exists and is staged
    await writeGitignore();

    // 2. Init repo and remote
    await git.initRepo(config.repo, token);

    // 3. Init LFS
    const lfsInstalled = await lfs.isLfsInstalled();
    if (lfsInstalled) {
      await lfs.lfsInit();
    }

    // 4. Stage all
    await git.stageAll();

    // 5. Check diff
    const changed = await git.hasChanges();
    if (!changed) {
      console.log('No changes to backup.');
      return { skipped: true };
    }

    // 6. Commit all staged changes (excludes RESTORE.md — not staged yet)
    await git.commit();

    // 7. Get the committed hash, write RESTORE.md with that hash, stage it
    const commit = await git.currentCommit();
    await generateRestoreMd(commit);
    await git.stageRestoreMd();

    // 8. Commit RESTORE.md as a separate commit (avoids amend complexity)
    await git.commit();

    // 9. Get the final commit hash (after the second commit)
    const finalCommit = await git.currentCommit();

    // 10. Push with retry
    await git.push(config.repo, token, config.push_retries, config.push_retry_interval_ms);

    return { success: true, commit: finalCommit };

  } catch (err) {
    // Release lock before re-throwing
    throw err;
  } finally {
    // Always release lock
    releaseLock();
  }
}

/**
 * Get backup status (last commit, time, etc.)
 */
export async function getBackupStatus() {
  const config = await loadConfig();

  const isRepo = await git.isGitRepo();
  if (!isRepo) {
    return { status: 'not_initialized' };
  }

  const commit = await git.currentCommit();
  if (!commit) {
    return { status: 'no_commits' };
  }

  try {
    const { stdout } = await execAsync(
      `git log -1 --format="%ci"`,
      { cwd: DOT }
    );
    const lastTime = stdout.trim();

    return {
      status: 'ok',
      lastCommit: commit,
      lastTime,
      repo: config.repo,
    };
  } catch {
    return { status: 'unknown', lastCommit: commit };
  }
}

/**
 * Acquire lock using atomic mkdir.
 * Returns true if lock acquired, false if already held by another process.
 */
function acquireLock() {
  try {
    // Atomic: only succeeds if LOCK_FILE does not exist as a directory
    fs.mkdirSync(LOCK_FILE, { recursive: false });
    // Write our pid into the lock so we can be identified
    fs.writeFileSync(path.join(LOCK_FILE, 'pid'), String(process.pid));
    return true;
  } catch (err) {
    if (err.code === 'EEXIST') {
      // Lock exists — check if holder is still alive
      const pidFile = path.join(LOCK_FILE, 'pid');
      try {
        const holderPid = parseInt(fs.readFileSync(pidFile, 'utf8').trim(), 10);
        try {
          // Signal 0 — check if process exists without sending signal
          process.kill(holderPid, 0);
          // Process still alive, lock is legitimately held
          return false;
        } catch {
          // Stale lock — holder is dead, take over
          console.warn(`Stale lock detected (PID ${holderPid} dead). Taking over.`);
          try {
            fs.rmSync(LOCK_FILE, { recursive: true });
            fs.mkdirSync(LOCK_FILE, { recursive: false });
            fs.writeFileSync(path.join(LOCK_FILE, 'pid'), String(process.pid));
            return true;
          } catch {
            return false;
          }
        }
      } catch {
        // Cannot read pid — stale lock, take over
        try {
          fs.rmSync(LOCK_FILE, { recursive: true });
          fs.mkdirSync(LOCK_FILE, { recursive: false });
          fs.writeFileSync(path.join(LOCK_FILE, 'pid'), String(process.pid));
          return true;
        } catch {
          return false;
        }
      }
    }
    return false;
  }
}

/**
 * Release lock (rmdir the lock directory).
 * Idempotent — safe to call multiple times.
 */
function releaseLock() {
  try {
    fs.rmSync(LOCK_FILE, { recursive: true });
  } catch { /* ignore */ }
}

/**
 * Write .gitignore and stage it.
 */
async function writeGitignore() {
  const giPath = path.join(DOT, '.gitignore');
  const content = generateGitignore();
  fs.writeFileSync(giPath, content);
  // Stage .gitignore so changes are included in the backup commit
  await execAsync(`git add .gitignore`, { cwd: DOT });
}

async function loadConfig() {
  const configPath = path.join(DOT, 'skills/claw-saver/config.json');
  try {
    return JSON.parse(fs.readFileSync(configPath, 'utf8'));
  } catch {
    // Fallback — will use default values if config is missing
    return {
      repo: 'https://example.com/user/repo',
      push_retries: 3,
      push_retry_interval_ms: 60000,
    };
  }
}

async function generateRestoreMd(commit) {
  const now = new Date().toISOString();
  const config = await loadConfig();
  const repoUrl = config.repo || 'https://example.com/user/repo';
  const content = `# Restore Guide

Last backup: ${now}
Commit: ${commit}

## To restore from this backup:

1. Clone the repository:
   \`\`\`bash
   git clone ${repoUrl} /tmp/openclaw-restore
   \`\`\`

2. Checkout this commit:
   \`\`\`bash
   cd /tmp/openclaw-restore
   git checkout ${commit}
   \`\`\`

3. Copy files to ~/.openclaw:
   \`\`\`bash
   cp -r /tmp/openclaw-restore/* ~/.openclaw/
   \`\`\`

4. Restart OpenClaw Gateway:
   \`\`\`bash
   openclaw gateway restart
   \`\`\`

## Excluded from backup (too large or private)

These are NOT in the backup and must be restored separately:
- Session logs (agents/*/sessions/*.jsonl)
- Node modules (skills/*/node_modules/, npm/node_modules/)
- Canvas files
- Media files (inbound images, etc.)
- Knowledge base data (kb/)
- Credentials and keys
- Vault files

## After restore

After copying files back, restart the gateway to apply changes.

Generated by OpenClaw Backup Skill
`;

  const restorePath = path.join(DOT, 'RESTORE.md');
  fs.writeFileSync(restorePath, content.replace('https://example.com/user/repo', config.repo));
}
