#!/usr/bin/env bash
# Hot update application (without deleting stack).
# Via Cloud Assistant RunCommand on ECS: stop old process -> pull new artifacts -> start new process.
# Does not destroy/recreate any cloud resources; public IP remains unchanged.
#
# Prerequisites:
#   - .qwencloud-deploy state file exists in project root (generated by initial deployment)
#   - New artifacts uploaded to OSS (Agent calls upload_artifacts.py then passes URL)
#
# Required environment variables:
#   BACKEND_URL   OSS signed URL for new backend artifacts (empty = don't update backend)
# Optional environment variables:
#   FRONTEND_URL  OSS signed URL for new frontend artifacts (empty = don't update frontend)
#   PROJECT_ROOT  Project root directory (default .)
#
# Usage:
#   BACKEND_URL="https://..." FRONTEND_URL="https://..." bash scripts/update_app.sh
#
# stdout: JSON {"status":"success","updated_instances":["i-xxx"],"invoke_ids":["t-xxx"]}
# Exit codes: 0=success 1=failure 2=state file error 3=RunCommand execution failed
set -uo pipefail

ROOT="${PROJECT_ROOT:-.}"
STATE="$ROOT/.qwencloud-deploy"

[ -f "$STATE" ] || { echo "Cannot find $STATE, please complete initial deployment first" >&2; exit 2; }

# Parse state file
EVAL=$(python3 - "$STATE" <<'PY'
import json, shlex, sys
path = sys.argv[1]
try:
    with open(path, encoding="utf-8") as f:
        d = json.load(f)
except Exception as e:
    sys.stderr.write(f"State file parse failed: {e}\n"); sys.exit(2)

def need(k):
    v = d.get(k)
    if not v:
        sys.stderr.write(f"State file missing field '{k}'\n"); sys.exit(2)
    return v

region = need("region_id")
outputs = d.get("outputs") or {}
ecs_raw = outputs.get("ecs_instance_ids") or []
if isinstance(ecs_raw, str):
    ecs_raw = [x.strip() for x in ecs_raw.split(",") if x.strip()]
if not ecs_raw:
    sys.stderr.write("State file missing outputs.ecs_instance_ids\n"); sys.exit(2)

app_type = d.get("app_type") or ""
nginx_mode = d.get("nginx_mode") or ""
bucket = d.get("artifact_bucket") or ""
public_ip = outputs.get("public_ip") or ""

vals = {
    "REGION": region,
    "ECS_IDS": " ".join(ecs_raw),
    "APP_TYPE": app_type,
    "NGINX_MODE": nginx_mode,
    "BUCKET": bucket,
    "PUBLIC_IP": public_ip,
}
for k, v in vals.items():
    print(f"{k}={shlex.quote(str(v))}")
PY
) || { echo "[update] Failed to read state file" >&2; exit 2; }
eval "$EVAL"

BACKEND_URL="${BACKEND_URL:-}"
FRONTEND_URL="${FRONTEND_URL:-}"

if [ -z "$BACKEND_URL" ] && [ -z "$FRONTEND_URL" ]; then
  echo "[update] Both BACKEND_URL and FRONTEND_URL are empty, nothing to update" >&2
  exit 1
fi

# Generate update script to execute on ECS
# Improved: download+verify+install deps -> stop service -> atomic swap -> start, minimizing downtime
gen_update_script() {
  local script="#!/bin/bash
set -euxo pipefail
exec >> /var/log/qwencloud-update.log 2>&1
echo \"[\$(date -u +%FT%TZ)] === qwencloud update start ===\"


"
  # Update backend
  if [ -n "$BACKEND_URL" ]; then
    script+="
# === Phase 1: Preparation — download, extract, install deps (service keeps running, no impact on production) ===
echo '[update] Phase 1: Download+verify new artifacts (service unaffected)'

STAGING_DIR=/opt/qwencloud.staging
rm -rf \"\$STAGING_DIR\"
mkdir -p \"\$STAGING_DIR\"

echo '[update] Pulling new backend artifacts to staging'
curl -fsSL '$BACKEND_URL' -o \"\$STAGING_DIR/backend.tar.gz\"
tar -tzf \"\$STAGING_DIR/backend.tar.gz\" >/dev/null
echo '[update] Artifact integrity check passed'
tar -xzf \"\$STAGING_DIR/backend.tar.gz\" -C \"\$STAGING_DIR\"
rm -f \"\$STAGING_DIR/backend.tar.gz\"
echo '[update] New artifacts downloaded+extracted successfully'
"
    # Runtime dependency pre-installation (done in staging, no impact on live service)
    case "$APP_TYPE" in
      binary-python)
        script+="
cd \"\$STAGING_DIR\"
if [ -f requirements.txt ]; then
  echo '[update] Pre-downloading Python dependencies (service unaffected)'
  mkdir -p /tmp/qwencloud-pip-cache
  python3 -m pip download -d /tmp/qwencloud-pip-cache -r requirements.txt
  echo '[update] Python dependency pre-download complete'
fi
"
        ;;
      binary-node)
        script+="
cd \"\$STAGING_DIR\"
if [ -f package.json ]; then
  echo '[update] Pre-installing Node dependencies (staging, service unaffected)'
  rm -rf node_modules
  yarn install --production
  echo '[update] Node dependency installation complete'
fi
"
        ;;
    esac
    script+="
# === Phase 2: Atomic swap — stop, replace, start (downtime minimized) ===
echo '[update] Phase 2: New artifacts ready, executing atomic swap'
echo '[update] Stopping backend service'
systemctl stop qwencloud-app || true

echo '[update] Atomic replacement of backend directory'
rm -rf /opt/qwencloud
mv \"\$STAGING_DIR\" /opt/qwencloud
"
    # Python needs fast offline install with cached packages after swap
    case "$APP_TYPE" in
      binary-python)
        script+="
cd /opt/qwencloud
if [ -f requirements.txt ] && [ -d /tmp/qwencloud-pip-cache ]; then
  echo '[update] Offline installing Python dependencies (using pre-downloaded cache)'
  python3 -m pip install --no-cache-dir --no-index --find-links /tmp/qwencloud-pip-cache -r requirements.txt
  rm -rf /tmp/qwencloud-pip-cache
fi
"
        ;;
    esac
    script+="
echo '[update] Starting backend service'
systemctl restart qwencloud-app

echo '[update] Health check...'
APP_PORT=\$(sed -n 's/^Environment=PORT=//p' /etc/systemd/system/qwencloud-app.service 2>/dev/null | head -1)
APP_PORT=\${APP_PORT:-8080}
sleep 3
HEALTHY=0
for _i in $(seq 1 15); do
  if curl -sf -o /dev/null --max-time 5 \"http://localhost:\${APP_PORT}/\"; then
    HEALTHY=1
    break
  fi
  sleep 2
done
if [ \"\$HEALTHY\" -eq 0 ]; then
  echo '[update] Health check failed'
  exit 1
fi
echo '[update] Health check passed'
"
  fi

  # Update frontend
  if [ -n "$FRONTEND_URL" ]; then
    script+="
# === Frontend update: download to staging and verify, then atomic swap (Nginx reload, zero downtime) ===
echo '[update] Downloading new frontend artifacts to staging'
FRONTEND_STAGING=/var/www/frontend.staging
rm -rf \"\$FRONTEND_STAGING\"
mkdir -p \"\$FRONTEND_STAGING\"
curl -fsSL '$FRONTEND_URL' -o /tmp/frontend.tar.gz
tar -tzf /tmp/frontend.tar.gz >/dev/null
echo '[update] Frontend artifact integrity check passed'
tar -xzf /tmp/frontend.tar.gz -C \"\$FRONTEND_STAGING\" --strip-components=0
rm -f /tmp/frontend.tar.gz
echo '[update] Frontend artifacts downloaded+extracted successfully'

echo '[update] Atomic replacement of frontend directory'
rm -rf /var/www/frontend
mv \"\$FRONTEND_STAGING\" /var/www/frontend
nginx -t && systemctl reload nginx
echo '[update] Frontend update complete'
"
  fi

  script+="
rm -rf /opt/qwencloud.staging /var/www/frontend.staging /tmp/qwencloud-pip-cache 2>/dev/null || true
echo \"[\$(date -u +%FT%TZ)] === qwencloud update complete ===\"
"
  echo "$script"
}

UPDATE_SCRIPT=$(gen_update_script)

# Execute RunCommand
run_on_instance() {
  local instance_id="$1"
  echo "[update] Sending update command to $instance_id ..." >&2

  local out
  out=$(PAGER=cat aliyun ecs RunCommand \
    --RegionId "$REGION" \
    --InstanceId.1 "$instance_id" \
    --Type RunShellScript \
    --CommandContent "$UPDATE_SCRIPT" \
    --Timeout 300 2>&1)
  local code=$?
  if [ $code -ne 0 ]; then
    echo "[update] RunCommand failed: $out" >&2
    return 3
  fi

  local invoke_id
  invoke_id=$(echo "$out" | python3 -c "import json,sys;print(json.load(sys.stdin).get('InvokeId',''))" 2>/dev/null)
  if [ -z "$invoke_id" ]; then
    echo "[update] Cannot parse InvokeId: $out" >&2
    return 3
  fi
  echo "[update] InvokeId=${invoke_id}, waiting for execution..." >&2

  # Poll execution status (max 5 minutes)
  local deadline=$(( $(date +%s) + 300 ))
  local status=""
  local wait=2
  # Poll status FIRST (short commands finish quickly), then back off up to 10s.
  while [ $(date +%s) -lt $deadline ]; do
    local inv_out
    inv_out=$(PAGER=cat aliyun ecs DescribeInvocations \
      --RegionId "$REGION" \
      --InvokeId "$invoke_id" 2>&1) || { sleep "$wait"; continue; }

    status=$(echo "$inv_out" | python3 -c "
import json, sys
try:
    d = json.load(sys.stdin)
    invs = d.get('Invocations', {}).get('Invocation', [])
    if invs:
        instances = invs[0].get('InvokeInstances', {}).get('InvokeInstance', [])
        if instances:
            print(instances[0].get('InvocationStatus', ''))
except: pass
" 2>/dev/null)

    case "$status" in
      Finished|Success)
        echo "[update] $instance_id update complete" >&2
        # Get output logs
        local result_out
        result_out=$(PAGER=cat aliyun ecs DescribeInvocationResults \
          --RegionId "$REGION" \
          --InvokeId "$invoke_id" 2>&1)
        local output_b64
        output_b64=$(echo "$result_out" | python3 -c "
import json, sys
try:
    d = json.load(sys.stdin)
    items = d.get('Invocation', {}).get('InvocationResults', {}).get('InvocationResult', [])
    if items: print(items[0].get('Output', ''))
except: pass
" 2>/dev/null)
        if [ -n "$output_b64" ]; then
          echo "[update] === Remote output ===" >&2
          echo "$output_b64" | base64 -d 2>/dev/null >&2 || true
          echo "[update] === End remote output ===" >&2
        fi
        echo "$invoke_id"
        return 0
        ;;
      Failed)
        echo "[update] $instance_id execution failed" >&2
        # Get error output
        local err_out
        err_out=$(PAGER=cat aliyun ecs DescribeInvocationResults \
          --RegionId "$REGION" \
          --InvokeId "$invoke_id" 2>&1)
        local err_b64
        err_b64=$(echo "$err_out" | python3 -c "
import json, sys
try:
    d = json.load(sys.stdin)
    items = d.get('Invocation', {}).get('InvocationResults', {}).get('InvocationResult', [])
    if items: print(items[0].get('Output', ''))
except: pass
" 2>/dev/null)
        if [ -n "$err_b64" ]; then
          echo "[update] === Error output ===" >&2
          echo "$err_b64" | base64 -d 2>/dev/null >&2 || true
        fi
        return 3
        ;;
      *)
        echo "[update] $(date -u +%H:%M:%S) $instance_id status=$status" >&2
        ;;
    esac
    sleep "$wait"; [ "$wait" -lt 10 ] && wait=$((wait + 2))
  done

  echo "[update] $instance_id execution timed out (5 minutes)" >&2
  return 3
}

# Execute update
UPDATED_INSTANCES=()
INVOKE_IDS=()
FAILED=0

IFS=' ' read -r -a ECS_ARRAY <<< "$ECS_IDS"

# Single-node update
ecs="${ECS_ARRAY[0]}"
invoke_id=$(run_on_instance "$ecs") || FAILED=1
if [ $FAILED -eq 0 ]; then
  UPDATED_INSTANCES+=("$ecs")
  INVOKE_IDS+=("$invoke_id")
fi

if [ $FAILED -ne 0 ]; then
  echo "[update] Update failed" >&2
  exit 3
fi

# Update state file: append updated_at
python3 - "$STATE" "$BACKEND_URL" "$FRONTEND_URL" <<'PY'
import json, sys
from datetime import datetime, timezone

path, new_backend, new_frontend = sys.argv[1:4]
with open(path, encoding="utf-8") as f:
    state = json.load(f)

state["current_artifact_urls"] = {}
if new_backend:
    state["current_artifact_urls"]["backend_url"] = new_backend
if new_frontend:
    state["current_artifact_urls"]["frontend_url"] = new_frontend

state["updated_at"] = datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")
state.pop("previous_artifact_urls", None)

with open(path, "w", encoding="utf-8") as f:
    json.dump(state, f, ensure_ascii=False, indent=2)
sys.stderr.write(f"[update] State file updated with updated_at\n")
PY

# Output result JSON
python3 - "${UPDATED_INSTANCES[@]}" -- "${INVOKE_IDS[@]}" <<'PY'
import json, sys
args = sys.argv[1:]
sep = args.index("--")
instances = args[:sep]
invoke_ids = args[sep+1:]
print(json.dumps({
    "status": "success",
    "updated_instances": instances,
    "invoke_ids": invoke_ids,
}, ensure_ascii=False))
PY
