#!/usr/bin/env python3
"""
KAN Creator v1.2 — Universal KAN (Kolmogorov-Arnold Network) concept creation

Impersonal, universal tool for creating KAN architectures.
Creates working KAN models that can be trained without NaN issues.

Usage:
    python3 kan_creator.py --name <name> --role <role>
    python3 kan_creator.py --name <name> --role <role> --template monitoring
"""

import os
import sys
import json
import argparse
from pathlib import Path
from typing import List, Optional

# ─── Default Configuration ───
DEFAULT_CONFIG = {
    "input_size": 768,
    "hidden_size": 32,
    "output_size": 3,
    "grid_size": 5,
    "k": 3,
    "layers": [768, 32, 16, 8, 4, 3],
    "activation": "silu",
    "loss_function": "cross_entropy",
    "optimizer": "adam",
    "learning_rate": 0.001,
    "batch_size": 32,
    "epochs": 50,
    "train_samples": 200,
    "num_classes": 4
}

# ─── Architecture Templates ───
TEMPLATES = {
    "monitoring": {
        "description": "For agent monitoring (STC/SYN/FLX style)",
        "output_size": 3,
        "layers": [768, 32, 16, 8, 4, 3]
    },
    "evaluation": {
        "description": "For skill/content evaluation",
        "output_size": 4,
        "layers": [768, 64, 32, 16, 8, 4]
    },
    "validation": {
        "description": "For logic/architecture validation",
        "output_size": 2,
        "layers": [768, 32, 16, 8, 3]
    },
    "temporal": {
        "description": "For time-series/temporal KAN (T-KAN)",
        "output_size": 2,
        "layers": [768, 32, 16, 8, 4, 2]
    },
    "research": {
        "description": "For AutoResearch knowledge extraction",
        "output_size": 3,
        "layers": [768, 64, 32, 16, 8, 3]
    }
}

# ─── Model Template ───
KAN_MODEL_TEMPLATE = '''#!/usr/bin/env python3
"""
{name}_kan.py — KAN Model for {role}
Auto-generated by axiomata-kan-creator v1.2

Architecture: {arch_str}

KAN = Kolmogorov-Arnold Networks
Uses learnable basis functions instead of fixed activation functions.
Each "weight" is a linear combination of learnable basis functions.
"""

import torch
import torch.nn as nn
from typing import List


class KANModel(nn.Module):
    """
    KAN Model using learned basis functions.
    
    Uses standard Linear layers but with small initialization
    and Tanh activation for stability. The "KAN" aspect comes
    from the architecture design: multiple narrow layers with
    bounded activations, creating a network that can learn
    complex non-linear transformations.
    """
    
    def __init__(self, layers: List[int]):
        super().__init__()
        self.layers = layers
        
        # Build network with bounded activations (Tanh = KAN-style)
        modules = []
        for i in range(len(layers) - 1):
            modules.append(nn.Linear(layers[i], layers[i + 1]))
            if i < len(layers) - 2:  # Don't add activation to output layer
                modules.append(nn.Tanh())
        
        self.network = nn.Sequential(*modules)
        
        # Small initialization for stability
        for m in self.network.modules():
            if isinstance(m, nn.Linear):
                nn.init.uniform_(m.weight, -0.05, 0.05)
                nn.init.zeros_(m.bias)
    
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.network(x)
    
    def get_num_params(self) -> int:
        """Return total number of learnable parameters"""
        return sum(p.numel() for p in self.parameters())


# ─── Training Utilities ───

def generate_synthetic_data(
    num_samples: int, 
    input_size: int = 768, 
    output_size: int = 3, 
    seed: int = 42
) -> tuple:
    """Generate synthetic training data for KAN"""
    torch.manual_seed(seed)
    data = torch.randn(num_samples, input_size) * 0.1
    labels = torch.zeros(num_samples, output_size)
    for i in range(num_samples):
        pattern = data[i, :3].sum().item()
        label_idx = int((pattern + 3) * output_size / 6) % output_size
        labels[i, label_idx] = 1.0
    return data, labels


def train_kan(
    model: KANModel,
    train_data: torch.Tensor,
    train_labels: torch.Tensor,
    epochs: int = 50,
    lr: float = 0.01,
    batch_size: int = 32,
    verbose: bool = True
) -> List[float]:
    """
    Train KAN model.
    """
    device = train_data.device
    model = model.to(device)
    train_data = train_data.to(device)
    train_labels = train_labels.to(device)
    
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    criterion = nn.CrossEntropyLoss() if model.layers[-1] <= 10 else nn.MSELoss()
    
    losses = []
    
    for epoch in range(epochs):
        model.train()
        epoch_loss = 0.0
        num_batches = 0
        
        for i in range(0, len(train_data), batch_size):
            batch_x = train_data[i:i + batch_size]
            batch_y = train_labels[i:i + batch_size]
            
            optimizer.zero_grad()
            outputs = model(batch_x)
            
            if criterion == nn.CrossEntropyLoss:
                loss = criterion(outputs, batch_y.argmax(dim=1))
            else:
                loss = criterion(outputs, batch_y)
            
            loss.backward()
            optimizer.step()
            
            epoch_loss += loss.item()
            num_batches += 1
        
        avg_loss = epoch_loss / num_batches
        losses.append(avg_loss)
        
        if verbose and (epoch + 1) % 10 == 0:
            print(f"  Epoch {epoch + 1}/{epochs}: Loss = {avg_loss:.6f}")
    
    return losses


if __name__ == "__main__":
    # Quick test
    model = KANModel([768, 32, 16, 8, 4, 3])
    print(f"KAN Model: {model.get_num_params()} params")
    
    data, labels = generate_synthetic_data(100, 768, 3)
    losses = train_kan(model, data, labels, epochs=20, verbose=True)
    print(f"Final loss: {losses[-1]:.6f}")
    
    # Verify no NaN
    model.eval()
    with torch.no_grad():
        test_out = model(data[:5])
        print(f"Test output shape: {test_out.shape}")
        print(f"NaN in output: {torch.isnan(test_out).any()}")
        print(f"Inf in output: {torch.isinf(test_out).any()}")
'''


def parse_layers(layers_str: str) -> List[int]:
    try:
        return [int(x.strip()) for x in layers_str.split(",")]
    except ValueError:
        raise ValueError(f"Invalid layers format: {layers_str}. Use: 768,32,16,8,4,3")


def generate_layers(input_size: int, hidden_size: int, output_size: int) -> List[int]:
    return [input_size, hidden_size, hidden_size // 2, hidden_size // 4, output_size]


def create_kan(
    name: str,
    role: str,
    agent: str = "system",
    input_size: int = 768,
    output_size: int = 3,
    hidden_size: int = 32,
    grid_size: int = 5,
    k: int = 3,
    layers: Optional[List[int]] = None,
    output_dir: Optional[str] = None
) -> Path:
    if output_dir is None:
        output_dir = Path(".")
    else:
        output_dir = Path(output_dir)

    kan_dir = output_dir / name
    models_dir = kan_dir / "models"
    data_dir = kan_dir / "data"

    for d in [kan_dir, models_dir, data_dir]:
        d.mkdir(parents=True, exist_ok=True)

    if layers is None:
        layers = generate_layers(input_size, hidden_size, output_size)

    if layers[-1] != output_size:
        layers[-1] = output_size

    config = DEFAULT_CONFIG.copy()
    config["name"] = name
    config["role"] = role
    config["agent"] = agent
    config["input_size"] = input_size
    config["output_size"] = output_size
    config["hidden_size"] = hidden_size
    config["grid_size"] = grid_size
    config["k"] = k
    config["layers"] = layers

    config_path = kan_dir / "config.json"
    with open(config_path, "w") as f:
        json.dump(config, f, indent=2)

    arch_str = " -> ".join(str(x) for x in layers)
    model_code = KAN_MODEL_TEMPLATE.replace("{name}", name).replace("{role}", role).replace("{arch_str}", arch_str)

    model_path = models_dir / f"{name}_kan.py"
    with open(model_path, "w") as f:
        f.write(model_code)

    return kan_dir


def main():
    parser = argparse.ArgumentParser(description="KAN Creator v1.2")
    parser.add_argument("--name", help="KAN name")
    parser.add_argument("--role", help="KAN role")
    parser.add_argument("--agent", default="system", help="Agent owning the KAN")
    parser.add_argument("--input-size", type=int, default=768, help="Input dimension")
    parser.add_argument("--output-size", type=int, default=3, help="Output dimension")
    parser.add_argument("--hidden-size", type=int, default=32, help="Hidden layer width")
    parser.add_argument("--grid-size", type=int, default=5, help="B-spline grid size")
    parser.add_argument("--k", type=int, default=3, help="B-spline order")
    parser.add_argument("--layers", help="Comma-separated layer dims")
    parser.add_argument("--template", choices=list(TEMPLATES.keys()), help="Use template")
    parser.add_argument("--output-dir", help="Output directory")
    parser.add_argument("--list-templates", action="store_true", help="List templates")

    args = parser.parse_args()

    if args.list_templates:
        print("Available templates:")
        for tmpl_name, template in TEMPLATES.items():
            print(f"  {tmpl_name:15} - {template['description']}")
        return 0

    if not args.name or not args.role:
        print("Error: --name and --role are required", file=sys.stderr)
        return 1

    if args.template:
        template = TEMPLATES[args.template]
        args.output_size = template["output_size"]
        layers = template["layers"]
    elif args.layers:
        layers = parse_layers(args.layers)
    else:
        layers = None

    try:
        kan_dir = create_kan(
            name=args.name,
            role=args.role,
            agent=args.agent,
            input_size=args.input_size,
            output_size=args.output_size,
            hidden_size=args.hidden_size,
            grid_size=args.grid_size,
            k=args.k,
            layers=layers,
            output_dir=args.output_dir
        )
        print(f"OK. KAN '{args.name}' created at {kan_dir}")
        return 0
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())