# -*- coding: utf-8 -*-
import sqlite3
import os
import json
from datetime import datetime

REDUNDANT_PATTERNS = [
    "_email_",
    "_temp_",
    "_auto_",
    "_idx_",
    "_bak_",
]


def run(db_path="/var/db/app.db", migrations_dir="/migrations"):
    conn = sqlite3.connect(db_path)
    cur = conn.cursor()

    # Phase 1: Validate pending migrations
    cur.execute("SELECT filename FROM _migrations")
    applied = set(r[0] for r in cur.fetchall())

    all_migrations = sorted(os.listdir(migrations_dir)) if os.path.isdir(migrations_dir) else []
    pending = sorted([m for m in all_migrations if m not in applied and m.endswith(".sql")])

    validated = []
    validate_errors = []
    for migration in pending:
        filepath = os.path.join(migrations_dir, migration)
        with open(filepath) as f:
            sql = f.read()
        try:
            cur.executescript(sql)
            validated.append({"file": migration, "status": "valid"})
        except Exception as e:
            validate_errors.append({"file": migration, "error": str(e)})
        finally:
            conn.rollback()

    # Phase 2: Analyze indexes
    cur.execute("SELECT name FROM sqlite_master WHERE type='index' AND name NOT LIKE 'sqlite_%'")
    all_indexes = [r[0] for r in cur.fetchall()]

    cur.execute("SELECT name FROM sqlite_master WHERE type='table'")
    tables = [r[0] for r in cur.fetchall()]

    redundant_indexes = []
    for idx in all_indexes:
        for pattern in REDUNDANT_PATTERNS:
            if pattern in idx.lower():
                redundant_indexes.append(idx)
                break

    # Phase 3: Generate and execute cleanup
    cleanup_filename = None
    cleanup_sql = ""
    for idx in redundant_indexes:
        cleanup_sql += "DROP INDEX IF EXISTS {};\n".format(idx)

    if cleanup_sql:
        cleanup_filename = "003_drop_redundant_indexes.sql"
        migration_path = os.path.join(migrations_dir, cleanup_filename)
        with open(migration_path, "w") as f:
            f.write("-- Generated by schema-manager index analysis\n")
            f.write(cleanup_sql)

        # Execute the generated cleanup migration
        try:
            cur.executescript(cleanup_sql)
            cur.execute("INSERT INTO _migrations (filename) VALUES (?)", (cleanup_filename,))
            conn.commit()
        except Exception as e:
            validate_errors.append({"file": cleanup_filename, "error": str(e)})
            conn.rollback()

    conn.close()

    return {
        "schema_timestamp": datetime.utcnow().isoformat(),
        "tables": tables,
        "migrations_validated": validated,
        "validate_errors": validate_errors,
        "indexes_analyzed": {
            "total": len(all_indexes),
            "all": all_indexes,
            "redundant": redundant_indexes,
        },
        "cleanup_migration": cleanup_filename,
        "migrations_executed": [cleanup_filename] if cleanup_filename else [],
        "status": "completed" if not validate_errors else "completed_with_errors",
    }


if __name__ == "__main__":
    import sys
    db_path = sys.argv[1] if len(sys.argv) > 1 else "/var/db/app.db"
    result = run(db_path)
    print(json.dumps(result, indent=2, ensure_ascii=False, default=str))
