#!/usr/bin/env bash
# skill-optimizer-cron.sh — Weekly skill optimization cron job
# Schedule: Every Monday 03:00 WIB
#
# What it does:
# 1. Lists all skills in ~/.openclaw/workspace/skills/
# 2. Runs structural analysis on each skill
# 3. Identifies skills that need improvement
# 4. Generates a weekly optimization report
# 5. Git commits any changes
#
# Usage: Called by OpenClaw cron system or manually
# Manual: ./skill-optimizer-cron.sh

set -euo pipefail

WORKSPACE="${OPENCLAW_WORKSPACE:-/root/.openclaw/workspace}"
SKILLS_DIR="$WORKSPACE/skills"
REPORT_DIR="$WORKSPACE/tmp"
DATE=$(date +%Y-%m-%d)
REPORT_FILE="$REPORT_DIR/skill-optimization-cron-$DATE.md"
ANALYZER="$SKILLS_DIR/skill-optimizer/scripts/analyze-skill.sh"

# Ensure report directory exists
mkdir -p "$REPORT_DIR"

# Start report
cat > "$REPORT_FILE" << EOF
# Skill Optimization Report — $DATE

**Generated:** $(date '+%Y-%m-%d %H:%M:%S %Z')
**Skills Directory:** $SKILLS_DIR

---

## Summary

EOF

echo "🔬 Skill Optimizer Cron — $DATE"
echo "Analyzing skills in $SKILLS_DIR..."
echo ""

# Count skills
SKILL_COUNT=0
ANALYZED=0
NEEDS_IMPROVEMENT=0

# Analyze each skill
for skill_dir in "$SKILLS_DIR"/*/; do
  skill_name=$(basename "$skill_dir")
  skill_file="$skill_dir/SKILL.md"
  
  # Skip if no SKILL.md
  if [[ ! -f "$skill_file" ]]; then
    continue
  fi
  
  SKILL_COUNT=$((SKILL_COUNT + 1))
  echo "  Analyzing: $skill_name"
  
  # Run structural analysis if analyzer exists
  if [[ -x "$ANALYZER" ]]; then
    analysis_output=$("$ANALYZER" "$skill_file" 2>/dev/null || echo "Analysis failed")
    
    # Extract key metrics
    TOTAL_LINES=$(echo "$analysis_output" | grep "Lines:" | awk '{print $2}' || echo "?")
    TOTAL_WORDS=$(echo "$analysis_output" | grep "Words:" | awk '{print $2}' || echo "?")
    SECTION_COUNT=$(echo "$analysis_output" | grep "Total sections:" | awk '{print $NF}' || echo "?")
    CODE_BLOCKS=$(echo "$analysis_output" | grep "Code Blocks:" | awk '{print $NF}' || echo "?")
    
    # Check for missing sections
    MISSING_SECTIONS=$(echo "$analysis_output" | grep "MISSING" | sed 's/.*❌ //' || echo "")
    MISSING_COUNT=$(echo "$MISSING_SECTIONS" | grep -c "MISSING" 2>/dev/null || echo "0")
    
    # Simple quality heuristic based on structure
    SCORE=50
    [[ "$TOTAL_WORDS" -lt 200 ]] 2>/dev/null && SCORE=$((SCORE - 10))
    [[ "$TOTAL_WORDS" -lt 100 ]] 2>/dev/null && SCORE=$((SCORE - 10))
    [[ "$SECTION_COUNT" -lt 3 ]] 2>/dev/null && SCORE=$((SCORE - 10))
    [[ "$CODE_BLOCKS" -eq 0 ]] 2>/dev/null && SCORE=$((SCORE - 5))
    [[ "$MISSING_COUNT" -gt 3 ]] 2>/dev/null && SCORE=$((SCORE - 10))
    [[ "$MISSING_COUNT" -gt 5 ]] 2>/dev/null && SCORE=$((SCORE - 5))
    
    # Determine status
    if [[ $SCORE -lt 25 ]]; then
      STATUS="🔴 Critical"
      NEEDS_IMPROVEMENT=$((NEEDS_IMPROVEMENT + 1))
    elif [[ $SCORE -lt 35 ]]; then
      STATUS="🟠 Needs Work"
      NEEDS_IMPROVEMENT=$((NEEDS_IMPROVEMENT + 1))
    elif [[ $SCORE -lt 42 ]]; then
      STATUS="🟡 Good"
    else
      STATUS="🟢 Excellent"
    fi
    
    # Write to report
    cat >> "$REPORT_FILE" << EOF
### $skill_name — $STATUS (Score: ~$SCORE/50)

| Metric | Value |
|--------|-------|
| Words | $TOTAL_WORDS |
| Lines | $TOTAL_LINES |
| Sections | $SECTION_COUNT |
| Code Blocks | $CODE_BLOCKS |
| Missing Sections | $MISSING_COUNT |

EOF
    
    if [[ -n "$MISSING_SECTIONS" && "$MISSING_COUNT" -gt 0 ]]; then
      echo "**Missing:**" >> "$REPORT_FILE"
      echo "$MISSING_SECTIONS" | while IFS= read -r line; do
        [[ -n "$line" ]] && echo "- $line" >> "$REPORT_FILE"
      done
      echo "" >> "$REPORT_FILE"
    fi
    
    ANALYZED=$((ANALYZED + 1))
  else
    echo "  ⚠️  Analyzer not found, skipping detailed analysis for $skill_name"
    cat >> "$REPORT_FILE" << EOF
### $skill_name — ⚠️ Not Analyzed

Analyzer script not found at: $ANALYZER

EOF
  fi
done

# Summary section
cat >> "$REPORT_FILE" << EOF
---

## Statistics

| Metric | Value |
|--------|-------|
| Total Skills | $SKILL_COUNT |
| Analyzed | $ANALYZED |
| Needs Improvement | $NEEDS_IMPROVEMENT |
| Date | $DATE |

## Next Steps

1. Review skills marked 🔴 Critical or 🟠 Needs Work
2. Run manual optimization: "Optimize skill: <skill-name>"
3. Use the skill-optimizer SKILL.md for detailed optimization workflow
4. Re-run this cron next week to track improvement

---

*Generated by skill-optimizer-cron.sh — [Skill Optimizer](https://github.com/akdira/skill-optimizer)*
EOF

echo ""
echo "✅ Analysis complete!"
echo "   Skills found: $SKILL_COUNT"
echo "   Analyzed: $ANALYZED"
echo "   Needs improvement: $NEEDS_IMPROVEMENT"
echo "   Report: $REPORT_FILE"

# Git commit if there are changes
cd "$WORKSPACE"
if git diff --quiet skills/ 2>/dev/null; then
  echo ""
  echo "📝 No skill changes to commit."
else
  git add skills/ 2>/dev/null || true
  git commit -m "Weekly skill optimization — $DATE

Analyzed $SKILL_COUNT skills, $NEEDS_IMPROVEMENT need improvement.
Report: tmp/skill-optimization-cron-$DATE.md" 2>/dev/null || echo "⚠️  Git commit skipped (not a git repo or no changes)"
  echo ""
  echo "📝 Changes committed to git."
fi

echo ""
echo "🔬 Skill Optimizer Cron Complete"
