"""Notification system — file output + optional SMTP email with HTML templates."""

from __future__ import annotations

import logging
import smtplib
from datetime import datetime, timezone
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from pathlib import Path

from mpt_portfolio.config import Config, EmailConfig
from mpt_portfolio.utils import get_portfolio_reports_dir, timestamp_str

logger = logging.getLogger(__name__)

_EMAIL_CSS = """\
body { font-family: Arial, Helvetica, sans-serif; color: #333; background: #f8f9fa;
       margin: 0; padding: 0; line-height: 1.6; }
.header { background: #1a1a2e; color: white; padding: 24px; text-align: center; }
.header h1 { margin: 0; font-size: 1.5em; font-weight: 600; }
.header .meta { color: #a0aec0; font-size: 0.85em; margin-top: 4px; }
.container { max-width: 600px; margin: 0 auto; padding: 20px; }
.card { background: white; border-radius: 6px; padding: 16px; margin: 12px 0;
        border: 1px solid #e2e8f0; }
table { width: 100%; border-collapse: collapse; }
th, td { padding: 8px 12px; text-align: left; border-bottom: 1px solid #e2e8f0; }
th { background: #f7fafc; font-weight: 600; color: #4a5568; font-size: 0.85em;
     text-transform: uppercase; letter-spacing: 0.5px; }
.metric-grid { text-align: center; padding: 12px 0; }
.metric-box { display: inline-block; text-align: center; padding: 10px 18px;
              margin: 4px; background: white; border-radius: 6px;
              border: 1px solid #e2e8f0; }
.metric-value { font-size: 1.3em; font-weight: 700; color: #1a1a2e; }
.metric-label { font-size: 0.75em; color: #718096; text-transform: uppercase;
                letter-spacing: 0.5px; margin-top: 2px; }
.callout { background: #ebf8ff; border-left: 4px solid #3182ce;
           padding: 12px 16px; border-radius: 0 6px 6px 0; margin: 12px 0; }
.callout-warn { background: #fff5f5; border-left-color: #e53e3e; }
.callout strong { color: #2c5282; }
.callout-warn strong { color: #c53030; }
.positive { color: #38a169; }
.negative { color: #e53e3e; }
.footer { text-align: center; color: #a0aec0; font-size: 0.75em;
          padding: 16px; border-top: 1px solid #e2e8f0; margin-top: 20px; }
"""


def _wrap_email_html(title: str, subtitle: str, body_content: str) -> str:
    gen_date = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    return f"""\
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><style>{_EMAIL_CSS}</style></head>
<body>
<div class="header">
  <h1>{title}</h1>
  <div class="meta">{subtitle} &mdash; {gen_date}</div>
</div>
<div class="container">
{body_content}
</div>
<div class="footer">
  Generated by MPT Portfolio Optimizer.<br>
  This is not financial advice. Past performance does not guarantee future results.
</div>
</body>
</html>"""


def _metrics_html(metrics: list[tuple[str, str]]) -> str:
    boxes = "".join(
        f'<div class="metric-box">'
        f'<div class="metric-value">{val}</div>'
        f'<div class="metric-label">{label}</div></div>'
        for val, label in metrics
    )
    return f'<div class="metric-grid">{boxes}</div>'


def _table_html(headers: list[str], rows: list[list[str]]) -> str:
    hdr = "".join(f"<th>{h}</th>" for h in headers)
    body = ""
    for row in rows:
        cells = "".join(f"<td>{c}</td>" for c in row)
        body += f"<tr>{cells}</tr>\n"
    return (
        f'<div class="card"><table>\n'
        f"<thead><tr>{hdr}</tr></thead>\n"
        f"<tbody>{body}</tbody>\n"
        f"</table></div>"
    )


# ---------------------------------------------------------------------------
# Template builders — each returns (html_body, plain_text_body)
# ---------------------------------------------------------------------------

def _build_portfolio_created_email(
    portfolio_name: str,
    method: str,
    weights: dict,
    expected_return: float,
    volatility: float,
    sharpe: float,
    risk_free_rate: float,
    investment: float,
    quantities: dict,
) -> tuple[str, str]:
    metrics = _metrics_html([
        (f"{expected_return * 100:.2f}%", "Expected Return"),
        (f"{volatility * 100:.2f}%", "Volatility"),
        (f"{sharpe:.3f}", "Sharpe Ratio"),
        (f"{risk_free_rate * 100:.2f}%", "Risk-Free Rate"),
    ])

    headers = ["Asset", "Weight", "Price", "Shares"]
    rows = []
    for ticker, data in sorted(quantities.items(), key=lambda x: x[1]["weight"], reverse=True):
        rows.append([
            ticker,
            f"{data['weight'] * 100:.2f}%",
            f"${data['price']:,.2f}",
            str(data["whole_shares"]),
        ])

    total_cost = sum(d["whole_shares"] * d["price"] for d in quantities.values())
    residual = investment - total_cost

    body = (
        f"{metrics}\n"
        f"<h3>Portfolio Weights</h3>\n"
        f"{_table_html(headers, rows)}\n"
        f'<p style="color:#4a5568;font-size:0.9em;">'
        f"Investment: ${investment:,.2f} &nbsp;|&nbsp; "
        f"Residual cash: ${residual:,.2f}</p>"
    )
    html = _wrap_email_html(portfolio_name, f"Portfolio Created &mdash; {method}", body)

    plain_lines = [
        f"Portfolio Created: {portfolio_name}",
        f"Method: {method}",
        f"Expected Return: {expected_return:.2%}  |  Volatility: {volatility:.2%}  |  Sharpe: {sharpe:.3f}",
        f"Risk-Free Rate: {risk_free_rate:.2%}",
        "",
        "Weights:",
    ]
    for ticker, data in sorted(quantities.items(), key=lambda x: x[1]["weight"], reverse=True):
        plain_lines.append(
            f"  {ticker}: {data['weight']:.2%}  ${data['price']:,.2f}  {data['whole_shares']} shares"
        )
    plain_lines.append(f"\nInvestment: ${investment:,.2f}  |  Residual cash: ${residual:,.2f}")

    return html, "\n".join(plain_lines)


def _build_backtest_complete_email(
    portfolio_name: str,
    recommended_strategy: str,
    recommendation_reason: str,
    strategies: dict,
) -> tuple[str, str]:
    callout = (
        f'<div class="callout">'
        f"<strong>Recommended: {recommended_strategy}</strong><br>"
        f"{recommendation_reason}</div>"
    )

    headers = ["Strategy", "Return", "CAGR", "Sharpe", "Max DD", "Turnover", "Costs"]
    rows = []
    for name, s in strategies.items():
        rows.append([
            f"<strong>{name}</strong>" if name == recommended_strategy else name,
            f"{s['total_return']:.2%}",
            f"{s['cagr']:.2%}",
            f"{s['sharpe']:.3f}",
            f"{s['max_drawdown']:.2%}",
            f"{s['turnover']:.2%}",
            f"${s['costs']:,.2f}",
        ])

    body = f"{callout}\n<h3>Strategy Comparison</h3>\n{_table_html(headers, rows)}"
    html = _wrap_email_html(portfolio_name, "Backtest Complete", body)

    plain_lines = [
        f"Backtest Complete: {portfolio_name}",
        f"Recommended: {recommended_strategy}",
        f"Reason: {recommendation_reason}",
        "",
        f"{'Strategy':<15} {'Return':>8} {'CAGR':>8} {'Sharpe':>8} {'Max DD':>8}",
        "-" * 55,
    ]
    for name, s in strategies.items():
        marker = " *" if name == recommended_strategy else ""
        plain_lines.append(
            f"{name:<15} {s['total_return']:>7.2%} {s['cagr']:>7.2%} "
            f"{s['sharpe']:>7.3f} {s['max_drawdown']:>7.2%}{marker}"
        )

    return html, "\n".join(plain_lines)


def _build_rebalance_reminder_email(
    portfolio_name: str,
    needs_rebalance: bool,
    reason: str,
    max_drift: float,
    max_drift_asset: str,
    orders: list,
    estimated_cost: float,
) -> tuple[str, str]:
    if needs_rebalance:
        status_html = (
            f'<div class="callout callout-warn">'
            f"<strong>Rebalance Needed</strong><br>"
            f"{reason}<br>"
            f"Max drift: {max_drift:.2%} ({max_drift_asset})</div>"
        )

        headers = ["Action", "Asset", "Shares", "Amount", "Current", "Target"]
        rows = []
        for o in orders:
            action_color = "#38a169" if o.action == "BUY" else "#e53e3e"
            rows.append([
                f'<span style="color:{action_color};font-weight:bold">{o.action}</span>',
                o.ticker,
                str(o.shares_rounded),
                f"${abs(o.dollar_amount):,.2f}",
                f"{o.current_weight:.2%}",
                f"{o.target_weight:.2%}",
            ])

        body = (
            f"{status_html}\n"
            f"<h3>Recommended Orders</h3>\n"
            f"{_table_html(headers, rows)}\n"
            f'<p style="color:#4a5568;font-size:0.9em;">'
            f"Estimated transaction cost: ${estimated_cost:,.2f}</p>"
        )
    else:
        body = (
            f'<div class="callout">'
            f'<strong style="color:#38a169;">No Rebalance Needed</strong><br>'
            f"Max drift: {max_drift:.2%} ({max_drift_asset})</div>"
        )

    html = _wrap_email_html(portfolio_name, "Rebalance Check", body)

    plain_lines = [f"Rebalance Check: {portfolio_name}"]
    if needs_rebalance:
        plain_lines += [
            f"Status: REBALANCE NEEDED",
            f"Reason: {reason}",
            f"Max drift: {max_drift:.2%} ({max_drift_asset})",
            "",
            "Recommended Orders:",
        ]
        for o in orders:
            plain_lines.append(
                f"  {o.action} {o.ticker}: {o.shares_rounded} shares (${abs(o.dollar_amount):,.2f})"
            )
        plain_lines.append(f"\nEstimated cost: ${estimated_cost:,.2f}")
    else:
        plain_lines += [
            "Status: No rebalance needed",
            f"Max drift: {max_drift:.2%} ({max_drift_asset})",
        ]

    return html, "\n".join(plain_lines)


def _build_performance_report_email(
    portfolio_name: str,
    total_value: float,
    portfolio_return: float,
    benchmark_return: float | None,
    sharpe: float,
    cagr: float,
    max_drawdown: float,
    volatility: float,
    live_days: int,
    rebalance_count: int,
) -> tuple[str, str]:
    ret_class = "positive" if portfolio_return >= 0 else "negative"
    bm_str = f"Benchmark: {benchmark_return:.2%}" if benchmark_return is not None else ""
    summary = (
        f'<div class="callout">'
        f'<strong>Total Value: ${total_value:,.2f}</strong> &nbsp;|&nbsp; '
        f'Return: <span class="{ret_class}">{portfolio_return:.2%}</span>'
    )
    if bm_str:
        summary += f" &nbsp;|&nbsp; {bm_str}"
    summary += f"<br>Live: {live_days} days &nbsp;|&nbsp; Rebalances: {rebalance_count}</div>"

    metrics = _metrics_html([
        (f"{cagr * 100:.2f}%", "CAGR"),
        (f"{sharpe:.3f}", "Sharpe"),
        (f"{volatility * 100:.2f}%", "Volatility"),
        (f"{max_drawdown * 100:.2f}%", "Max Drawdown"),
    ])

    body = f"{summary}\n{metrics}"
    html = _wrap_email_html(portfolio_name, "Performance Report", body)

    plain_lines = [
        f"Performance Report: {portfolio_name}",
        f"Total Value: ${total_value:,.2f}",
        f"Return: {portfolio_return:.2%}",
    ]
    if benchmark_return is not None:
        plain_lines.append(f"Benchmark: {benchmark_return:.2%}")
    plain_lines += [
        f"CAGR: {cagr:.2%}  |  Sharpe: {sharpe:.3f}  |  Vol: {volatility:.2%}  |  Max DD: {max_drawdown:.2%}",
        f"Live: {live_days} days  |  Rebalances: {rebalance_count}",
    ]

    return html, "\n".join(plain_lines)


# ---------------------------------------------------------------------------
# Core dispatch
# ---------------------------------------------------------------------------

def notify_file(portfolio_name: str, subject: str, body: str) -> Path:
    """Write notification to a timestamped file."""
    reports_dir = get_portfolio_reports_dir(portfolio_name)
    path = reports_dir / f"notification_{timestamp_str()}.txt"
    content = f"Subject: {subject}\n{'=' * 60}\n\n{body}"
    path.write_text(content)
    logger.info(f"Notification saved: {path}")
    return path


def notify_email(
    email_config: EmailConfig,
    subject: str,
    html_body: str,
    plain_body: str,
    attachments: list[Path] | None = None,
) -> bool:
    """Send HTML email via SMTP. Returns True on success."""
    resolved = email_config.resolve_env()

    if not all([resolved.smtp_host, resolved.smtp_user, resolved.sender, resolved.recipients]):
        logger.warning("Email not configured — missing required fields.")
        return False

    msg = MIMEMultipart("mixed")
    msg["From"] = resolved.sender
    msg["To"] = ", ".join(resolved.recipients)
    msg["Subject"] = subject

    alt = MIMEMultipart("alternative")
    alt.attach(MIMEText(plain_body, "plain"))
    alt.attach(MIMEText(html_body, "html"))
    msg.attach(alt)

    if attachments:
        for filepath in attachments:
            if not filepath.exists():
                continue
            part = MIMEBase("application", "octet-stream")
            part.set_payload(filepath.read_bytes())
            encoders.encode_base64(part)
            part.add_header("Content-Disposition", f"attachment; filename={filepath.name}")
            msg.attach(part)

    try:
        with smtplib.SMTP(resolved.smtp_host, resolved.smtp_port) as server:
            if resolved.smtp_use_tls:
                server.starttls()
            if resolved.smtp_password:
                server.login(resolved.smtp_user, resolved.smtp_password)
            server.send_message(msg)
        logger.info(f"Email sent to {', '.join(resolved.recipients)}")
        return True
    except Exception as e:
        logger.error(f"Failed to send email: {e}")
        return False


def send_notification(
    portfolio_name: str,
    config: Config,
    subject: str,
    html_body: str,
    plain_body: str,
    attachments: list[Path] | None = None,
) -> None:
    """Dispatch notification based on config: file, email, or both."""
    method = config.notifications.method

    if method in ("file", "both"):
        notify_file(portfolio_name, subject, plain_body)

    if method in ("email", "both"):
        if config.email.enabled:
            notify_email(config.email, subject, html_body, plain_body, attachments)
        else:
            logger.debug("Email notifications not enabled; skipping.")


# ---------------------------------------------------------------------------
# High-level event dispatchers (called from CLI commands)
# ---------------------------------------------------------------------------

def notify_portfolio_created(
    portfolio_name: str,
    config: Config,
    method: str,
    weights: dict,
    expected_return: float,
    volatility: float,
    sharpe: float,
    risk_free_rate: float,
    investment: float,
    quantities: dict,
    html_report_path: Path | None = None,
) -> None:
    if not config.notifications.portfolio_created:
        return
    subject = f"Portfolio Created: {portfolio_name}"
    html_body, plain_body = _build_portfolio_created_email(
        portfolio_name, method, weights, expected_return, volatility,
        sharpe, risk_free_rate, investment, quantities,
    )
    attachments = [html_report_path] if html_report_path and html_report_path.exists() else None
    send_notification(portfolio_name, config, subject, html_body, plain_body, attachments)


def notify_backtest_complete(
    portfolio_name: str,
    config: Config,
    recommended_strategy: str,
    recommendation_reason: str,
    strategies: dict,
    html_report_path: Path | None = None,
) -> None:
    if not config.notifications.backtest_complete:
        return
    subject = f"Backtest Complete: {portfolio_name} — Recommended: {recommended_strategy}"
    html_body, plain_body = _build_backtest_complete_email(
        portfolio_name, recommended_strategy, recommendation_reason, strategies,
    )
    attachments = [html_report_path] if html_report_path and html_report_path.exists() else None
    send_notification(portfolio_name, config, subject, html_body, plain_body, attachments)


def notify_rebalance_reminder(
    portfolio_name: str,
    config: Config,
    needs_rebalance: bool,
    reason: str,
    max_drift: float,
    max_drift_asset: str,
    orders: list,
    estimated_cost: float,
) -> None:
    if not config.notifications.rebalance_reminder:
        return
    if needs_rebalance:
        subject = f"Rebalance Needed: {portfolio_name} (drift: {max_drift:.1%})"
    else:
        subject = f"Rebalance Check: {portfolio_name} — No Action Needed"
    html_body, plain_body = _build_rebalance_reminder_email(
        portfolio_name, needs_rebalance, reason,
        max_drift, max_drift_asset, orders, estimated_cost,
    )
    send_notification(portfolio_name, config, subject, html_body, plain_body)


def notify_performance_report(
    portfolio_name: str,
    config: Config,
    total_value: float,
    portfolio_return: float,
    benchmark_return: float | None,
    sharpe: float,
    cagr: float,
    max_drawdown: float,
    volatility: float,
    live_days: int,
    rebalance_count: int,
    html_report_path: Path | None = None,
) -> None:
    if not config.notifications.performance_report:
        return
    subject = f"Performance Report: {portfolio_name} ({portfolio_return:+.2%})"
    html_body, plain_body = _build_performance_report_email(
        portfolio_name, total_value, portfolio_return, benchmark_return,
        sharpe, cagr, max_drawdown, volatility, live_days, rebalance_count,
    )
    attachments = [html_report_path] if html_report_path and html_report_path.exists() else None
    send_notification(portfolio_name, config, subject, html_body, plain_body, attachments)
