#!/bin/bash
echo "=== 数字人能力检测 ==="
echo ""
echo "1. 飞影数字人（Coze商店）"
echo "   状态：待安装（需到Coze商店手动安装）"
echo "   用途：开篇/结尾动态数字人代替静态照片"
echo ""
echo "2. Kameo数字人"
echo "   状态：已安装（免费版15秒限制）"
echo "   用途：短片段数字人"
echo ""
echo "3. 百炼数字人"
echo "   状态：有API Key（0.9元/秒太贵）"
echo "   用途：高质量数字人（暂不启用）"
echo ""
echo "=== 建议 ==="
echo "优先安装飞影数字人（免费无限），然后自动替换视频生产线中的静态照片"
