#!/bin/bash
# Crypto Market Briefing Generator
# Generated by OpenClaw

# Set search query for latest crypto morning news
SEARCH_QUERY="global cryptocurrency market morning briefing today"

# 1. Search for latest crypto news
search_results=$(web_search --query="$SEARCH_QUERY" --count=3)

# 2. Extract top links and fetch content
top_link=$(echo "$search_results" | jq -r '.results[0].url')
top2_link=$(echo "$search_results" | jq -r '.results[1].url')
top3_link=$(echo "$search_results" | jq -r '.results[2].url')

content1=$(web_fetch --url="$top_link" --extract-mode=text --max-chars=500)
content2=$(web_fetch --url="$top2_link" --extract-mode=text --max-chars=300)
content3=$(web_fetch --url="$top3_link" --extract-mode=text --max-chars=200)

# 3. Structure the briefing
echo -e "📈 全球加密货币市场晨报 [$(date +%Y-%m-%d)]\n"
echo -e "---\n### 市场概览\n$content1\n"
echo -e "### 重点资产动态\n$content2\n"
echo -e "### 宏观/监管消息\n$content3\n"
echo -e "---\n### 风险提示\n crypto市场波动剧烈，本简报仅供参考，不构成投资建议。\n"
echo -e "---\n### 信息来源\n1. $top_link\n2. $top2_link\n3. $top3_link"
