"""Endpoint registry for linkfox-tiktok-shop-product (ERP /product APIs).

PRODUCT_ENDPOINTS["api_name"] = {
    "summary": "...",
    "method": "GET|POST|PUT|DELETE",
    "path": "product/...",
    "required": [...],
    "query_fields": [...],
    "body_fields": [...],
    "path_params": [...],
    "needs_shop_cipher": True/False,
    "doc_url": "...",
}
"""

from __future__ import annotations

from typing import Any, Dict, List

RESERVED_PARAM_KEYS = {
    "api",
    "openId",
    "ttsAccessToken",
    "region",
    "contentType",
    "body",
    "requestBody",
    "queryString",
    "skipDepCheck",
    "skipShopCipherResolve",
    "shop_id",
    "shopId",
}

PRODUCT_ENDPOINTS: Dict[str, Dict[str, Any]] = {
    "get_authorized_shops": {
        "summary": "Get Authorized Shops — 获取已授权店铺与 shop_cipher",
        "method": "GET",
        "path": "authorization/202309/shops",
        "required": [],
        "query_fields": [],
        "body_fields": [],
        "needs_shop_cipher": False,
        "response_key": "data",
        "doc_url": "https://partner.tiktokshop.com/docv2/page/get-authorized-shops-202309",
    },
    "check_listing_prerequisites": {
        "summary": "Check Listing Prerequisites — 刊登前置条件检查",
        "method": "GET",
        "path": "product/202312/prerequisites",
        "required": [],
        "query_fields": [],
        "body_fields": [],
        "needs_shop_cipher": True,
        "response_key": "data",
        "doc_url": "https://partner.tiktokshop.com/docv2/page/check-listing-prerequisites-202312",
    },
    "get_categories": {
        "summary": "Get Categories — 获取类目树",
        "method": "GET",
        "path": "product/202309/categories",
        "required": [],
        "query_fields": [
            "locale",
            "keyword",
            "category_version",
            "listing_platform",
            "include_prohibited_categories",
        ],
        "body_fields": [],
        "needs_shop_cipher": True,
        "response_key": "data",
        "doc_url": "https://partner.tiktokshop.com/docv2/page/get-categories-202309",
    },
    "get_category_rules": {
        "summary": "Get Category Rules — 获取类目规则",
        "method": "GET",
        "path": "product/202309/categories/{category_id}/rules",
        "required": ["category_id"],
        "path_params": ["category_id"],
        "query_fields": ["category_version", "locale"],
        "body_fields": [],
        "needs_shop_cipher": True,
        "response_key": "data",
        "doc_url": "https://partner.tiktokshop.com/docv2/page/get-category-rules-202309",
    },
    "get_attributes": {
        "summary": "Get Attributes — 获取类目属性",
        "method": "GET",
        "path": "product/202309/categories/{category_id}/attributes",
        "required": ["category_id"],
        "path_params": ["category_id"],
        "query_fields": ["locale", "category_version"],
        "body_fields": [],
        "needs_shop_cipher": True,
        "response_key": "data",
        "doc_url": "https://partner.tiktokshop.com/docv2/page/get-attributes-202309",
    },
    "recommend_category": {
        "summary": "Recommend Category — 推荐类目",
        "method": "POST",
        "path": "product/202309/categories/recommend",
        "required": [],
        "query_fields": [],
        "body_fields": [
            "product_title",
            "description",
            "images",
            "category_version",
            "listing_platform",
            "include_prohibited_categories",
            "locale",
        ],
        "needs_shop_cipher": True,
        "response_key": "data",
        "doc_url": "https://partner.tiktokshop.com/docv2/page/recommend-category-202309",
    },
    "get_brands": {
        "summary": "Get Brands — 获取品牌列表",
        "method": "GET",
        "path": "product/202309/brands",
        "required": ["page_size"],
        "defaults": {"page_size": 20},
        "query_fields": [
            "category_id",
            "is_authorized",
            "brand_name",
            "page_size",
            "page_token",
            "category_version",
        ],
        "body_fields": [],
        "needs_shop_cipher": True,
        "response_key": "data",
        "doc_url": "https://partner.tiktokshop.com/docv2/page/get-brands-202309",
    },
    "search_products": {
        "summary": "Search Products — 搜索店铺商品（202502）",
        "method": "POST",
        "path": "product/202502/products/search",
        "required": ["page_size"],
        "defaults": {"page_size": 20},
        "query_fields": ["page_size", "page_token"],
        "body_fields": [
            "status",
            "seller_skus",
            "create_time_ge",
            "create_time_le",
            "update_time_ge",
            "update_time_le",
            "category_version",
            "listing_quality_tiers",
            "listing_platforms",
            "audit_status",
            "sku_ids",
            "sns_filter",
            "return_draft_version",
            "locale",
        ],
        "needs_shop_cipher": True,
        "response_key": "data",
        "doc_url": "https://partner.tiktokshop.com/docv2/page/search-products-202502",
        "allow_empty_body": True,
    },
    "get_product": {
        "summary": "Get Product — 获取单个商品详情",
        "method": "GET",
        "path": "product/202309/products/{product_id}",
        "required": ["product_id"],
        "path_params": ["product_id"],
        "query_fields": [
            "return_under_review_version",
            "return_draft_version",
            "locale",
        ],
        "body_fields": [],
        "needs_shop_cipher": True,
        "response_key": "data",
        "doc_url": "https://partner.tiktokshop.com/docv2/page/get-product-202309",
    },
    "create_product": {
        "summary": "Create Product — 创建商品",
        "method": "POST",
        "path": "product/202309/products",
        "required": [],
        "query_fields": [],
        "body_fields": [
            "save_mode",
            "description",
            "category_id",
            "brand_id",
            "main_images",
            "skus",
            "title",
            "is_cod_allowed",
            "certifications",
            "package_dimensions",
            "product_attributes",
            "package_weight",
            "video",
            "external_product_id",
            "delivery_option_ids",
            "size_chart",
            "primary_combined_product_id",
            "is_not_for_sale",
            "category_version",
            "manufacturer_ids",
            "responsible_person_ids",
            "listing_platforms",
        ],
        "needs_shop_cipher": True,
        "response_key": "data",
        "doc_url": "https://partner.tiktokshop.com/docv2/page/create-product-202309",
    },
    "edit_product": {
        "summary": "Edit Product — 全量编辑商品",
        "method": "PUT",
        "path": "product/202309/products/{product_id}",
        "required": ["product_id"],
        "path_params": ["product_id"],
        "query_fields": [],
        "body_fields": [
            "description",
            "category_id",
            "brand_id",
            "main_images",
            "skus",
            "title",
            "is_cod_allowed",
            "certifications",
            "package_dimensions",
            "product_attributes",
            "package_weight",
            "video",
            "external_product_id",
            "delivery_option_ids",
            "size_chart",
            "category_version",
            "manufacturer_ids",
            "responsible_person_ids",
            "listing_platforms",
        ],
        "needs_shop_cipher": True,
        "response_key": "data",
        "doc_url": "https://partner.tiktokshop.com/docv2/page/edit-product-202309",
    },
    "partial_edit_product": {
        "summary": "Partial Edit Product — 部分编辑商品",
        "method": "POST",
        "path": "product/202309/products/{product_id}/partial_edit",
        "required": ["product_id"],
        "path_params": ["product_id"],
        "query_fields": [],
        "body_fields": [
            "save_mode",
            "description",
            "brand_id",
            "main_images",
            "skus",
            "title",
            "is_cod_allowed",
            "certifications",
            "package_weight",
            "product_attributes",
            "size_chart",
            "package_dimensions",
            "video",
            "external_product_id",
            "manufacturer_ids",
            "responsible_person_ids",
            "listing_platforms",
            "replicated_products",
            "subscribe_info_edit",
            "scheduled_sale",
        ],
        "needs_shop_cipher": True,
        "response_key": "data",
        "doc_url": "https://partner.tiktokshop.com/docv2/page/partial-edit-product-202309",
        "allow_empty_body": False,
    },
    "check_product_listing": {
        "summary": "Check Product Listing — 商品刊登校验",
        "method": "POST",
        "path": "product/202309/products/listing_check",
        "required": [],
        "query_fields": ["is_diagnosis_required"],
        "body_fields": [
            "description",
            "category_id",
            "brand_id",
            "main_images",
            "skus",
            "title",
            "is_cod_allowed",
            "certifications",
            "package_weight",
            "product_attributes",
            "size_chart",
            "package_dimensions",
            "external_product_id",
            "delivery_option_ids",
            "video",
            "primary_combined_product_id",
            "manufacturer_ids",
            "responsible_person_ids",
            "listing_platforms",
            "shipping_insurance_requirement",
        ],
        "needs_shop_cipher": True,
        "response_key": "data",
        "doc_url": "https://partner.tiktokshop.com/docv2/page/check-product-listing-202309",
    },
    "activate_product": {
        "summary": "Activate Product — 上架商品",
        "method": "POST",
        "path": "product/202309/products/activate",
        "required": [],
        "query_fields": [],
        "body_fields": ["product_ids", "listing_platforms"],
        "needs_shop_cipher": True,
        "response_key": "data",
        "doc_url": "https://partner.tiktokshop.com/docv2/page/activate-product-202309",
    },
    "deactivate_products": {
        "summary": "Deactivate Products — 下架商品",
        "method": "POST",
        "path": "product/202309/products/deactivate",
        "required": [],
        "query_fields": [],
        "body_fields": ["product_ids", "listing_platforms"],
        "needs_shop_cipher": True,
        "response_key": "data",
        "doc_url": "https://partner.tiktokshop.com/docv2/page/deactivate-products-202309",
    },
    "update_price": {
        "summary": "Update Price — 更新 SKU 价格",
        "method": "POST",
        "path": "product/202309/products/{product_id}/prices/update",
        "required": ["product_id"],
        "path_params": ["product_id"],
        "query_fields": [],
        "body_fields": ["skus"],
        "needs_shop_cipher": True,
        "response_key": "data",
        "doc_url": "https://partner.tiktokshop.com/docv2/page/update-price-202309",
    },
    "update_inventory": {
        "summary": "Update Inventory — 更新 SKU 库存",
        "method": "POST",
        "path": "product/202309/products/{product_id}/inventory/update",
        "required": ["product_id"],
        "path_params": ["product_id"],
        "query_fields": [],
        "body_fields": ["skus"],
        "needs_shop_cipher": True,
        "response_key": "data",
        "doc_url": "https://partner.tiktokshop.com/docv2/page/update-inventory-202309",
    },
    "delete_products": {
        "summary": "Delete Products — 删除商品",
        "method": "DELETE",
        "path": "product/202309/products",
        "required": [],
        "query_fields": [],
        "body_fields": ["product_ids"],
        "needs_shop_cipher": True,
        "response_key": "data",
        "doc_url": "https://partner.tiktokshop.com/docv2/page/delete-products-202309",
    },
    "recover_products": {
        "summary": "Recover Products — 恢复已删商品",
        "method": "POST",
        "path": "product/202309/products/recover",
        "required": [],
        "query_fields": [],
        "body_fields": ["product_ids"],
        "needs_shop_cipher": True,
        "response_key": "data",
        "doc_url": "https://partner.tiktokshop.com/docv2/page/recover-products-202309",
    },
}


def list_api_names() -> List[str]:
    return sorted(PRODUCT_ENDPOINTS.keys())
