#!/usr/bin/env bash
# install-autopush.sh - install "push on commit" hooks + autopush.sh + scheduled task (github-autosetup v2, bash)
# Usage:
#   bash install-autopush.sh [-d OUTDIR] [-t TASK] [-m MIN] <repo1> <repo2> ...
#   -d OUTDIR   where autopush.sh + .autopush.log live (default: parent of this script's dir)
#   -t TASK     scheduled task name (default AutoSync)
#   -m MIN      interval minutes (default 30)
# Everything bash / LF / no credentials.

set -u

OUTDIR=""
TASK="AutoSync"
MIN=30
while getopts "d:t:m:h" o; do
  case "$o" in
    d) OUTDIR="$OPTARG" ;;
    t) TASK="$OPTARG" ;;
    m) MIN="$OPTARG" ;;
    h) echo "Usage: bash install-autopush.sh [-d OUTDIR] [-t TASK] [-m MIN] <repo1> <repo2> ..."; exit 0 ;;
    *) exit 2 ;;
  esac
done
shift $((OPTIND-1))
REPOS=("$@")
if [ ${#REPOS[@]} -eq 0 ]; then
  echo "error: no repos given" >&2; exit 2
fi

# default OUTDIR = parent of this script dir
if [ -z "$OUTDIR" ]; then
  OUTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
fi
AUTOPUSH="$OUTDIR/autopush.sh"
LOG="$OUTDIR/.autopush.log"
mkdir -p "$OUTDIR"

# 1) post-commit hooks (printf => LF, no BOM)
HOOK='#!/bin/sh
# autopush: push on commit (github-autosetup v2)
branch=$(git symbolic-ref --short HEAD 2>/dev/null || echo main)
[ "$branch" = "main" ] || exit 0
git push origin "$branch" -q 2>/dev/null || echo "[autopush] push failed - retried by scheduler" >&2'
for r in "${REPOS[@]}"; do
  hk="$r/.git/hooks/post-commit"
  if [ -f "$hk" ]; then
    echo "hook exists (skip): $hk"
  else
    printf '%s\n' "$HOOK" > "$hk"
    echo "hook installed: $hk"
  fi
done

# 2) generate autopush.sh (repos embedded)
{
  echo '#!/usr/bin/env bash'
  echo '# autopush.sh - auto commit + push (generated by install-autopush.sh; no credentials)'
  echo "LOG=\"$LOG\""
  echo 'log(){ echo "[$(date "+%F %T")] $*" >> "$LOG"; }'
  echo 'ssh-add -l >/dev/null 2>&1 || log "WARN: ssh-agent has no key; run: ssh-add ~/.ssh/id_ed25519_gh"'
  echo 'REPOS=('
  for r in "${REPOS[@]}"; do printf '  "%s"\n' "$r"; done
  echo ')'
  echo 'for r in "${REPOS[@]}"; do'
  echo '  [ -d "$r/.git" ] || { log "skip(no .git): $r"; continue; }'
  echo '  ( cd "$r" && git add -A 2>/dev/null'
  echo '    if [ -n "$(git status --porcelain)" ]; then'
  echo '      git commit -m "chore: autosync $(date "+%F %H:%M")" -q 2>/dev/null'
  echo '      git push origin HEAD -q 2>/dev/null && log "pushed: $r" || log "push FAILED: $r"'
  echo '    else'
  echo '      git push origin HEAD -q 2>/dev/null && log "synced(clean): $r"'
  echo '    fi )'
  echo 'done'
  echo 'log "--- done ---"'
} > "$AUTOPUSH"
echo "generated: $AUTOPUSH"

# 3) scheduled task: git-bash + autopush.sh
BASH_WIN="$(cygpath -w "$(command -v bash)" 2>/dev/null || echo "C:\\Program Files\\Git\\bin\\bash.exe")"
SCRIPT_WIN="$(cygpath -w "$AUTOPUSH" 2>/dev/null || echo "$AUTOPUSH")"
schtasks //create //tn "$TASK" //tr "\"$BASH_WIN\" \"$SCRIPT_WIN\"" //sc MINUTE //mo "$MIN" //f >/dev/null 2>&1
if [ $? -eq 0 ]; then
  echo "task registered: $TASK (every ${MIN}min)"
else
  echo "task FAILED (schtasks) - run manually with admin if needed"
fi
echo "done."
