#!/usr/bin/env python3
"""Generate professional job descriptions from role parameters."""

import json
import argparse
import sys
import os

SKILL_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATES_PATH = os.path.join(SKILL_DIR, "references", "jd_templates.json")


def load_templates():
    with open(TEMPLATES_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def generate_jd(
    role_template: str,
    company_name: str = "Our Company",
    seniority: str = "Mid-level",
    location: str = "Remote",
    employment_type: str = "Full-time",
    team: str = "Engineering",
    key_responsibility: str = "building and scaling our core products",
    years: str = "3",
    primary_language: str = "your preferred language",
    framework_or_tool: str = "modern frameworks and tools",
    secondary_skill: str = "CI/CD and cloud infrastructure",
    industry: str = "technology",
    product_area: str = "our core product",
    business_goal: str = "key business decisions",
    product_type: str = "our platform",
    channel_or_area: str = "digital",
    goal: str = "growth and engagement",
    sales_focus: str = "expanding our enterprise customer base",
) -> str:
    """Generate a formatted job description."""
    templates = load_templates()

    if role_template not in templates["templates"]:
        available = ", ".join(templates["templates"].keys())
        return f"ERROR: Unknown role template '{role_template}'. Available: {available}"

    tpl = templates["templates"][role_template]
    sections = tpl["sections"]

    # Fill in the about_role text
    about = sections["about_role"].format(
        seniority=seniority,
        team=team,
        product_area=product_area,
        business_goal=business_goal,
        product_type=product_type,
        channel_or_area=channel_or_area,
        goal=goal,
        sales_focus=sales_focus,
        key_responsibility=key_responsibility,
    )

    # Fill requirements
    reqs = []
    for r in sections["requirements"]:
        reqs.append(
            r.format(
                years=years,
                primary_language=primary_language,
                framework_or_tool=framework_or_tool,
                secondary_skill=secondary_skill,
                industry=industry,
                channel_or_area=channel_or_area,
                product_type=product_type,
            )
        )

    # Fill nice-to-have
    nice = []
    for n in sections["nice_to_have"]:
        nice.append(
            n.format(
                industry=industry,
                product_type=product_type,
            )
        )

    # Build the JD
    jd = []
    jd.append(f"# {tpl['title']} — {seniority}")
    jd.append(f"**Company:** {company_name}")
    jd.append(f"**Location:** {location}")
    jd.append(f"**Type:** {employment_type}")
    jd.append("")
    jd.append("## About the Role")
    jd.append(about)
    jd.append("")
    jd.append("## Requirements")
    for r in reqs:
        jd.append(f"- {r}")
    jd.append("")
    jd.append("## Nice to Have")
    for n in nice:
        jd.append(f"- {n}")
    jd.append("")
    jd.append("## Benefits & Perks")
    for b in sections["benefits"]:
        jd.append(f"- {b}")
    jd.append("")
    jd.append("---")
    jd.append("*Generated by HireMate AI Recruiting Assistant*")

    return "\n".join(jd)


def main():
    parser = argparse.ArgumentParser(description="Generate a professional job description")
    parser.add_argument("--role", required=True, help="Role template (software_engineer, product_manager, data_scientist, ux_designer, marketing_manager, sales_representative)")
    parser.add_argument("--company", default="Our Company", help="Company name")
    parser.add_argument("--seniority", default="Mid-level", help="Seniority level")
    parser.add_argument("--location", default="Remote", help="Work location")
    parser.add_argument("--type", dest="employment_type", default="Full-time", help="Employment type")
    parser.add_argument("--team", default="Engineering", help="Team name")
    parser.add_argument("--responsibility", default="building and scaling our core products", help="Key responsibility")
    parser.add_argument("--years", default="3", help="Years of experience required")
    parser.add_argument("--language", default="Python", help="Primary programming language")
    parser.add_argument("--framework", default="React/Django", help="Framework or tool")
    parser.add_argument("--secondary", default="cloud infrastructure", help="Secondary skill")
    parser.add_argument("--industry", default="technology", help="Industry domain")
    parser.add_argument("--output", help="Output file path (default: stdout)")

    args = parser.parse_args()

    jd = generate_jd(
        role_template=args.role,
        company_name=args.company,
        seniority=args.seniority,
        location=args.location,
        employment_type=args.employment_type,
        team=args.team,
        key_responsibility=args.responsibility,
        years=args.years,
        primary_language=args.language,
        framework_or_tool=args.framework,
        secondary_skill=args.secondary,
        industry=args.industry,
    )

    if args.output:
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(jd)
        print(f"Job description saved to {args.output}")
    else:
        print(jd)


if __name__ == "__main__":
    main()
