#!/usr/bin/env python3
"""Generate customized interview questions for a given role."""

import json
import argparse
import random
import os

SKILL_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
QUESTIONS_PATH = os.path.join(SKILL_DIR, "references", "interview_questions_db.json")


def load_questions():
    with open(QUESTIONS_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def generate_questions(
    role: str,
    num_technical: int = 5,
    num_behavioral: int = 3,
    level: str = "all",
    include_general: bool = True,
    num_general: int = 3,
    seed: int = None,
) -> dict:
    """Generate interview questions for a specific role."""
    if seed is not None:
        random.seed(seed)

    db = load_questions()
    result = {
        "role": role,
        "level": level,
        "technical_questions": [],
        "behavioral_questions": [],
        "general_questions": [],
    }

    # Map role to category
    category_map = {
        "software_engineer": "software_engineering",
        "product_manager": "product_management",
        "data_scientist": "data_science",
        "ux_designer": "ux_design",
        "marketing_manager": "marketing",
        "sales_representative": "sales",
    }

    cat = category_map.get(role)
    if not cat or cat not in db["categories"]:
        cat = "general"

    category = db["categories"][cat]

    # Technical questions
    if "technical" in category:
        tech_pool = [q for q in category["technical"] if q["level"] in (level, "all")]
        if not tech_pool:
            tech_pool = category["technical"]
        selected = random.sample(tech_pool, min(num_technical, len(tech_pool)))
        result["technical_questions"] = selected

    # Behavioral questions (role-specific)
    if "behavioral" in category:
        beh_pool = [q for q in category["behavioral"] if q["level"] in (level, "all")]
        if not beh_pool:
            beh_pool = category["behavioral"]
        selected = random.sample(beh_pool, min(num_behavioral, len(beh_pool)))
        result["behavioral_questions"] = selected

    # General behavioral questions
    if include_general and "general" in db["categories"] and "behavioral" in db["categories"]["general"]:
        gen_pool = db["categories"]["general"]["behavioral"]
        selected = random.sample(gen_pool, min(num_general, len(gen_pool)))
        result["general_questions"] = selected

    return result


def format_questions(data: dict) -> str:
    """Format questions as readable markdown."""
    lines = []
    role_name = data["role"].replace("_", " ").title()
    lines.append(f"# Interview Questions: {role_name}")
    lines.append(f"**Target Level:** {data['level']}")
    lines.append("")

    if data["technical_questions"]:
        lines.append("## 🔧 Technical Questions")
        for i, q in enumerate(data["technical_questions"], 1):
            tags = ", ".join(q["tags"])
            level_badge = f"[{q['level']}]" if q["level"] != "all" else ""
            lines.append(f"{i}. **{q['question']}** {level_badge}")
            lines.append(f"   _Tags: {tags}_")
            lines.append("")

    if data["behavioral_questions"]:
        lines.append("## 🧠 Behavioral Questions")
        for i, q in enumerate(data["behavioral_questions"], 1):
            tags = ", ".join(q["tags"])
            lines.append(f"{i}. **{q['question']}**")
            lines.append(f"   _Tags: {tags}_")
            lines.append("")

    if data["general_questions"]:
        lines.append("## 🌟 General Questions")
        for i, q in enumerate(data["general_questions"], 1):
            tags = ", ".join(q["tags"])
            lines.append(f"{i}. **{q['question']}**")
            lines.append(f"   _Tags: {tags}_")
            lines.append("")

    total = len(data["technical_questions"]) + len(data["behavioral_questions"]) + len(data["general_questions"])
    lines.append(f"**Total Questions:** {total}")
    lines.append("")
    lines.append("---")
    lines.append("*Generated by HireMate AI Recruiting Assistant*")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate interview questions for a role")
    parser.add_argument("--role", required=True, help="Role (software_engineer, product_manager, data_scientist, ux_designer, marketing_manager, sales_representative)")
    parser.add_argument("--num-tech", type=int, default=5, help="Number of technical questions")
    parser.add_argument("--num-behavioral", type=int, default=3, help="Number of behavioral questions")
    parser.add_argument("--level", choices=["junior", "mid", "senior", "all"], default="all", help="Seniority level")
    parser.add_argument("--no-general", action="store_true", help="Exclude general questions")
    parser.add_argument("--num-general", type=int, default=3, help="Number of general questions")
    parser.add_argument("--seed", type=int, default=None, help="Random seed for reproducibility")
    parser.add_argument("--format", choices=["markdown", "json"], default="markdown", help="Output format")
    parser.add_argument("--output", help="Output file path (default: stdout)")

    args = parser.parse_args()

    data = generate_questions(
        role=args.role,
        num_technical=args.num_tech,
        num_behavioral=args.num_behavioral,
        level=args.level,
        include_general=not args.no_general,
        num_general=args.num_general,
        seed=args.seed,
    )

    if args.format == "json":
        output = json.dumps(data, indent=2, ensure_ascii=False)
    else:
        output = format_questions(data)

    if args.output:
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(output)
        print(f"Interview questions saved to {args.output}")
    else:
        print(output)


if __name__ == "__main__":
    main()
