#!/usr/bin/env python3
"""
Premium: Generate salary market report for a given role and region.
"""

import json
import argparse
import os
import sys

SKILL_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SALARY_PATH = os.path.join(SKILL_DIR, "references", "salary_data.json")


def load_salary_data():
    with open(SALARY_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def generate_salary_report(
    role: str,
    region: str = "us",
    seniority: str = "mid",
    currency: str = None,
) -> dict:
    """Generate a salary market report."""
    data = load_salary_data()

    if region not in data["regions"]:
        available = ", ".join(data["regions"].keys())
        return {"error": f"Unknown region '{region}'. Available: {available}"}

    region_data = data["regions"][region]
    roles = region_data.get("roles", {})

    if role not in roles:
        available = ", ".join(roles.keys())
        return {"error": f"Role '{role}' not found in {region_data['name']}. Available: {available}"}

    role_data = roles[role]

    if seniority not in role_data:
        available = ", ".join(role_data.keys())
        return {"error": f"Seniority '{seniority}' not found. Available: {available}"}

    salary = role_data[seniority]
    curr = region_data.get("currency", "USD")

    report = {
        "role": role.replace("_", " ").title(),
        "region": region_data["name"],
        "seniority": seniority.capitalize(),
        "currency": curr,
        "salary_data": {
            "min": salary.get("min", "N/A"),
            "median": salary.get("median", "N/A"),
            "max": salary.get("max", "N/A"),
            "p75": salary.get("p75", "N/A"),
            "p90": salary.get("p90", "N/A"),
        },
    }

    if "ote" in salary:
        report["salary_data"]["ote"] = salary["ote"]

    # Cross-region comparison
    comparisons = {}
    for other_region, other_data in data["regions"].items():
        if other_region == region:
            continue
        other_roles = other_data.get("roles", {})
        if role in other_roles and seniority in other_roles[role]:
            other_salary = other_roles[role][seniority]
            comparisons[other_data["name"]] = {
                "currency": other_data.get("currency", "USD"),
                "median": other_salary.get("median", "N/A"),
            }
    report["regional_comparison"] = comparisons

    report["notes"] = data.get("notes", [])

    return report


def format_report(report: dict) -> str:
    """Format salary report as markdown."""
    if "error" in report:
        return f"## Error\n\n{report['error']}"

    lines = []
    lines.append(f"# Salary Market Report")
    lines.append("")
    lines.append(f"**Role:** {report['role']}")
    lines.append(f"**Region:** {report['region']}")
    lines.append(f"**Seniority:** {report['seniority']}")
    lines.append(f"**Currency:** {report['currency']}")
    lines.append("")

    sd = report["salary_data"]
    lines.append("## Salary Range")
    lines.append("| Metric | Amount |")
    lines.append("|--------|--------|")
    for key, val in sd.items():
        label = key.upper() if key == "ote" else key.replace("p", "P").title()
        if isinstance(val, (int, float)):
            lines.append(f"| {label} | {report['currency']} {val:,} |")
        else:
            lines.append(f"| {label} | {val} |")
    lines.append("")

    if "regional_comparison" in report and report["regional_comparison"]:
        lines.append("## Regional Comparison (Median)")
        lines.append("| Region | Currency | Median |")
        lines.append("|--------|----------|--------|")
        for region_name, data in report["regional_comparison"].items():
            median = data["median"]
            if isinstance(median, (int, float)):
                lines.append(f"| {region_name} | {data['currency']} | {median:,} |")
            else:
                lines.append(f"| {region_name} | {data['currency']} | {median} |")
        lines.append("")

    if report.get("notes"):
        lines.append("## Notes")
        for note in report["notes"]:
            lines.append(f"- {note}")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by HireMate AI Recruiting Assistant (Premium)*")
    lines.append(f"*Data last updated: {load_salary_data().get('last_updated', 'N/A')}*")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate salary market report (Premium)")
    parser.add_argument("--role", required=True, help="Role (software_engineer, product_manager, data_scientist, ux_designer, marketing_manager, sales_representative)")
    parser.add_argument("--region", default="us", choices=["us", "europe", "uk", "asia_pacific"], help="Region")
    parser.add_argument("--seniority", default="mid", choices=["junior", "mid", "senior", "staff"], help="Seniority level")
    parser.add_argument("--format", choices=["markdown", "json"], default="markdown")
    parser.add_argument("--output", help="Output file path")

    args = parser.parse_args()

    report = generate_salary_report(
        role=args.role,
        region=args.region,
        seniority=args.seniority,
    )

    if args.format == "json":
        output = json.dumps(report, indent=2, ensure_ascii=False)
    else:
        output = format_report(report)

    if args.output:
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(output)
        print(f"Salary report saved to {args.output}")
    else:
        print(output)


if __name__ == "__main__":
    main()
