#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path

from eval_common import evaluate_text


ROOT = Path(__file__).resolve().parents[1]
CASES = ROOT / "tests" / "agent-eval-cases.json"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Evaluate outputs generated by an independent agent.")
    parser.add_argument("--outputs-dir", type=Path, required=True)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    cases = json.loads(CASES.read_text(encoding="utf-8"))
    results = []
    failed = False

    for case in cases:
        output_path = args.outputs_dir / f"{case['id']}.md"
        output = output_path.read_text(encoding="utf-8") if output_path.exists() else ""
        failures = [] if output else [f"missing agent output: {output_path}"]
        if output:
            failures.extend(evaluate_text(case, output))
        failed = failed or bool(failures)
        results.append({
            "id": case["id"],
            "passed": not failures,
            "output": str(output_path),
            "failures": failures,
        })

    summary = {
        "suite_type": "independent_agent_output",
        "case_count": len(cases),
        "passed_count": sum(1 for item in results if item["passed"]),
        "failed_count": sum(1 for item in results if not item["passed"]),
        "results": results,
    }
    print(json.dumps(summary, ensure_ascii=False, indent=2))
    if failed:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
