"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.generateTokensJson = exports.generateTailwindConfig = exports.generateDesignMd = exports.generateCssVariables = exports.extractCssVariables = exports.collectVisibleElements = exports.collectRawPageAnalysis = exports.collectPageMeta = exports.collectLayoutSamples = exports.collectColorSamples = exports.buildDesignSnapshot = exports.analyzeCurrentPage = void 0;
var pageAnalyzer_1 = require("./analyzer/pageAnalyzer");
Object.defineProperty(exports, "analyzeCurrentPage", { enumerable: true, get: function () { return pageAnalyzer_1.analyzeCurrentPage; } });
Object.defineProperty(exports, "buildDesignSnapshot", { enumerable: true, get: function () { return pageAnalyzer_1.buildDesignSnapshot; } });
Object.defineProperty(exports, "collectColorSamples", { enumerable: true, get: function () { return pageAnalyzer_1.collectColorSamples; } });
Object.defineProperty(exports, "collectLayoutSamples", { enumerable: true, get: function () { return pageAnalyzer_1.collectLayoutSamples; } });
Object.defineProperty(exports, "collectPageMeta", { enumerable: true, get: function () { return pageAnalyzer_1.collectPageMeta; } });
Object.defineProperty(exports, "collectRawPageAnalysis", { enumerable: true, get: function () { return pageAnalyzer_1.collectRawPageAnalysis; } });
Object.defineProperty(exports, "collectVisibleElements", { enumerable: true, get: function () { return pageAnalyzer_1.collectVisibleElements; } });
Object.defineProperty(exports, "extractCssVariables", { enumerable: true, get: function () { return pageAnalyzer_1.extractCssVariables; } });
var generators_1 = require("./export/generators");
Object.defineProperty(exports, "generateCssVariables", { enumerable: true, get: function () { return generators_1.generateCssVariables; } });
Object.defineProperty(exports, "generateDesignMd", { enumerable: true, get: function () { return generators_1.generateDesignMd; } });
Object.defineProperty(exports, "generateTailwindConfig", { enumerable: true, get: function () { return generators_1.generateTailwindConfig; } });
Object.defineProperty(exports, "generateTokensJson", { enumerable: true, get: function () { return generators_1.generateTokensJson; } });