#!/usr/bin/env python3
"""Create a standard webapp project folder for upstage-builder work.

Usage:
  python skills/upstage-builder/scripts/init_webapp_project.py <project-slug>
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONFIG_PATH = ROOT / "config.json"


def slugify(value: str) -> str:
    value = value.strip().lower()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    value = re.sub(r"-+", "-", value).strip("-")
    if not value:
        raise ValueError("Project slug is empty after normalization")
    return value


def main() -> None:
    if len(sys.argv) < 2:
        raise SystemExit("Usage: python skills/upstage-builder/scripts/init_webapp_project.py <project-slug>")

    raw_slug = sys.argv[1]
    slug = slugify(raw_slug)
    config = json.loads(CONFIG_PATH.read_text())
    project_root = Path(config["projectRoot"])
    provider = config["deploymentProvider"]
    stack = config["defaultWebStack"]

    project_dir = project_root / slug
    project_dir.mkdir(parents=True, exist_ok=True)

    (project_dir / "README.md").write_text(
        f"# {slug}\n\n"
        f"Generated by upstage-builder.\n\n"
        f"- Stack: {stack}\n"
        f"- Deployment: {provider}\n"
        f"- Path: {project_dir}\n"
    )

    (project_dir / ".env.example").write_text(
        "UPSTAGE_API_KEY=\n"
    )

    (project_dir / "DEPLOY.md").write_text(
        f"# Deploy\n\n"
        f"Provider: {provider}\n\n"
        f"Expected outcome: external URL instead of localhost-only preview.\n"
    )

    print(project_dir)


if __name__ == "__main__":
    main()
