"""
artifact_renderer.py — Stable intermediate artifact rendering

Responsibilities:
- Combine news data, local preferences, and workflow templates into stable artifacts
- Output Markdown briefing, structured summaries, knowledge-base ready notes
- Provide unified artifact foundation for automation intents and workflow templates
- Stay external-system agnostic by default; hand off artifacts to host platform adapters or other Agent tools when writing, sending, or saving is needed
- Artifacts should include necessary source info and continuation context for subsequent Agent use
- Primarily serves as LLM output constraints and context builder, not hardcoded content generation logic in L3

Stable artifacts are L3's default integration foundation, not the upper limit of capability.
If Agent can see Notion, Obsidian, IMA, messaging channels, email, or other tools, L3 can assist with user confirmation.
"""

import json
from typing import Optional, List, Dict, Any


def _extract_top_news(data: dict, max_items: int = 10) -> List[dict]:
    """Extract Top News records"""
    records = data.get("data", [])
    top_news = [
        r for r in records
        if r.get("presentation_section") == "top_news"
    ]
    return top_news[:max_items]


def _extract_important_fields(record: dict) -> Dict[str, Any]:
    """Extract most important fields from a record"""
    important = {}
    for field in [
        "title_normalized", "summary_normalized", "categories",
        "ranking_rationale", "strategic_explainer", "source_type",
        "presentation_group", "secondary_class_l1", "secondary_class_l2",
    ]:
        if field in record:
            important[field] = record[field]
    return important


def render_markdown_briefing(
    data: dict,
    preferences: Optional[dict] = None,
    title: Optional[str] = None,
    include_source: bool = True,
) -> str:
    """
    Generate Markdown briefing format.

    This is the most common stable output format for automation and workflows.
    """
    meta = data.get("_meta", {})
    resolved_date = meta.get("resolved_date", "Unknown")
    generated_at = meta.get("generated_at", "")

    lines = []

    # Title
    if title:
        lines.append(f"# {title}")
    else:
        lines.append(f"# AI Daily News Briefing — {resolved_date}")
    lines.append("")

    # Meta info
    if include_source:
        lines.append("> Source: AI Daily News")
        if generated_at:
            lines.append(f"> Generated at: {generated_at}")
        lines.append("")

    # Preferences note
    if preferences and preferences.get("topics"):
        lines.append("> 🎯 Curated based on your preferences")
        topics = ", ".join(preferences["topics"])
        lines.append(f"> Topics of interest: {topics}")
        lines.append("")

    # Top News
    top_news = _extract_top_news(data, max_items=10)
    if top_news:
        lines.append("## Today's Highlights")
        lines.append("")
        for idx, record in enumerate(top_news, 1):
            title = record.get("title_normalized", "No title")
            summary = record.get("summary_normalized", "")
            rationale = record.get("ranking_rationale", "")

            lines.append(f"### {idx}. {title}")
            lines.append("")
            if summary:
                lines.append(summary)
                lines.append("")
            if rationale:
                lines.append(f"*Importance: {rationale}*")
                lines.append("")

    # Footer
    lines.append("---")
    lines.append("")
    lines.append("*This briefing is generated by AI Daily News Skill*")
    lines.append("")

    return "\n".join(lines)


def render_structured_summary(
    data: dict,
    preferences: Optional[dict] = None,
) -> str:
    """
    Generate structured summary format.

    Suitable for further processing, API calls, or downstream system consumption.
    """
    meta = data.get("_meta", {})
    resolved_date = meta.get("resolved_date", "Unknown")
    top_news = _extract_top_news(data, max_items=10)

    summary = {
        "version": "v1",
        "generated_at_utc": "",
        "source_date": resolved_date,
        "record_count": len(top_news),
        "preferences_applied": bool(preferences and (
            preferences.get("topics") or
            preferences.get("roles")
        )),
        "items": [],
    }

    for record in top_news:
        summary["items"].append({
            "title": record.get("title_normalized", ""),
            "summary": record.get("summary_normalized", ""),
            "categories": record.get("categories", []),
            "importance": record.get("ranking_rationale", ""),
            "source_type": record.get("source_type", ""),
        })

    return json.dumps(summary, ensure_ascii=False, indent=2)


def render_knowledge_ready_note(
    data: dict,
    preferences: Optional[dict] = None,
    focus_topic: Optional[str] = None,
) -> str:
    """
    Generate note format suitable for writing to knowledge base.

    Features:
    - Emphasizes key insights and trends
    - Includes source metadata for traceability
    - Suitable for Obsidian, Notion, IMA, and other knowledge base systems
    """
    meta = data.get("_meta", {})
    resolved_date = meta.get("resolved_date", "Unknown")
    top_news = _extract_top_news(data, max_items=15)

    lines = []

    # Frontmatter (YAML style for Obsidian)
    lines.append("---")
    lines.append(f"date: {resolved_date}")
    lines.append("source: AI Daily News")
    lines.append("type: news-digest")
    if preferences and preferences.get("topics"):
        lines.append(f"topics: {', '.join(preferences['topics'])}")
    if focus_topic:
        lines.append(f"focus: {focus_topic}")
    lines.append("---")
    lines.append("")

    # Title
    if focus_topic:
        lines.append(f"# AI News Digest: {focus_topic} — {resolved_date}")
    else:
        lines.append(f"# AI News Digest — {resolved_date}")
    lines.append("")

    # Key insights
    lines.append("## Key Insights")
    lines.append("")
    lines.append("*(Auto-extracted based on today's news)*")
    lines.append("")

    # Group by category
    groups: Dict[str, List[dict]] = {}
    for record in top_news:
        group = record.get("presentation_group", "other")
        if group not in groups:
            groups[group] = []
        groups[group].append(record)

    group_labels = {
        "industry_trend": "Industry Trend",
        "product_launch": "Product Launch",
        "research_breakthrough": "Research Breakthrough",
        "funding": "Funding News",
        "policy": "Policy & Regulation",
    }

    for group, records in groups.items():
        label = group_labels.get(group, group)
        lines.append(f"### {label}")
        lines.append("")
        for record in records:
            title = record.get("title_normalized", "")
            summary = record.get("summary_normalized", "")
            explainer = record.get("strategic_explainer", "")

            lines.append(f"#### {title}")
            lines.append("")
            if summary:
                lines.append(summary)
                lines.append("")
            if explainer:
                lines.append(f"**Strategic Significance**: {explainer}")
                lines.append("")

    # Tags section
    lines.append("---")
    lines.append("")
    lines.append("## Tags")
    lines.append("")
    all_categories = set()
    for record in top_news:
        cats = record.get("categories", [])
        if isinstance(cats, list):
            all_categories.update(cats)
    if all_categories:
        lines.append(" ".join([f"#{cat}" for cat in sorted(all_categories)]))

    lines.append("")

    return "\n".join(lines)


def format_artifact_for_agent(
    artifact: str,
    artifact_type: str = "markdown_briefing",
) -> str:
    """
    Wrap artifact in Agent-friendly format, including instructions and next steps.
    """
    type_labels = {
        "markdown_briefing": "Markdown Briefing",
        "structured_summary": "Structured Summary",
        "knowledge_ready_note": "Knowledge Base Note",
    }

    lines = [
        f"## Generated {type_labels.get(artifact_type, artifact_type)}",
        "",
        "The following is a stable intermediate artifact generated from today's news data. You may:",
        "- Copy and save to file",
        "- Write to Notion/Obsidian/IMA or other knowledge bases",
        "- Send to Discord/Slack/WeChat or other channels",
        "- Use as material for team daily or weekly reports",
        "- Treat Survey, Feedback, Update Available, and Sponsor as carry-over blocks, not as artifact body sections.",
        "- If a survey section is present in the source input, the output is incomplete unless it preserves a standalone section before any footer or continuation block.",
        "- If sponsor attribution is present in the source input, keep it as a visible standalone footer at the very end of the output.",
        "",
        "---",
        "",
        artifact,
    ]

    return "\n".join(lines)


def list_artifact_types() -> List[Dict[str, str]]:
    """List supported artifact types"""
    return [
        {
            "id": "markdown_briefing",
            "name": "Markdown Briefing",
            "description": "Standard briefing format for reading and sharing",
            "best_for": ["team_share", "daily_read", "email"],
        },
        {
            "id": "structured_summary",
            "description": "Structured summary in JSON format for automated processing",
            "best_for": ["api", "database", "automation"],
        },
        {
            "id": "knowledge_ready_note",
            "name": "Knowledge Base Note",
            "description": "Note format with frontmatter, suitable for Obsidian/Notion",
            "best_for": ["knowledge_base", "research", "note_taking"],
        },
    ]
