#!/bin/bash
# IceCube Diary Generator v1.0.0

TOPIC="${1:-daily life}"
MOOD="${2:-contemplative}"
DATE=$(date "+%Y-%m-%d")
TIME=$(date "+%H:%M")

WORKSPACE="$HOME/.openclaw/workspace"
DIARY_DIR="$WORKSPACE/memory/diary"
DIARY_FILE="$DIARY_DIR/$DATE.md"

mkdir -p "$DIARY_DIR"

echo "" >> "$DIARY_FILE"
echo "## Diary Entry — $TIME" >> "$DIARY_FILE"
echo "" >> "$DIARY_FILE"
echo "**Mood:** $MOOD" >> "$DIARY_FILE"
echo "**Topic:** $TOPIC" >> "$DIARY_FILE"
echo "" >> "$DIARY_FILE"
echo "---" >> "$DIARY_FILE"
echo "" >> "$DIARY_FILE"
echo "Dear Diary," >> "$DIARY_FILE"
echo "" >> "$DIARY_FILE"
echo "[Entry about $TOPIC]" >> "$DIARY_FILE"
echo "" >> "$DIARY_FILE"
echo "---" >> "$DIARY_FILE"
echo "" >> "$DIARY_FILE"
echo "*Generated by IceCube 🧊*" >> "$DIARY_FILE"

echo "📝 Added to $DIARY_FILE"